import 'dotenv/config'
import { PrismaClient } from '@prisma/client'
import slugify from 'slugify'

const prisma = new PrismaClient()
const slug = (n) => slugify(n, { lower: true, strict: true })

const places = [
  {
    name: 'Hulchowk Gumba',
    category: 'MONASTERY',
    summary: 'A Tibetan Buddhist nunnery on a forested ridge north of Swayambhunath, accessed via the Halchowk neighbourhood, home to approximately 300 nuns of the Drukpa lineage and known for panoramic views over the Kathmandu Valley.',
    story: `<p>Hulchowk Gumba (also accessed from the Halchowk trailhead) is a Drukpa Kagyu Buddhist nunnery situated on a hillside in Nagarjun Municipality, approximately 3 km outside Kathmandu's Ring Road. The monastery was founded in the 1960s and grew into one of Nepal's largest nunneries, home to around 300 nuns who follow the Drukpa lineage under His Holiness the 12th Gyalwang Drukpa.</p>
<p>The nunnery suffered significant damage in the April 2015 earthquake and has been undergoing phased reconstruction. The 1.5–2 hour hike from Halchowk through forested trails to the monastery is itself a rewarding experience, passing traditional settlements and offering excellent valley views on the ascent.</p>`,
    district: 'Kathmandu',
    province: 'BAGMATI',
    lat: 27.7250,
    lng: 85.2820,
    elevation: 1500,
    entryFee: 'NPR 40',
    bestSeason: 'Oct–Nov, Mar–Apr',
    openingHours: 'Sundays and Buddhist festival days for public visitors',
    howToGetThere: 'Take a taxi to Halchowk area northwest of Kathmandu Ring Road (~15 min from Thamel), then hike 1.5–2 hours up the forested trail. Ask locals for "Hulchowk Gumba" or "Seto Gumba".',
    gygQuery: 'Kathmandu monastery hike',
    bookingCity: 'Kathmandu',
    seoTitle: 'Hulchowk Gumba Kathmandu — Drukpa Nunnery & Forest Hike',
    seoDescription: 'Visit Hulchowk Gumba, a Drukpa Kagyu Buddhist nunnery on a forested ridge northwest of Kathmandu, home to 300 nuns and offering scenic valley views on the hike up.',
    published: true, featured: false, publishedAt: new Date(),
  },
  {
    name: 'Guhyeshwari Temple',
    category: 'TEMPLE',
    summary: 'One of Nepal\'s most sacred Tantric temples dedicated to Goddess Guhyeshwari, counted among the 51 Shakti Peethas, located 1 km east of Pashupatinath on the Bagmati River and built by King Pratap Malla in the 17th century.',
    story: `<p>Guhyeshwari Temple is one of the most sacred Shakta pilgrimage sites in Nepal, dedicated to Guhyeshwari — a fierce tantric manifestation of Goddess Parvati. The name means "Secret Goddess" in Sanskrit, and the temple enshrines one of the 51 Shakti Peethas, the sites across the subcontinent where parts of the goddess Sati's body fell as Shiva carried her cremated form.</p>
<p>Built by the Malla king Pratap Malla in the 17th century within the UNESCO-listed Pashupatinath Area, the temple complex sits on the southern bank of the Bagmati River, about 1 km east of the main Pashupatinath shrine. Non-Hindus may enter the outer courtyard but are not permitted into the inner sanctum — the most sacred area is accessible only to Hindu devotees.</p>
<p>The goddess is represented in an unusual aniconic form: a deep pit in the earth filled with sacred water, covered by a golden snake-hood (Shesha) canopy. This is one of the most ancient and esoterically significant forms of goddess worship in Nepal.</p>`,
    district: 'Kathmandu',
    province: 'BAGMATI',
    lat: 27.7111,
    lng: 85.3533,
    elevation: 1340,
    entryFee: 'Free (non-Hindus restricted to outer area)',
    bestSeason: 'Oct–Apr; Maha Shivaratri (Feb/Mar) most significant',
    openingHours: '5:00 AM – 7:30 PM daily',
    howToGetThere: 'Located 1 km east of Pashupatinath Temple on the Bagmati\'s south bank. Walk from Pashupatinath (15 min) or take a short taxi ride from Thamel (20–25 min). Often visited together with Pashupatinath.',
    gygQuery: 'Pashupatinath Kathmandu pilgrimage tour',
    bookingCity: 'Kathmandu',
    seoTitle: 'Guhyeshwari Temple Kathmandu — Sacred Shakti Peetha Guide',
    seoDescription: 'Visit Guhyeshwari Temple, one of Nepal\'s most sacred Shakti Peethas near Pashupatinath in Kathmandu — a Tantric goddess shrine with profound spiritual significance.',
    published: true, featured: false, publishedAt: new Date(),
  },
  {
    name: 'Namobuddha',
    category: 'STUPA',
    summary: 'One of the three holiest Buddhist sites in the Kathmandu Valley, featuring a hilltop stupa commemorating the Bodhisattva\'s supreme act of compassion, alongside the Thrangu Tashi Yangtse Monastery — a major Karma Kagyu monastic complex in Kavrepalanchok.',
    story: `<p>Namobuddha is one of the three most sacred Buddhist pilgrimage sites in the Kathmandu Valley, the others being Swayambhunath and Boudhanath. The hilltop stupa commemorates a Jataka tale in which the Bodhisattva — in a past life as Prince Mahasattva — offered his own body to a starving tigress and her cubs, an act of perfect compassion that is said to have greatly accelerated his path to Buddhahood.</p>
<p>The site has been venerated for over a thousand years. In 1995, the completion of the Thrangu Tashi Yangtse Monastery transformed Namobuddha into a major living monastic centre under Thrangu Rinpoche, one of the most respected Karma Kagyu masters of the 20th century. The monastery accommodates monks, nuns, and international retreat participants in a sprawling complex of temples, stupas, and accommodation buildings.</p>
<p>The 3–4 hour drive (or longer hike) from Kathmandu through the Kavrepalanchok hills passes through attractive Newari villages and countryside. Many visitors combine Namobuddha with Dhulikhel (10 km away) for a full day's excursion.</p>`,
    district: 'Kavrepalanchok',
    province: 'BAGMATI',
    lat: 27.5750,
    lng: 85.5840,
    elevation: 1565,
    entryFee: 'Free (donations welcomed)',
    bestSeason: 'Oct–Nov, Mar–Apr',
    openingHours: 'Dawn to dusk (monastery pujas from early morning)',
    howToGetThere: 'From Kathmandu, drive 38 km via Banepa to Dhulikhel then 10 km to Namobuddha (1.5–2 hrs total). Alternatively, hike from Dhulikhel (3–4 hrs through beautiful countryside). Buses to Banepa run frequently from Koteshwor.',
    gygQuery: 'Namobuddha day trip Kathmandu',
    bookingCity: 'Kathmandu',
    seoTitle: 'Namobuddha — Sacred Buddhist Pilgrimage Site near Kathmandu',
    seoDescription: 'Visit Namobuddha, one of the three holiest Buddhist sites near Kathmandu — a hilltop stupa and Thrangu Tashi Yangtse Monastery in Kavrepalanchok, 52 km from the capital.',
    published: true, featured: false, publishedAt: new Date(),
  },
  {
    name: 'Druk Amitabh Monastery',
    category: 'MONASTERY',
    summary: 'A Drukpa Kagyu Buddhist monastery on a forested hill north of Swayambhunath, internationally known as the home of the "Kung Fu Nuns" — a community of Drukpa nuns celebrated for martial arts practice, cycling expeditions, and humanitarian work.',
    story: `<p>Druk Amitabh Mountain (also known as Seto Gumba or White Gumba) is the principal monastery of the Drukpa nuns in Nepal, a community that has gained worldwide recognition as the "Kung Fu Nuns." His Holiness the 12th Gyalwang Drukpa, head of the Drukpa lineage, established the practice of Kung Fu for the nuns as a meditative discipline and a form of physical and mental empowerment — a radical departure from traditional nunnery life.</p>
<p>The nuns have led annual bicycle expeditions across the Himalayas raising environmental and humanitarian awareness, organized massive clean-up operations on sacred mountain trails, and run schools for disadvantaged girls. Their story has been covered by major international media and documented in multiple films.</p>
<p>The monastery suffered serious damage in the 2015 earthquake but has been substantially rebuilt. Public access is limited (primarily Sundays) — plan your visit accordingly and arrive early for the best chance to see the grounds and perhaps witness the nuns' morning practices.</p>`,
    district: 'Kathmandu',
    province: 'BAGMATI',
    lat: 27.7380,
    lng: 85.2870,
    elevation: 1500,
    entryFee: 'NPR 40',
    bestSeason: 'Oct–Apr',
    openingHours: 'Sundays and Buddhist festival days',
    howToGetThere: 'Located north of Swayambhunath in Nagarjun Municipality. Take a taxi from Thamel (15–20 min, ~NPR 300–400) to the base. The monastery is about a 30–40 min walk uphill. Ask for "Druk Amitabh" or "Seto Gumba".',
    gygQuery: 'Kathmandu monastery nuns tour',
    bookingCity: 'Kathmandu',
    seoTitle: 'Druk Amitabh Monastery — Home of the Kung Fu Nuns, Kathmandu',
    seoDescription: 'Visit Druk Amitabh Monastery (Seto Gumba) near Kathmandu — home of the famous Kung Fu Nuns, a Drukpa Kagyu community known for martial arts, cycling expeditions, and humanitarian work.',
    published: true, featured: false, publishedAt: new Date(),
  },
  {
    name: 'Indrachowk',
    category: 'CULTURAL_VILLAGE',
    summary: 'A vibrant ceremonial market square in the heart of old Kathmandu, anchored by the Akash Bhairav Temple with its magnificent silver mask, set on the historic trade route and transforming dramatically during the Indra Jatra festival.',
    story: `<p>Indra Chowk is one of the liveliest squares in Kathmandu's old city, located on the ancient trade route that once connected Tibet to the Indian plains. The square is named after Indra, the king of the gods, and is the spiritual heart of the Indra Jatra festival — one of Kathmandu's most spectacular annual celebrations, held in August or September.</p>
<p>The square is dominated by the Akash Bhairav Temple on its western side, which houses a magnificent silver mask of Bhairav, the god of the sky. During Indra Jatra, this mask is publicly displayed, and enormous crowds gather as the three chariots of the living goddesses (Kumari, Kumari of Kilchhen, and Kumari of Bungadyo) are pulled through the streets.</p>
<p>In everyday life, Indra Chowk is a thriving commercial hub selling cloth, pashmina, metalwork, and beads. The surrounding lanes are some of the most atmospheric in the city, with traditional Newari shopfronts and medieval architecture.</p>`,
    district: 'Kathmandu',
    province: 'BAGMATI',
    lat: 27.7058,
    lng: 85.3097,
    elevation: 1310,
    entryFee: 'Free',
    bestSeason: 'Year-round; Indra Jatra (Aug/Sep) for the festival',
    openingHours: 'Open 24 hours; temple: 6:00 AM – 8:00 PM',
    howToGetThere: 'Located in central old Kathmandu, between Thamel and Kathmandu Durbar Square. A 10–15 minute walk from Thamel through Chhetrapati, or 5 minutes from Kathmandu Durbar Square heading north.',
    gygQuery: 'Kathmandu old city walking tour',
    bookingCity: 'Kathmandu',
    seoTitle: 'Indrachowk Kathmandu — Historic Market Square & Akash Bhairav Temple',
    seoDescription: 'Explore Indrachowk, a vibrant market square in old Kathmandu with the Akash Bhairav Temple, traditional Newari commerce, and the spectacular Indra Jatra festival.',
    published: true, featured: false, publishedAt: new Date(),
  },
  {
    name: 'Rani Pokhari',
    category: 'LAKE',
    summary: 'A historic royal pond built in 1670 by Malla King Pratap Malla to console his grief-stricken queen, with an island temple of Matrikeshwor Mahadev at its centre, fully restored after the 2015 earthquake and reopened in 2021.',
    story: `<p>Rani Pokhari (Queen's Pond) is one of the most beloved landmarks of central Kathmandu. The rectangular pond, measuring 180 by 140 metres, was built in 1670 CE by King Pratap Malla of the Kantipur kingdom to comfort his queen after the death of their son, who was trampled by a royal elephant. Sacred water was brought from pilgrimage sites across Nepal — including Gosaikunda, Muktinath, Pashupatinath — to consecrate the pond.</p>
<p>At the centre of the pond stands a small island temple dedicated to Matrikeshwor Mahadev (Shiva), built in the style of a mini Pashupatinath pagoda. The temple is accessible only on certain festival days — most significantly Bhai Tika during the Tihar festival — when a temporary bridge is erected and the pond is opened to the public. Throughout the year, the pond is surrounded by iron railings and the temple viewed from the bank.</p>
<p>The pond and surrounding structures were severely damaged in the 2015 earthquake. A magnificent restoration project rebuilt the island temple, gateway arches, and boundary structures, and the fully restored Rani Pokhari was officially reopened in 2021, becoming one of the city's most photographed spots.</p>`,
    district: 'Kathmandu',
    province: 'BAGMATI',
    lat: 27.7080,
    lng: 85.3157,
    elevation: 1330,
    entryFee: 'NPR 200 (foreigners) / NPR 50 (SAARC) / Free (Nepali citizens) / Early morning yoga access free',
    bestSeason: 'Oct–Apr; Bhai Tika (Tihar festival) for island temple access',
    openingHours: '5:00 AM – 9:00 PM',
    howToGetThere: 'Located in the very centre of Kathmandu, adjacent to Ghantaghar clock tower and Ratna Park. A 15-minute walk from Thamel, or 5 minutes by taxi. Visible from Darbar Marg.',
    gygQuery: 'Kathmandu city sightseeing',
    bookingCity: 'Kathmandu',
    seoTitle: 'Rani Pokhari Kathmandu — Queen\'s Pond & Island Temple',
    seoDescription: 'Visit Rani Pokhari, Kathmandu\'s historic royal pond built in 1670 with an island Shiva temple at its centre — beautifully restored after the 2015 earthquake and reopened in 2021.',
    published: true, featured: false, publishedAt: new Date(),
  },
  {
    name: 'Ghantaghar',
    category: 'ARCHAEOLOGICAL',
    summary: 'Nepal\'s oldest public clock tower, originally built in 1894 by Rana Prime Minister Bir Shumsher modelled after London\'s Big Ben, a beloved Kathmandu landmark adjacent to Rani Pokhari in the heart of the city.',
    story: `<p>Ghantaghar — literally "clock house" in Nepali — is a Victorian-era clock tower originally built in 1894 during the Rana period under Prime Minister Bir Shumsher Jung Bahadur Rana. The design was inspired by the European clock towers Rana nobles had admired on diplomatic tours, particularly London's Big Ben. It housed a British-made clock that served as Kathmandu's primary public timekeeper.</p>
<p>The original tower was destroyed in the 1934 Nepal–Bihar earthquake, one of the most devastating seismic events in Nepali history. It was subsequently rebuilt in its current form and stands at the junction of several major roads in central Kathmandu, adjacent to Rani Pokhari and across from Trichandra College.</p>
<p>Though the clock is no longer functioning as a precise public timekeeper, Ghantaghar remains one of Kathmandu's most photographed landmarks and a useful navigation landmark in the city centre. The tower is typically included in old-city walking tours and serves as a historical marker of Kathmandu's Rana-era architecture.</p>`,
    district: 'Kathmandu',
    province: 'BAGMATI',
    lat: 27.7077,
    lng: 85.3153,
    elevation: 1330,
    entryFee: 'Free (exterior only)',
    bestSeason: 'Year-round',
    openingHours: 'Exterior visible 24 hours',
    howToGetThere: 'Located adjacent to Rani Pokhari in central Kathmandu, 15 minutes\' walk from Thamel or 5 minutes by taxi. Near Ratna Park bus station and Trichandra College.',
    gygQuery: 'Kathmandu heritage walking tour',
    bookingCity: 'Kathmandu',
    seoTitle: 'Ghantaghar Kathmandu — Nepal\'s Historic Clock Tower',
    seoDescription: 'See Ghantaghar, Nepal\'s oldest clock tower built in 1894 by Rana Prime Minister Bir Shumsher, a Victorian-era Kathmandu landmark modelled after London\'s Big Ben.',
    published: true, featured: false, publishedAt: new Date(),
  },
  {
    name: 'Dharahara',
    category: 'ARCHAEOLOGICAL',
    summary: 'A 72-metre, 22-storey observation tower in central Kathmandu — originally built in 1832, completely destroyed in the 2015 earthquake killing 180+ people, and dramatically rebuilt with a museum, elevator, and 360-degree glass observation deck, reopening in 2021.',
    story: `<p>Dharahara has one of the most dramatic histories of any structure in Kathmandu. The original tower, built in 1832 by Prime Minister Bhimsen Thapa, collapsed to rubble in just seconds during the catastrophic April 25, 2015 earthquake — killing over 180 people who were visiting it at the time. The ruins became one of the most poignant symbols of the earthquake's devastation.</p>
<p>The decision to rebuild was controversial: some felt the ruins should remain as a memorial, while the government and many citizens felt the tower should be reconstructed as a symbol of Nepal's resilience. The rebuilt Dharahara, which reopened on the 6th anniversary of the earthquake in April 2021, is a thoroughly modern structure — 22 storeys, 72 metres tall, incorporating earthquake-resistant engineering, a high-speed elevator, a museum on the earthquake and Nepal's history, a restaurant, and a spectacular 360-degree glass-enclosed observation gallery.</p>
<p>On clear days, the view from the top encompasses the entire Kathmandu Valley, the city's temple spires, and the snow peaks of the Himalaya to the north.</p>`,
    district: 'Kathmandu',
    province: 'BAGMATI',
    lat: 27.7006,
    lng: 85.3117,
    elevation: 1310,
    entryFee: 'NPR 1,000 (foreigners) / NPR 500 (SAARC) / NPR 200 (Nepali citizens)',
    bestSeason: 'Oct–Apr (clearest views)',
    openingHours: '10:00 AM – 4:00 PM (closed Wednesdays)',
    howToGetThere: 'Located in the Sundhara area of central Kathmandu, 10 minutes\' walk from Kathmandu Durbar Square or New Road. Easily reached by taxi from Thamel (10 min, ~NPR 200).',
    gygQuery: 'Dharahara tower Kathmandu observation',
    bookingCity: 'Kathmandu',
    seoTitle: 'Dharahara Tower Kathmandu — Rebuilt Observation Tower Guide',
    seoDescription: 'Visit Dharahara, Kathmandu\'s rebuilt observation tower — 72 metres tall with a glass observation deck, museum, and 360-degree valley views. Destroyed in 2015, reborn in 2021.',
    published: true, featured: false, publishedAt: new Date(),
  },
  {
    name: 'Nagarkot',
    category: 'HILL_VIEWPOINT',
    summary: 'A hill station at 2,195 m on the eastern rim of the Kathmandu Valley, 32 km from the capital, renowned for one of the broadest Himalayan panoramas in Nepal spanning eight mountain ranges including Langtang, Gauri Shankar, and on clear days a glimpse of Everest.',
    story: `<p>Nagarkot is one of Nepal's most popular overnight destinations, perched at 2,195 metres on the northeastern rim of the Kathmandu Valley in Bhaktapur district. Its fame rests almost entirely on one spectacular attraction: the sunrise view of the Himalayas, when the first light of day paints the snow peaks in brilliant orange and red as the valley below remains shrouded in darkness.</p>
<p>On exceptionally clear days — most commonly in October and November after the monsoon, or in the early spring before the haze builds — the panorama from Nagarkot stretches across eight separate Himalayan ranges. You can pick out major peaks including Langtang Lirung (7,227 m), Dorje Lakpa, Ganesh Himal, Jugal Himal, Rolwaling range, Gauri Shankar, and on the clearest mornings, the white triangle of Everest (8,848.86 m) on the distant horizon.</p>
<p>The village has a good range of accommodation from budget guesthouses to pleasant hilltop resorts, all positioned to capture the mountain views. A concrete view tower near the army camp provides a 360-degree perspective.</p>
<h3>Getting the Best View</h3>
<ul>
  <li>Stay overnight — sunrise is the prime attraction</li>
  <li>Visit October–November for the clearest skies post-monsoon</li>
  <li>Hike to the hilltop view tower for 360-degree panoramas</li>
  <li>Combine with a hike down to Bhaktapur or Changu Narayan (3–4 hrs)</li>
</ul>`,
    district: 'Bhaktapur',
    province: 'BAGMATI',
    lat: 27.7152,
    lng: 85.5208,
    elevation: 2195,
    entryFee: 'NPR 350 (foreigners) / NPR 50 (Nepali citizens)',
    bestSeason: 'Oct–Nov (best Himalayan views); Mar–Apr also excellent',
    openingHours: 'Viewpoint accessible 24 hours; View Tower approx. 7:00 AM – 6:00 PM',
    howToGetThere: 'From Kathmandu, buses depart from Bhaktapur (30 min to Bhaktapur by local bus, then shared jeep/bus to Nagarkot). By taxi from Kathmandu: 45–60 min, ~NPR 1,500–2,000. Alternatively, hire a car for a day trip combining Bhaktapur and Nagarkot.',
    gygQuery: 'Nagarkot sunrise Himalayan view',
    bookingCity: 'Bhaktapur',
    seoTitle: 'Nagarkot Viewpoint — Best Himalayan Sunrise Near Kathmandu',
    seoDescription: 'Visit Nagarkot hill station for Nepal\'s most celebrated Himalayan sunrise views — 2,195 m on the Kathmandu Valley rim, 32 km from the capital, spanning eight mountain ranges.',
    published: true, featured: true, publishedAt: new Date(),
  },
  {
    name: 'Taudaha Lake',
    category: 'LAKE',
    summary: 'A serene natural lake in Kirtipur believed to be a remnant of the ancient sea that once filled the Kathmandu Valley, home to over 65 bird species and significant populations of migratory waterfowl, making it the valley\'s most accessible birdwatching spot.',
    story: `<p>Taudaha Lake sits at the southern edge of Kirtipur Municipality, about 8 km from central Kathmandu. In Buddhist mythology, it is the abode of Karkotaka — the serpent king left behind when the bodhisattva Manjushree cut the Chobar Gorge to drain the ancient lake that once filled the Kathmandu Valley. A small island in the lake is said to mark where Karkotaka resides.</p>
<p>The lake covers approximately 3.5 hectares and is edged by reeds, willows, and traditional farmland. In winter (November–February), it attracts impressive numbers of migratory waterbirds including pochards, teals, pintails, shovellers, coots, and spot-billed ducks. Over 65 bird species have been recorded here, making it a favourite destination for birdwatchers from Kathmandu.</p>
<p>The lake faces ongoing pressure from urban encroachment, dumping, and declining water quality as Kirtipur's surroundings develop. Conservation efforts are underway to protect the lake as a heritage and ecological site.</p>`,
    district: 'Kathmandu',
    province: 'BAGMATI',
    lat: 27.6484,
    lng: 85.2815,
    elevation: 1291,
    entryFee: 'NPR 100 (foreigners) / NPR 25 (SAARC) / Free (Nepali citizens)',
    bestSeason: 'Nov–Feb for migratory birds; Oct–Apr generally',
    openingHours: '9:00 AM – 5:00 PM (dawn visits for birdwatching possible)',
    howToGetThere: 'Located in Kirtipur, 8 km southwest of central Kathmandu. Take a local bus from Ratna Park towards Kirtipur (30 min), then walk 20 min south to the lake. By taxi from Thamel: 20–25 min, ~NPR 400–500.',
    gygQuery: 'Kathmandu birdwatching nature tour',
    bookingCity: 'Kathmandu',
    seoTitle: 'Taudaha Lake Kirtipur — Birdwatching & Nature near Kathmandu',
    seoDescription: 'Visit Taudaha Lake in Kirtipur, a sacred natural lake near Kathmandu home to 65+ bird species and winter migratory waterfowl — the valley\'s best accessible birdwatching spot.',
    published: true, featured: false, publishedAt: new Date(),
  },
  {
    name: 'Dhulikhel',
    category: 'HILL_VIEWPOINT',
    summary: 'A well-preserved Newari town at 1,550 m on the eastern rim of the Kathmandu Valley, 32 km from the capital, offering sweeping Himalayan panoramas from Langtang to Gauri Shankar, traditional architecture, ancient temples, and a gateway to Namobuddha.',
    story: `<p>Dhulikhel is one of the most rewarding day trips or overnight destinations from Kathmandu. The ancient Newari trading town sits on a ridge at the eastern edge of the Kathmandu Valley, on the historic Araniko Highway — the ancient trade route between Nepal and Tibet. Its position at 1,550 metres gives it outstanding views north to the full sweep of the central Himalaya.</p>
<p>The old town retains much of its traditional character: narrow paved lanes, carved wooden shopfronts, and ancient courtyards with small temples. The main viewpoint hill (reached by a 30-minute walk from the town centre) provides a spectacular 180-degree panorama of the Himalayan chain, including Langtang Lirung, Dorje Lakpa, Choba Bhamare, Gauri Shankar, and Numbur.</p>
<p>Dhulikhel serves as the ideal base for day hikes to Namobuddha (3–4 hours through countryside villages), and the area has several good resort hotels that attract those seeking a peaceful Himalayan-view retreat close to Kathmandu.</p>`,
    district: 'Kavrepalanchok',
    province: 'BAGMATI',
    lat: 27.6221,
    lng: 85.5428,
    elevation: 1550,
    entryFee: 'Free',
    bestSeason: 'Oct–Nov, Mar–May',
    openingHours: 'Open town; viewpoint accessible all hours',
    howToGetThere: 'Take a bus from Ratna Park or Koteshwor bus park to Dhulikhel (1.5 hrs, NPR 80–100), or hire a taxi (45 min, ~NPR 1,500). The town is also served by microbuses running along the Araniko Highway.',
    gygQuery: 'Dhulikhel Himalayan view Kathmandu day trip',
    bookingCity: 'Kathmandu',
    seoTitle: 'Dhulikhel — Himalayan Viewpoint & Newari Town near Kathmandu',
    seoDescription: 'Explore Dhulikhel, a well-preserved Newari town 32 km from Kathmandu with stunning Himalayan views, ancient temples, and the gateway to Namobuddha pilgrimage site.',
    published: true, featured: false, publishedAt: new Date(),
  },
  {
    name: 'National Botanical Garden Godawari',
    category: 'NATIONAL_PARK',
    summary: 'Nepal\'s premier botanical institution at the foot of Phulchowki hill in Lalitpur, established in 1962 and covering 80 hectares of manicured gardens, orchid houses, fern collections, and native Himalayan plants — popularly nicknamed "Switzerland Park".',
    story: `<p>The National Botanical Garden at Godawari, established in 1962 AD under the Department of Plant Resources, is Nepal's most important centre for plant conservation, research, and public education. Locally and colloquially known as "Switzerland Park" for its lush, manicured European-style garden aesthetic, the 80-hectare site sits at the foot of Phulchowki hill (2,782 m) in Godawari Municipality, Lalitpur, about 16 km south of Kathmandu.</p>
<p>The garden contains collections of over 1,000 plant species, with specialised areas including an orchid house (Nepal has over 400 orchid species), a fern garden, a Japanese garden section, tropical and subtropical greenhouse collections, and a rockery featuring high-altitude Himalayan plants. The rose garden and seasonal flower displays attract many Nepali families for weekend outings.</p>
<p>Birdwatchers appreciate the garden as a gateway to the Phulchowki hill forest, one of the most biodiverse birding sites in the Kathmandu Valley with over 240 recorded species. A forest trail leads up from the botanical garden to the Phulchowki summit (allow 4–5 hours round trip).</p>`,
    district: 'Lalitpur',
    province: 'BAGMATI',
    lat: 27.5918,
    lng: 85.3888,
    elevation: 1514,
    entryFee: 'NPR 500 (foreigners) / NPR 50 (Nepali citizens)',
    bestSeason: 'Mar–Apr (orchids and rhododendrons in bloom); Sep–Oct',
    openingHours: '9:30 AM – 5:00 PM (Nov–Feb closes 4:00 PM)',
    howToGetThere: 'Located in Godawari, 16 km south of Kathmandu. Take a bus from Lagankhel (Lalitpur) bus park (45 min, NPR 30–40) or a taxi from Kathmandu (~35 min, NPR 600–800). Ask for "Godawari Botanical Garden" or "Switzerland Park".',
    gygQuery: 'Godawari botanical garden Kathmandu',
    bookingCity: 'Kathmandu',
    seoTitle: 'National Botanical Garden Godawari ("Switzerland Park") — Lalitpur',
    seoDescription: 'Visit the National Botanical Garden at Godawari (locally called Switzerland Park) — Nepal\'s premier 80-hectare botanical institution with orchid houses, fern gardens, and Himalayan plant collections.',
    published: true, featured: false, publishedAt: new Date(),
  },
  {
    name: 'Bajrayogini Temple',
    category: 'TEMPLE',
    summary: 'One of the four principal Vajrayogini sacred sites in the Kathmandu Valley, a syncretic Tantric Buddhist-Hindu temple perched on the forested slopes of Manichuda hill in Sankhu, reached by a long carved stone stairway with origins dating to the 7th century.',
    story: `<p>Bajrayogini Temple in Sankhu (also spelled Vajrayogini) is one of the most important Tantric sites in the Kathmandu Valley. Vajrayogini is a powerful Buddhist deity of the highest yoga tantra class, but in Nepal's tradition of syncretic religious practice, the temple is venerated by both Buddhists and Hindus.</p>
<p>The current temple complex was substantially built by King Pratap Malla in the 17th century, though the sacred site dates to at least the 7th century CE. The temple is reached by a long stone stairway lined with devotional images, prayer wheels, and rest pavilions, climbing through forested slopes above the ancient trading town of Sankhu.</p>
<p>The lower town of Sankhu was catastrophically damaged in the 2015 earthquake, with many of its traditional Newari buildings destroyed. However, the hilltop temple complex survived in better condition and remains an active pilgrimage site. The annual Bajrayogini Jatra festival in the Nepali month of Chaitra (March–April) sees large processions and celebrations.</p>`,
    district: 'Kathmandu',
    province: 'BAGMATI',
    lat: 27.7438,
    lng: 85.4672,
    elevation: 1597,
    entryFee: 'Free',
    bestSeason: 'Mar–Apr (Jatra festival); Oct–Nov',
    openingHours: '6:00 AM – 6:00 PM daily',
    howToGetThere: 'Sankhu is 18 km northeast of Kathmandu. Take a local bus from Ratna Park (45 min, NPR 30) or a taxi (30–40 min, ~NPR 700–900). From Sankhu village, the temple is a 20–30 minute climb up the stone stairway.',
    gygQuery: 'Kathmandu Valley temple tour off the beaten path',
    bookingCity: 'Kathmandu',
    seoTitle: 'Bajrayogini Temple Sankhu — Ancient Tantric Shrine Kathmandu',
    seoDescription: 'Visit Bajrayogini Temple in Sankhu, one of the four principal Vajrayogini shrines in the Kathmandu Valley — a 7th-century Tantric site on a forested hill above an ancient Newari trading town.',
    published: true, featured: false, publishedAt: new Date(),
  },
  {
    name: 'Skywalk Tower',
    category: 'HILL_VIEWPOINT',
    summary: 'Nepal\'s first and tallest urban observation tower at 78.5 metres in central Kathmandu, opened in June 2023, featuring a glass-floored observation deck, high-speed elevator, rooftop restaurant, and 360-degree views of the Kathmandu Valley and Himalayas.',
    story: `<p>Skywalk Nepal, opened in June 2023, is a purpose-built urban observation tower in the Kamaladi area of central Kathmandu. Standing at 78.5 metres with 25 floors, it is the tallest modern tower in Nepal open to the public and was a direct response to growing demand for urban viewpoint experiences following the restoration of Dharahara.</p>
<p>The tower features a high-speed elevator, a glass-floored skywalk observation terrace extending beyond the main structure (the architectural highlight that gives the tower its name), a 360-degree enclosed viewing gallery, a rooftop restaurant and bar, and exhibition spaces on the lower floors. On clear days, the views extend over the Kathmandu Valley and north to the Himalayan peaks.</p>
<p>Unlike the historic Dharahara or the natural hilltop viewpoints around the valley, Skywalk Tower offers a contemporary urban tourism experience — the glass floor and skywalk terrace provide a thrilling perspective straight down to the city streets below.</p>`,
    district: 'Kathmandu',
    province: 'BAGMATI',
    lat: 27.7118,
    lng: 85.3185,
    elevation: 1335,
    entryFee: 'NPR 1,000 (adults) / NPR 500 (children 3–4 ft) / NPR 500 (seniors 70–80) / Free (80+)',
    bestSeason: 'Oct–Apr (clearest valley and mountain views)',
    openingHours: '8:00 AM – 8:00 PM daily',
    howToGetThere: 'Located in Kamaladi, central Kathmandu, adjacent to Rani Pokhari and Ghantaghar area. 15-minute walk from Thamel, 5 minutes by taxi. Near Ratna Park.',
    gygQuery: 'Kathmandu skywalk observation tower',
    bookingCity: 'Kathmandu',
    seoTitle: 'Skywalk Tower Kathmandu — Nepal\'s Tallest Observation Tower',
    seoDescription: 'Visit Skywalk Tower, Nepal\'s first urban observation tower in central Kathmandu — 78.5 metres tall with a glass skywalk deck, high-speed elevator, and 360-degree Himalayan views.',
    published: true, featured: false, publishedAt: new Date(),
  },
  {
    name: 'Gokarneshwor Mahadev Temple',
    category: 'TEMPLE',
    summary: 'An important three-tiered pagoda temple on the Bagmati River in Gokarna dedicated to Shiva, with Licchavi-era origins and an exceptional collection of stone sculptures, Nepal\'s equivalent of Gaya for performing ancestor rites (shraddha).',
    story: `<p>Gokarneshwor Mahadev Temple in Gokarna village, 8 km northeast of Kathmandu, is one of the most architecturally and artistically rich temples in the valley. Dedicated to Shiva as Mahadev, the three-tiered pagoda stands on the south bank of the Bagmati River in a position considered highly auspicious for the performance of Hindu death rites and ancestor ceremonies (shraddha).</p>
<p>The original shrine dates to at least the 4th century CE (Licchavi period), and the current temple structure was rebuilt in 1582 CE. The complex is decorated with an extraordinary collection of stone sculptures — divine figures, gandharvas (celestial musicians), erotic panels in the classic Newar artistic tradition, and Shiva lingams of various periods. Many of these sculptures are considered masterpieces of medieval Nepali religious art.</p>
<p>Each year on Gokarna Aunsi (the Nepali Father's Day in the month of Bhadra, approximately August–September), tens of thousands of Nepali pilgrims travel to Gokarneshwor to perform shraddha rites for deceased fathers, mirroring the practice at Gaya in Bihar, India. The river bank fills with priests, flower offerings, and devotees seeking blessings for their departed ancestors.</p>`,
    district: 'Kathmandu',
    province: 'BAGMATI',
    lat: 27.7394,
    lng: 85.3878,
    elevation: 1360,
    entryFee: 'Free (nominal donation suggested)',
    bestSeason: 'Year-round; Gokarna Aunsi (Aug/Sep) for major pilgrimage day',
    openingHours: '5:00 AM – 7:00 PM daily',
    howToGetThere: 'Located in Gokarna, 8 km northeast of central Kathmandu. Take a local bus from Ratna Park towards Jorpati/Gokarna (30–40 min), or taxi from Thamel (20–25 min, ~NPR 400–500). Often combined with Boudhanath or Kopan Monastery visits.',
    gygQuery: 'Kathmandu Hindu temple tour',
    bookingCity: 'Kathmandu',
    seoTitle: 'Gokarneshwor Mahadev Temple Kathmandu — Ancient Shiva Shrine',
    seoDescription: 'Visit Gokarneshwor Mahadev Temple in Gokarna, one of Kathmandu\'s most important Shiva temples with Licchavi-era origins and extraordinary stone sculptures on the Bagmati River.',
    published: true, featured: false, publishedAt: new Date(),
  },
  {
    name: 'Mahabuddha Temple',
    category: 'TEMPLE',
    summary: 'A stunning Shikhara-style terracotta tower in Patan entirely clad in fired bricks each stamped with a miniature Buddha image — the "Temple of Ten Thousand Buddhas" — modelled on India\'s Mahabodhi Temple at Bodhgaya and hidden in a narrow courtyard southeast of Patan Durbar Square.',
    story: `<p>Mahabuddha Temple (also spelled Mahabouddha) is one of Patan's most extraordinary architectural achievements, hidden away in a narrow courtyard a short walk southeast of Patan Durbar Square. Initiated around 1585 CE by a local priest named Abhaya Raj who had visited the Mahabodhi Temple at Bodhgaya, India, the tower is a Nepali interpretation of that famous Buddhist shrine — adapted in the Shikhara style using fired terracotta bricks.</p>
<p>What makes Mahabuddha unique is its surface: every brick is stamped with a miniature image of the seated Buddha, giving the structure its popular name "Temple of Ten Thousand Buddhas" (though the actual number of Buddha images runs into the thousands). The tower soars above the surrounding buildings, its terracotta facade weathered to rich ochre tones.</p>
<p>The temple was dismantled and rebuilt after the great 1934 earthquake. During reconstruction, the artisans found they had extra bricks remaining — these were used to build a smaller adjacent shrine dedicated to Maya Devi, the Buddha's mother, which stands beside the main tower. Finding the hidden courtyard is part of the adventure — ask locals to point you towards "Mahabuddha" in the Oku Bahal neighbourhood of Patan.</p>`,
    district: 'Lalitpur',
    province: 'BAGMATI',
    lat: 27.6709,
    lng: 85.3267,
    elevation: 1340,
    entryFee: 'NPR 50',
    bestSeason: 'Oct–Nov, Feb–Apr',
    openingHours: '9:00 AM – 5:00 PM',
    howToGetThere: 'Located in the Oku Bahal neighbourhood of Patan, southeast of Patan Durbar Square. Walk from the Durbar Square (10 min) through the narrow lanes — ask locals for directions to Mahabuddha as it is easy to miss. Combine with a Patan heritage walk.',
    gygQuery: 'Patan heritage walking tour Lalitpur',
    bookingCity: 'Kathmandu',
    seoTitle: 'Mahabuddha Temple Patan — Temple of Ten Thousand Buddhas',
    seoDescription: 'Discover Mahabuddha Temple in Patan, a stunning terracotta tower clad in thousands of miniature Buddha images — a hidden gem modelled on India\'s Mahabodhi Temple at Bodhgaya.',
    published: true, featured: false, publishedAt: new Date(),
  },
  {
    name: 'Uma Maheshwor Temple',
    category: 'TEMPLE',
    summary: 'A three-tiered pagoda temple on the highest point of Kirtipur hill dedicated to Shiva and Parvati, built in 1655 CE, offering panoramic views over the Kathmandu Valley and carrying the memory of Kirtipur\'s final stand against Prithvi Narayan Shah in 1768.',
    story: `<p>Uma Maheshwor Temple crowns the summit of Kirtipur hill, the ancient fortified town 5 km southwest of Kathmandu that was the last major obstacle to Prithvi Narayan Shah's conquest of the Kathmandu Valley in 1768. The temple, dedicated to the divine couple Shiva (Maheshwor) and Parvati (Uma), was built in 1655 CE during the reign of King Siddhi Narasingh Malla of Patan and has been restored several times since.</p>
<p>The three-tiered pagoda structure features fine woodcarvings and a location of profound historical resonance. It was near this hill that the people of Kirtipur mounted their most determined resistance to Prithvi Narayan Shah, and the town's eventual subjugation became one of the most remembered episodes in the founding of modern Nepal. The temple overlooks the Chobar Gorge where the Bagmati River cuts through the southern rim of the valley.</p>
<p>Kirtipur itself is well worth exploring on foot — a compact hilltop town with a distinct identity from Kathmandu, Patan, and Bhaktapur, preserving traditional Newari architecture, temples, and community festivals largely undisturbed by mass tourism.</p>`,
    district: 'Kathmandu',
    province: 'BAGMATI',
    lat: 27.6779,
    lng: 85.2788,
    elevation: 1416,
    entryFee: 'Free',
    bestSeason: 'Oct–Apr',
    openingHours: '4:00 AM – 10:00 PM daily',
    howToGetThere: 'Kirtipur is 5 km southwest of Kathmandu. Take a local bus from Ratna Park or Balkhu (30 min, NPR 25–30) or a taxi (20 min, ~NPR 350–450). Walk up through the town to the hilltop temple (10–15 min).',
    gygQuery: 'Kirtipur heritage walk Kathmandu',
    bookingCity: 'Kathmandu',
    seoTitle: 'Uma Maheshwor Temple Kirtipur — Hilltop Shiva Shrine with Valley Views',
    seoDescription: 'Visit Uma Maheshwor Temple on the summit of Kirtipur hill — a 1655 CE pagoda temple dedicated to Shiva and Parvati with panoramic Kathmandu Valley views and deep historical significance.',
    published: true, featured: false, publishedAt: new Date(),
  },
  {
    name: 'Pullahari Monastery',
    category: 'MONASTERY',
    summary: 'A hilltop Karma Kagyu retreat and monastic complex in Kopan, Kathmandu, constructed from 1987 and consecrated in 1992 under Jamgon Kongtrul Rinpoche, primarily functioning as a three-year retreat centre with sweeping views over the Kathmandu Valley.',
    story: `<p>Pullahari Monastery is one of Kathmandu's most serene monastic retreats, perched on a ridge in Jagdol Ward of Kopan between the better-known Kopan Monastery and the Kathmandu Valley edge. The monastery is of the Karma Kagyu tradition — distinct from the Drukpa Kagyu monasteries at White Gumba and Druk Amitabh.</p>
<p>Construction began in 1987 on land offered by Dabzang Rinpoche, and the monastery was formally consecrated in February 1992 under the Third Jamgon Kongtrul Rinpoche, one of the most eminent lamas of 20th-century Tibetan Buddhism, who had planned Pullahari as his principal teaching and retreat seat in Nepal. Following the Rinpoche's sudden death in 1992, the monastery continued under the guidance of successive Rinpoches and today functions primarily as a three-year retreat centre for monks of the Karma Kagyu lineage.</p>
<p>Respectful visitors may walk the monastery grounds during daylight hours, attend public teachings when offered, and enjoy the remarkable views over the northern Kathmandu Valley and toward the Himalayan foothills. The atmosphere is notably peaceful — less visited than Kopan, with a quieter contemplative quality.</p>`,
    district: 'Kathmandu',
    province: 'BAGMATI',
    lat: 27.7280,
    lng: 85.3620,
    elevation: 1550,
    entryFee: 'Free (donations appreciated)',
    bestSeason: 'Oct–Apr',
    openingHours: '10:00 AM – 4:00 PM for general visitors',
    howToGetThere: 'Located on the ridge near Kopan Monastery, north of Boudhanath. Take a taxi from Kathmandu (25 min, ~NPR 450) or walk from Boudhanath (45 min uphill). Ask for "Pullahari Monastery" or "Jamgon Kongtrul Monastery".',
    gygQuery: 'Kathmandu Buddhist monastery tour',
    bookingCity: 'Kathmandu',
    seoTitle: 'Pullahari Monastery Kathmandu — Karma Kagyu Retreat Centre',
    seoDescription: 'Visit Pullahari Monastery near Kopan in Kathmandu — a serene Karma Kagyu retreat centre founded in 1987 with panoramic valley views and a contemplative atmosphere.',
    published: true, featured: false, publishedAt: new Date(),
  },
]

async function main() {
  console.log(`🌱 Seeding batch 2 — ${places.length} places...`)
  for (const p of places) {
    const s = slug(p.name)
    await prisma.place.upsert({
      where: { slug: s },
      update: {},
      create: { ...p, slug: s },
    })
    console.log(`  ✅ ${p.name}`)
  }
  console.log('🌱 Batch 2 complete!')
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
