import 'dotenv/config'
import { PrismaClient } from '@prisma/client'
import slugify from 'slugify'

const prisma = new PrismaClient()
const slug = (n) => slugify(n, { lower: true, strict: true })

const places = [
  {
    name: `Kagbeni Village`,
    category: "CULTURAL_VILLAGE",
    summary: `Perched at 2,804 m where the Kali Gandaki and Jhong rivers meet, Kagbeni is a medieval walled village of narrow alleys, mud-brick houses, and the ancient Red Monastery. It marks the boundary between Lower and Upper Mustang, making it the last free-access point before the restricted permit zone begins.`,
    story: `<p>Kagbeni is one of Nepal's most atmospheric medieval settlements, a labyrinth of mud-brick lanes and flat-roofed houses that has changed little since the 15th century. Sitting at 2,804 metres at the dramatic confluence of the Kali Gandaki and Jhong rivers, the village commands a position of historic strategic importance: for centuries, trading caravans carrying salt north from India and wool and grain south from Tibet were obliged to pass through Kagbeni's narrow gateway.</p><p>The village's defining landmark is the Kag Chode Thupten Samphel Ling Gompa, popularly called the Red Monastery, founded around 1429 CE. Its ochre-red walls and fluttering prayer flags stand in vivid contrast to the parched grey landscape of the surrounding Mustang plateau. Inside, butter lamps cast a golden glow over century-old thangka paintings and imposing clay statues, the scent of juniper incense thick in the air. Monks conduct morning and evening prayer sessions that visitors are usually welcome to observe quietly.</p><p>Beyond the monastery, Kagbeni rewards slow exploration. Ancient irrigation channels still water small barley fields that turn green in summer, a startling contrast to the arid rock faces looming above. The village is dotted with chortens, mani walls, and carved doorways that speak of a deep Tibetan Buddhist heritage largely preserved because of Kagbeni's relative isolation from mainstream Nepal.</p><p>Kagbeni also serves as the gateway to Upper Mustang, the ancient kingdom of Lo whose capital Lo Manthang lies three days' walk to the north. All trekkers and jeep travellers heading into Upper Mustang must pass through Kagbeni's checkpoint. Even for those who do not hold the special permit for Upper Mustang, the village itself offers enough mystery: the sound of wind rushing through the Kali Gandaki gorge, the world's deepest river gorge flanked by Dhaulagiri and Annapurna, provides an unforgettable backdrop to evenings spent on rooftop terraces watching the peaks turn crimson at dusk.</p>`,
    district: `Mustang`,
    province: "GANDAKI",
    lat: 28.8167,
    lng: 83.7667,
    elevation: 2804,
    entryFee: `Free (Upper Mustang permit NPR 500/day required to continue north)`,
    bestSeason: `March–May and September–November`,
    openingHours: `Open all day; monastery 6:00–18:00`,
    howToGetThere: `Fly Pokhara–Jomsom then drive or trek 18 km north to Kagbeni; or drive Pokhara–Beni–Jomsom via Mustang Highway (approx 8–10 hours)`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Kagbeni Mustang Upper Mustang tour`,
    bookingCity: `Pokhara`,
    seoTitle: `Kagbeni Village Mustang: Medieval Gateway to Upper Mustang Nepal`,
    seoDescription: `Discover Kagbeni Village in Mustang, Nepal — a medieval walled settlement at 2,804 m on the Kali Gandaki, home to the 15th-century Red Monastery and gateway to the forbidden kingdom of Upper Mustang.`,
    published: true,
    featured: false,
  },
  {
    name: `Muktinath–Jomsom Trail`,
    category: "TREK_ROUTE",
    summary: `One of Nepal's oldest pilgrimage corridors, this ancient trail winds 56 km through the dramatic Kali Gandaki gorge past Kagbeni, Marpha, and apple orchards to Jomsom, following the historic Trans-Himalayan salt trade route. It is accessible to moderately fit walkers and offers majestic views of Dhaulagiri and Annapurna.`,
    story: `<p>Long before trekking became an industry, the Muktinath–Jomsom Trail was a lifeline of commerce and devotion. Salt harvested from the high Tibetan plateau was carried by yak caravans south through this corridor, while grains and manufactured goods made their way north. The ancient trail follows the Kali Gandaki River — whose gorge is the deepest in the world, dropping between Dhaulagiri at 8,167 m and Annapurna I at 8,091 m — creating a natural highway through the Himalayas that has been in continuous use for over 2,000 years.</p><p>The journey begins at the sacred Muktinath Temple at 3,760 metres, one of the holiest sites in both Hinduism and Tibetan Buddhism, where 108 water spouts and a perpetual natural flame draw pilgrims from across South Asia. From Muktinath the trail descends through the ochre cliffs of Jharkot, the medieval checkpoint village of Kagbeni, the apple and apricot orchards of Marpha, and past the whitewashed town of Jomsom nestled beside the Kali Gandaki.</p><p>Each day on the trail is a study in contrasts. Arid, wind-scoured desert landscapes give way suddenly to irrigated terraces bright with mustard flowers. Traditional Thakali inns — famed throughout Nepal for their hearty buckwheat pancakes and apple brandy — provide warm shelter against the afternoon gales that funnel reliably through the gorge from midday onward. The architecture of each village reflects the Tibetan cultural influence: flat roofs bearing stacked firewood, painted prayer stones along the path, and red-walled gompas marking every high point.</p><p>The trail today is rated easy to moderate, making it one of the most rewarding short treks in Nepal for visitors of all experience levels. It can be completed in five to six days from Muktinath to Jomsom, or walked in reverse. Side trips to Lupra cave monastery, Dhumba Lake, and the fossil beds of the Kali Gandaki add richness to an already exceptional journey.</p>`,
    district: `Mustang`,
    province: "GANDAKI",
    lat: 28.8198,
    lng: 83.8723,
    elevation: 3760,
    entryFee: `ACAP permit NPR 3,000; TIMS card NPR 2,000`,
    bestSeason: `March–May and September–November`,
    openingHours: `Trek year-round; avoid December–February for high winds and snow`,
    howToGetThere: `Fly Kathmandu or Pokhara to Jomsom (30 min); jeep or bus from Pokhara to Jomsom via Mustang Highway (8–10 hrs); trek from Muktinath end by jeep from Jomsom`,
    trekDays: 6,
    trekDifficulty: "EASY",
    trekMaxElevation: 3760,
    trekDistance: 56,
    trekStartPoint: `Muktinath (3,760 m)`,
    trekEndPoint: `Jomsom (2,720 m)`,
    trekHighlights: [`Muktinath Temple with 108 water spouts and eternal flame`, `World's deepest river gorge between Dhaulagiri and Annapurna`, `Medieval village of Kagbeni and the Red Monastery`, `Marpha orchard village and famous apple brandy`, `Fossil beds of Shaligram ammonites in the Kali Gandaki`],
    gygQuery: `Muktinath Jomsom trek Mustang Nepal`,
    bookingCity: `Pokhara`,
    seoTitle: `Muktinath–Jomsom Trail: Ancient Pilgrim Route through Mustang Nepal`,
    seoDescription: `Walk the historic Muktinath–Jomsom Trail through the world's deepest gorge, past Kagbeni's medieval monastery and Marpha's apple orchards on Nepal's legendary Trans-Himalayan salt trade route.`,
    published: true,
    featured: false,
  },
  {
    name: `Thorong La Pass`,
    category: "TREK_ROUTE",
    summary: `Standing at 5,416 m, Thorong La is the highest and most dramatic crossing on the Annapurna Circuit, a wind-swept mountain pass linking Manang to the sacred Muktinath Temple. The ten-hour crossing demands an alpine start at 4 am and rewards with sweeping views of the Annapurna and Dhaulagiri ranges.`,
    story: `<p>Thorong La Pass, at 5,416 metres above sea level, is the crown jewel of the Annapurna Circuit, a legendary crossing that has drawn adventurous walkers from around the world since the trek was first opened to foreigners in the 1970s. Located in the Damodar Himal on the boundary between Manang and Mustang districts, the pass is the single greatest challenge — and single greatest reward — of the entire circuit.</p><p>The crossing begins in darkness. Most trekkers depart Thorong High Camp at 4:00 or 5:00 am to beat the fierce afternoon winds that arrive without warning across the exposed ridge. In the beam of a headlamp, the trail climbs relentlessly through scree fields and frozen snowpack, the air growing noticeably thinner with every step. At 5,416 metres the oxygen concentration is roughly 52 percent of what exists at sea level, making even simple exertion feel laboured for the unacclimatised. A mandatory rest day in Manang at 3,540 m and the intermediate camp at Thorong Phedi (4,450 m) are strongly advised before attempting the crossing.</p><p>When the summit ridge comes into view and the prayer-flag-draped cairn marking the pass appears against a cobalt sky, the effort dissolves into elation. The panorama is staggering: Annapurna III, Gangapurna, Tilicho Peak, and Yakawa Kang fill the horizon, while the descent drops 1,600 vertical metres in one long sweep down to the pilgrimage town of Muktinath (3,760 m), where a warm meal and the sacred temple await.</p><p>The pass is generally open from late April through November, though early spring and late autumn crossings carry avalanche risk. Acute mountain sickness is a genuine danger, and any trekker showing symptoms of severe headache, vomiting, or ataxia must descend immediately. With proper acclimatisation and preparation, however, Thorong La ranks among the most achievable high-altitude accomplishments in the Himalaya, a moment of pure mountain joy that is relived long after the muscles have stopped aching.</p>`,
    district: `Mustang`,
    province: "GANDAKI",
    lat: 28.802,
    lng: 83.941,
    elevation: 5416,
    entryFee: `Included in ACAP permit (NPR 3,000) and TIMS card (NPR 2,000)`,
    bestSeason: `Late March–May and late September–November`,
    openingHours: `Best crossed 04:00–14:00 to avoid afternoon gales`,
    howToGetThere: `Trek from Besisahar along the Annapurna Circuit (9–12 days) to reach Thorong High Camp; then cross to Muktinath`,
    trekDays: 1,
    trekDifficulty: "HARD",
    trekMaxElevation: 5416,
    trekDistance: 16,
    trekStartPoint: `Thorong High Camp (4,925 m)`,
    trekEndPoint: `Muktinath (3,760 m)`,
    trekHighlights: [`Highest trekking pass on the Annapurna Circuit at 5,416 m`, `360-degree panorama of Annapurna and Dhaulagiri ranges`, `Pre-dawn alpine ascent by headlamp`, `Dramatic 1,600 m descent to sacred Muktinath Temple`, `Iconic prayer-flag cairn at the summit`],
    gygQuery: `Thorong La Pass Annapurna Circuit trek`,
    bookingCity: `Pokhara`,
    seoTitle: `Thorong La Pass (5,416 m): Annapurna Circuit's Highest Crossing Nepal`,
    seoDescription: `Cross Thorong La Pass at 5,416 m, the highest point on Nepal's famous Annapurna Circuit, with breathtaking Himalayan panoramas and a dramatic descent to the sacred temple of Muktinath.`,
    published: true,
    featured: false,
  },
  {
    name: `Manang Village`,
    category: "CULTURAL_VILLAGE",
    summary: `Nestled in a high-altitude valley at 3,540 m, Manang is the essential acclimatisation hub of the Annapurna Circuit, a compact Tibetan-influenced village surrounded by glacier-carved peaks including Annapurna III and Gangapurna. Trekkers spend a mandatory rest day here before tackling Thorong La Pass.`,
    story: `<p>Manang sits in a broad, glacially carved valley at 3,540 metres, ringed by some of the most dramatic mountain scenery on the entire Annapurna Circuit. The peaks of Annapurna III (7,555 m), Gangapurna (7,455 m), and Tilicho Peak (7,134 m) loom directly above the village, their glaciers calving ice into the valley below with periodic thundering booms that echo off the surrounding cliffs. The village is firmly in the rain shadow of the Annapurna massif, giving it a climate closer to the Tibetan plateau than to the lush foothills below.</p><p>Life in Manang revolves around the rhythms of high-altitude subsistence: yaks are herded to high pastures in summer, barley and buckwheat are cultivated on narrow terraces, and prayer flags snap constantly in the relentless plateau wind. The Himalayan Rescue Association maintains a medical post here and conducts daily altitude lectures during trekking season, a practical precaution given that the village sits at 65 percent of sea-level oxygen concentration. Attending the lecture is free and strongly recommended for all trekkers planning to cross Thorong La.</p><p>The standard Annapurna Circuit itinerary calls for two nights in Manang with one full acclimatisation day. The classic day hike climbs to Ice Lake at 4,620 metres, a stunning alpine lake cradled in a high cirque offering perhaps the finest panoramic views on the entire circuit. Shorter options include the walk up to the abandoned village of Ghyaru and Ngawal on the upper ridge, or a visit to the small Bodzo Gompa monastery that has watched over Manang for centuries.</p><p>In the evenings, the village's teahouses fill with trekkers from every corner of the globe, swapping stories over bowls of tsampa porridge and cups of butter tea. It is a democratic, convivial community that forms only at altitude, dissolving again as the trail continues upward toward the pass. Manang reminds every trekker that the mountains set the pace, and that patience and preparation are virtues well rewarded here.</p>`,
    district: `Manang`,
    province: "GANDAKI",
    lat: 28.6667,
    lng: 84.0167,
    elevation: 3540,
    entryFee: `Included in ACAP permit (NPR 3,000) and TIMS card (NPR 2,000)`,
    bestSeason: `March–May and September–November`,
    openingHours: `Village accessible year-round; HRA clinic open during trekking season`,
    howToGetThere: `Trek from Besisahar along the Annapurna Circuit (approximately 7–9 days); or drive from Chame by jeep in season`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Manang Annapurna Circuit trek acclimatization`,
    bookingCity: `Pokhara`,
    seoTitle: `Manang Village Nepal: Annapurna Circuit Acclimatisation Hub at 3,540 m`,
    seoDescription: `Explore Manang Village on the Annapurna Circuit at 3,540 m — a Tibetan-influenced mountain settlement surrounded by glaciers and high peaks, and the essential acclimatisation stop before Thorong La Pass.`,
    published: true,
    featured: false,
  },
  {
    name: `Pisang Village`,
    category: "CULTURAL_VILLAGE",
    summary: `Divided into photogenic Upper and Lower sections at 3,200–3,300 m, Pisang is one of the most charming stops on the Annapurna Circuit, where traditional Tibetan architecture, ancient monasteries, and views of Pisang Peak rising sharply overhead create an unforgettable mountain village experience.`,
    story: `<p>Pisang Village marks the transition point on the Annapurna Circuit from the subtropical Marsyangdi River valley into the high-altitude Tibetan cultural zone. At around 3,200 metres, the vegetation thins, the sky deepens to a richer blue, and the architecture shifts dramatically: mud-brick walls replace stone, prayer wheels line every path, and the bold pyramid of Pisang Peak (6,091 m) dominates the skyline like a sentinel.</p><p>The village is divided into two distinct sections with quite different characters. Lower Pisang, clustered along the main trekking trail beside the river, serves as the practical hub with teahouses, shops, and permit checkpoints. Upper Pisang, reached by a steeper path climbing 100 metres above the valley floor, is quieter and more traditional, a medieval-feeling cluster of flat-roofed houses with an ancient gompa overlooking the entire valley. Trekkers who make the extra effort to stay in Upper Pisang are rewarded with one of the finest sunrise views on the circuit, as the golden light first strikes Annapurna II and Pisang Peak while the valley below remains in blue shadow.</p><p>The surrounding landscape reflects the classic Tibetan rain-shadow climate: dry, open, and dramatic. Chortens dot the ridgelines, mani walls border the paths, and the cultivated fields of barley, buckwheat, and potatoes are protected by elaborate irrigation systems that have functioned without interruption for generations. Locals here are predominantly Gurung and Tibetan-influenced communities whose cultural traditions remain strong despite the steady flow of trekkers passing through each season.</p><p>From Pisang, the circuit continues toward the high route via Ngawal and Ghyaru, a spectacular alternative that climbs above the valley for panoramic views before rejoining the main trail near Manang. Pisang's position makes it an ideal overnight stop between the lower forests of Chame and the high-altitude world that begins above Manang, and few trekkers who spend a night here forget the sight of a full moon rising over Pisang Peak.</p>`,
    district: `Manang`,
    province: "GANDAKI",
    lat: 28.6307,
    lng: 84.1107,
    elevation: 3200,
    entryFee: `Included in ACAP permit (NPR 3,000) and TIMS card (NPR 2,000)`,
    bestSeason: `March–May and September–November`,
    openingHours: `Village accessible all day`,
    howToGetThere: `Trek from Besisahar along the Annapurna Circuit (approximately 5–6 days); road access from Chame passable by jeep in season`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Pisang Village Annapurna Circuit Manang Nepal`,
    bookingCity: `Pokhara`,
    seoTitle: `Pisang Village Annapurna Circuit: Tibetan Culture & Mountain Views Nepal`,
    seoDescription: `Visit Pisang Village on Nepal's Annapurna Circuit — a traditional Tibetan-style settlement at 3,200 m with stunning views of Pisang Peak, ancient monasteries, and a choice of upper and lower village stays.`,
    published: true,
    featured: false,
  },
  {
    name: `Besisahar`,
    category: "CULTURAL_VILLAGE",
    summary: `At just 760 m above sea level, Besisahar is the traditional gateway town and starting point of the world-famous Annapurna Circuit trek, a lively Lamjung bazaar on the Marsyangdi River offering easy road access from Pokhara and Kathmandu. It provides all essential trekking supplies and permit services.`,
    story: `<p>Besisahar occupies a strategic position in the hills of Lamjung where the Marsyangdi River emerges from its deep gorge and the road from Pokhara ends — or rather, begins — for thousands of trekkers each year. At 760 metres, the town sits in a subtropical climate of deciduous forests and terraced rice fields, giving little hint of the extreme altitudes awaiting those who walk north into the Annapurna massif. The surrounding hills are covered in rhododendron and oak, the air warm and humid, the birdsong loud and complex: a world away from the wind-scoured passes that define the circuit's high sections.</p><p>The town itself is a functional, hospitable bazaar. Trekking agencies, gear shops, permit offices, banks, and a well-stocked medical post line the main street, catering to the steady stream of trekkers, porters, and mule teams that flow through each day during the trekking seasons. ACAP entry permits can be obtained here at the checkpoint, and porters can be hired in the main bazaar. The town also serves as the starting point for the Manaslu Circuit Trek, which branches west from Besisahar toward the restricted Tsum Valley.</p><p>A short walk through town reveals a more settled, agricultural community beneath the trekking infrastructure. Gurung and Brahmin families have farmed these terraces for generations, and local festivals such as Ghode Jatra and Tihar fill the streets with colour and music during autumn. The Marsyangdi River, which the Annapurna Circuit follows northward for many days, is already impressive at Besisahar: wide, braided, and rushing with glacial meltwater from the high peaks invisible beyond the forest ridges above.</p><p>For trekkers arriving by bus or jeep from Pokhara — a four-hour journey — Besisahar represents the end of motorised comfort and the beginning of one of the world's great walking journeys. Those who camp here the night before setting out often note a particular anticipatory quality in the evening air, as though the mountains are already calling from their unseen heights to the north.</p>`,
    district: `Lamjung`,
    province: "GANDAKI",
    lat: 28.2307,
    lng: 84.371,
    elevation: 760,
    entryFee: `ACAP permit NPR 3,000 (obtainable here); TIMS card NPR 2,000`,
    bestSeason: `March–May and September–November`,
    openingHours: `Town open all hours; permit offices 07:00–17:00`,
    howToGetThere: `Bus or jeep from Pokhara (approx 4 hrs); bus from Kathmandu via Dumre junction (approx 6–7 hrs)`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Besisahar Annapurna Circuit start Nepal trek`,
    bookingCity: `Pokhara`,
    seoTitle: `Besisahar: Gateway to the Annapurna Circuit Trek Nepal`,
    seoDescription: `Besisahar in Lamjung is the traditional starting point of the Annapurna Circuit, Nepal's most celebrated trek, offering easy access from Pokhara and all trekking permit services.`,
    published: true,
    featured: false,
  },
  {
    name: `Baglung`,
    category: "HILL_VIEWPOINT",
    summary: `Perched on a ridge at 1,552 m above the holy Kali Gandaki River, Baglung is an increasingly important trekking hub in western Gandaki Province, serving as the primary gateway to the remote Dhorpatan Hunting Reserve, Dolpo, and lesser-trodden trails of the Dhaulagiri foothills.`,
    story: `<p>Baglung district headquarters sits on a broad plateau overlooking the Kali Gandaki, one of Nepal's most sacred rivers, at an elevation of 1,552 metres. The town commands sweeping views of the surrounding Gandaki hills and, on clear days, glimpses of the distant Dhaulagiri massif rising white and immense to the north. It is a growing bazaar town that has long served as an administrative and commercial centre for western Nepal, and it is increasingly recognised as a serious trekking hub with access to some of the country's most pristine and least-visited wilderness.</p><p>The most significant draw for adventurers is the road and trail network leading north and west toward Dhorpatan, Nepal's only hunting reserve, located in a spectacular east-west valley at 3,900 metres at the foot of the Dhaulagiri range. The reserve covers 1,325 square kilometres shared across Baglung, Myagdi, and Rukum districts, sheltering blue sheep, Himalayan tahr, snow leopard, and musk deer. The approach from Baglung through Burtibang passes through beautiful terraced hill country and rhododendron forests little visited by tourists.</p><p>Baglung town itself merits a day of exploration. The Baglung Bazaar along the river is a lively market where farmers from surrounding villages sell seasonal produce, and the suspension footbridge over the Kali Gandaki — once one of the longest in the world — connects the town to Beni and onward routes to Mustang. The town has an important regional hospital, a campus of Pokhara University, and a growing hotel industry catering to trekking groups heading toward Dhorpatan and Dolpo.</p><p>For travellers seeking an authentic Nepali hill town with genuine adventure potential and without the heavy tourist infrastructure of Pokhara, Baglung offers a compelling alternative base. The surrounding district is rich in waterfalls, traditional Magar villages, and forested ridgelines perfect for shorter day hikes, making it a worthwhile destination in its own right rather than merely a transit point.</p>`,
    district: `Baglung`,
    province: "GANDAKI",
    lat: 28.2719,
    lng: 83.5898,
    elevation: 1552,
    entryFee: `Free; Dhorpatan entry fees apply for reserve access`,
    bestSeason: `October–April`,
    openingHours: `Town open all day`,
    howToGetThere: `Bus from Pokhara via Beni (approx 5–6 hrs); jeep from Beni (approx 1–2 hrs); no scheduled flights currently`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Baglung Dhorpatan trek western Nepal`,
    bookingCity: `Pokhara`,
    seoTitle: `Baglung Nepal: Gateway to Dhorpatan & Western Himalayan Trekking`,
    seoDescription: `Baglung in Gandaki Province is a scenic hill town at 1,552 m and the primary gateway to the Dhorpatan Hunting Reserve and Dolpo trails, offering authentic western Nepal trekking adventures.`,
    published: true,
    featured: false,
  },
  {
    name: `Waling`,
    category: "CULTURAL_VILLAGE",
    summary: `A charming market town at 800 m on the Andhikhola River in Syangja district, Waling is emerging as a quiet heritage destination surrounded by ginger and coffee farms, traditional Licchavi-era trails, and forested hills offering paragliding and village-tourism experiences away from the main tourist circuit.`,
    story: `<p>Waling sits in the Andhikhola valley of Syangja district at around 800 metres above sea level, a point where the foothills of Gandaki Province display their quieter, more agricultural character. The Andhikhola River, according to local folk legend connected to the story of Shravan from the Ramayana, bisects the valley in a rush of clear mountain water that feeds the surrounding farmland and powers small mills along its banks. The town is not grand or dramatic, but it is genuine — a place where Nepali hill-town life unfolds at its own unhurried pace.</p><p>Waling has been famous across western Nepal as a major ginger-producing area, its bright-orange rhizomes packed into jute sacks and carried to markets in Pokhara and beyond. More recently, the surrounding hills have attracted attention for a different crop entirely: high-altitude organic coffee. Small-holder farmers on the slopes above Waling are producing beans that have found their way to specialty roasters in the United States, Japan, and Europe, drawing food enthusiasts and agricultural tourists who want to trace their morning cup to its source.</p><p>Ancient trails dating to the Licchavi period thread through the forests and villages surrounding Waling, connecting communities that have traded and visited along these paths for fifteen hundred years. These routes are now being revived as heritage trekking corridors, offering visitors multi-day walks through genuinely rural Nepal largely untouched by commercial tourism. The forested ridgelines above the valley are also suitable for paragliding, a sport gradually taking root in the hills of Syangja as instructors trained in Pokhara bring their skills to new launch sites.</p><p>Waling Municipality is investing in homestay programs and community tourism infrastructure, and visitors who spend a night with a local family gain access to the rhythms of Nepali hill life — morning tea with fresh ginger, evenings around a wood fire, and the extraordinary quiet of a mountain town when the bazaar closes and the stars come out over the Andhikhola valley.</p>`,
    district: `Syangja`,
    province: "GANDAKI",
    lat: 27.9889,
    lng: 83.7675,
    elevation: 800,
    entryFee: `Free`,
    bestSeason: `October–May`,
    openingHours: `Town open all day`,
    howToGetThere: `Bus from Pokhara (approx 2–3 hrs) via Siddhartha Highway; also accessible from Butwal direction`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Syangja Waling village trek coffee farm Nepal`,
    bookingCity: `Pokhara`,
    seoTitle: `Waling Syangja Nepal: Heritage Trails, Coffee Farms & Village Tourism`,
    seoDescription: `Visit Waling in Syangja, Gandaki Province — a peaceful Nepali hill town famous for ginger and organic coffee, with ancient Licchavi-era trails and emerging village-tourism experiences.`,
    published: true,
    featured: false,
  },
  {
    name: `Butwal`,
    category: "CULTURAL_VILLAGE",
    summary: `Butwal is a major commercial and transit city in Rupandehi at around 200 m elevation, positioned at the critical junction of the Mahendra and Siddhartha highways. It serves as the main gateway to Lumbini, Tansen and the hills of western Nepal, and is a busy, growing hub with a rich river-front character.`,
    story: `<p>Butwal occupies one of the most strategically important positions in Nepal's road network: the junction where the Mahendra Highway (running east–west across the Terai) meets the Siddhartha Highway (climbing north into the hills toward Tansen, Pokhara, and ultimately Mustang). This location has made Butwal one of the most important commercial and transit cities in western Nepal, a place through which an extraordinary volume of goods, vehicles, and people move each day.</p><p>The city sits at approximately 200 metres above sea level on the banks of the Tinau River, which rushes out of the Siwalik Hills just north of town before spreading across the flat Terai plains. The Tinau Riverfront has become a focal point for leisure and recreation, with a promenade, parks, and restaurants giving Butwal a pleasant public face that belies its reputation as primarily a transit stop. The city's main bazaars are dense, energetic, and full of the commercial vitality of a place that has been an important crossroads for centuries.</p><p>Butwal serves as the practical gateway to the UNESCO World Heritage Site of Lumbini (approximately 22 km west), and most travellers heading to the birthplace of the Buddha pass through or stop in the city. It is also the most convenient base for visiting Tansen (80 km north by the Siddhartha Highway), the historic Newari hill town famous for its metalwork and Rani Mahal. For travellers coming from India via the Sunauli border crossing, Butwal is often the first substantial Nepali city encountered.</p><p>The city is growing rapidly, with new hospitals, colleges, industrial estates, and hotel developments transforming it from a mere transit hub into a substantial urban centre. The Tinau corridor north of Butwal into the Siwalik hills offers pleasant cycling and motorbike day trips, and the surrounding Terai is notable for bird watching along the river edges where kingfishers, herons, and seasonal waterfowl congregate in large numbers.</p>`,
    district: `Rupandehi`,
    province: "LUMBINI",
    lat: 27.7004,
    lng: 83.4658,
    elevation: 200,
    entryFee: `Free`,
    bestSeason: `October–March`,
    openingHours: `City open all hours`,
    howToGetThere: `Bus from Kathmandu (approx 7–8 hrs) or Pokhara (approx 4–5 hrs); 5 km from Sunauli/Bhairahawa border crossing from India; domestic flights to Bhairahawa Airport (22 km)`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Butwal Lumbini tour Siddhartha Highway Nepal`,
    bookingCity: `Bhairahawa`,
    seoTitle: `Butwal Nepal: Gateway City to Lumbini, Tansen & Western Hills`,
    seoDescription: `Butwal in Rupandehi is Nepal's key highway junction city, serving as the main gateway to Lumbini's UNESCO heritage site, Tansen's Newari culture, and the Siddhartha Highway into the western hills.`,
    published: true,
    featured: false,
  },
  {
    name: `Tilaurakot`,
    category: "ARCHAEOLOGICAL",
    summary: `Tilaurakot is the ancient fortified capital of the Shakya kingdom where Prince Siddhartha Gautama — the future Buddha — is believed to have spent the first 29 years of his life before his great renunciation. The UNESCO-listed site preserves palace ruins, city walls, gateways, and stupas dating to the 6th–5th centuries BCE.`,
    story: `<p>Tilaurakot stands as one of the most evocative archaeological sites in South Asia: a carefully excavated fortified city where, according to Buddhist tradition and a growing body of archaeological evidence, the young prince Siddhartha Gautama grew up before abandoning royal life to seek enlightenment. The site covers a citadel area of 500 by 400 metres within an earth-and-brick fortification wall, and excavations since the 19th century have revealed palace complexes, monastery ruins, stupas, a central pond, and the famous Eastern Gate through which Siddhartha is said to have departed on his final journey into the world beyond.</p><p>The Western Gate, one of the most moving features of the site, marks the point where the prince first encountered the realities of aging, sickness, death, and renunciation that prompted his spiritual journey — the legendary 'Four Sights' described in the Pali Canon. Walking through the original gate structures today, even in their ruined state, creates a palpable connection to one of the most significant moments in human spiritual history. Samples collected from the site in 2015 confirmed continuous human settlement dating back to the 8th century BCE, supporting Tilaurakot's identification as Kapilavastu, the Shakya capital.</p><p>The site was listed on UNESCO's World Heritage Tentative List in 1996 and remains a pilgrimage destination for Buddhists from around the world, particularly from Japan, South Korea, Sri Lanka, and Thailand. The adjacent Tilaurakot Museum houses artefacts recovered from the site including terracotta figurines, coins, and decorated bricks that bring the ancient city to life with remarkable clarity.</p><p>The surrounding landscape of the Kapilvastu district is dotted with related archaeological sites, including the Kudan Stupa complex 5 km to the east — believed to mark the spot where Buddha returned to visit his father after achieving enlightenment — making Tilaurakot the centrepiece of a broader pilgrimage circuit that rewards a full day's exploration.</p>`,
    district: `Kapilvastu`,
    province: "LUMBINI",
    lat: 27.575,
    lng: 83.05,
    elevation: 250,
    entryFee: `NPR 100 for foreign nationals; NPR 50 for SAARC nationals; free for Nepali citizens`,
    bestSeason: `October–March`,
    openingHours: `07:00–17:00 daily`,
    howToGetThere: `Drive from Bhairahawa (Lumbini) approx 30 km west to Taulihawa, then 2 km to Tilaurakot; buses and shared jeeps from Bhairahawa to Taulihawa`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Tilaurakot Kapilvastu ancient capital Buddha Nepal`,
    bookingCity: `Lumbini`,
    seoTitle: `Tilaurakot Nepal: Ancient Shakya Capital & Siddhartha's Childhood Home`,
    seoDescription: `Explore Tilaurakot in Kapilvastu — the archaeological remains of the Shakya kingdom capital where Prince Siddhartha Gautama spent his first 29 years before becoming the Buddha, on UNESCO's tentative heritage list.`,
    published: true,
    featured: false,
  },
  {
    name: `Ramagrama Stupa`,
    category: "STUPA",
    summary: `Ramagrama Stupa in Nawalparasi is the only one of the original eight stupas built to enshrine the Buddha's cremated relics that has never been disturbed, making it the most sacred and rare of all Buddhist stupas in the world. It sits on the UNESCO World Heritage Tentative List and is surrounded by serene countryside 50 km from Lumbini.`,
    story: `<p>When Gautama Buddha passed into final Nirvana around 480 BCE, his cremated remains were divided among eight ruling clans of the Gangetic plains, each of whom constructed a great stupa to enshrine their portion. These eight original reliquary mounds were the most sacred objects in early Buddhism. Over subsequent centuries, Emperor Ashoka the Great, who had converted to Buddhism after the bloody Kalinga war, sought to retrieve the relics from all eight stupas to redistribute them in a vast network of new shrines across his empire. He succeeded at seven of them.</p><p>At Ramagrama, however, the great emperor was turned back. The Buddhist text Mahavamsa records that when Ashoka's delegation arrived at the Ramagrama stupa, they encountered a powerful Naga — a serpent deity of immense spiritual power — who had been guarding the relics for generations and who convinced Ashoka that the Buddha's wishes were best served by leaving the stupa undisturbed. The relics of Ramagrama have remained sealed ever since, making this the sole original relic stupa in existence, its core unexcavated to this day.</p><p>The stupa sits in the quiet countryside of Ramgram Municipality in Nawalparasi district, approximately 50 km east of Lumbini. The mound, though not imposing in size, radiates an extraordinary atmosphere of antiquity and sacredness. Buddhist pilgrims from Sri Lanka, Japan, Myanmar, and Thailand visit regularly, walking clockwise around the stupa while chanting suttas, and the surrounding grounds are kept as a simple park with grassy lawns and mature trees that shade meditating visitors.</p><p>Archaeological research places the stupa's construction between the Mauryan and Gupta periods, with roots going back to around 600 BCE. The site was placed on UNESCO's World Heritage Tentative List in 1996 and remains one of the most spiritually significant yet least-visited of all Buddhist pilgrimage sites in Nepal, a hidden jewel for those willing to venture beyond Lumbini's main complex.</p>`,
    district: `Nawalparasi West`,
    province: "LUMBINI",
    lat: 27.4978,
    lng: 83.6811,
    elevation: 95,
    entryFee: `Free`,
    bestSeason: `October–March`,
    openingHours: `Open all day`,
    howToGetThere: `Drive from Bhairahawa approx 50 km east via Sunwal; take bus or jeep from Bhairahawa toward Nawalpur and alight at Ramgram junction, then 2 km to stupa`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Ramagrama Stupa Buddha relics Lumbini Nepal pilgrimage`,
    bookingCity: `Lumbini`,
    seoTitle: `Ramagrama Stupa Nepal: World's Only Undisturbed Original Buddha Relic Stupa`,
    seoDescription: `Visit Ramagrama Stupa in Nawalparasi — the world's sole remaining undisturbed original stupa containing relics of Gautama Buddha, on the UNESCO tentative heritage list near Lumbini, Nepal.`,
    published: true,
    featured: false,
  },
  {
    name: `Nepalgunj`,
    category: "CULTURAL_VILLAGE",
    summary: `Nepalgunj is a major sub-metropolitan city and domestic aviation hub in Banke district at 165 m elevation, serving as the primary gateway to Nepal's remote western and far-western regions including Bardia, Rara Lake, Dolpo, and Humla. It blends a vibrant Terai bazaar culture with influences from the nearby Indian border.`,
    story: `<p>Nepalgunj sits on the flat Terai plains of Banke district, barely 6 kilometres from the India border at Jamunaha, at an elevation of just 165 metres. It is not a Himalayan destination in the conventional sense, but it is an absolutely essential one for anyone seeking to explore Nepal's wild and largely roadless western regions. The Nepalgunj Airport handles ten to twenty flights daily and is one of the few Nepali airports equipped for night operations, making it a far more reliable hub than most domestic airports during periods of bad weather or disruption.</p><p>From Nepalgunj, small aircraft depart daily for Jumla, Simikot, Dolpo, and other remote airstrips that serve communities reachable no other way. Trekkers heading to Rara Lake — Nepal's largest lake, set in a remote national park at 2,990 metres — almost always route through Nepalgunj. The same is true for those attempting the Humla district trek to Mount Kailash in Tibet, the restricted Dolpo circuit, or the Mugu district wilderness. In this sense, Nepalgunj punches far above its modest appearance as a Terai bazaar town.</p><p>The city itself is a fascinating hybrid of cultures. Its majority Muslim population, concentrated around the old bazaar, gives the town a distinct character compared to elsewhere in Nepal: mosques mingle with Hindu temples along narrow lanes, the call to prayer sounds five times daily, and the market specialises in goods that flow back and forth across the porous border. The evening bazaar near Bheri Chowk is one of the most authentic market experiences in western Nepal, piled with spices, fabrics, agricultural tools, and street food.</p><p>Bardia National Park — a world-class wildlife sanctuary with some of Nepal's best tiger, rhino, and elephant sightings — is accessible by road in about 1.5 hours from Nepalgunj, making the city a natural base for wildlife safari visits. The combination of frontier city character, cultural diversity, and role as a gateway to some of Nepal's greatest wilderness makes Nepalgunj far more interesting than its location suggests.</p>`,
    district: `Banke`,
    province: "LUMBINI",
    lat: 28.05,
    lng: 81.6167,
    elevation: 165,
    entryFee: `Free`,
    bestSeason: `October–March (avoid May–August heat)`,
    openingHours: `City open all hours; airport operations 06:00–20:00`,
    howToGetThere: `Daily domestic flights from Kathmandu (50 min) and Pokhara; overnight bus from Kathmandu (10–12 hrs) via Kohalpur junction`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Nepalgunj western Nepal Bardia Rara Lake gateway flight`,
    bookingCity: `Nepalgunj`,
    seoTitle: `Nepalgunj Nepal: Gateway to Bardia, Rara Lake & Remote Western Nepal`,
    seoDescription: `Nepalgunj in Banke, Lumbini Province is the main domestic aviation hub and gateway city for Nepal's remote western regions including Bardia National Park, Rara Lake, Dolpo, and Humla.`,
    published: true,
    featured: false,
  },
  {
    name: `Thakurdwara`,
    category: "NATIONAL_PARK",
    summary: `Thakurdwara is the small buffer-zone village that serves as the headquarters and primary entry point for Bardia National Park — Nepal's largest and least-visited national park, home to Bengal tigers, one-horned rhinos, wild elephants, and gharial crocodiles in pristine Terai jungle habitat.`,
    story: `<p>Thakurdwara is the kind of village that exists entirely because of what surrounds it. A small settlement of lodges, restaurants, and guide services clustered along the forest edge of Bardia National Park, it owes its modest prosperity to the extraordinary wildlife that roams the sal and grassland forests stretching away from its doorstep. The park headquarters, permit office, and army checkpost are all located here, making Thakurdwara the unavoidable gateway through which every visitor to Bardia must pass.</p><p>Bardia National Park, which begins literally at the village boundary, covers 968 square kilometres of pristine Terai wilderness — Nepal's largest national park and arguably its finest wildlife destination. Unlike Chitwan, which is well-known and heavily visited, Bardia receives a fraction of the tourist traffic, meaning that game drives, walking safaris, and canoe trips here have a genuine quality of discovery rather than performance. Bengal tiger sightings, while never guaranteed anywhere, are more frequent at Bardia than almost any other park in Nepal due to the recovering tiger population now numbering over 125 individuals.</p><p>The surrounding Tharu community villages in the buffer zone add a powerful cultural dimension to a Bardia visit. The Tharu people, who have inhabited these forests for centuries and developed a remarkable immunity to the malaria that long kept outsiders away, maintain traditions of woodcarving, stick dancing, and textile weaving that distinguish their culture from any other in Nepal. Community homestays in the buffer zone allow visitors to participate in evening Tharu cultural programmes and morning farm walks before heading into the park for wildlife activities.</p><p>The Babai River, which flows through the heart of the park, offers magical canoe safaris through corridors of overhanging forest where gharial crocodiles bask on sandbanks and the calls of fishing eagles echo across the water. Thakurdwara is the launch point for all of these experiences, a village that in its quietness and directness feels like an antidote to the commercialised safari circuits elsewhere in South Asia.</p>`,
    district: `Bardiya`,
    province: "LUMBINI",
    lat: 28.3827,
    lng: 81.396,
    elevation: 150,
    entryFee: `Bardia NP entry NPR 3,000 (foreign); NPR 1,500 (SAARC); NPR 100 (Nepali)`,
    bestSeason: `October–March and June (pre-monsoon)`,
    openingHours: `Park 06:00–18:00; village accessible all hours`,
    howToGetThere: `Drive from Nepalgunj approx 1.5 hrs (100 km); bus from Kathmandu to Ambasa junction then local transport; overnight buses from major cities stop at Kohalpur near Nepalgunj`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Bardia National Park tiger safari Thakurdwara Nepal`,
    bookingCity: `Nepalgunj`,
    seoTitle: `Thakurdwara: Gateway to Bardia National Park Tiger Safari Nepal`,
    seoDescription: `Thakurdwara village is the base for exploring Bardia National Park in Lumbini Province — Nepal's largest national park offering Bengal tiger tracking, rhino sightings, and authentic Tharu cultural experiences.`,
    published: true,
    featured: false,
  },
  {
    name: `Dang Valley`,
    category: "CULTURAL_VILLAGE",
    summary: `Dang is the second-largest valley in Asia, a sweeping inner Terai basin in Lumbini Province enclosed by the Siwalik and Mahabharata ranges at 600–700 m elevation. It is the heartland of Tharu culture, home to ancient temples, the Babai River, and the vibrant market cities of Ghorahi and Tulsipur.`,
    story: `<p>Dang Valley unfolds as one of Nepal's great geographical surprises: an enormous, fertile basin — the second-largest valley in Asia — tucked between the Siwalik Hills to the south and the Mahabharata Range to the north, entirely enclosed by forested ridges yet lying at modest elevations of 600 to 700 metres in the western Terai lowlands. The valley stretches for roughly 60 kilometres east to west and 20 kilometres north to south, its flat floor divided between irrigated rice and wheat fields, riverine forests along the Babai River, and the expanding urban centres of Ghorahi and Tulsipur.</p><p>Dang is above all the homeland of the Tharu people, one of Nepal's indigenous communities with a history in the Terai stretching back thousands of years. The Tharu developed a remarkable coexistence with the malaria-laden jungle environment that kept outsiders away for centuries, and their cultural traditions — bamboo and mud architecture, elaborate woodcarving on doorways, distinctive textile patterns, stick-dance performance, and a rich oral literary tradition — remain vibrant and accessible to visitors who seek them out in buffer zone villages and the Tharu Cultural Museum near Chakhaura.</p><p>The Babai River, which originates in the remote Dang hills to the north and flows east through Bardia National Park, is the ecological lifeline of the valley and offers excellent birdwatching along its wooded banks. Religious life centres on the ancient Ambikeshwari Temple and the revered Dhorbarahi Temple, both of which draw thousands of pilgrims from across western Nepal during major festivals, filling the valley with devotional music and processions that transform the normally quiet landscape.</p><p>For those with energy for higher ground, the ridge-top viewpoint at Sawarikot requires a four-hour climb but delivers a magnificent panorama across the entire valley: from above, Dang's extraordinary scale becomes fully comprehensible, a vast green bowl rimmed by blue-green forested hills that seems altogether too large and too hidden to exist. Dang is not on most Nepal travel itineraries, and that is precisely why it rewards those who make the effort.</p>`,
    district: `Dang`,
    province: "LUMBINI",
    lat: 27.9167,
    lng: 82.3,
    elevation: 650,
    entryFee: `Free`,
    bestSeason: `October–March`,
    openingHours: `Open all day`,
    howToGetThere: `Bus from Kathmandu (approx 9–10 hrs) via Butwal or Nepalgunj; bus from Nepalgunj to Ghorahi (approx 3 hrs); Tulsipur Airport has seasonal flights`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Dang Valley Tharu culture Nepal inner Terai`,
    bookingCity: `Nepalgunj`,
    seoTitle: `Dang Valley Nepal: Asia's Second-Largest Valley & Tharu Cultural Heartland`,
    seoDescription: `Explore Dang Valley in Lumbini Province — Asia's second-largest inner Terai basin, the cultural heartland of the Tharu people, and home to ancient temples, the Babai River, and sweeping hill panoramas.`,
    published: true,
    featured: false,
  },
  {
    name: `Tulsipur`,
    category: "CULTURAL_VILLAGE",
    summary: `Tulsipur is a rapidly growing sub-metropolitan city in Dang district at 753 m, the second-largest urban centre in the valley after Ghorahi, and the site of the district's only airport. It serves as a commercial hub, a base for exploring the Dang Valley, and home to Nepal Sanskrit University and a picturesque airport lake.`,
    story: `<p>Tulsipur occupies the western end of Dang Valley at an elevation of approximately 753 metres, a position that gives the city a slightly cooler and breezier character than the rest of the lowland basin. It is Dang's second city after the district capital Ghorahi, but in commercial energy and infrastructure development it is arguably the more dynamic of the two. The city has grown substantially in recent decades, absorbing rural migrants from surrounding hill districts attracted by its expanding markets, educational institutions, and employment opportunities.</p><p>The city's airport — Tarigaun Airport, the only one in the Dang district — connects Tulsipur to Kathmandu and Nepalgunj by seasonal propeller flights, making it an accessible destination for travellers who want to reach western Nepal without the full land journey. The airport road passes one of Tulsipur's most pleasant features: a scenic lake that has become a popular picnic and boating destination for local families, its banks dotted with small shrines and shaded by mature trees that provide welcome respite from the Terai heat.</p><p>Five kilometres north of the city centre, the small settlement of Chillikot has developed an unusual attraction: a restaurant dedicated to vulture conservation, part of Nepal's broader effort to protect endangered Himalayan griffon and white-rumped vultures from the secondary poisoning that devastated their populations across South Asia in the 1990s. The feeding station also offers views of surrounding forested hills and an ancient temple dedicated to the goddesses Kalika and Malika Devi, which has served as a pilgrimage site for the region's Hindu communities for several centuries.</p><p>Nepal Sanskrit University, located near Tulsipur, is one of the most prestigious institutions of its kind in the country, drawing scholars from across Nepal and South Asia for the study of Sanskrit literature, Vedic philosophy, and classical Nepali cultural traditions. Its presence gives Tulsipur an unexpected intellectual and cultural weight that sets it apart from most Terai market towns of comparable size.</p>`,
    district: `Dang`,
    province: "LUMBINI",
    lat: 28.131,
    lng: 82.2973,
    elevation: 753,
    entryFee: `Free`,
    bestSeason: `October–March`,
    openingHours: `City open all hours`,
    howToGetThere: `Seasonal flights from Kathmandu and Nepalgunj to Tarigaun Airport; bus from Nepalgunj (approx 3 hrs); bus from Kathmandu (approx 10–12 hrs)`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Tulsipur Dang Valley Nepal western Lumbini travel`,
    bookingCity: `Nepalgunj`,
    seoTitle: `Tulsipur Dang Nepal: Gateway to Dang Valley with Airport & Cultural Sites`,
    seoDescription: `Visit Tulsipur in Dang, Lumbini Province — a growing sub-metropolitan city with Nepal's only Dang district airport, a scenic lake, vulture conservation restaurant, and access to Dang Valley's Tharu culture.`,
    published: true,
    featured: false,
  },
  {
    name: `Pyuthan`,
    category: "HILL_VIEWPOINT",
    summary: `Pyuthan is a scenic middle-hills district in western Lumbini Province at around 855 m elevation, best known for the revered Swargadwari Temple at 2,100 m — Nepal's 'Gateway to Heaven' — which draws over 500,000 pilgrims annually. Dense forests, the Jhimruk river valley, and Magar cultural villages make it an emerging eco-tourism destination.`,
    story: `<p>Pyuthan district spreads across a diverse landscape of subtropical valleys and temperate mid-hills in western Nepal, stretching from the warm lowlands near the Dang border at 305 metres to the forested ridges of the Mahabharata Range rising above 3,659 metres at Syaliwang in the north. The district headquarters town sits at around 855 metres, a modest hill bazaar where the local Magar and Brahmin communities have lived and farmed the surrounding terraces for many generations.</p><p>The district's defining attraction is unquestionably the Swargadwari Temple, meaning literally the 'Gateway to Heaven.' Perched on a dramatic hilltop at 2,100 metres above sea level, the temple complex is dedicated to a revered Hindu saint and draws an estimated 500,000 pilgrims annually from Nepal and India — an astonishing number for a site so remote. The approach is itself an experience: a forest trail winding steeply upward through rhododendron and oak, the scent of incense already detectable long before the temple comes into view, and the sound of devotional songs rising from groups of pilgrims who often walk the entire distance barefoot as an act of spiritual dedication.</p><p>The Jhimruk River valley, which threads through the heart of the district, offers one of western Nepal's finest and least-explored trekking corridors. The Jhimruk trail passes through genuine rural communities where outsider visitors are still a novelty, the forests are intact, and the river runs clear and cold from its Mahabharata Range origins. Rafting on the Jhimruk during the post-monsoon season provides an exhilarating alternative for those who prefer water to trail.</p><p>Pyuthan's Magar villages preserve traditions of bronze casting, folk music played on the khaijadi drum, and a distinctive oral literary tradition linked to the Kirat cultural heritage of eastern Nepal. Community tourism initiatives are bringing travellers into contact with these living traditions in ways that benefit the communities directly, making Pyuthan one of the most compelling off-the-beaten-path destinations in Lumbini Province.</p>`,
    district: `Pyuthan`,
    province: "LUMBINI",
    lat: 28.0886,
    lng: 82.8833,
    elevation: 855,
    entryFee: `Swargadwari Temple NPR 50 entry; district access free`,
    bestSeason: `October–May (Swargadwari main festival in Baisakh/April–May)`,
    openingHours: `Town all day; Swargadwari Temple 05:00–18:00`,
    howToGetThere: `Bus from Dang/Tulsipur (3–4 hrs) or Nepalgunj (5 hrs); jeep from Dang valley via Salyan junction; no scheduled flights`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Swargadwari Temple Pyuthan Nepal pilgrimage trek`,
    bookingCity: `Nepalgunj`,
    seoTitle: `Pyuthan Nepal: Swargadwari Temple, Jhimruk Valley & Hidden Hill District`,
    seoDescription: `Discover Pyuthan in western Lumbini Province — home to the revered Swargadwari 'Gateway to Heaven' temple at 2,100 m, the scenic Jhimruk River valley, and rich Magar cultural traditions.`,
    published: true,
    featured: false,
  },
  {
    name: `Okhaldhunga`,
    category: "HILL_VIEWPOINT",
    summary: `Okhaldhunga is a peaceful hill district headquarters in Koshi Province at 1,561 m, offering stunning panoramic views of Mount Everest, Makalu, Kangchenjunga, and Gaurishankar from its ridges. It is a gateway to Solukhumbu and home to Pokali Waterfall, Champadevi viewpoint, and an authentic Nepali mid-hills lifestyle.`,
    story: `<p>Okhaldhunga lies where the mid-hills of eastern Nepal begin their ascent toward the high mountains of Solukhumbu, and the district headquarters town at 1,561 metres captures this transitional character perfectly. The surrounding landscape is one of rolling green ridges covered in pine and rhododendron, small stone-walled farmhouses terracing the hillsides, and the silver ribbons of rivers threading through valleys far below. It is Nepal at its most quietly beautiful, without the crowds of the Everest region to the north or the lowland heat of the Terai to the south.</p><p>The great reward of Okhaldhunga's elevated position is the mountain panorama it commands on clear days. From the Ribdi hilltop viewpoint — a short drive or easy hike from town — it is possible to see sixteen different districts stretching away across the hills and Terai plains, and on the northern horizon the white summits of some of the world's highest mountains emerge: Sagarmatha (Everest) at 8,848 metres, Makalu at 8,463 metres, Lhotse at 8,516 metres, and Kangchenjunga at 8,586 metres. It is a view that reminds every visitor of the extraordinary geographical privilege of life in Nepal.</p><p>The district's most dramatic natural feature is Pokali Waterfall, located approximately 30 kilometres from the headquarters and considered one of the tallest waterfalls in Nepal. The approach through forested hills is itself a rewarding walk, and the waterfall's plunge into the gorge below creates a perpetual mist that sustains a lush garden of mosses and ferns along the canyon walls. Local guides from Okhaldhunga can arrange a full-day excursion combining the waterfall with a visit to a traditional Rai or Magar village in the surrounding hills.</p><p>Okhaldhunga is also a jumping-off point for the southern approach to Solukhumbu district, and trekkers who prefer a less-travelled route to the Khumbu region occasionally choose to walk north from here through genuinely remote territory before joining the main Everest trail. The Champadevi hilltop above town, accessible in about two hours of walking, provides one of the finest vantage points in the district and a peaceful place for the kind of quiet reflection the hills of Nepal so naturally inspire.</p>`,
    district: `Okhaldhunga`,
    province: "KOSHI",
    lat: 27.3167,
    lng: 86.5,
    elevation: 1561,
    entryFee: `Free`,
    bestSeason: `October–May`,
    openingHours: `Town open all day`,
    howToGetThere: `Bus from Kathmandu via Sindhuli (approx 7–8 hrs) or via Salleri; jeep from Salleri or Ramechhap; no regular scheduled flights`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Okhaldhunga eastern Nepal hill trek Koshi province`,
    bookingCity: `Kathmandu`,
    seoTitle: `Okhaldhunga Nepal: Himalayan Panoramas & Pokali Waterfall in Koshi Province`,
    seoDescription: `Visit Okhaldhunga in Koshi Province — a scenic hill district at 1,561 m with sweeping views of Everest and the high Himalaya, Pokali Waterfall, and peaceful mid-hills trekking routes toward Solukhumbu.`,
    published: true,
    featured: false,
  },
  {
    name: `Diktel`,
    category: "CULTURAL_VILLAGE",
    summary: `Diktel is the hill headquarters of Khotang district in eastern Nepal at 1,631 m, a quiet bazaar town serving as the base for visiting the sacred Halesi-Maratika cave complex — one of the holiest Buddhist and Hindu pilgrimage sites in the Himalaya — and the forest trails of the remote Khotang hills.`,
    story: `<p>Diktel sits on a ridge in the Khotang hills of eastern Nepal at 1,631 metres, a compact district headquarters that sees relatively few foreign visitors yet occupies an important position as the administrative and commercial centre of one of Nepal's more remote mid-hill districts. The town itself is modest — a main bazaar street of shops and tea stalls, a district hospital, and a scattering of government offices — but its strategic importance lies in its proximity to the Halesi-Maratika cave complex, one of the most sacred pilgrimage destinations in all of Buddhism.</p><p>The Halesi-Maratika caves, located roughly 15 kilometres from Diktel near the town of Halesi, are revered as the site where the great Tibetan Buddhist master Padmasambhava (Guru Rinpoche) attained longevity siddhi through meditation, accompanied by the Indian tantric master Humkara and the princess Mandarava. Both Hindus and Buddhists regard the caves as supremely sacred: Hindus identify the main cave as an abode of Lord Shiva (Mahadev) and a Jyotirlinga site, while Buddhists venerate the caves as one of the most powerful practice places of Guru Rinpoche in all of South Asia. Pilgrims from across Nepal, India, Tibet, and the global Tibetan Buddhist community converge here especially during the Tibetan New Year celebrations in February and March.</p><p>The surrounding Khotang hills offer excellent trekking through traditional Rai and Magar communities, dense rhododendron forests that blaze with colour from February to April, and dramatic ridge-top viewpoints commanding panoramas of the eastern Himalaya. Lamidanda Airport, located 25 kilometres north of Diktel, provides the main air access to the district from Kathmandu, making Diktel a manageable destination for those willing to combine a short flight with local transport.</p><p>Khotang is also notable as one of the original homeland districts of the Kirat-Rai people, whose shamanic religious practice (Mundhum) and distinctive oral literature represent one of Nepal's oldest surviving indigenous traditions. A visit to Diktel and its surrounding villages offers a rare encounter with a culture that has maintained its identity with remarkable tenacity through centuries of political change.</p>`,
    district: `Khotang`,
    province: "KOSHI",
    lat: 27.2133,
    lng: 86.7932,
    elevation: 1631,
    entryFee: `Free (Halesi-Maratika cave entry fee applies separately)`,
    bestSeason: `October–May (February–March for Halesi pilgrimage festival)`,
    openingHours: `Town open all day`,
    howToGetThere: `Fly Kathmandu to Lamidanda Airport (35 min) then jeep to Diktel (approx 2 hrs); or bus from Okhaldhunga or Salleri via rough roads`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Halesi Maratika cave Khotang Nepal pilgrimage`,
    bookingCity: `Kathmandu`,
    seoTitle: `Diktel Khotang Nepal: Gateway to Halesi-Maratika Sacred Caves`,
    seoDescription: `Visit Diktel in Khotang, Koshi Province — the hill headquarters near the sacred Halesi-Maratika caves revered by Hindus and Buddhists, gateway to remote Khotang trekking and Kirat-Rai cultural heritage.`,
    published: true,
    featured: false,
  },
  {
    name: `Bhojpur`,
    category: "CULTURAL_VILLAGE",
    summary: `Bhojpur is an enchanting hilltop town in Koshi Province at 1,600 m, world-famous as the centre of production of the Bhojpure Khukuri — Nepal's iconic curved blade — and celebrated for its Kirat-Rai cultural heritage, traditional metalworking smithies, and sweeping views over the Arun River valley and eastern Himalaya.`,
    story: `<p>Bhojpur town clings to a hilltop in eastern Nepal at approximately 1,600 metres, looking out over successive ridgelines that fall away toward the deep canyon of the Arun River far below. Its name derives from the bhojpatra — the Himalayan birch tree whose bark was historically used as writing material — and the town has been inhabited continuously since at least the medieval period, serving as an important trading post on the routes between the Terai lowlands and the high Himalayan valleys of Solukhumbu and Sankhuwasabha.</p><p>Bhojpur's global reputation rests on a blade. The Bhojpure Khukuri — the curved knife that has been the signature weapon, tool, and cultural symbol of Nepal's Gurkha soldiers for centuries — is manufactured here in traditional smithies that have operated for generations. The Bhojpure style is distinguished by its wide, thick blade with a pronounced curve and a substantial karda (small utility knife) tucked into the back of the sheath. The forging process uses traditional bellows, charcoal fires, and hand-hammering techniques that have changed little over centuries, and a skilled smith can be watched at work in the workshops along the market street. The knives are sold throughout Nepal and internationally, and serious collectors consider genuine Bhojpure Khukuris among the finest examples of Nepali metalwork.</p><p>The town itself is the heartland of the Kirat-Rai ethnic group, one of Nepal's oldest indigenous peoples. Rai cultural traditions — the Mundhum oral religious text, the sakela dance performed during the rice planting and harvest seasons, the distinctive weaving patterns of their dhaka cloth, and a cuisine featuring fermented millet, bamboo shoots, and dried fish — are present everywhere in Bhojpur and the surrounding villages. The town's bazaar reflects this cultural vitality with a mix of Nepali and Rai architecture, food stalls serving local specialities, and the sound of Rai folk music during festival periods.</p><p>Bhojpur is connected to the outside world by Bhojpur Airport, served by small aircraft from Kathmandu, and by the Madan Bhandari Highway that is gradually being extended through the district. The view from the Bhojpur ridge on a clear morning — eastward toward Kangchenjunga, north toward the Khumbu peaks — is one of the finest hilltop panoramas in eastern Nepal.</p>`,
    district: `Bhojpur`,
    province: "KOSHI",
    lat: 27.1715,
    lng: 87.0461,
    elevation: 1600,
    entryFee: `Free`,
    bestSeason: `October–May`,
    openingHours: `Town open all day; smithies typically 07:00–17:00`,
    howToGetThere: `Fly Kathmandu to Bhojpur Airport (35 min); or bus/jeep from Dharan via Hile and Chainpur (approx 6–8 hrs on rough roads)`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Bhojpur Khukuri knife Nepal Kirat Rai culture`,
    bookingCity: `Kathmandu`,
    seoTitle: `Bhojpur Nepal: Home of the Khukuri Knife & Kirat-Rai Cultural Heritage`,
    seoDescription: `Discover Bhojpur in Koshi Province — Nepal's hilltop capital of Khukuri knife craftsmanship, traditional Kirat-Rai culture, and sweeping Himalayan views over the Arun River valley.`,
    published: true,
    featured: false,
  },
  {
    name: `Dhankuta`,
    category: "HILL_VIEWPOINT",
    summary: `Dhankuta is a remarkably clean and picturesque Newari hill town at 1,150 m in eastern Nepal, often proposed as Nepal's cleanest city, perched on a ridge above the Arun and Tamor river valleys with sweeping views of Everest, Makalu, Kangchenjunga, and sixteen districts from the Dhoje Danda viewpoint.`,
    story: `<p>Dhankuta stands on a long ridge in the hills of eastern Nepal at 1,150 metres, a town whose character is shaped as much by its Newari heritage and civic pride as by its extraordinary geographical setting. Proposed as Nepal's cleanest city by The Kathmandu Post, Dhankuta maintains an orderliness and quiet dignity unusual in Nepali hill towns: whitewashed stone houses with carved wooden facades line the main bazaar, bougainvillea spills over compound walls, and the streets are swept clean each morning by residents who take visible pride in the appearance of their community.</p><p>Until around 1963, Dhankuta served as the administrative headquarters for the entire north-eastern region of Nepal, and the old Bada Hakim's compound above the town still hints at this former authority. The bazaar retains a traditional Newari character, with metalworkers, weavers, and spice traders occupying shops that have been in the same families for generations. The weekly market draws villagers from the surrounding hills who descend to trade in a tradition unchanged over centuries.</p><p>The greatest reward of Dhankuta is the view. From the Dhoje Danda ridge above the town — reached by a pleasant two-hour walk through pine forest — the panorama encompasses sixteen districts of Nepal's hills and Terai plains, and on the northern horizon the Himalayan giants emerge with stunning clarity: Sagarmatha (Everest) at 8,848 m, Makalu at 8,463 m, Lhotse at 8,516 m, Kangchenjunga at 8,586 m, and Kumbhakarna (Jannu) at 7,710 m. In the evening, the same ridge offers one of Nepal's finest sunset views as the peaks turn from gold to orange to deep crimson against a violet sky.</p><p>Dhankuta lies on the route between the lowland city of Dharan and the hill trading post of Hile, from which trekkers historically set out for the Arun Valley and Makalu Base Camp. The town makes an excellent overnight stop on this journey, offering comfortable lodges, good food, and the quiet pleasure of walking streets that feel genuinely cared for in a country where civic maintenance is often a secondary priority.</p>`,
    district: `Dhankuta`,
    province: "KOSHI",
    lat: 26.9833,
    lng: 87.3333,
    elevation: 1150,
    entryFee: `Free`,
    bestSeason: `October–May`,
    openingHours: `Town open all day; Dhoje Danda viewpoint best at dawn`,
    howToGetThere: `Bus from Dharan (approx 2 hrs) or from Biratnagar (approx 3 hrs); jeep from Hile or Basantapur; bus from Kathmandu overnight to Dharan then onward`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Dhankuta Koshi Province Nepal hill town Himalayan views`,
    bookingCity: `Kathmandu`,
    seoTitle: `Dhankuta Nepal: Nepal's Cleanest Hill Town with Himalayan Panoramas`,
    seoDescription: `Visit Dhankuta in Koshi Province — a beautifully maintained Newari hill town at 1,150 m offering stunning Himalayan panoramas including Everest and Kangchenjunga from the Dhoje Danda viewpoint.`,
    published: true,
    featured: false,
  },
]

async function main() {
  console.log('🌱 Seeding batch 12 — 20 places...')
  for (const p of places) {
    const s = slug(p.name)
    await prisma.place.upsert({
      where: { slug: s },
      update: {},
      create: { ...p, slug: s },
    })
    console.log('  ✅', p.name)
  }
  console.log('🌱 Batch 12 complete!')
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
