import 'dotenv/config'
import { PrismaClient } from '@prisma/client'
import slugify from 'slugify'

const prisma = new PrismaClient()
const slug = (n) => slugify(n, { lower: true, strict: true })

const places = [
  {
    name: "Bungee Jumping \u2013 The Last Resort",
    category: "ADVENTURE_SPORTS",
    summary: "The Last Resort sits above the raging Bhotekoshi gorge in Sindhupalchok, offering Nepal's original and most iconic 160-metre bungee jump from a suspension bridge. Operating since 1999, it holds one of Asia's longest free-falls, overseen by New Zealand-trained jump masters to international safety standards. The dramatic gorge setting, framed by dense jungle and towering cliffs, makes this one of the most visually spectacular bungee sites anywhere in the world.",
    story: `<p>Nepal's adventure tourism scene was transformed in 1999 when The Last Resort opened the country's first commercial bungee jump above the Bhotekoshi River canyon in Sindhupalchok district. The site was chosen for its extraordinary natural drama: a narrow suspension bridge spans a gorge where the turquoise Bhotekoshi River roars 160 metres below, flanked by sheer cliffs draped in subtropical vegetation. Within a few years it had earned a reputation as one of the top ten bungee experiences in Asia.</p><h3>The Jump Experience</h3><p>Jumpers are fitted into a full-body harness on the wooden suspension bridge before stepping off into a near-vertical free-fall that lasts roughly four seconds. The rebound swings participants out over the gorge in a series of oscillations before a trained crew slowly winches them back to the bridge. The resort also offers a swing (canyon swing), white-water rafting on the Bhotekoshi, and multi-day tented camps, making it a full adventure destination rather than a single-activity stop.</p><h3>Highlights</h3><ul><li>160-metre free-fall from historic suspension bridge</li><li>Canyon swing option for those who prefer a pendulum arc</li><li>Gorge-side tented camp accommodation available</li><li>Certified by international bungee safety standards</li><li>3–4 hour drive from Kathmandu on the Arniko Highway toward Tibet</li></ul>`,
    district: "Sindhupalchok",
    province: "BAGMATI",
    lat: 27.897,
    lng: 85.988,
    elevation: 640,
    entryFee: "USD 80\u2013100 per jump (includes canyon swing combo packages)",
    bestSeason: "October to May (avoid monsoon June\u2013September due to flooding risk)",
    openingHours: "Typically 09:00\u201316:00 daily; check with operator",
    howToGetThere: "Drive approximately 100 km northeast of Kathmandu on the Arniko Highway (about 3\u20134 hours by private vehicle or tourist bus toward the Tibet border). The Last Resort is signposted at the Bhotekoshi gorge crossing near Listikot village in Sindhupalchok district. Most Kathmandu tour operators offer day-trip or overnight packages with transport included.",
    gygQuery: "bungee jumping Last Resort Bhotekoshi Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Bungee Jumping at The Last Resort \u2013 160m Bhotekoshi Gorge, Nepal",
    seoDescription: "Leap 160 metres above the Bhotekoshi River at Nepal's first and most thrilling bungee site. Book The Last Resort bungee jump from Kathmandu \u2013 canyon swing available.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Zip Flyer Pokhara",
    category: "ADVENTURE_SPORTS",
    summary: "Operated by HighGround Adventures from the ridge above Sarangkot, the Zip Flyer is widely recognised as the world's steepest commercial zip line, plunging 1.8 km at a 56-degree incline with a 600-metre vertical drop and speeds exceeding 120 km/h. Riders launch from 1,550 m above sea level and fly over terraced hills and forest canopy with Phewa Lake and the Annapurna Himalaya as a spectacular backdrop. The ride lasts about 90 seconds and lands near the shores of Pokhara valley.",
    story: `<p>Inaugurated in 2010, the Zip Flyer was purpose-built on the steep southern face of Sarangkot Hill, the viewpoint ridge overlooking Pokhara. The operators recognised that the dramatic gradient, coupled with sweeping views of the Annapurna massif and Phewa Lake below, could deliver a zip-line experience without peer anywhere in the world. Record-setters in zip-line engineering certified it as the tallest-start, steepest, and among the fastest zip lines ever constructed.</p><h3>The Ride</h3><p>Participants are fitted into a seated harness at the upper platform at 1,550 m and launched down a steel cable angled at 56 degrees. Within seconds speeds exceed 120 km/h, and the panorama of Dhaulagiri, Annapurna South, Machhapuchhre (Fishtail), and the blue mirror of Phewa Lake unfolds in a breathtaking 90-second arc. The lower landing platform sits near Pokhara valley at around 950 m elevation.</p><h3>Highlights</h3><ul><li>World's steepest commercial zip line at 56-degree incline</li><li>1.8 km cable length with 600 m vertical drop</li><li>Speeds exceeding 120 km/h</li><li>Panoramic views of Annapurna, Dhaulagiri, and Phewa Lake</li><li>30-minute drive from Lakeside Pokhara via Sarangkot road</li></ul>`,
    district: "Kaski",
    province: "GANDAKI",
    lat: 28.228,
    lng: 83.955,
    elevation: 1550,
    entryFee: "NPR 7,000\u20138,000 per person (approx. USD 55\u201365)",
    bestSeason: "October to May; best Himalayan views October\u2013December and February\u2013April",
    openingHours: "09:00\u201317:00 daily (weather permitting)",
    howToGetThere: "From Lakeside Pokhara, drive or take a taxi approximately 8 km northwest to Sarangkot (30 minutes). The upper Zip Flyer platform is at the Sarangkot viewpoint ridge. Operators also run shuttle services from Lakeside hotels. The lower landing zone is accessible from Pokhara town.",
    gygQuery: "zip flyer zipline Pokhara Sarangkot Nepal",
    bookingCity: "Pokhara",
    seoTitle: "Zip Flyer Pokhara \u2013 World's Steepest Zip Line from Sarangkot, Nepal",
    seoDescription: "Fly at 120 km/h down the world's steepest zip line above Pokhara with Annapurna views. Book your Zip Flyer Sarangkot experience today.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Mountain Biking Kathmandu Valley",
    category: "ADVENTURE_SPORTS",
    summary: "The forested ridgelines and rural tracks of Shivapuri Nagarjun National Park on Kathmandu's northern fringe offer Nepal's best mountain biking terrain, ranging from buff singletrack through dense forest to demanding technical descents toward Budhanilkantha and Sundarijal. Riders can string together routes that pass Buddhist stupas, terraced farmland, and panoramic Himalayan viewpoints within 30 minutes of the city centre. Bike rentals and guided tours are widely available from Thamel.",
    story: `<p>Kathmandu Valley's proximity to forested hills makes it one of Asia's most convenient mountain biking destinations. The northern rim—defined by Shivapuri Nagarjun National Park and its adjacent Nagarjun Forest Reserve—provides a tiered playground of dirt roads, jeep tracks, and forested singletrack that climbs from around 1,300 m in the valley to the Shivapuri Peak area at 2,732 m. Routes can be tailored for a relaxed three-hour outing or a full-day epic crossing from Kakani to Sundarijal.</p><h3>Key Routes</h3><p>The Budhanilkantha–Shivapuri–Sundarijal traverse follows the national park's northern edge on a mix of off-road track and forest path, passing waterfalls and rhododendron forest. The Nagarjun–Kakani loop climbs through the royal forest reserve to the Kakani hilltop at 2,070 m, renowned for its Himalayan panorama, before descending to Balaju. The Scar Route inside Shivapuri is considered the most technically demanding, featuring sustained climbs and rooty, rocky descents through dense jungle.</p><h3>Highlights</h3><ul><li>Singletrack through Shivapuri and Nagarjun national forests</li><li>Himalayan viewpoints at Kakani, Shivapuri, and Jamacho</li><li>Accessible from Thamel in under 30 minutes</li><li>Bike rental from Thamel shops: USD 10–25/day depending on spec</li><li>Best October–May; trails dry and grippy in autumn and early spring</li></ul>`,
    district: "Kathmandu",
    province: "BAGMATI",
    lat: 27.795,
    lng: 85.347,
    elevation: 1350,
    entryFee: "NPR 1,000 foreigners / NPR 100 Nepali (Shivapuri National Park entry); Nagarjun forest NPR 250 foreigners",
    bestSeason: "October to May",
    openingHours: "Sunrise to sunset; park gates open from 06:00",
    howToGetThere: "Multiple entry points from Kathmandu: Budhanilkantha gate (12 km north on Budhanilkantha Road), Phulbari gate for Nagarjun Forest (9 km northwest via Balaju), and Sundarijal gate (15 km northeast). All accessible by taxi or local microbus from central Kathmandu.",
    gygQuery: "mountain biking Kathmandu Shivapuri Nagarjun Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Mountain Biking Kathmandu Valley \u2013 Shivapuri & Nagarjun Forest Trails",
    seoDescription: "Discover Nepal's best mountain biking on the forest singletrack of Shivapuri Nagarjun National Park, just 30 minutes from Kathmandu. Guided rides and bike rentals available.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Rock Climbing Nagarjun Forest",
    category: "ADVENTURE_SPORTS",
    summary: "The limestone cliffs inside Nagarjun Forest Reserve, just 5 km from central Kathmandu, host more than 21 bolted sport-climbing routes on a dramatic 55-metre wall near the Balaju Quarry. Routes range from beginner-friendly slabs to overhanging test-pieces, making it Nepal's most accessible natural outdoor climbing venue. Certified guides and equipment rental are available on-site, and the dense forest setting provides welcome shade year-round.",
    story: `<p>Rock climbing as a recreational sport in Nepal is anchored by the crags at Nagarjun Forest Reserve, which have served as the training ground for Nepali climbers and a convenient day-out for visiting mountaineers for over two decades. The main crag, near the Balaju Quarry entrance, presents a solid limestone wall rising 55 metres above the forest floor, split into three distinct sectors. Pioneer route developers bolted more than 21 lines, ensuring sport climbers can move between grades comfortably without trad gear.</p><h3>The Climbing</h3><p>The Balaju Quarry sector features both vertical face routes and overhanging crimpy lines suited to intermediate and advanced climbers. A slab sector on the right side of the wall offers gentler angles ideal for beginners learning movement technique. Most routes are 20–55 m, and top-rope setups can be rigged at the bolted anchors for those in instruction. Several Kathmandu climbing schools use the crag weekly for training sessions and introductory courses.</p><h3>Highlights</h3><ul><li>21+ bolted sport routes on 55-metre limestone cliff</li><li>Grades ranging from beginner slabs to advanced overhangs</li><li>Only 5 km (20-minute drive) from Thamel, Kathmandu</li><li>Forest setting with shade and natural ambiance</li><li>Guided climbing and equipment hire available from Kathmandu operators</li><li>Entry fee: NPR 250 for foreigners</li></ul>`,
    district: "Kathmandu",
    province: "BAGMATI",
    lat: 27.742,
    lng: 85.289,
    elevation: 1410,
    entryFee: "NPR 250 foreigners / NPR 10 Nepali (Nagarjun Forest Reserve entry)",
    bestSeason: "October to May (avoid wet rock during monsoon June\u2013September)",
    openingHours: "06:00\u201318:00 daily",
    howToGetThere: "From central Kathmandu (Thamel), drive approximately 5 km northwest to Balaju via the Ring Road, then follow signs to Nagarjun Forest Reserve Phulbari gate. The climbing area is a short walk inside the gate. Taxis or ride-share services reach the gate in 15\u201320 minutes.",
    gygQuery: "rock climbing Nagarjun Kathmandu Nepal outdoor",
    bookingCity: "Kathmandu",
    seoTitle: "Rock Climbing at Nagarjun Forest Reserve \u2013 Sport Climbing near Kathmandu",
    seoDescription: "Climb 21+ bolted sport routes on the limestone crags of Nagarjun Forest Reserve, just 5 km from Kathmandu. Guided rock climbing for all levels in a stunning forest setting.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Canyoning Jalbire",
    category: "ADVENTURE_SPORTS",
    summary: "Jalbire Canyoning offers an exhilarating full-day descent of a narrow river canyon approximately 100 km from Kathmandu, featuring a dramatic 60-metre waterfall rappel, natural water slides, cliff jumps, and swim-throughs in crystalline pools. Situated near the Chitwan borderland, the site is accessible on the Prithvi Highway and combines easily with Pokhara or Chitwan itineraries. It is considered the most beginner-friendly canyoning destination in Nepal, suitable for adults and older children alike.",
    story: `<p>Jalbire emerged as Nepal's premier canyoning destination because it delivers all the classic elements of the sport—rappelling, sliding, jumping, and swimming—within a single canyon that requires no prior experience. The site's centrepiece is a tiered waterfall system culminating in a 60-metre rappel down a moss-covered cliff face into a jade-green plunge pool. The entire canyon descent takes four to six hours including safety briefings, gear fitting, and photography stops.</p><h3>The Canyon Experience</h3><p>Groups begin with a 12-metre starter cliff jump to test nerves before moving deeper into the canyon. A series of natural rock slides funnels participants into pools before the main rappel section arrives. The 60-metre waterfall rappel is conducted in two pitches with certified guides belaying from above and below, ensuring safety even for first-timers. After the descent, the canyon opens into a broad river valley where participants can swim before the return walk to the road.</p><h3>Highlights</h3><ul><li>60-metre main waterfall rappel (largest in Nepal's canyoning circuits)</li><li>Natural rock slides and cliff jumps up to 12 metres</li><li>Suitable for beginners including older children</li><li>Located 97–117 km from Pokhara and Kathmandu respectively</li><li>Best season: October–May; avoid peak monsoon</li><li>Full equipment (wetsuit, helmet, harness) provided by operators</li></ul>`,
    district: "Chitwan",
    province: "BAGMATI",
    lat: 27.682,
    lng: 84.728,
    elevation: 430,
    entryFee: "USD 50\u201370 per person (guide, equipment, and transport from Kathmandu/Pokhara typically included in package)",
    bestSeason: "October to May",
    openingHours: "Full-day activity; departs early morning from Kathmandu or Pokhara",
    howToGetThere: "Jalbire is located approximately 100 km west of Kathmandu and 97 km east of Pokhara on the Prithvi Highway. Most visitors join day-tour packages from either city that include transport by private vehicle or tourist bus. Independent travellers can take a Kathmandu\u2013Pokhara bus and disembark at Jalbire junction.",
    gygQuery: "canyoning Jalbire Nepal waterfall rappel",
    bookingCity: "Kathmandu",
    seoTitle: "Canyoning Jalbire Nepal \u2013 60m Waterfall Rappel & Canyon Adventure",
    seoDescription: "Experience Nepal's best canyoning at Jalbire \u2013 rappel a 60-metre waterfall, slide natural rock chutes, and swim through pools. Day trips from Kathmandu and Pokhara available.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Janakpur",
    category: "CULTURAL_VILLAGE",
    summary: "Janakpur, the capital of Madhesh Province, is one of the holiest cities in the Hindu world, revered as the birthplace of Goddess Sita and the ancient capital of the kingdom of Mithila. The city is studded with more than 70 ponds, numerous temples, and the magnificent Janaki Mandir, and pulses with Maithili culture expressed through traditional Mithila painting, festivals like Vivah Panchami, and the unique Janakpur Women's Development Centre. Located about 225 km southeast of Kathmandu, it draws pilgrims from across Nepal and India.",
    story: `<p>According to Hindu tradition, Janakpur was the capital of King Janak's kingdom of Mithila during the Treta Yuga, the era of the Ramayana epic. It was here that King Janak discovered the infant Sita in a ploughed furrow of a field and raised her as his daughter; the city's ponds, known as kunds, are said to have been used for her childhood play and ritual bathing. The site was rediscovered in 1657 by the saint Shurkishordas, who found a golden statue of Sita at the spot now occupied by the Janaki Mandir.</p><h3>Sacred Ponds and Temples</h3><p>Janakpur is called the City of Ponds for its 72 sacred tanks, the largest being Ganga Sagar Kund. The city contains dozens of temples dedicated to Ram, Sita, Hanuman, and Shiva, and the annual Vivah Panchami festival—celebrating Ram and Sita's wedding—draws hundreds of thousands of pilgrims each November. The narrow-gauge Janakpur Railway, one of Nepal's oldest, still connects the city to the Indian border at Jaynagar.</p><h3>Highlights</h3><ul><li>Janaki Mandir – ornate marble temple of Goddess Sita</li><li>72 sacred ponds including Ganga Sagar Kund</li><li>Mithila painting tradition visible on homes and at the Women's Development Centre</li><li>Vivah Panchami festival (November) – one of Nepal's largest pilgrimages</li><li>Janakpur Railway heritage narrow-gauge line to Indian border</li><li>UNESCO tentative World Heritage Site (Ram Janaki Temple, 2008)</li></ul>`,
    district: "Dhanusha",
    province: "MADHESH",
    lat: 26.7183,
    lng: 85.9065,
    elevation: 70,
    entryFee: "Free to enter the city; Janaki Mandir entry free for worship",
    bestSeason: "October to March; Vivah Panchami festival (November) is especially atmospheric",
    openingHours: "City always accessible; major temples 05:00\u201321:00 daily",
    howToGetThere: "Janakpur is approximately 225 km southeast of Kathmandu. By air, Buddha Air and Shree Airlines operate daily 30-minute flights from Kathmandu to Janakpur Airport. By road, take a bus from Kathmandu's Ratna Park or New Bus Park toward Janakpur via Sindhuli (6\u20138 hours). From the Indian border at Jaynagar, the historic narrow-gauge railway links to Janakpur station.",
    gygQuery: "Janakpur city tour holy pilgrimage Sita birthplace Nepal",
    bookingCity: "Janakpur",
    seoTitle: "Janakpur \u2013 Holy City of Goddess Sita & Mithila Culture, Madhesh Nepal",
    seoDescription: "Visit Janakpur, Nepal's sacred Maithili city and birthplace of Goddess Sita. Explore the Janaki Mandir, 72 sacred ponds, Mithila art, and the vibrant Vivah Panchami festival.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Janaki Mandir",
    category: "TEMPLE",
    summary: "The Janaki Mandir in Janakpur is a breathtaking three-storied marble and stone temple dedicated to Goddess Sita (Janaki), built in 1910 by Queen Vrisha Bhanu of Tikamgarh and considered one of Nepal's most magnificent religious structures. Constructed in Koiri Hindu architectural style with 60 rooms, ornate turrets, Madhubani paintings, and lattice windows, the temple marks the very spot where a golden statue of Sita was discovered in 1657. It is a UNESCO tentative World Heritage Site and one of the most important pilgrimage destinations in the Hindu world.",
    story: `<p>The Janaki Mandir stands on the sacred ground where, according to tradition, King Janak discovered the infant Sita and where she spent her childhood in the ancient Mithila kingdom. In 1657, the saint Shurkishordas unearthed a golden statue of Sita at this precise location, and a small shrine was established. Two and a half centuries later, Queen Vrisha Bhanu of Tikamgarh in central India financed the construction of the present grand temple, completed around 1910 at a cost of nine lakhs of rupees—earning it the popular name Nau Lakha Mandir.</p><h3>Architecture and Interiors</h3><p>The temple covers 1,480 square metres and rises through three stories of gleaming white stone and marble. Its 60 rooms are decorated with traditional Madhubani (Mithila) paintings and coloured glass engravings. The outer walls are adorned with intricate relief carvings and lattice windows, while dozens of small turrets rise to a central spire. Inside the inner sanctum, a flower-garlanded image of Sita is enshrined alongside Ram and Lakshman; the mandapa (pavilion) attached to the temple is believed to be the site of the legendary Swayamvara ceremony where Sita chose Ram as her husband.</p><h3>Highlights</h3><ul><li>Nau Lakha Mandir – built at cost of nine lakhs by Queen Vrisha Bhanu, 1910</li><li>Three-storied marble and stone Koiri Hindu architecture</li><li>60 rooms with Madhubani paintings and coloured glass</li><li>Believed site of Ram-Sita Swayamvara ceremony</li><li>UNESCO tentative World Heritage Site since 2008</li><li>Vivah Panchami celebrations draw hundreds of thousands of devotees</li></ul>`,
    district: "Dhanusha",
    province: "MADHESH",
    lat: 26.7311,
    lng: 85.9309,
    elevation: 70,
    entryFee: "Free entry for worship; donations welcome",
    bestSeason: "October to March; Vivah Panchami (November) is the peak pilgrimage season",
    openingHours: "05:00\u201321:00 daily; special aarti at dawn and dusk",
    howToGetThere: "The temple is at the centre of Janakpur city, easily reached by rickshaw from Janakpur Airport (2 km) or the bus station. Flights from Kathmandu take 30 minutes; road journey takes 6\u20138 hours. Within Janakpur, cycle-rickshaws and e-rickshaws are the primary transport.",
    gygQuery: "Janaki Mandir Janakpur temple tour Nepal",
    bookingCity: "Janakpur",
    seoTitle: "Janaki Mandir Janakpur \u2013 Sacred Temple of Goddess Sita, Nepal",
    seoDescription: "Discover the magnificent Janaki Mandir in Janakpur \u2013 Nepal's most ornate Hindu temple dedicated to Goddess Sita, a UNESCO tentative heritage site and key pilgrimage destination.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Saptakoshi River",
    category: "RIVER",
    summary: "The Saptakoshi (Kosi River) is one of Nepal's mightiest rivers, formed by seven Himalayan tributaries and carrying immense volumes of water through eastern Terai before entering India. The river system supports over 134 native fish species including the prized Golden Mahseer, making it a premier destination for sport fishing, while its extensive wetlands and sandbars host more than 485 bird species. The Koshi Barrage and the floodplains around Koshi Tappu Wildlife Reserve are the most rewarding stretches for naturalists and anglers.",
    story: `<p>The Saptakoshi is born from seven major Himalayan rivers—the Sun Koshi, Tamor, Arun, Dudh Koshi, Bhote Koshi, Indrawati, and Tama Koshi—that converge near the Tribeni confluence in eastern Nepal before the combined river cuts through the Siwalik Hills at the Koshi Gorge and spreads across the Terai. The name Saptakoshi literally means 'seven Koshis', and the river's legendary floods have historically made it both a bringer of life and a fearsome force—it is sometimes called the Sorrow of Bihar for its tendency to shift course and inundate vast areas.</p><h3>Fishing and Wildlife</h3><p>The river's clear cold upper reaches near the Koshi Gorge and the tributary confluences at Mai Beni and Triveni are renowned for Golden Mahseer (Tor putitora) and Goonch catfish, drawing fly fishermen from around the world between October and April. Downstream, the Koshi Tappu Wildlife Reserve preserves the river's floodplain ecology, sheltering Nepal's last wild water buffalo, gharial crocodiles, and an extraordinary diversity of migratory waterbirds that use the Koshi as a flyway corridor between Central Asia and the Indian Subcontinent.</p><h3>Highlights</h3><ul><li>Seven tributaries creating one of Asia's most biodiverse river systems</li><li>Golden Mahseer and Goonch fishing at Mai Beni and Triveni</li><li>485 bird species including large adjutant stork, Pallas's fish eagle</li><li>Koshi Barrage viewpoint for flamingo and waterfowl aggregations</li><li>Koshi Tappu Wildlife Reserve on the river's floodplain (Ramsar site)</li></ul>`,
    district: "Sunsari",
    province: "KOSHI",
    lat: 26.645,
    lng: 87.052,
    elevation: 75,
    entryFee: "Free access to river; fishing permits required (contact Nepal government or tour operators)",
    bestSeason: "October to April for fishing and birdwatching; avoid June\u2013September monsoon floods",
    openingHours: "Always accessible",
    howToGetThere: "The Saptakoshi River is best accessed near Itahari in Sunsari district or at the Koshi Tappu area. From Kathmandu, fly to Biratnagar (45 minutes) or take an overnight bus (~8 hours) to Itahari. Local buses and jeeps cover the remaining 30\u201340 km to riverside access points. The Koshi Barrage is near Bhardaha in Saptari district.",
    gygQuery: "Saptakoshi river fishing birdwatching Koshi Nepal",
    bookingCity: "Biratnagar",
    seoTitle: "Saptakoshi River Nepal \u2013 Fishing, Birdwatching & Wildlife in Eastern Terai",
    seoDescription: "Explore the mighty Saptakoshi River in eastern Nepal for Golden Mahseer fishing, 485 species of birds, and floodplain wildlife at Koshi Tappu. Nepal's finest river ecosystem.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Koshi Tappu Wildlife Reserve",
    category: "NATIONAL_PARK",
    summary: "Koshi Tappu Wildlife Reserve is a 175 km\u00b2 Ramsar-designated wetland reserve in the Saptakoshi floodplain of eastern Terai, sheltering Nepal's last surviving herd of wild water buffalo and an extraordinary 485 bird species. Established in 1976, it encompasses seasonally flooded grasslands, reed beds, and riverine forest that provide critical habitat for waterbirds, gharial crocodiles, spotted deer, and smooth-coated otters. It is consistently ranked as one of Asia's most important freshwater wetland sites for avifauna.",
    story: `<p>Koshi Tappu Wildlife Reserve was established in 1976 to protect a critical island of biodiversity in Nepal's heavily farmed eastern Terai. The name 'Tappu' means 'island' in Nepali, referring to the way the Saptakoshi River historically bifurcated around the reserve's forested core. In 1987, UNESCO and the Ramsar Convention recognised its international importance as a wetland of global significance, and the reserve has since become the cornerstone of a larger conservation landscape extending south into India's Bihar state.</p><h3>Wild Buffalo and Wetland Ecology</h3><p>The reserve holds Nepal's only wild population of the Asian wild water buffalo (Bubalus arnee), a species classified as Endangered globally. The 2016 census recorded 432 individuals, growing at an impressive annual rate. The reserve's mosaic of grasslands, shallow wetlands, and gallery forest also supports hog deer, blue bull, wild boar, jackal, and smooth-coated otter. The Koshi River's sandbanks provide nesting sites for gharial crocodiles and Gangetic dolphins are occasionally spotted in deeper channels.</p><h3>Highlights</h3><ul><li>Nepal's last herd of wild water buffalo (432 individuals, 2016 census)</li><li>485 bird species including large adjutant stork, swamp francolin, Pallas's fish eagle</li><li>Ramsar Wetland of International Importance (1987)</li><li>Excellent jeep and elephant safaris through grassland and forest</li><li>Koshi River boat rides for waterbird observation</li><li>Peak birding October–March when migratory species arrive</li></ul>`,
    district: "Sunsari",
    province: "KOSHI",
    lat: 26.655,
    lng: 86.985,
    elevation: 75,
    entryFee: "NPR 1,000 foreigners / NPR 100 Nepali per day",
    bestSeason: "October to March for birdwatching; December\u2013February for migratory waterbirds",
    openingHours: "Gates open from 06:00 to 18:00",
    howToGetThere: "Fly from Kathmandu to Biratnagar (45 minutes) then drive approximately 60 km southwest to the reserve headquarters at Kusaha (1.5 hours by jeep). Alternatively, take an overnight bus from Kathmandu to Itahari (8 hours) and then a local bus or jeep to Kusaha. Several Kathmandu-based wildlife operators run 3\u20135 day Koshi Tappu safari packages.",
    gygQuery: "Koshi Tappu Wildlife Reserve safari birdwatching Nepal",
    bookingCity: "Biratnagar",
    seoTitle: "Koshi Tappu Wildlife Reserve \u2013 Wild Buffalo & Bird Paradise, Eastern Nepal",
    seoDescription: "Visit Nepal's only Ramsar wetland reserve \u2013 Koshi Tappu in eastern Terai. Home to wild water buffalo, 485 bird species, and outstanding river wildlife. Safari and birding tours available.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Parsa National Park",
    category: "NATIONAL_PARK",
    summary: "Parsa National Park is a 627 km\u00b2 protected area in Nepal's south-central Terai, characterised by dense sal forest, Siwalik hill ranges, and rich wildlife including a booming Bengal tiger population that grew from 4 in 2008 to 41 in 2022. Sharing a border with Chitwan National Park to the west and India's Valmiki Tiger Reserve to the south, Parsa forms a critical wildlife corridor that supports tigers, elephants, sloth bears, leopards, and gaur. It was upgraded from Wildlife Reserve to National Park status in 2017.",
    story: `<p>Parsa's conservation story is one of Nepal's most remarkable recovery narratives. When it was first surveyed in 2008, only four Bengal tigers remained in the entire reserve. Through intensive anti-poaching efforts, community engagement, and its 2017 upgrade to National Park status, the tiger population surged to 19 by 2017 and reached 41 by 2022—a tenfold increase in fourteen years. The park's 627 square kilometres encompass the rugged Churia (Siwalik) hills rising 435–950 metres above the Terai plains, cloaked almost entirely in sal forest.</p><h3>Wildlife and Landscape</h3><p>Parsa's proximity to Chitwan and the transboundary connection with India's Valmiki Tiger Reserve means large mammals move freely across a vast landscape. Elephants traverse the hills seasonally, and the park's network of waterholes and river courses supports gharial crocodiles, Indian pythons, and a host of deer species including barasingha. Birdlife is equally impressive, with over 320 species recorded including Bengal florican, lesser adjutant, and multiple raptor species.</p><h3>Highlights</h3><ul><li>41 Bengal tigers (2022) – one of Nepal's fastest-recovering tiger populations</li><li>Connected to Chitwan NP and India's Valmiki Tiger Reserve</li><li>Dense sal forest covering 90% of the park</li><li>Elephant, jeep, and walking safaris available</li><li>Less visited than Chitwan – more wilderness feel</li><li>Upgraded from Wildlife Reserve to National Park in 2017</li></ul>`,
    district: "Bara",
    province: "MADHESH",
    lat: 27.371,
    lng: 84.916,
    elevation: 435,
    entryFee: "NPR 1,000 foreigners / NPR 100 Nepali per day",
    bestSeason: "October to April; February\u2013March excellent for wildlife viewing as vegetation thins",
    openingHours: "Gates open 06:00\u201318:00",
    howToGetThere: "Parsa National Park headquarters are near Pathlaiya in Bara district, approximately 130 km south of Kathmandu via the Mahendra Highway. From Kathmandu, drive or take a bus to Pathlaiya (3\u20134 hours), then local transport to the park entry points at Amlekhgunj or Madi. Several Kathmandu tour operators offer overnight safari packages to Parsa.",
    gygQuery: "Parsa National Park tiger safari Nepal Terai",
    bookingCity: "Kathmandu",
    seoTitle: "Parsa National Park \u2013 Bengal Tiger Safari in Nepal's Hidden Terai Wilderness",
    seoDescription: "Explore Parsa National Park in Nepal's Madhesh Terai \u2013 home to 41 Bengal tigers, elephants, and vast sal forests. Less visited than Chitwan but equally wild. Book your safari now.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Patan Museum",
    category: "ARCHAEOLOGICAL",
    summary: "Widely regarded as the finest museum in Nepal, the Patan Museum occupies the restored Keshav Narayan Chowk courtyard of the Patan Royal Palace within the UNESCO World Heritage Patan Durbar Square, presenting over 1,100 religious artworks including gilded bronzes, stone sculptures, woodcarvings, and illuminated manuscripts from the Malla period. Inaugurated in 1997 with Austrian government support, it sets a global standard for contextual museum presentation, explaining each artefact's iconographic and ritual significance. The museum building itself\u2014an exquisitely restored 17th-century palace wing\u2014is as remarkable as its contents.",
    story: `<p>The Patan Museum's origins lie in the late Malla period palaces of Patan (Lalitpur), which served as the royal court of successive Malla kings until the Gorkha conquest of 1768. The palace complex fell into gradual disrepair over the following centuries until a landmark conservation partnership between the Nepalese government and the Austrian Development Agency transformed the Keshav Narayan Chowk wing into a world-class museum. The restoration, completed in the 1990s, became a model for sympathetic heritage conservation in South Asia.</p><h3>The Collection</h3><p>Over 200 artefacts are on permanent display, thoughtfully arranged in rooms that mirror their original functional contexts. Gilded copper repoussé panels, stone Vishnu sculptures, exquisite Tara bronzes, and manuscript pages illuminated with mineral pigments trace the evolution of Newar religious art across more than a millennium. Interactive explanations guide visitors through the complex iconography of Hindu and Buddhist deities, making the collection accessible to those with no prior knowledge of South Asian religious traditions.</p><h3>Highlights</h3><ul><li>Best museum in Nepal by consistent critical consensus</li><li>17th-century Malla palace courtyard setting</li><li>1,100+ artefacts; 200+ on permanent display</li><li>Gilded bronzes, stone carvings, and illuminated manuscripts</li><li>Overlooks Patan Durbar Square (UNESCO World Heritage Site)</li><li>Rooftop café with views over the square</li></ul>`,
    district: "Lalitpur",
    province: "BAGMATI",
    lat: 27.6726,
    lng: 85.3236,
    elevation: 1340,
    entryFee: "NPR 1,000 foreigners (includes Patan Durbar Square entry) / NPR 30 Nepali",
    bestSeason: "Year-round; October to May preferred",
    openingHours: "10:00\u201317:00 daily except Tuesday (closed Tuesday)",
    howToGetThere: "Patan Museum is at the centre of Patan Durbar Square in Lalitpur, approximately 5 km south of central Kathmandu. Take a taxi (15\u201320 minutes) from Thamel, or board a local microbus from Ratna Park toward Lagankhel and alight at Mangal Bazar/Patan Durbar Square. The museum entrance is inside the main square courtyard.",
    gygQuery: "Patan Museum Lalitpur Durbar Square tour Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Patan Museum \u2013 Nepal's Finest Art Museum inside Patan Durbar Square",
    seoDescription: "Explore Nepal's best museum inside Patan's UNESCO World Heritage Durbar Square. Over 1,100 Malla-era bronzes, sculptures, and manuscripts in a restored 17th-century royal palace.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "National Museum of Nepal",
    category: "ARCHAEOLOGICAL",
    summary: "The National Museum of Nepal at Chhauni, Kathmandu, is the country's premier repository of historical, cultural, and natural heritage, housed across three buildings at the foot of Swayambhunath Hill. Founded in 1928, its collection spans pre-historic stone tools, medieval arms and armour, royal regalia, Buddhist and Hindu sculptures, postage stamps, coins, and a notable Doll Gallery containing gifts to the royal family from heads of state. The museum's most prized possession is a sword presented by French Emperor Louis-Napoleon Bonaparte.",
    story: `<p>The National Museum of Nepal was founded in 1928 as the Shree Teen Sarkar Library and Museum under Prime Minister Chandra Shamsher Rana, initially housing royal trophies and arms. Over the following decades the collection expanded dramatically to encompass pre-historic artefacts, Hindu and Buddhist religious sculptures, and ethnographic material from across Nepal's diverse cultures. Today the museum complex comprises the Historical Museum Building, the Buddhist Art Gallery (Juddha Jayatia Kala Shala), and additional galleries for numismatics and natural history.</p><h3>The Collections</h3><p>The arms and armour gallery is one of the most visited sections, featuring khukuris, swords, shields, cane helmets, and leather cannons seized during Nepal's 1792 war with Tibet. A remarkable exhibit is a submachine gun and sword presented by Louis-Napoleon Bonaparte of France. The Buddhist Art Gallery houses gilded statues, thangka paintings, and ritual objects spanning several centuries. The Doll Gallery, a quirky but beloved section, displays dolls gifted to female royalty from world leaders and foreign dignitaries.</p><h3>Highlights</h3><ul><li>Founded 1928 – Nepal's oldest and largest national museum</li><li>Louis-Napoleon Bonaparte's sword – most prized artefact</li><li>Extensive arms gallery including Tibetan-war-era leather cannons</li><li>Buddhist Art Gallery with thangkas and gilded sculptures</li><li>Located near Swayambhunath Stupa – easy to combine visits</li><li>Postage stamp and coin collection gallery</li></ul>`,
    district: "Kathmandu",
    province: "BAGMATI",
    lat: 27.7057,
    lng: 85.2899,
    elevation: 1320,
    entryFee: "NPR 150 foreigners / NPR 50 SAARC / NPR 10 Nepali; extra for camera",
    bestSeason: "Year-round",
    openingHours: "Wednesday\u2013Monday 10:30\u201316:30 (Nov\u2013Jan closes 15:30); closed Tuesday",
    howToGetThere: "The National Museum is in Chhauni, approximately 3 km west of central Kathmandu and 800 m south of Swayambhunath Stupa. Take a taxi from Thamel (10 minutes), or walk from Swayambhunath via Chhauni Road. Local microbuses toward Kalanki pass the museum junction.",
    gygQuery: "National Museum Kathmandu Nepal heritage tour",
    bookingCity: "Kathmandu",
    seoTitle: "National Museum of Nepal \u2013 History & Heritage at Chhauni, Kathmandu",
    seoDescription: "Visit Nepal's National Museum in Chhauni \u2013 housing arms, royal artefacts, Buddhist art, and the Napoleon-gifted sword. Nepal's oldest and most comprehensive national museum.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Aircraft Museum Kathmandu",
    category: "ARCHAEOLOGICAL",
    summary: "Nepal's only aviation museum occupies an Airbus A330-300 Turkish Airlines aircraft that suffered a runway overrun at Tribhuvan International Airport in 2015 and has been converted into a unique museum at Sinamangal, Kathmandu. Opened in 2017 under the initiative of pilot Captain Bed Upreti, it houses over 350 miniature aircraft models tracing aviation history from the Wright Brothers to modern jets, alongside a preserved original cockpit and exhibits on Nepalese aviation milestones. The aircraft-turned-museum is a novel attraction for aviation enthusiasts and curious visitors near the airport.",
    story: `<p>On 4 March 2015, Turkish Airlines Flight TK726, an Airbus A330-300, overshot Tribhuvan International Airport's runway and came to rest in a field at the end of the strip. Remarkably, all 238 passengers and crew survived. The aircraft, too damaged to fly again, remained at Kathmandu for two years until pilot Captain Bed Upreti conceived the idea of converting it into Nepal's first aviation museum. Using NPR 70 million—partly personal savings, partly an Everest Bank loan—the project was completed and the museum opened on 28 November 2017.</p><h3>The Collection</h3><p>The museum's centrepiece is the aircraft's preserved cockpit, where visitors can sit in the captain's seat and examine the original instrument panels. Beyond the cockpit, 350+ scale models and miniatures trace the full arc of powered flight: from detailed replicas of the Wright Flyer and World War I biplanes to Cold War fighter jets and contemporary widebody airliners. Documentary exhibits chart Nepal's own aviation history, including the pioneering flights that opened Himalayan air routes and the stories of Nepal's commercial airlines.</p><h3>Highlights</h3><ul><li>Unique museum inside a real Airbus A330-300</li><li>350+ miniature aircraft from Wright Brothers era to present</li><li>Original cockpit open for visitor exploration</li><li>Exhibits on Nepalese aviation pioneers and Himalayan air routes</li><li>Located adjacent to Tribhuvan International Airport, Sinamangal</li></ul>`,
    district: "Kathmandu",
    province: "BAGMATI",
    lat: 27.694,
    lng: 85.354,
    elevation: 1340,
    entryFee: "NPR 250 adults / NPR 125 students (Nepali); NPR 600 foreigners",
    bestSeason: "Year-round",
    openingHours: "10:00\u201317:00 daily (confirm current hours with museum)",
    howToGetThere: "The Aircraft Museum is in Sinamangal, on the left side of the Ring Road adjacent to Tribhuvan International Airport, approximately 5 km east of Thamel. Easily reached by taxi (15 minutes from Thamel) or by app-based ride-share. Look for the distinctive aircraft fuselage visible from the road.",
    gygQuery: "aircraft aviation museum Kathmandu Nepal airplane",
    bookingCity: "Kathmandu",
    seoTitle: "Aircraft Museum Kathmandu \u2013 Nepal's Unique Aviation Museum in a Real Airbus A330",
    seoDescription: "Step inside a real Airbus A330 converted into Nepal's only aviation museum at Sinamangal. Explore 350+ aircraft models, the original cockpit, and Nepal's aviation history.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Thapathali Suspension Bridge",
    category: "ARCHAEOLOGICAL",
    summary: "The Thapathali area on the Bagmati River in central Kathmandu is historically significant as the site of Nepal's first modern bridge, originally built in 1810 under Prime Minister Bhimsen Thapa, and subsequently replaced by a 400-foot black iron suspension bridge imported from Paris and inaugurated in 1939 under Prime Minister Juddha Shamsher Rana. The bridge connects Thapathali in Kathmandu with Teku in Lalitpur across the Bagmati and remains an engineering and heritage landmark along the river. The surrounding Thapathali Durbar grounds add royal historical significance to the site.",
    story: `<p>Thapathali holds a unique place in Nepal's infrastructure history as the crossing point where the country's first engineered bridge was constructed in 1810. Commissioned by the formidable Prime Minister Bhimsen Thapa at the behest of Queen Regent Lalit Tripura Sundari, the original timber and pile structure spanned the Bagmati River at a point where the royal palace grounds of Thapathali Durbar met the southern bank. It was inaugurated in 1868 Bikram Sambat by King Girvan Yuddha Bikram Shah.</p><h3>The 1939 Iron Bridge</h3><p>The current and most celebrated structure at Thapathali is the 400-foot (approximately 120 m) black iron suspension bridge, prefabricated in Paris and shipped to Nepal under the direction of Prime Minister Juddha Shamsher Rana, who inaugurated it in March 1939. The imported French engineering was a statement of modernity by the Rana regime and represented Nepal's first significant use of European industrial infrastructure. The bridge connects Thapathali on the Kathmandu bank with Teku on the Lalitpur side, and pedestrians and cyclists still use it today.</p><h3>Highlights</h3><ul><li>Nepal's first bridge site – original 1810 timber structure by Bhimsen Thapa</li><li>1939 Paris-fabricated iron suspension bridge – still standing</li><li>Crosses Bagmati River between Thapathali and Teku</li><li>Adjacent to Thapathali Durbar – former royal palace grounds</li><li>Part of the Bagmati Promenade riverside heritage walk</li></ul>`,
    district: "Kathmandu",
    province: "BAGMATI",
    lat: 27.6956,
    lng: 85.3212,
    elevation: 1290,
    entryFee: "Free",
    bestSeason: "October to May",
    openingHours: "Always accessible (pedestrian bridge)",
    howToGetThere: "Thapathali is approximately 2 km south of Thamel in central Kathmandu. Walk or take a taxi down Tripureshwar Marg to the Thapathali junction. The suspension bridge is visible from the main road where it crosses the Bagmati River toward Teku. The Bagmati Promenade walking path connects Thapathali to Teku along the riverbank.",
    gygQuery: "Thapathali bridge Bagmati River Kathmandu heritage walk",
    bookingCity: "Kathmandu",
    seoTitle: "Thapathali Suspension Bridge \u2013 Nepal's Historic 1939 Iron Bridge, Kathmandu",
    seoDescription: "Visit the Thapathali Suspension Bridge in Kathmandu \u2013 a historic 1939 Paris-built iron bridge across the Bagmati River, marking the site of Nepal's first ever bridge from 1810.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Nagarjun Forest Reserve",
    category: "NATIONAL_PARK",
    summary: "Nagarjun Forest Reserve (also known as Rani Ban or Royal Forest) is a 1,423-hectare protected forest northwest of Kathmandu, historically used as a royal retreat by King Mahendra and now managed by the Nepal Army as part of Shivapuri Nagarjun National Park. The forested hill rises to Jamacho Peak at 2,094 m, offering panoramic views of the Kathmandu Valley and Himalayan ranges, and provides habitat for leopards, deer, and over 100 bird species. It is the closest forest wilderness to the capital, reachable in under 20 minutes from Thamel.",
    story: `<p>Nagarjun Forest Reserve takes its name from the renowned 2nd-century Buddhist philosopher Nagarjuna, who is believed to have meditated on this forested hill. The summit is still marked by a small Buddhist stupa, and Tibetan Buddhist pilgrims occasionally circumambulate the hill. During the Shah dynasty, the forest was designated as Rani Ban (Queen's Forest) and later as a royal hunting reserve for King Mahendra, whose summer palace still stands on the wooded slopes. The Nepal Army assumed management after the abolition of the monarchy.</p><h3>Hiking and Wildlife</h3><p>The main trail from the Phulbari Gate climbs steadily through subtropical and temperate forest to Jamacho Peak at 2,094 m, a two-and-a-half-hour ascent offering one of the finest unobstructed Himalayan panoramas accessible on foot from Kathmandu. The forest shelters common leopard, barking deer, wild boar, and porcupine, and the canopy is rich with babblers, laughingthrushes, sunbirds, and migrating raptors in spring and autumn. The rock climbing crags at Balaju Quarry inside the forest are among Kathmandu's best sport climbing venues.</p><h3>Highlights</h3><ul><li>Jamacho Peak (2,094 m) – best Himalayan viewpoint accessible on foot from Kathmandu</li><li>Historic royal forest and former King Mahendra's summer retreat</li><li>Buddhist summit stupa associated with philosopher Nagarjuna</li><li>Leopard, deer, wild boar, and 100+ bird species</li><li>Rock climbing crags at Balaju Quarry inside the reserve</li><li>Only 9 km from Thamel; Phulbari Gate accessible by taxi in 20 minutes</li></ul>`,
    district: "Kathmandu",
    province: "BAGMATI",
    lat: 27.746,
    lng: 85.281,
    elevation: 1460,
    entryFee: "NPR 250 foreigners / NPR 10 Nepali",
    bestSeason: "October to May; avoid monsoon for clear Himalayan views",
    openingHours: "06:00\u201317:00 daily",
    howToGetThere: "From Thamel, drive approximately 9 km northwest via Balaju to reach the Phulbari gate (main entrance) of Nagarjun Forest Reserve, behind Balaju Water Gardens. Journey takes 15\u201320 minutes by taxi. A secondary entry point exists at Budhanilkantha. Motorbikes and bicycles are permitted on certain trails inside the forest.",
    gygQuery: "Nagarjun Forest Reserve hiking Kathmandu Jamacho viewpoint",
    bookingCity: "Kathmandu",
    seoTitle: "Nagarjun Forest Reserve \u2013 Royal Forest Hike & Himalayan Views near Kathmandu",
    seoDescription: "Hike to Jamacho Peak (2,094 m) through Nagarjun Royal Forest Reserve for panoramic Himalayan views just 9 km from Kathmandu. Leopards, birds, rock climbing, and Buddhist history.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Shivapuri Nagarjun National Park",
    category: "NATIONAL_PARK",
    summary: "Shivapuri Nagarjun National Park is a 159 km\u00b2 protected area on the northern rim of the Kathmandu Valley, encompassing the forested ridgeline from Shivapuri Peak (2,732 m) to the Nagarjun Forest Reserve, and serving as Kathmandu's primary freshwater catchment and a vital urban wildlife sanctuary. Established in 2002, the park protects 19 mammal species including leopard and Himalayan black bear, and 177 bird species, while offering accessible hiking, mountain biking, and nature walks from multiple entry gates. It is the most easily accessible national park for Kathmandu residents and visitors.",
    story: `<p>Shivapuri Nagarjun National Park represents a rare case of a national park embedded in a megacity's periphery. When it was gazetted in 2002 as Nepal's ninth national park, its primary purpose was both conservation and watershed protection—the rivers Bagmati, Bishnumati, Rudramati, and several others that supply Kathmandu with drinking water all originate within the park. The park spans the districts of Kathmandu, Nuwakot, and Sindhupalchok, with its highest point at Shivapuri Peak (2,732 m) providing clear views of Langtang, Ganesh Himal, and on exceptional days, the Everest group.</p><h3>Wildlife and Ecosystems</h3><p>The park's elevational range from approximately 1,350 m at the valley floor to 2,732 m at Shivapuri supports a transition from subtropical broadleaf forest at lower elevations through temperate oak, rhododendron, and alder forests to subalpine scrub near the summit. Common leopard prowl the middle elevations and are occasionally glimpsed on camera traps. Himalayan black bear, yellow-throated marten, and Assamese macaque are resident, and the park is outstanding for woodland birding with Himalayan phylloscopus warblers, flycatchers, and laughingthrushes.</p><h3>Highlights</h3><ul><li>Shivapuri Peak (2,732 m) – panoramic Himalayan views</li><li>Primary watershed for Kathmandu Valley's drinking water rivers</li><li>19 mammal species including leopard and Himalayan black bear</li><li>177 bird species – excellent for woodland birding</li><li>Mountain biking, hiking, and camping within 12 km of city centre</li><li>Multiple entry gates: Budhanilkantha, Sundarijal, Panimuhan</li></ul>`,
    district: "Kathmandu",
    province: "BAGMATI",
    lat: 27.823,
    lng: 85.387,
    elevation: 2732,
    entryFee: "NPR 1,000 foreigners / NPR 600 SAARC / NPR 100 Nepali",
    bestSeason: "October to May; rhododendrons bloom March\u2013April",
    openingHours: "Gates open 06:00\u201318:00",
    howToGetThere: "The main Budhanilkantha gate is 12 km north of central Kathmandu on Budhanilkantha Road (25 minutes by taxi). Sundarijal gate (northeast entry) is 15 km from Kathmandu, 30 minutes by vehicle. Buses toward Budhanilkantha depart from Ratna Park. For Sundarijal, take a microbus from Chabahil ring road junction.",
    gygQuery: "Shivapuri National Park Kathmandu hiking trekking Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Shivapuri Nagarjun National Park \u2013 Hiking & Wildlife near Kathmandu",
    seoDescription: "Explore Shivapuri Nagarjun National Park on Kathmandu's doorstep \u2013 hike to 2,732 m, spot leopards and birds, and enjoy mountain biking through Nepal's urban wilderness.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Kopan Monastery",
    category: "MONASTERY",
    summary: "Kopan Monastery is one of the world's most renowned Tibetan Buddhist study centres, perched on a forested hill near Boudhanath in Kathmandu, offering internationally acclaimed month-long and shorter meditation and dharma courses to students from across the globe. Founded by Lamas Thubten Yeshe and Zopa Rinpoche in 1969 as a centre of the Gelugpa tradition under FPMT, it now houses over 360 monks and runs an annual November meditation course that has been drawing Western practitioners since 1971. Its hilltop setting and serene garden atmosphere make it a peaceful sanctuary just 15 km from Kathmandu's city centre.",
    story: `<p>Kopan Monastery's story begins in 1969 when Lamas Thubten Yeshe and Thubten Zopa Rinpoche purchased a hilltop property from Nepal's royal astrologer near the ancient stupa of Boudhanath. The two lamas had fled Tibet following the Chinese occupation and were teaching Buddhism to a growing circle of Western students in Kathmandu. In 1971 they held the first of what became annual month-long November meditation courses at Kopan, initially gathering a handful of seekers in a simple room. That first course was so transformative that students returned year after year, and word spread globally.</p><h3>Study and Practice</h3><p>Today Kopan offers a spectrum of programs ranging from 5-day introductory courses in Tibetan medicine and thangka painting to 10-day residential Buddhist psychology intensives and the celebrated month-long Lam Rim course held each November. The curriculum follows the Gelugpa Lam Rim (graduated path) tradition, combining formal teachings on ethics, meditation, and Buddhist philosophy with silent sitting periods and individual consultation with teachers. Accommodation ranges from shared dormitories to simple private rooms on the monastery's terraced garden grounds.</p><h3>Highlights</h3><ul><li>Annual November month-long Lam Rim meditation course – world-famous</li><li>5-day, 10-day, and specialised short courses year-round</li><li>Spectacular hilltop views over Boudhanath Stupa and Kathmandu Valley</li><li>Foundation for the Preservation of the Mahayana Tradition (FPMT) flagship centre</li><li>360+ resident monks; library and meditation halls open to students</li><li>25-minute taxi from Thamel; 5-minute walk uphill from Boudhanath Stupa area</li></ul>`,
    district: "Kathmandu",
    province: "BAGMATI",
    lat: 27.7422,
    lng: 85.3638,
    elevation: 1430,
    entryFee: "Free to visit the grounds; course fees vary by program (NPR 3,000\u201315,000 for short courses)",
    bestSeason: "Year-round; November for the famous month-long course",
    openingHours: "Grounds open to visitors 09:00\u201317:00; advance booking required for courses",
    howToGetThere: "Kopan Monastery is approximately 15 km northeast of central Kathmandu, near Boudhanath. Take a taxi from Thamel (25 minutes) to Boudhanath Stupa, then walk uphill for 20\u201325 minutes or take a short taxi ride to the monastery gate. Local buses toward Boudha depart from Ratna Park.",
    gygQuery: "Kopan Monastery meditation course Boudhanath Kathmandu Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Kopan Monastery Kathmandu \u2013 Tibetan Buddhist Meditation Courses near Boudhanath",
    seoDescription: "Join a meditation or dharma course at Kopan Monastery, one of the world's most respected Tibetan Buddhist centres near Boudhanath, Kathmandu. Month-long and short courses available.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Ka-Nying Shedrub Ling Monastery",
    category: "MONASTERY",
    summary: "Ka-Nying Shedrub Ling is one of Nepal's largest Tibetan Buddhist monasteries, built near Boudhanath in 1974\u20131976 at the wish of the 16th Karmapa and blending Kagyu and Nyingma traditions as reflected in its combined name. Under the stewardship of Ch\u00f6kyi Nyima Rinpoche, the monastery houses over 700 monks and runs the prestigious Rangjung Yeshe Institute\u2014the only institution offering accredited university degrees in Buddhist Studies and Himalayan Languages in Nepal in partnership with Kathmandu University. Its large golden-roofed temple complex is a magnificent example of Tibetan monastic architecture minutes from the great Boudhanath Stupa.",
    story: `<p>Ka-Nying Shedrub Ling—whose name blends the Kagyu (Ka) and Nyingma (Nying) schools of Tibetan Buddhism—was conceived by the 16th Gyalwang Karmapa, who selected Tulku Urgyen Rinpoche and his family to build and administer it. Construction began in 1974 on a parcel of land just north of the ancient Boudhanath Stupa, and the monastery was formally inaugurated by King Birendra of Nepal in the spring of 1976. The 16th Karmapa appointed Chökyi Nyima Rinpoche—Tulku Urgyen's eldest son—as the monastery's first abbot, a role he continues to hold today.</p><h3>The Monastery Complex</h3><p>The main temple (Tsuglagkhang) is a soaring multi-storied structure whose golden finials and ornate facade rise above the Boudha neighbourhood skyline. The interior houses an enormous gilded Buddha Shakyamuni, floor-to-ceiling murals depicting the Tibetan Buddhist cosmological universe, and elaborate ritual objects used in continuous liturgical practice by the monastic community of 700+ monks and resident tulkus. Adjacent to the main temple, the Rangjung Yeshe Institute was established in 1997 and offers multi-year courses in Tibetan language, Buddhist philosophy, and Himalayan culture with full university accreditation through Kathmandu University.</p><h3>Highlights</h3><ul><li>700+ monks and multiple resident tulkus</li><li>Kagyu-Nyingma synthesis – rare ecumenical tradition</li><li>Rangjung Yeshe Institute – BA, MA, PhD in Buddhist Studies (KU-accredited)</li><li>Magnificent golden-roofed temple with floor-to-ceiling murals</li><li>2-minute walk north of Boudhanath Stupa – easily combined</li><li>Public welcome for morning and evening pujas</li></ul>`,
    district: "Kathmandu",
    province: "BAGMATI",
    lat: 27.7218,
    lng: 85.3622,
    elevation: 1370,
    entryFee: "Free to visit and attend pujas; academic programs have fees",
    bestSeason: "Year-round",
    openingHours: "Morning puja ~07:00; grounds open during daylight hours; check schedule for evening puja",
    howToGetThere: "Ka-Nying Shedrub Ling is just north of Boudhanath Stupa in Boudha, approximately 8 km northeast of central Kathmandu. Take a taxi from Thamel (20 minutes), or take a local microbus from Ratna Park or Chabahil to Boudhanath, then walk 2\u20133 minutes north of the stupa.",
    gygQuery: "Ka-Nying Shedrub Ling monastery Boudhanath Kathmandu Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Ka-Nying Shedrub Ling Monastery \u2013 Boudha's Grand Tibetan Buddhist Temple",
    seoDescription: "Visit Ka-Nying Shedrub Ling Monastery near Boudhanath \u2013 one of Nepal's largest Tibetan Buddhist monasteries with 700+ monks, stunning murals, and the Rangjung Yeshe Institute.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Neydo Tashi Choling Monastery",
    category: "MONASTERY",
    summary: "Neydo Tashi Choling Monastery is a vibrant hilltop Kagyu monastery established in 2006 above the sacred village of Pharping in the south Kathmandu Valley, home to approximately 200 monks and perched dramatically above the Asura Cave where Padmasambhava attained enlightenment. The monastery's elevated position commands sweeping views of the forested Pharping valley, the Dakshinkali gorge, and on clear days the distant Himalayan horizon. It is both an active seat of Neydo Kagyu lineage teaching and a welcoming spiritual retreat destination for international visitors.",
    story: `<p>Pharping, a small hillside village 22 km southwest of Kathmandu, is one of the most densely sacred sites in Tibetan Buddhism, and the Neydo Tashi Choling Monastery was deliberately built here to maintain proximity to the Asura Cave below—where Guru Padmasambhava is said to have attained the Mahamudra siddhi in the 8th century. Established in 2006 under the Neydo Kagyu lineage, the monastery serves as both a training institution for around 200 young monks and a retreat facility for lay practitioners following the Neydo tradition.</p><h3>The Monastery and Its Setting</h3><p>The main temple building is constructed in traditional Tibetan style with a gilded roof, vibrant thangka-style murals, and a large altar featuring the principal lineage deities. The monastery's hilltop location—reached by a steep footpath or vehicle track from Pharping village—provides commanding views in all directions. Below the monastery, within easy walking distance, lie the Asura and Yangleshö caves, the Dakshinkali temple, and several smaller shrines within Pharping's sacred landscape. The combined Pharping pilgrimage circuit takes three to four hours on foot.</p><h3>Highlights</h3><ul><li>Hilltop monastery above Padmasambhava's Asura Cave</li><li>200+ resident monks in the Neydo Kagyu tradition</li><li>Panoramic views of Pharping valley and Himalayan foothills</li><li>Guest house accommodation available for retreatants</li><li>Combined visit with Asura Cave, Dakshinkali Temple, and Vajrayogini shrine</li><li>22 km from central Kathmandu – accessible day trip</li></ul>`,
    district: "Kathmandu",
    province: "BAGMATI",
    lat: 27.614,
    lng: 85.266,
    elevation: 1640,
    entryFee: "Free to visit; guesthouse accommodation available at modest fees",
    bestSeason: "October to May",
    openingHours: "Grounds accessible during daylight; morning puja ~06:30",
    howToGetThere: "From central Kathmandu, drive approximately 22 km southwest via Dakshinkali Road to Pharping village (45 minutes by taxi). The monastery is on the hill above Pharping, reached by a 10-minute walk on a steep footpath from the village, or by vehicle via a winding track. Combine with Dakshinkali Temple (2 km further) for a full half-day outing.",
    gygQuery: "Neydo Monastery Pharping Kathmandu Buddhist retreat Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Neydo Tashi Choling Monastery \u2013 Hilltop Buddhist Retreat above Pharping, Kathmandu",
    seoDescription: "Visit Neydo Tashi Choling Monastery above sacred Pharping, south Kathmandu \u2013 home to 200 monks of the Neydo Kagyu lineage, overlooking Padmasambhava's Asura Cave.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Asura Cave Pharping",
    category: "CAVE",
    summary: "The Asura Cave in Pharping, 19 km south of Kathmandu, is one of the most sacred sites in Vajrayana Buddhism\u2014the place where Guru Padmasambhava (Guru Rinpoche) engaged in intensive meditation in the 8th century and attained the Mahamudra siddhi through the combined practices of Yangdak Heruka and Vajrakilaya. Buddhist masters have called it as important for Vajrayana practitioners as Bodh Gaya is for all Buddhists. A preserved handprint believed to be Padmasambhava's is visible at the cave entrance, and small kila (ritual dagger) formations in the rock are said to have rained down when he accomplished the Vajrakilaya practice.",
    story: `<p>In the 8th century CE, Guru Padmasambhava—the tantric master credited with establishing Vajrayana Buddhism in Tibet—spent a prolonged period of intensive retreat in the caves above Pharping village, south of Kathmandu. The upper cave, known as Asura Cave or Yangleshö (upper), is where he is said to have attained the highest realisation of Mahamudra through the combined practice of Yangdak Heruka and Vajrakilaya. According to traditional accounts, a rain of iron kilas (ritual daggers) fell from the sky when he accomplished the Vajrakilaya practice, and small blackish kila formations remain visible in a narrow passage inside the cave to this day.</p><h3>Sacred Features and Pilgrimage</h3><p>The cave's entrance is marked by a large outdoor statue of Guru Rinpoche and a shrine room where butter lamps burn continuously, tended by monks from the Neydo Tashi Choling Monastery on the hill above. Inside the cave, a handprint impression in the rock near the entrance is venerated by pilgrims as a miraculous imprint left by Padmasambhava. The lower Yangleshö cave, where Padmasambhava retreated in summer months, is a short walk downhill near the Vajrayogini shrine. The entire Pharping area constitutes a mandala of sacred sites—caves, springs, and temples—that practitioners circumambulate on pilgrimage.</p><h3>Highlights</h3><ul><li>8th-century meditation site of Guru Padmasambhava</li><li>Iron kila formations in the rock – miraculous relics of Vajrakilaya practice</li><li>Padmasambhava's handprint impression at cave entrance</li><li>Considered equal to Bodh Gaya in importance for Vajrayana practitioners</li><li>Adjacent to Neydo Tashi Choling and Vajrayogini shrines</li><li>19 km southwest of Kathmandu – easy day trip or pilgrimage circuit</li></ul>`,
    district: "Kathmandu",
    province: "BAGMATI",
    lat: 27.613,
    lng: 85.264,
    elevation: 1570,
    entryFee: "Free; donations to the shrine are customary",
    bestSeason: "Year-round; avoid heavy monsoon rains July\u2013August for trail access",
    openingHours: "Dawn to dusk; butter lamps tended by monks throughout the day",
    howToGetThere: "From Kathmandu (Thamel), drive approximately 19\u201322 km southwest on the Dakshinkali Road to Pharping village (40\u201345 minutes by taxi). The Asura Cave is located above the village, reached by a short 10-minute climb on stone steps past the outdoor Guru Rinpoche statue. Combine with Dakshinkali Temple (2 km beyond Pharping) and Neydo Monastery for a full pilgrimage day.",
    gygQuery: "Asura Cave Pharping Padmasambhava sacred cave Kathmandu Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Asura Cave Pharping \u2013 Sacred Meditation Cave of Padmasambhava near Kathmandu",
    seoDescription: "Visit the Asura Cave in Pharping \u2013 where Guru Padmasambhava attained enlightenment in the 8th century. One of Vajrayana Buddhism's holiest sites, just 19 km from Kathmandu.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
]

async function main() {
  console.log(`🌱 Seeding batch 8 — ${places.length} places...`)
  for (const p of places) {
    await prisma.place.upsert({
      where: { slug: slug(p.name) },
      update: {},
      create: { ...p, slug: slug(p.name) },
    })
    console.log(`  ✅ ${p.name}`)
  }
  console.log('🌱 Batch 8 complete!')
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())