import 'dotenv/config'
import { PrismaClient } from '@prisma/client'
import slugify from 'slugify'

const prisma = new PrismaClient()
const slug = (n) => slugify(n, { lower: true, strict: true })

const places = [
  {
    name: `Daman Viewpoint`,
    category: "MOUNTAIN_VIEW",
    summary: `Perched at 2,322 metres on the Tribhuvan Highway in Makwanpur, Daman offers one of Nepal's most celebrated Himalayan panoramas. On clear days the horizon sweeps from Dhaulagiri in the west to Mount Everest in the east — more than 300 miles of unbroken snow-capped peaks. A viewpoint tower, rhododendron forests, and hillside monasteries complete the experience.`,
    story: `<p>Daman sits quietly on a forested ridge of the Mahabharat Range, roughly 77 kilometres southwest of Kathmandu along the historic Tribhuvan Highway — Nepal's first road, hand-carved through dramatic terrain in the 1950s. At 2,322 metres, the village commands what many seasoned travellers and mountain photographers consider the single finest wide-angle Himalayan panorama accessible by road anywhere in Nepal.</p><p>On a crisp autumn morning, the ridge unfurls an extraordinary sweep of the high Himalaya: Dhaulagiri (8,167 m) anchors the west, then the eye travels through the Annapurna massif, Manaslu, Ganesh Himal, Langtang, Dorje Lakpa, Gauri Shankar, Numbur, and finally the distant pyramid of Everest (8,849 m) in the east — a continuous white rampart stretching more than 500 kilometres. Few places on earth allow a motorable road traveller to witness so many eight-thousanders in a single glance.</p><p>The area is wrapped in dense forests of rhododendron, oak, and pine. In March and April the hillsides blush crimson and pink with rhododendron blooms, attracting bird-watchers alongside the mountain-view seekers. Light snowfall transforms the ridge into a winter wonderland between December and February, when the crystal-clear air often delivers the sharpest mountain views of all.</p><p>A modest observation tower on the hilltop provides an elevated platform, while a Tibetan Buddhist monastery nearby adds spiritual atmosphere. Small tea-houses and lodges line the roadside, welcoming overnight guests who wish to catch the golden alpenglow at dawn. The drive itself — winding through terraced fields, river gorges, and cloud-forest — is half the pleasure of a Daman visit.</p>`,
    district: `Makwanpur`,
    province: "BAGMATI",
    lat: 27.6833,
    lng: 85.1167,
    elevation: 2322,
    entryFee: `Free`,
    bestSeason: `October to December, March to April`,
    openingHours: `Open all day`,
    howToGetThere: `Drive 77 km southwest of Kathmandu on the Tribhuvan Highway (approximately 3 hours). Regular buses depart from Kathmandu's Kalanki bus station toward Hetauda; alight at Daman. Private vehicle or hired taxi offers the most flexibility.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Daman Viewpoint Nepal Himalaya panorama`,
    bookingCity: `Kathmandu`,
    seoTitle: `Daman Viewpoint Makwanpur | Nepal's Best Himalayan Panorama`,
    seoDescription: `Visit Daman Viewpoint in Makwanpur for Nepal's most spectacular Himalayan panorama. See 500 km of peaks from Dhaulagiri to Everest just 3 hours from Kathmandu.`,
    published: true,
    featured: false,
  },
  {
    name: `Panauti`,
    category: "CULTURAL_VILLAGE",
    summary: `Panauti is one of Nepal's oldest Newari towns, resting at the confluence of the Punyamati and Roshi rivers 32 km southeast of Kathmandu. Its medieval streetscapes, intricate wood-carved temples — including the 13th-century Indreshwar Mahadev — and centuries-old bathing ghats have earned it a UNESCO tentative listing. It is a living museum of Newar art and architecture.`,
    story: `<p>Nestled at around 1,450 metres amid the gentle hills of Kavrepalanchok, Panauti has been inhabited since at least the first century AD, making it one of the oldest continuously occupied towns in Nepal. Its recorded history stretches back through the Licchavi, Thakuri, and Malla dynasties, each layer leaving temples, courtyards, and stone sculptures that visitors can still touch today.</p><p>The town's spiritual heart is the Indreshwar Mahadev Temple, a three-tiered pagoda originally built in 1294 AD over an ancient Shiva lingam — acknowledged as one of the oldest surviving temples in Nepal. Its carved wooden struts, torana arches, and gilded finials represent Newari craftsmanship at its most refined. Equally revered is the Brahmayani Temple and the riverside Unmatta Bhairav shrine at the Tribeni ghat, where the Punyamati and Roshi rivers meet and a third mythical river is said to join them underground.</p><p>Bathing ghats line the riverbanks, and during festivals such as the Makar Mela (held every twelve years) tens of thousands of pilgrims converge to bathe in the sacred confluence. The town's alleyways are flanked by traditional double-storey Newari houses with elaborately carved timber balconies, pati (rest houses), and sunken water conduits — all preserved in a state rarely seen even in Bhaktapur.</p><p>The Nepal government nominated Panauti's medieval architectural complex to the UNESCO World Heritage tentative list in 1996, and restoration work continues today with international support. Day-trippers from Kathmandu discover an unhurried town where potters still work at street-side wheels, and where the scent of incense mingles with the sound of temple bells at dusk.</p>`,
    district: `Kavrepalanchok`,
    province: "BAGMATI",
    lat: 27.5829,
    lng: 85.5097,
    elevation: 1450,
    entryFee: `Free (small heritage fee may apply)`,
    bestSeason: `October to April`,
    openingHours: `Temples open sunrise to sunset`,
    howToGetThere: `From Kathmandu, take a bus or microbus from the Ratnapark area to Banepa (1 hour), then a shared jeep or local bus to Panauti (20 minutes). By private vehicle it is about 1.5 hours via the Araniko Highway.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Panauti ancient Newari town cultural tour Kathmandu`,
    bookingCity: `Kathmandu`,
    seoTitle: `Panauti Ancient Newari Town | UNESCO Tentative Site Kavrepalanchok`,
    seoDescription: `Explore Panauti, one of Nepal's oldest Newari towns. Visit the 13th-century Indreshwar temple, sacred river confluences, and medieval architecture just 32 km from Kathmandu.`,
    published: true,
    featured: false,
  },
  {
    name: `Sankhu`,
    category: "TEMPLE",
    summary: `Sankhu is an ancient Newar settlement 17 km northeast of Kathmandu, renowned for the sacred Vajrayogini Temple perched dramatically on the Manichuda hillside. One of the four principal Vajrayogini shrines in the Kathmandu Valley, it is a vital centre of Vajrayana Buddhist and Hindu Tantric worship. The steep stone-paved climb passes water spouts, a Milarepa cave, and sweeping valley views.`,
    story: `<p>Sankhu — whose name translates roughly as 'conch-shell town' — is one of the oldest continuously inhabited settlements in the Kathmandu Valley, predating the current era by many centuries. It once served as a major waystation on the trans-Himalayan trade route connecting the valley to Tibet, and its wealth is still reflected in the carved courtyard facades and traditional Newari row-houses that line its narrow lanes.</p><p>The town's most celebrated monument is the Vajrayogini Temple (Bajrayogini), enshrined halfway up the forested Manichuda hill above the settlement. Built in its current form by King Prakash Malla in 1655 AD, the temple is dedicated to Vajrayogini, a powerful tantric deity simultaneously revered by both Hindus and Vajrayana Buddhists. According to tradition, the goddess is said to have manifested spontaneously at this spot, and the site has drawn pilgrims for over a thousand years.</p><p>The ascent from Sankhu's bus stop is a 40-minute climb up stone steps shaded by ancient trees, punctuated by stone water spouts where devotees pause to cool themselves. About 200 metres below the main temple lies the Milarepa Cave — a small rocky grotto associated with the great Tibetan yogi Milarepa, who is said to have meditated here during his journeys across the Himalaya.</p><p>The temple complex itself comprises a golden-roofed main shrine, surrounding smaller shrines, and a large courtyard where religious festivals draw enormous crowds, particularly during Dashain. The annual Vajrayogini Jatra procession, when the deity's image is paraded through Sankhu's streets, remains one of the most vibrant and least-touristy festivals in the valley — an authentic glimpse into living Newar religious culture.</p>`,
    district: `Kathmandu`,
    province: "BAGMATI",
    lat: 27.6992,
    lng: 85.3136,
    elevation: 1305,
    entryFee: `Free`,
    bestSeason: `October to April`,
    openingHours: `Temple open daily 06:00–18:00`,
    howToGetThere: `From Kathmandu (Ratnapark or Boudha), take a local bus to Sankhu (approximately 1 hour, 17 km). From the bus stop a 40-minute uphill walk on stone steps leads to the Vajrayogini Temple. Taxis and private vehicles also available.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Sankhu Vajrayogini Temple Kathmandu Valley day trip`,
    bookingCity: `Kathmandu`,
    seoTitle: `Sankhu Vajrayogini Temple | Ancient Newar Town Kathmandu Valley`,
    seoDescription: `Discover Sankhu and its sacred Vajrayogini Temple, a key Tantric pilgrimage site 17 km from Kathmandu. Explore ancient Newari heritage, Milarepa Cave, and panoramic valley views.`,
    published: true,
    featured: false,
  },
  {
    name: `Sauraha`,
    category: "NATIONAL_PARK",
    summary: `Sauraha is the vibrant tourist village on the northern bank of the East Rapti River, serving as the main gateway to Chitwan National Park — Nepal's first and most celebrated UNESCO World Heritage wildlife reserve. Visitors come for elephant encounters, jungle safaris, canoe rides, and the chance to spot one-horned rhinoceros, Bengal tigers, and gharial crocodiles in their natural habitat.`,
    story: `<p>Situated where the East Rapti River forms a shimmering border with Chitwan National Park, Sauraha has evolved from a small Tharu fishing community into Nepal's most popular wildlife destination. The village sits at just 188 metres above sea level in the Terai lowlands, where subtropical jungle meets a network of oxbow lakes, grassland meadows called phanta, and dense sal forest — creating one of Asia's richest wildlife habitats.</p><p>Chitwan National Park, gazetted in 1973 and designated a UNESCO World Heritage Site in 1984, protects 952 km² of pristine jungle harbouring over 700 one-horned rhinoceros, 150 Bengal tigers, wild elephants, sloth bears, leopards, and more than 600 species of birds. Early-morning jeep safaris and elephant-back rides into the park from Sauraha offer extraordinary close encounters with megafauna in their natural environment.</p><p>Canoe rides along the East Rapti River drift silently past gharial and mugger crocodiles basking on sandbanks, while clouds of kingfishers and bee-eaters flash overhead. The Tharu Cultural Programme — performed each evening in Sauraha — showcases the indigenous Tharu people's distinctive stick dances, oil-lamp dances, and peacock dances, preserving traditions that stretch back centuries before the park's establishment.</p><p>The village itself has grown into a comfortable hub of eco-lodges, open-air restaurants, elephant-breeding centres (now transitioning away from elephant riding toward more ethical interactions), and the famous Sauraha sunset point on the riverbank — where the reflection of the Himalayan foothills in the still water makes for an unforgettable close to a day in the jungle.</p>`,
    district: `Chitwan`,
    province: "BAGMATI",
    lat: 27.5779,
    lng: 84.4945,
    elevation: 188,
    entryFee: `NPR 2,000 for foreigners, NPR 1,000 for SAARC nationals, NPR 150 for Nepali citizens (national park entry)`,
    bestSeason: `October to March`,
    openingHours: `Park open daily; safari departures at dawn and late afternoon`,
    howToGetThere: `From Kathmandu, take a tourist bus (6–7 hours) or fly to Bharatpur airport (25 minutes) then drive 23 km east. Regular public buses run from Kathmandu's Gongabu bus park to Tadi Bazaar, from where a short rickshaw ride reaches Sauraha.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Sauraha Chitwan jungle safari rhino tiger Nepal`,
    bookingCity: `Kathmandu`,
    seoTitle: `Sauraha Chitwan | Nepal's Premier Wildlife Safari Destination`,
    seoDescription: `Book a Sauraha Chitwan safari to spot one-horned rhinos, tigers, and elephants in UNESCO-listed Chitwan National Park. Best wildlife experience in Nepal.`,
    published: true,
    featured: false,
  },
  {
    name: `Hetauda`,
    category: "CULTURAL_VILLAGE",
    summary: `Hetauda is the provincial capital of Bagmati Province and the main industrial city of Makwanpur, positioned at the strategic meeting point of the Terai plains and the Mahabharat hills. As a key junction on both the Tribhuvan Highway and the East-West Mahendra Highway, it is the commercial gateway between Kathmandu and the Terai lowlands, with scenic surroundings of forested hills and the Rapti River.`,
    story: `<p>Hetauda occupies a pivotal geographic position in central Nepal — cradled between the forested slopes of the Mahabharat Range to the north and the flat expanse of the inner Terai to the south. At an elevation of just 300–390 metres, it enjoys a subtropical climate year-round, with the Rapti River threading through its outskirts and the hills providing a dramatic backdrop.</p><p>Declared the capital of Bagmati Province in 2020, Hetauda has rapidly transformed from an industrial town into a growing administrative city. Its reputation as an industrial hub was established during the 1970s and 1980s when cement factories, textile mills, and chemical plants were established here under government development initiatives. This industrial heritage sits alongside a surprisingly green urban landscape, with tree-lined boulevards and parks.</p><p>For travellers, Hetauda is frequently the first taste of the Terai after the mountain drive from Kathmandu — a descent through misty switchbacks and sal forest that culminates in the warm, humid air of the lowlands. The local market area buzzes with commerce, and regional Tharu and Magar cultural influences flavour the food and festivals. Nearby Chitwan National Park is accessible as a day excursion.</p><p>The drive from Kathmandu via the Tribhuvan Highway passes through Daman viewpoint and offers spectacular mountain scenery. An alternative route via the new Kathmandu-Nijgadh Fast Track (under development) promises to cut journey times dramatically, further integrating Hetauda as a logistics gateway for the entire Terai belt stretching east and west.</p>`,
    district: `Makwanpur`,
    province: "BAGMATI",
    lat: 27.4286,
    lng: 85.0313,
    elevation: 350,
    entryFee: `Free`,
    bestSeason: `October to March`,
    openingHours: `Open all day`,
    howToGetThere: `Hetauda is 76 km from Kathmandu via the Kathmandu-Hetauda fast track or 132 km via Tribhuvan Highway. Regular buses from Kathmandu's Gongabu bus park (4–5 hours). Also reachable from Narayanghat on the East-West Highway.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Hetauda Makwanpur Nepal gateway Terai travel`,
    bookingCity: `Kathmandu`,
    seoTitle: `Hetauda Makwanpur | Bagmati Province Capital & Terai Gateway`,
    seoDescription: `Discover Hetauda, the industrial capital of Bagmati Province in Makwanpur. A key junction city between Kathmandu and Nepal's Terai lowlands with scenic hill surroundings.`,
    published: true,
    featured: false,
  },
  {
    name: `Jiri`,
    category: "TREK_ROUTE",
    summary: `Jiri is a prosperous hill town in Dolakha District, historically renowned as the starting point of the original overland trekking route to Everest Base Camp. Before the Lukla airport era, every major Himalayan expedition — including Hillary and Tenzing's 1953 summit team — passed through Jiri. The classic Jiri-to-EBC trek remains the most culturally immersive and physically rewarding approach to the Khumbu.`,
    story: `<p>Long before a dirt airstrip at Lukla transformed the Everest trekking industry, Jiri was the undisputed gateway to the highest mountains on earth. Located 188 kilometres east of Kathmandu at 1,905 metres, this bustling market town in Dolakha District marked the end of the road and the beginning of weeks of walking for generations of mountaineers and adventurers.</p><p>In 1953, Edmund Hillary, Tenzing Norgay, and the entire British expedition team marched out of Jiri on their way to the world's first successful ascent of Mount Everest. For three decades afterwards, every serious Himalayan trekker and climber made this same journey — a multi-week crossing of successive ridges and river valleys through Sherpa, Rai, and Tamang villages that provided unparalleled cultural immersion before even approaching the high mountains.</p><p>The Jiri-to-Everest Base Camp trek is a formidable undertaking of 19–21 days, covering approximately 205 kilometres with an extraordinary sequence of dramatic ascents and descents — crossing the Lamjura Pass (3,530 m), Solu-Khumbu highlands, Namche Bazaar, and the iconic Khumbu Glacier route to Base Camp at 5,364 m. The gradual acclimatisation profile of the Jiri approach makes altitude sickness significantly less common than the fly-to-Lukla option.</p><p>Today Jiri is a thriving town with regular bus connections to Kathmandu (8–9 hours), a busy Thursday market, and a Swiss-funded development project legacy that transformed its hospital and infrastructure in the 1980s. The town serves as a base for exploration of Dolakha's own attractions, including the Charikot viewpoint and Gaurishankar peaks.</p>`,
    district: `Dolakha`,
    province: "BAGMATI",
    lat: 27.6336,
    lng: 86.232,
    elevation: 1905,
    entryFee: `Free (Sagarmatha National Park entry NPR 3,000 for foreigners applies if continuing to EBC)`,
    bestSeason: `March to May, October to November`,
    openingHours: `Open all day`,
    howToGetThere: `Daily buses depart from Kathmandu's Ratnapark bus station (8–9 hours, approximately 188 km). Alternatively, drive via the B.P. Highway through Banepa. No airport; road transport only.`,
    trekDays: 19,
    trekDifficulty: "HARD",
    trekMaxElevation: 5364,
    trekDistance: 205,
    trekStartPoint: `Jiri`,
    trekEndPoint: `Everest Base Camp`,
    trekHighlights: [`Historic route of the 1953 Everest expedition`, `Lamjura Pass (3,530 m) — highest point before Khumbu`, `Culturally rich Sherpa, Rai, and Tamang villages`, `Namche Bazaar Sherpa capital`, `Optimal acclimatisation profile`, `Tengboche Monastery with Everest views`],
    gygQuery: `Jiri to Everest Base Camp classic trek Nepal`,
    bookingCity: `Kathmandu`,
    seoTitle: `Jiri Nepal | Classic Gateway to Everest Trekking Route`,
    seoDescription: `Start the legendary Jiri to Everest Base Camp trek — the original route of Hillary and Tenzing. 19-day classic trek through Dolakha with cultural immersion and superior acclimatisation.`,
    published: true,
    featured: false,
  },
  {
    name: `Charikot`,
    category: "HILL_VIEWPOINT",
    summary: `Charikot — officially known as Bhimeshwar — is the district headquarters of Dolakha, set at around 1,950 metres with commanding views of the Gaurishankar and Langtang ranges. This ancient Newari town on the road to Jiri is a quiet hill station with traditional architecture, a vibrant weekly market, and easy access to the Sailung Hill trekking area and Gaurishankar Conservation Area.`,
    story: `<p>Charikot sits at the administrative and cultural heart of Dolakha District, occupying a broad ridge at approximately 1,950 metres above sea level. Renamed Bhimeshwar Municipality in recent administrative restructuring, the town retains its local identity as Charikot — a name that resonates through centuries of Newari settlement in this eastern hill district, some 139 kilometres from Kathmandu.</p><p>The view from Charikot's ridge is one of the town's most compelling attractions. On clear mornings, the snow-capped pyramid of Gaurishankar (7,134 m) — known in Hindu mythology as the combined abode of Shiva (Shankara) and Parvati (Gauri) — dominates the northern skyline, flanked by the peaks of the Rolwaling Himal. The Langtang range floats on the horizon to the northwest, and the forested ridges of the Mahabharat hills recede to the south.</p><p>The town's historic core preserves traditional Newari double-storey houses, carved wood-lattice windows, and small temples dedicated to the valley's tutelary deities. The weekly Thursday market draws traders and farmers from surrounding villages, filling the main street with a colourful commerce of vegetables, textiles, and livestock. The famous Dolakha Bhimsen Temple — one of the most important Bhimsen shrines in Nepal — draws pilgrims from across the country.</p><p>Charikot is the natural base for trekkers heading to Sailung Hill, the Gaurishankar Conservation Area, and the Rolwaling Valley. The town was significantly affected by the 2015 Gorkha earthquake but has rebuilt steadily, and its resilience is visible in the mix of restored heritage buildings and newer construction lining the main bazaar.</p>`,
    district: `Dolakha`,
    province: "BAGMATI",
    lat: 27.6667,
    lng: 86.0333,
    elevation: 1950,
    entryFee: `Free`,
    bestSeason: `October to May`,
    openingHours: `Open all day`,
    howToGetThere: `Buses depart from Kathmandu (Ratnapark) daily to Charikot, approximately 5–6 hours (139 km). Private vehicle on the Sindhuli or Dolakha highway. The town is the road junction for Jiri and Sailung.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Charikot Dolakha Nepal hill station Gaurishankar view`,
    bookingCity: `Kathmandu`,
    seoTitle: `Charikot Dolakha Nepal | Hill Station with Gaurishankar Views`,
    seoDescription: `Visit Charikot (Bhimeshwar), Dolakha's district headquarters at 1,950 m with stunning Gaurishankar mountain views. Gateway to Sailung trekking and Gaurishankar Conservation Area.`,
    published: true,
    featured: false,
  },
  {
    name: `Sailung Hill`,
    category: "HILL_VIEWPOINT",
    summary: `Sailung Hill rises to 3,146 metres on the border of Dolakha and Ramechhap districts, revered equally as a sacred Hindu pilgrimage site dedicated to Sailungeshwor Mahadev and as a panoramic Himalayan viewpoint. Trekkers are rewarded with views spanning Everest, Langtang, Ganesh Himal, and Dorje Lakpa, while spiritual seekers find ancient chortens, temples, and the mystical 'land of 100 hills' landscape.`,
    story: `<p>Sailung Hill occupies one of the most singular landscapes in the Bagmati hills — a broad, undulating summit zone at 3,146 metres that local Tamang and Magar communities describe as 'saya thumba', meaning the land of one hundred sacred hills. Each rounded summit within this extraordinary highland terrain is considered by believers to carry its own spiritual energy, connected to the presiding deity Sailungeshwor Mahadev, a manifestation of Lord Shiva who is said to reside here overlooking the Himalaya.</p><p>The religious significance of Sailung is ancient and deeply felt. At the summit area, a cluster of stone chortens (Buddhist stupas), Hindu shrines, prayer flag lines, and a small temple dedicated to Sailungeshwor Mahadev create a remarkable interfaith sacred landscape where Hindu and Buddhist traditions interweave seamlessly — a pattern common across Nepal's middle hills. Every year, especially during Shivaratri, thousands of pilgrims make the arduous ascent to offer worship.</p><p>For secular trekkers and nature lovers, Sailung delivers a spectacular 360-degree panorama on clear days: Everest and Lhotse gleam to the northeast, the Rolwaling Himal and Gaurishankar fill the north, Langtang and Dorje Lakpa stretch to the northwest, and the Ganesh Himal group anchors the west. The forested flanks harbour diverse Himalayan flora including rhododendron, juniper, and high-altitude medicinal plants, while birds of prey circle the thermal currents above the ridgeline.</p><p>The most common trekking approach begins at Charikot or Manthali (Ramechhap), with a 2–3 day hike through terraced hillside villages. Simple teahouses and homestays have emerged along the route as visitor numbers grow, though Sailung remains relatively uncrowded and rewards those seeking a less commercial Himalayan experience.</p>`,
    district: `Dolakha`,
    province: "BAGMATI",
    lat: 27.7,
    lng: 86.15,
    elevation: 3146,
    entryFee: `Free`,
    bestSeason: `March to May, October to November`,
    openingHours: `Open all day`,
    howToGetThere: `From Kathmandu, drive or bus to Charikot (5–6 hours) or Manthali in Ramechhap (4–5 hours). From either trailhead, a 2–3 day trek reaches the summit. Local jeeps may cover part of the approach road.`,
    trekDays: 3,
    trekDifficulty: "MODERATE",
    trekMaxElevation: 3146,
    trekDistance: 30,
    trekStartPoint: `Charikot or Manthali`,
    trekEndPoint: `Sailung Hill Summit`,
    trekHighlights: [`Sacred Sailungeshwor Mahadev temple at summit`, `Panoramic view of Everest, Langtang, and Ganesh Himal`, `Ancient chortens and prayer flags`, `Rhododendron forests and alpine meadows`, `Land of 100 Hills sacred landscape`, `Tamang and Magar village culture en route`],
    gygQuery: `Sailung Hill trek Dolakha Nepal Himalaya viewpoint`,
    bookingCity: `Kathmandu`,
    seoTitle: `Sailung Hill Trek Dolakha | Sacred 3,146m Himalayan Viewpoint Nepal`,
    seoDescription: `Trek to Sailung Hill (3,146 m) in Dolakha for panoramic views of Everest, Langtang, and Ganesh Himal. A sacred Hindu-Buddhist pilgrimage site with stunning Himalayan panoramas.`,
    published: true,
    featured: false,
  },
  {
    name: `Banepa`,
    category: "CULTURAL_VILLAGE",
    summary: `Banepa is a historic Newari municipality at the eastern edge of the Kathmandu Valley, 25 km from the capital on the Araniko Highway. Once a powerful independent kingdom and a major waypoint on the ancient Nepal-Tibet trade route, it retains Newari-style temples, traditional architecture, and the celebrated Chandeshwari Temple — a sacred Shaktipeeth set in forested hills above the town.`,
    story: `<p>Perched at roughly 1,500 metres at the eastern gateway of the Kathmandu Valley, Banepa commands the critical junction where the valley's eastward road branches toward Tibet via the Araniko Highway and south toward Panauti and Kavrepalanchok. This strategic position made Banepa a prosperous trading town and, for a brief period in the 14th and 15th centuries, the capital of an independent principality that exercised considerable power in the region.</p><p>The town's Newari heritage is evident in its traditional architecture — double-storey brick houses with intricately carved timber windows, sunken water spouts (dhunge dhara), and small neighbourhood shrines at every street corner. During the Malla period, eight Ganesh temples were constructed at the eight directional gates of the town, forming a sacred protective ring; several of these still stand. The main bazaar retains its traditional character despite growing modernity.</p><p>Banepa's most celebrated religious site is the Chandeshwari Temple, situated on a forested hill about one kilometre from the town centre. Dedicated to the goddess Chandeshwari — who, according to myth, slew the demon Chand here — the temple is one of the valley's important Shaktipeeths. The annual Chandeshwari Jatra chariot festival is one of the most spectacular processions in the Kavrepalanchok region, drawing thousands of devotees.</p><p>As the first major town encountered after leaving the Kathmandu Valley toward the east, Banepa marks a psychological as well as geographical threshold — the point where the valley's dense urban fabric gives way to the open landscapes of the Palung, Panauti, and Dhulikhel hills. It is an ideal half-day stop for those exploring the eastern Kathmandu Valley circuit.</p>`,
    district: `Kavrepalanchok`,
    province: "BAGMATI",
    lat: 27.6333,
    lng: 85.5167,
    elevation: 1500,
    entryFee: `Free`,
    bestSeason: `October to April`,
    openingHours: `Temples open sunrise to sunset`,
    howToGetThere: `Frequent microbuses and buses depart from Kathmandu's Ratnapark for Banepa (about 1 hour, 25 km). Also on the Araniko Highway for private vehicles. Banepa is the junction for Panauti, Dhulikhel, and Namobuddha.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Banepa Chandeshwari Temple Kavrepalanchok Nepal cultural tour`,
    bookingCity: `Kathmandu`,
    seoTitle: `Banepa Kavrepalanchok | Historic Newari Town Gateway to Eastern Nepal`,
    seoDescription: `Explore Banepa, the historic Newari gateway town 25 km from Kathmandu. Visit Chandeshwari Temple, traditional architecture, and the ancient Tibet trade route junction.`,
    published: true,
    featured: false,
  },
  {
    name: `Shuklaphanta National Park`,
    category: "NATIONAL_PARK",
    summary: `Shuklaphanta National Park in Kanchanpur, far-western Nepal, protects 305 km² of Terai grasslands, riverine forests, and wetlands harbouring the world's largest single herd of swamp deer — over 2,300 individuals. The park is also home to Bengal tigers, elephants, and over 500 bird species, making it one of Nepal's most biodiverse yet least-visited protected areas.`,
    story: `<p>Shuklaphanta — meaning 'white grassland' — takes its name from the vast open phanta meadows that characterise much of its 305 km² landscape in the Terai lowlands of Kanchanpur District. Gazetted as a wildlife reserve in 1976 and elevated to national park status in 2017, making it Nepal's youngest national park, Shuklaphanta protects one of the last great Terai grassland ecosystems in the western Himalayan foothills.</p><p>The park's most extraordinary wildlife spectacle is the swamp deer (Rucervus duvaucelii), known locally as barasingha. Shuklaphanta hosts the world's single largest congregation of this endangered species, with over 2,300 individuals gathering in the open grasslands — a sight of staggering biological significance that draws wildlife researchers and photographers from around the globe. The park is one of the few places on earth where this majestic deer can be observed in such numbers.</p><p>Bengal tigers stalk through the tall elephant grass and riverine sal forest, and the Sarda River system supports populations of gharial and mugger crocodiles, smooth-coated otters, and the endangered Gangetic river dolphin. Asian elephants cross between Nepal and India through corridor forests adjoining the park. Over 500 bird species have been recorded, including the Bengal florican, sarus crane, and various raptors that hunt over the open meadows.</p><p>Despite its extraordinary biodiversity, Shuklaphanta receives far fewer visitors than Chitwan or Bardia, making it ideal for travellers seeking an uncrowded, off-the-beaten-track wildlife experience. The remote location in Nepal's far-western Sudurpashchim Province requires a commitment to travel — but rewards with authentic encounters and a sense of genuine wilderness that the more famous parks can no longer offer.</p>`,
    district: `Kanchanpur`,
    province: "SUDURPASHCHIM",
    lat: 28.8333,
    lng: 80.2333,
    elevation: 174,
    entryFee: `NPR 1,000 for foreigners, NPR 500 for SAARC nationals, NPR 50 for Nepali citizens (per day)`,
    bestSeason: `November to March`,
    openingHours: `Park open daily 06:00–18:00`,
    howToGetThere: `Fly from Kathmandu to Dhangadhi (1.5 hours), then drive approximately 65 km south to Mahendranagar and the park entrance. Alternatively, take a bus from Kathmandu or Nepalgunj on the Mahendra Highway. The nearest town is Mahendranagar (10 km).`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Shuklaphanta National Park safari swamp deer Nepal far west`,
    bookingCity: `Dhangadhi`,
    seoTitle: `Shuklaphanta National Park Kanchanpur | Nepal's Swamp Deer Sanctuary`,
    seoDescription: `Visit Shuklaphanta National Park in far-western Nepal for the world's largest swamp deer herd, Bengal tigers, and pristine Terai grasslands. Nepal's youngest and most unspoiled national park.`,
    published: true,
    featured: false,
  },
  {
    name: `Mahendranagar`,
    category: "CULTURAL_VILLAGE",
    summary: `Mahendranagar — officially Bhimdattanagar — is Nepal's westernmost major city in Kanchanpur District, positioned just 5 km from the Indian border at the Mahakali River. It is the commercial capital of far-western Nepal and the gateway to Shuklaphanta National Park, offering a window into the distinctive culture of the Sudurpashchim region blended with cross-border Indo-Nepali trade traditions.`,
    story: `<p>Mahendranagar sits at the far western edge of Nepal, where the Mahakali River — sacred boundary between Nepal and India — marks the international frontier near the Indian town of Banbasa in Uttarakhand. Named after King Mahendra and later officially renamed Bhimdattanagar in honour of a local martyr, the city exists in a fascinating liminal zone between two nations, two cultures, and two economies.</p><p>Founded as a planned settlement in the 1960s to develop Nepal's far-western Terai, Mahendranagar grew rapidly as a commercial hub for agricultural produce from Kanchanpur's fertile plains and for cross-border trade with India. Today it is the largest city in Sudurpashchim Province, with a diverse population including Tharu, Awadhi-speaking communities, Doteli hill migrants, and Indian traders who cross the open border daily.</p><p>The city centre is compact and busy, with a main bazaar selling everything from Indian consumer goods to Nepali handicrafts. The Mahakali River, revered as a goddess, is visible from the western edge of town, and the forested buffer zones around Shuklaphanta National Park begin practically at the city's doorstep — tigers and elephants occasionally wander into the outskirts, reminding residents and visitors alike of the wild landscape that envelops this frontier city.</p><p>For travellers, Mahendranagar is typically the base for Shuklaphanta National Park visits. The city also offers the Kalika Temple, a popular local pilgrimage site, and the vibrant scene of an open-border crossing — a cultural study in itself as Indian and Nepali citizens mingle freely through the immigration checkpoint without visas.</p>`,
    district: `Kanchanpur`,
    province: "SUDURPASHCHIM",
    lat: 28.9167,
    lng: 80.3333,
    elevation: 228,
    entryFee: `Free`,
    bestSeason: `November to February`,
    openingHours: `Open all day`,
    howToGetThere: `Fly from Kathmandu to Dhangadhi airport (1.5 hours), then take a bus or taxi 65 km west to Mahendranagar (1.5 hours). The Mahendra Highway also connects the city to Nepalganj and all eastern Terai cities. Indian travellers can cross from Banbasa, Uttarakhand.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Mahendranagar far western Nepal Shuklaphanta safari gateway`,
    bookingCity: `Dhangadhi`,
    seoTitle: `Mahendranagar Kanchanpur | Far-Western Nepal City & Shuklaphanta Gateway`,
    seoDescription: `Explore Mahendranagar, Nepal's far-western frontier city on the Mahakali River. Gateway to Shuklaphanta National Park with vibrant cross-border culture and Terai wildlife.`,
    published: true,
    featured: false,
  },
  {
    name: `Dipayal Silgadhi`,
    category: "HILL_VIEWPOINT",
    summary: `Dipayal Silgadhi is the administrative headquarters of Doti District in Sudurpashchim Province, perched at 1,310 metres along the Seti River in the Lesser Himalayas. It is the key junction on the Mahakali and Seti highways, offering access to the remote far-western hills and the historic Silgadhi Fort — site of a celebrated 1814 battle where Gurkha soldiers repelled British forces.`,
    story: `<p>Dipayal Silgadhi straddles both banks of the Seti River where the river has carved a dramatic gorge through the Lesser Himalayan foothills. At 1,310 metres, the town enjoys a temperate mountain climate and commanding views of the surrounding ridges. Its name combines two settlement areas — Dipayal on the western bank and Silgadhi on the eastern — that have grown into a single municipality serving as the nerve centre of Doti District.</p><p>The town carries deep historical weight. The Silgadhi Fort, situated on a wooded hilltop above the settlement, was the site of a significant military engagement during the Anglo-Nepal War of 1814–16. A determined force of Gurkha soldiers held the fort against superior British forces for an extended period before ultimately withdrawing — an act of resistance commemorated annually as a national festival day (Tansen Praja Diwas) in Nepal. The crumbling fort walls are now a heritage site and pilgrimage point for Nepali nationalists.</p><p>The Seti River flowing through the gorge below Dipayal is a striking sight — its milky-white waters, laden with glacial limestone sediment, give the river its name (Seti means 'white' in Nepali). The river is a tributary system that eventually joins the larger Karnali drainage, and its gorge provides dramatic scenery for those exploring the town's surroundings on foot.</p><p>As the Seti Highway extends connectivity northward toward Bajhang and Bajura, Dipayal has become the staging post for travellers venturing into Nepal's most remote far-western districts. The weekly market day brings farmers, traders, and herders from surrounding villages, making it one of the more vivid rural market scenes in Sudurpashchim Province.</p>`,
    district: `Doti`,
    province: "SUDURPASHCHIM",
    lat: 29.2608,
    lng: 80.94,
    elevation: 1310,
    entryFee: `Free`,
    bestSeason: `October to May`,
    openingHours: `Open all day`,
    howToGetThere: `Fly from Kathmandu to Dhangadhi (1.5 hours), then take a bus or jeep 140 km northeast to Dipayal Silgadhi (approximately 4–5 hours on the Mahakali Highway). Daily buses also run from Mahendranagar. Road conditions vary seasonally.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Dipayal Silgadhi Doti Nepal far west travel Seti River`,
    bookingCity: `Dhangadhi`,
    seoTitle: `Dipayal Silgadhi Doti | Far-Western Nepal Hill Town & Historic Fort`,
    seoDescription: `Visit Dipayal Silgadhi, headquarters of Doti District in Sudurpashchim Province. Explore Silgadhi Fort, the Seti River gorge, and gateway to Nepal's remote far-western hills.`,
    published: true,
    featured: false,
  },
  {
    name: `Baitadi`,
    category: "TEMPLE",
    summary: `Baitadi is a hill district in Sudurpashchim Province known for its ancient Hindu temples, traditional Doteli culture, and dramatic landscapes bordering India and the Api-Nampa Conservation Area. The Tripura Sundari Temple and Ninglashaini Temple are major pilgrimage sites, while the district's terraced hillscapes, dense forests, and proximity to high Himalayan peaks offer rewarding off-beat exploration.`,
    story: `<p>Baitadi District occupies a rugged stretch of far-western Nepal where the hills rise from the Sarda River valley to the glaciated peaks of the Api-Nampa massif (7,132 m). The district headquarters town of Dasharathchand — named in honour of a local freedom fighter — sits at around 1,793 metres amidst terraced agricultural slopes and pine-rhododendron forest, offering views of Nepal's extreme western Himalaya on clear days.</p><p>The district is steeped in religious tradition, hosting some of the most revered temples in Nepal's far west. The Tripura Sundari Temple, dedicated to the goddess of the three worlds, draws thousands of pilgrims during Dashain and other festivals. The Ninglashaini Temple perched on a forested hilltop is considered one of Nepal's 108 Shaktipeeths and attracts devotees who make the steep climb as an act of devotion. The Gwallek Kedar forest shrine near the Indian border is shared by pilgrims from both countries.</p><p>Baitadi's cultural identity is shaped by the Doteli language and traditions of the Khas-Arya communities who have inhabited these hills for centuries. Traditional architecture features distinctive stone-roofed houses, and local festivals such as the Gaura Parva celebration — the major festival of the far-western hills — transform village squares into vibrant gathering points of song, dance, and communal worship.</p><p>The district offers potential for trekking toward the Api-Nampa Conservation Area, one of Nepal's least-visited protected zones, where snow leopards, Himalayan tahr, and blue sheep inhabit pristine alpine terrain. Access remains challenging, requiring fly-in to Dhangadhi followed by road travel, but the rewards for adventurous travellers are considerable.</p>`,
    district: `Baitadi`,
    province: "SUDURPASHCHIM",
    lat: 29.5333,
    lng: 80.5667,
    elevation: 1793,
    entryFee: `Free (temple offerings customary)`,
    bestSeason: `March to May, October to November`,
    openingHours: `Temples open sunrise to sunset`,
    howToGetThere: `Fly to Dhangadhi from Kathmandu (1.5 hours), then take a bus or jeep northeast via the Mahakali Highway to Dasharathchand, Baitadi headquarters (approximately 6–7 hours). Road conditions are seasonal.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Baitadi temples far western Nepal Tripura Sundari pilgrimage`,
    bookingCity: `Dhangadhi`,
    seoTitle: `Baitadi Sudurpashchim | Ancient Temples & Far-Western Nepal Hills`,
    seoDescription: `Explore Baitadi's ancient Hindu temples including Tripura Sundari and Ninglashaini shrines in Nepal's far-western hills. A remote pilgrimage and cultural destination near the Api-Nampa Conservation Area.`,
    published: true,
    featured: false,
  },
  {
    name: `Dadeldhura`,
    category: "TEMPLE",
    summary: `Dadeldhura is a hill district headquarters in Sudurpashchim Province, best known as the home of the revered Ugratara Temple — one of Nepal's most important Shaktipeeths set in dense forest at Amargadhi, 4 km from the town centre. The district offers traditional Doteli culture, panoramic hill views, and a gateway role for the Seti corridor to Nepal's remote far-western districts.`,
    story: `<p>Dadeldhura District's headquarters town of Amargadhi stands at roughly 1,700 metres in the far-western hills of Sudurpashchim Province, looking out over a landscape of terraced fields, pine forests, and distant Himalayan ridges. The town is compact but significant — as the administrative centre of Dadeldhura and a key stop on the road network linking Dipayal, Mahendranagar, and the Seti River corridor.</p><p>The spiritual heart of Dadeldhura is the Ugratara Temple, located on a forested hilltop in Amargadhi Municipality Ward 7, approximately four kilometres from the district centre. Dedicated to Ugratara — a fierce form of the goddess Tara worshipped as both a Buddhist and Hindu deity in Nepal's complex religious landscape — the temple is regarded as one of the most powerful Shaktipeeths in the far west. Thousands of devotees make the pilgrimage during the Dashain festival and other auspicious occasions.</p><p>The temple complex is surrounded by ancient trees draped in prayer flags, creating an atmospheric forest sanctuary that feels profoundly removed from the modern world. Stone-carved images of Ugratara and accompanying deities line the approach path, which itself is a form of devotional practice. The rituals observed here are deeply rooted in Tantric traditions preserved by the Khas-Arya communities of the far-western hills.</p><p>Beyond the temple, Dadeldhura offers insight into the traditional Doteli culture of Nepal's extreme west — a culture of strong women farmers, distinct dialects, distinctive jewellery and dress, and ancient oral literary traditions. The Gaura Parva festival, celebrated with particular energy across Dadeldhura and neighbouring districts, is a UNESCO-recognised expression of intangible cultural heritage unique to the far-western hills.</p>`,
    district: `Dadeldhura`,
    province: "SUDURPASHCHIM",
    lat: 29.3197,
    lng: 80.6059,
    elevation: 1700,
    entryFee: `Free (temple offerings customary)`,
    bestSeason: `March to May, October to November`,
    openingHours: `Temple open sunrise to sunset`,
    howToGetThere: `Fly from Kathmandu to Dhangadhi (1.5 hours), then take a bus or jeep on the Mahakali or Seti Highway to Amargadhi, Dadeldhura (approximately 5–6 hours). The town is connected to Dipayal Silgadhi and Mahendranagar by road.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Dadeldhura Ugratara Temple Nepal far west pilgrimage`,
    bookingCity: `Dhangadhi`,
    seoTitle: `Dadeldhura Ugratara Temple | Sacred Shaktipeeth Nepal Far West`,
    seoDescription: `Discover Dadeldhura and the revered Ugratara Temple — a powerful Shaktipeeth in Nepal's Sudurpashchim Province. Traditional Doteli culture and Himalayan hill landscapes await.`,
    published: true,
    featured: false,
  },
  {
    name: `Bajura`,
    category: "RIVER",
    summary: `Bajura is one of Nepal's most remote and rugged districts in Sudurpashchim Province, anchored by the sacred Tribeni confluence where three rivers meet at Triveni Municipality and the dramatic Badimalika Temple at 4,200 metres. The district offers an off-the-beaten-path experience of pristine Himalayan wilderness, ancient religious sites, and the traditional cultures of Khas and Thakuri communities.`,
    story: `<p>Bajura District stretches across a dramatic range of terrain in Nepal's extreme northwest — from subtropical river valleys carved by the Karnali tributary systems at around 726 metres to the glaciated summits of the Api-Nampa range reaching beyond 7,000 metres. The district headquarters at Martadi (approximately 2,000 metres) is a two-day journey from Dhangadhi, requiring jeep travel on mountain roads that are frequently disrupted by landslides and seasonal flooding.</p><p>The most celebrated pilgrimage destination in Bajura is the confluence of Tribeni — where three sacred rivers meet at Triveni Municipality — and the associated Badimalika Temple complex. The main Badimalika shrine sits at the Mallagiri peak at an extraordinary 4,200 metres, making it one of the highest permanently worshipped Hindu temples in Nepal. Pilgrims undertake a challenging multi-day journey to reach the temple, which is dedicated to the goddess Badimalika (Bhagawati), arriving in their thousands during the annual Badimalika Mahotsav festival in August.</p><p>The Tribeni Patan, a high-altitude grassland at around 3,840 metres near the confluence, presents a remarkable alpine landscape of rolling meadows, sacred shrines, and prayer flag clusters framed by Himalayan peaks. The spiritually charged atmosphere at this remote confluence — where rivers from different directions merge — creates a pilgrimage experience of unusual intensity and authenticity.</p><p>Bajura's natural environment is extraordinary: snow leopards roam the upper valleys, Himalayan tahr and blue sheep graze on rocky slopes, and the forests harbour pheasants, eagles, and Himalayan black bears. For the rare adventurous traveller willing to make the journey, Bajura offers Nepal as it was before mass tourism — untouched, challenging, and deeply moving.</p>`,
    district: `Bajura`,
    province: "SUDURPASHCHIM",
    lat: 29.4415,
    lng: 81.4853,
    elevation: 2109,
    entryFee: `Free`,
    bestSeason: `April to June, September to October`,
    openingHours: `Open all day`,
    howToGetThere: `Fly from Kathmandu to Dhangadhi (1.5 hours). From Dhangadhi take a jeep on the Seti Highway toward Bajura (2 days, road conditions permitting). Alternatively, charter flights or STOL aircraft occasionally serve Bajura's Sanphebagar airstrip. The Tribeni area requires additional trekking from Martadi.`,
    trekDays: 4,
    trekDifficulty: "HARD",
    trekMaxElevation: 4200,
    trekDistance: 60,
    trekStartPoint: `Martadi, Bajura`,
    trekEndPoint: `Badimalika Temple / Tribeni Patan`,
    trekHighlights: [`Sacred Badimalika Temple at 4,200 m`, `Tribeni sacred river confluence`, `Tribeni Patan alpine grasslands at 3,840 m`, `Remote Himalayan wilderness with snow leopard habitat`, `Ancient Khas-Thakuri cultural traditions`, `Panoramic views of Api-Nampa range`],
    gygQuery: `Bajura Badimalika Temple Tribeni trek far western Nepal`,
    bookingCity: `Dhangadhi`,
    seoTitle: `Bajura Tribeni Confluence | Remote Himalayan Pilgrimage Nepal`,
    seoDescription: `Explore Bajura, one of Nepal's most remote districts. Trek to the sacred Tribeni confluence and Badimalika Temple at 4,200 m in Sudurpashchim's untouched Himalayan wilderness.`,
    published: true,
    featured: false,
  },
  {
    name: `Mugu District`,
    category: "LAKE",
    summary: `Mugu is Nepal's most remote district in Karnali Province, home to the stunning Rara Lake — the country's largest lake at 2,975 metres — set within the pristine Rara National Park. Accessible only by small aircraft or multi-day trek from Jumla, Mugu offers unparalleled wilderness solitude, crystal-clear mountain lakes, and the traditional culture of the Karnali highland communities.`,
    story: `<p>Mugu District is consistently ranked as Nepal's most remote and least-developed district — a distinction that, paradoxically, makes it one of the country's most compelling travel destinations for those willing to make the considerable effort required to reach it. Nestled in the Karnali Zone of northwestern Nepal, Mugu is accessible only by small aircraft to Talcha Airport or Jumla Airport, followed by trekking, as it has no connection to Nepal's national road network.</p><p>The crown jewel of Mugu is Rara Lake (Rara Tal), Nepal's largest lake, occupying a mountain basin at 2,975 metres above sea level. With a surface area of 10.8 km² and a maximum depth of 167 metres, Rara is renowned for its extraordinary clarity and its shifting spectrum of colours — emerald green in morning light, deep sapphire at midday, and burnished gold at sunset. The lake is surrounded by the dense forests of Rara National Park (106 km²), Nepal's smallest national park, where red panda, Himalayan black bear, musk deer, and diverse Himalayan bird species inhabit the pristine woodland.</p><p>The Mugu Karnali River drains the lake northward through increasingly remote Himalayan terrain toward Tibet, and the district borders China along its northern edge. The villages of the Mugu valley are inhabited by Tibetan-influenced communities — some speaking Tibetan dialects — who maintain traditional herding, trading, and farming lifestyles that have changed little in centuries.</p><p>The trek to Rara Lake from Jumla typically takes 4–5 days through beautiful mountain terrain, passing through rhododendron forests, alpine meadows, and traditional stone villages. The combination of extreme remoteness, extraordinary natural beauty, and cultural authenticity makes Mugu one of Nepal's most memorable and meaningful wilderness destinations.</p>`,
    district: `Mugu`,
    province: "KARNALI",
    lat: 29.5236,
    lng: 82.1244,
    elevation: 2975,
    entryFee: `NPR 3,000 for foreigners, NPR 1,500 for SAARC nationals (Rara National Park entry)`,
    bestSeason: `May to June, September to October`,
    openingHours: `Open all day`,
    howToGetThere: `Fly from Kathmandu to Nepalgunj (1 hour), then to Talcha Airport in Mugu or Jumla Airport (45 minutes). From Jumla or Talcha, trek 4–5 days to Rara Lake. Alternatively, a long overland route via Surkhet and Gamgadhi is possible by jeep with additional trekking.`,
    trekDays: 5,
    trekDifficulty: "MODERATE",
    trekMaxElevation: 3450,
    trekDistance: 70,
    trekStartPoint: `Jumla or Talcha`,
    trekEndPoint: `Rara Lake`,
    trekHighlights: [`Rara Lake — Nepal's largest and most pristine mountain lake`, `Rara National Park wildlife including red panda and Himalayan bear`, `Remote Karnali highland villages and Tibetan-influenced culture`, `Dense rhododendron and conifer forest`, `Extraordinary mountain solitude and wilderness`, `Views of the Mugu Karnali valley and Himalayan peaks`],
    gygQuery: `Rara Lake Mugu District trek Karnali Nepal wilderness`,
    bookingCity: `Nepalgunj`,
    seoTitle: `Mugu District Rara Lake | Nepal's Most Remote Karnali Wilderness`,
    seoDescription: `Trek to Rara Lake in Mugu District — Nepal's largest lake at 2,975 m in pristine Rara National Park. Nepal's most remote and beautiful wilderness destination in Karnali Province.`,
    published: true,
    featured: false,
  },
  {
    name: `Jajarkot`,
    category: "ARCHAEOLOGICAL",
    summary: `Jajarkot is a historically significant district in Karnali Province with deep roots in Nepal's medieval kingdom history. The Khalanga Durbar (White Palace) built in 1795 AD, views of Mount Sisne (5,911 m), and the dramatic Bheri River valley define a district that played a pivotal role in the Karnali region's royal and political history. An off-beat destination for cultural and historical exploration.`,
    story: `<p>Jajarkot District occupies a rugged stretch of Karnali Province between the Bheri River in the south and the high Himalayan watershed to the north. The district headquarters, Khalanga, sits at approximately 1,350 metres above sea level — a hilltop town with panoramic views of Mount Sisne (5,911 m) and the broader Karnali highlands. Khalanga is named in the tradition of hill capitals across Nepal's western region, the suffix 'khala' indicating a 'flat area' suited to settlement and administration.</p><p>The historical significance of Jajarkot is considerable. During the medieval period, Jajarkot was an independent princely state — one of the twenty-two and twenty-four principalities (Baise and Chaubise rajyas) that fragmented Nepal's western hills before the unification by Prithvi Narayan Shah in the late 18th century. The most visible relic of this royal past is the Seto Durbar (White Palace) at Khalanga, constructed around 1795 AD by King Indra Narayan Shah. Its whitewashed walls, though weathered, remain the most distinctive landmark of the district headquarters.</p><p>The Bheri River, one of Nepal's major river systems, flows through the southern reaches of the district, enriching agricultural lands and supporting communities of fishers whose traditions extend back centuries. The river valley also carries the Bheri Highway, the main road connection linking Jajarkot to Surkhet and the broader national road network — though road conditions remain challenging in monsoon season.</p><p>Jajarkot's forests harbour diverse Himalayan wildlife, and trekking routes from the district connect northward toward Dolpa and the Crystal Mountain region. The district gained additional global attention in November 2023 when a powerful earthquake caused significant damage and casualties — but community reconstruction efforts have been ongoing with government and international support.</p>`,
    district: `Jajarkot`,
    province: "KARNALI",
    lat: 28.7833,
    lng: 82.2167,
    elevation: 1350,
    entryFee: `Free`,
    bestSeason: `October to May`,
    openingHours: `Open all day`,
    howToGetThere: `Fly from Kathmandu to Nepalgunj (1 hour), then take a bus or jeep on the Bheri Highway to Khalanga, Jajarkot (approximately 6–8 hours from Surkhet). Alternatively, fly to Surkhet and continue by road. No direct air service to Jajarkot.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Jajarkot Karnali Nepal historical district travel`,
    bookingCity: `Nepalgunj`,
    seoTitle: `Jajarkot Karnali | Historic Kingdom District & Bheri River Valley Nepal`,
    seoDescription: `Discover Jajarkot's royal history, the Seto Durbar palace, and dramatic Karnali landscapes. An off-beat cultural and historical destination in Nepal's remote Karnali Province.`,
    published: true,
    featured: false,
  },
  {
    name: `Rukum East`,
    category: "TREK_ROUTE",
    summary: `Rukum East is a remote mountainous district of Karnali Province (though administratively in Lumbini Province), bisected by the Bheri River and characterised by rugged high-altitude terrain, Magar cultural traditions, and trekking routes that pass through pristine Himalayan wilderness. The district formed part of the historic Guerrilla Trek route through Nepal's Maoist heartland and offers unique cultural-adventure exploration.`,
    story: `<p>Eastern Rukum District encompasses a dramatically varied landscape from the Bheri River valleys at below 800 metres to alpine ridges approaching 6,000 metres in the Dhaulagiri massif to the north. The district was created in 2017 when the original Rukum was divided, with Eastern Rukum remaining in Karnali Province (though administratively grouped with Lumbini Province in some classifications) while Western Rukum joined Karnali Province.</p><p>The district is predominantly inhabited by Magar communities — one of Nepal's largest indigenous groups with a distinct language, culture, and ancestral connection to the hills of mid-western Nepal. Magar villages are characterised by stone houses with flat roofs, traditional weaving traditions, and a cultural vitality expressed through their own festivals, music, and oral history traditions. The communities here were significantly affected by Nepal's decade-long Maoist conflict (1996–2006), which began in this very region.</p><p>This Maoist history has been creatively reimagined as a tourism asset through the Guerrilla Trek (also known as the Peace Trail), which routes trekkers through the villages and mountain terrain where the People's War unfolded. The trek passes through Rolpa and Rukum districts, taking 10–14 days to complete and offering insights into one of the most significant periods in contemporary Nepali history alongside spectacular mountain scenery.</p><p>Eastern Rukum's 52 lakes and 53 hill summits offer rewarding trekking in less-visited terrain, where the combination of high-altitude wilderness — home to Himalayan tahr, pheasants, and bear — and living Magar cultural traditions creates a multi-layered travel experience available to only a small number of adventurous visitors each year.</p>`,
    district: `Rukum East`,
    province: "KARNALI",
    lat: 28.6167,
    lng: 82.7833,
    elevation: 1800,
    entryFee: `Free`,
    bestSeason: `March to May, October to November`,
    openingHours: `Open all day`,
    howToGetThere: `Fly from Kathmandu to Nepalgunj or Surkhet, then travel by bus or jeep through the Bheri Highway into Eastern Rukum. Road access has improved in recent years though remains challenging. Local bus or hired jeep from Surkhet recommended.`,
    trekDays: 10,
    trekDifficulty: "HARD",
    trekMaxElevation: 3800,
    trekDistance: 120,
    trekStartPoint: `Surkhet or Thabang`,
    trekEndPoint: `Libang or Sandhikharka`,
    trekHighlights: [`Guerrilla Trek (Peace Trail) through Maoist heartland`, `Magar indigenous culture and village life`, `52 high-altitude lakes in remote mountain terrain`, `Dhaulagiri Himalayan panoramas`, `Pristine Himalayan wilderness with tahr and pheasants`, `Bheri River valley scenery`],
    gygQuery: `Rukum East Guerrilla Trek Karnali Nepal off-beat trekking`,
    bookingCity: `Nepalgunj`,
    seoTitle: `Rukum East Nepal | Guerrilla Trek & Magar Culture Karnali Province`,
    seoDescription: `Trek through Rukum East's remote Himalayan landscape on the historic Guerrilla (Peace) Trail. Discover Magar culture, pristine mountain wilderness, and 52 high-altitude lakes in Karnali Province.`,
    published: true,
    featured: false,
  },
  {
    name: `Salyan`,
    category: "HILL_VIEWPOINT",
    summary: `Salyan is a peaceful hill district headquarters in Karnali Province, set at 1,530 metres amid the mid-western hills of Nepal. Known for its panoramic views of the Dhaulagiri and Karnali highlands, traditional market town atmosphere, and the nearby Kalimati viewpoint, Salyan offers an authentic window into mid-western Nepali hill culture away from the main trekking circuits.`,
    story: `<p>Salyan Khalanga — the district headquarters of Salyan — occupies a prominent ridge at 1,530 metres in the mid-western hills of Karnali Province. With coordinates placing it centrally within the broader Karnali basin, the town commands views north to the Dhaulagiri and Karnali highland ranges and south across the rolling hills descending toward the Terai. The district itself covers 1,462 square kilometres of diverse terrain from subtropical river valleys to temperate highland forests.</p><p>Salyan has historically been a crossroads district — connected to Dang in the south, Surkhet to the west, and Rolpa and Rukum to the north and east. The weekly market at the district headquarters draws traders and farmers from a wide catchment, and the town has a lively bazaar culture characteristic of Nepal's mid-western administrative centres. The local cuisine features the distinctive dishes of the Khas-Arya communities of the mid-western hills — dhedo (buckwheat porridge), local varieties of fermented greens, and home-distilled spirits.</p><p>The Kalimati viewpoint near the district headquarters offers panoramic vistas of the surrounding mountain country, and rhododendron forests bloom spectacularly in March and April on the hillsides above the town. Several small temples and religious sites dot the town and its surrounding villages, reflecting the deep Hindu traditions of the Salyan communities.</p><p>As part of Nepal's developing road network, Salyan has become increasingly connected in recent years, with a road linking it to the East-West Highway at Lamahi in Dang. This improved connectivity is gradually opening the district to domestic tourists from the Terai cities, though international visitor numbers remain minimal — making it genuinely off-beat for foreign travellers seeking an unmediated experience of mid-western Nepali hill life.</p>`,
    district: `Salyan`,
    province: "KARNALI",
    lat: 28.3753,
    lng: 82.1617,
    elevation: 1530,
    entryFee: `Free`,
    bestSeason: `October to May`,
    openingHours: `Open all day`,
    howToGetThere: `Fly from Kathmandu to Nepalgunj (1 hour), then take a bus or jeep north through Surkhet and Dang to Salyan Khalanga (approximately 5–6 hours from Surkhet). The new road via Lamahi-Dang also connects the district to the East-West Highway.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Salyan district Nepal Karnali hill town travel off-beat`,
    bookingCity: `Nepalgunj`,
    seoTitle: `Salyan Karnali Province | Peaceful Mid-Western Nepal Hill District`,
    seoDescription: `Discover Salyan, a tranquil hill district headquarters in Karnali Province at 1,530 m. Experience authentic mid-western Nepali culture, panoramic mountain views, and rhododendron forests away from tourist crowds.`,
    published: true,
    featured: false,
  },
  {
    name: `Gaurishankar Conservation Area`,
    category: "TREK_ROUTE",
    summary: `The Gaurishankar Conservation Area in Dolakha and Sindhupalchok protects 2,179 km² of pristine Himalayan terrain centred on the sacred Gaurishankar peak (7,134 m) and the dramatic Rolwaling Valley. Home to the holy Tsho Rolpa glacial lake, high-altitude monasteries, and challenging trekking routes, it is one of Nepal's most scenically spectacular and spiritually significant protected areas.`,
    story: `<p>Established in January 2010, the Gaurishankar Conservation Area encompasses 2,179 km² of Himalayan landscape across Dolakha, Ramechhap, and Sindhupalchok districts in Bagmati Province. The conservation area takes its name from Gaurishankar (7,134 m), the towering peak that dominates the northern skyline — a mountain so sacred in Hindu tradition that it is believed to be the combined abode of Shiva (Shankar) and his consort Parvati (Gauri). The mountain was not permitted to be climbed until 1979, such was its religious significance.</p><p>The centrepiece of the conservation area is the Rolwaling Valley — one of Nepal's most remote and dramatically beautiful glacier valleys, stretching westward from the Tibetan border toward the Tesi Lapcha Pass. The valley harbours the sacred Tsho Rolpa glacial lake (4,580 m), one of Nepal's largest and fastest-growing glacial lakes, which has expanded significantly due to climate-change-driven glacial retreat and is now closely monitored for outburst flood risk. Above the lake, the Tesi Lapcha Pass (5,755 m) provides a challenging high-altitude crossing into the Khumbu region.</p><p>The Tamang and Sherpa communities of the Rolwaling Valley maintain a living Buddhist culture shaped by centuries of relative isolation. The small monastery at Na village and the seasonal high pastures above it preserve traditions of yak herding and high-mountain Buddhism that are rapidly disappearing elsewhere. The valley's wildlife is exceptional — snow leopard, Himalayan tahr, red panda, and over 250 bird species inhabit the diverse altitudinal zones from 968 m to 7,181 m.</p><p>The conservation area receives a modest but growing number of trekkers, particularly on the Rolwaling-Everest crossing route and the Gaurishankar base camp approaches. Its relative remoteness compared to Langtang and Everest makes it a prized destination for experienced trekkers seeking solitude and genuine Himalayan adventure.</p>`,
    district: `Dolakha`,
    province: "BAGMATI",
    lat: 27.965,
    lng: 86.3378,
    elevation: 4580,
    entryFee: `NPR 3,000 for foreigners (conservation area entry); additional trekking permits may apply`,
    bestSeason: `March to May, October to November`,
    openingHours: `Open all day (seasonal route conditions apply)`,
    howToGetThere: `From Kathmandu, drive or take a bus to Charikot/Dolakha (5–6 hours). From Charikot, trek or take a jeep toward Simigaun village — the main entry point for the Rolwaling Valley trek. The valley road from Charikot to Gongar has been extended in recent years.`,
    trekDays: 14,
    trekDifficulty: "HARD",
    trekMaxElevation: 5755,
    trekDistance: 140,
    trekStartPoint: `Charikot / Dolakha`,
    trekEndPoint: `Tesi Lapcha Pass or Gaurishankar Base Camp`,
    trekHighlights: [`Sacred Gaurishankar peak (7,134 m) views`, `Tsho Rolpa glacial lake at 4,580 m`, `Tesi Lapcha Pass (5,755 m) — Rolwaling to Khumbu crossing`, `Remote Rolwaling Valley Sherpa and Tamang monasteries`, `Snow leopard, red panda, and Himalayan tahr habitat`, `Pristine glacier and alpine scenery with minimal crowds`],
    gygQuery: `Gaurishankar Conservation Area Rolwaling Valley trek Nepal`,
    bookingCity: `Kathmandu`,
    seoTitle: `Gaurishankar Conservation Area | Rolwaling Valley Trek Dolakha Nepal`,
    seoDescription: `Trek the Gaurishankar Conservation Area in Dolakha — home to Rolwaling Valley, Tsho Rolpa glacier lake, and the sacred Gaurishankar peak (7,134 m). Nepal's most dramatic and least-crowded Himalayan trekking region.`,
    published: true,
    featured: false,
  },
]

async function main() {
  console.log('🌱 Seeding batch 13 — 20 places...')
  for (const p of places) {
    const s = slug(p.name)
    await prisma.place.upsert({
      where: { slug: s },
      update: {},
      create: { ...p, slug: s },
    })
    console.log('  ✅', p.name)
  }
  console.log('🌱 Batch 13 complete!')
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
