import 'dotenv/config'
import { PrismaClient } from '@prisma/client'
import slugify from 'slugify'

const prisma = new PrismaClient()
const slug = (n) => slugify(n, { lower: true, strict: true })

const places = [
  {
    name: `Upper Mustang Trek`,
    category: "TREK_ROUTE",
    summary: `Journey into the forbidden kingdom of Lo Manthang, a walled medieval city carved from the Tibetan plateau at 3,840 metres. This restricted-area trek crosses wind-sculpted canyons, ancient cave monasteries and Tibetan-influenced villages virtually unchanged for centuries, offering one of the most culturally immersive adventures in the Himalayas.`,
    story: `<p>Hidden behind the great Himalayan wall that blocks the monsoon, Upper Mustang occupies a rain-shadow desert of ochre cliffs, fluttering prayer flags and cave-riddled escarpments that feel more Tibetan than Nepali. For decades this was a closed kingdom ruled by the Mustang Raja, and the landscape still carries an air of untouched remoteness that few trekking destinations can match.</p><p>The standard route begins with a thrilling flight from Pokhara to Jomsom, then follows the Kali Gandaki gorge north through Kagbeni, the gateway to the restricted zone. Beyond here, the terrain shifts dramatically: the trail winds past Chele, Syangboche and Ghami before arriving at Charang and finally Lo Manthang, the walled capital where whitewashed chortens and ancient gompas crowd against the desert sky. Side trips to Luri Gompa and Chhoser cave monastery reward the curious explorer.</p><p>The culture is unmistakably Tibetan Buddhist. Monks spin prayer wheels in dimly lit chapels, women weave on wooden looms, and the air carries the scent of juniper incense. Lo Manthang's four-storey royal palace and the 15th-century Thubchen Gompa murals are among the finest examples of Buddhist art in all of Nepal.</p><p>Logistically, every trekker requires a Restricted Area Permit costing USD 50 per day and a licensed local guide. The dry season stretches from October through May, and the high-altitude desert is navigable even in shoulder seasons when the lower Annapurna region is buried in monsoon rain. This is trekking at its most frontier, civilisation peeled back to reveal something ancient and extraordinary.</p>`,
    district: `Mustang`,
    province: "GANDAKI",
    lat: 29.1804,
    lng: 83.9714,
    elevation: 3840,
    entryFee: `USD 50 per day Restricted Area Permit + ACAP NPR 3000`,
    bestSeason: `Oct-Nov, Mar-May`,
    openingHours: `Always open`,
    howToGetThere: `Fly Kathmandu to Pokhara, then Pokhara to Jomsom (20 min flight). Trek north from Jomsom to Kagbeni and into Upper Mustang. All trekkers must arrange permits and a licensed guide through a registered agency.`,
    trekDays: 14,
    trekDifficulty: "MODERATE",
    trekMaxElevation: 4210,
    trekDistance: 180,
    trekStartPoint: `Jomsom / Kagbeni`,
    trekEndPoint: `Lo Manthang`,
    trekHighlights: [`Medieval walled city of Lo Manthang (3,840m)`, `Luri Gompa and Chhoser cave monasteries`, `Kali Gandaki gorge and Tibetan-plateau scenery`, `Ancient Thubchen and Jampa Lhakhang gompa murals`, `Traditional Mustangi villages and royal palace`, `Wind-eroded badlands and rainbow-coloured cliffs`],
    gygQuery: `Upper Mustang Trek Lo Manthang Nepal`,
    bookingCity: `Jomsom`,
    seoTitle: `Upper Mustang Trek – The Forbidden Kingdom of Lo Manthang`,
    seoDescription: `Explore the medieval walled city of Lo Manthang on the Upper Mustang Trek. 14-day restricted-area adventure through Tibetan plateau landscapes, ancient cave monasteries and centuries-old Buddhist culture in Gandaki, Nepal.`,
    published: true,
    featured: false,
  },
  {
    name: `Dhaulagiri Circuit Trek`,
    category: "TREK_ROUTE",
    summary: `One of Nepal's most demanding wilderness circuits, the Dhaulagiri Circuit loops around the world's seventh-highest peak through two passes above 5,000 metres, Italian Base Camp and a spectacular hidden valley draped in glaciers. This raw, committing route rewards only the fittest and most experienced trekkers with landscapes of extraordinary scale.`,
    story: `<p>Standing at 8,167 metres, Dhaulagiri dominates the skyline of western Nepal like a white fortress above the clouds. The circuit that bears its name is considered by many seasoned trekkers to be Nepal's most challenging non-technical trekking route, rivalling even the most rugged terrain of the Himalayas in terms of sheer commitment and physical demand.</p><p>The trek begins in the subtropical lowlands near Beni or Babiyachaur in Myagdi District and climbs aggressively through rhododendron forest and alpine meadows toward Italian Base Camp at 3,660 metres. From there the trail ascends to Dhaulagiri Base Camp at 4,740 metres, where the sheer south face of the mountain rises overhead in an almost overwhelming spectacle of ice and rock. The crossing of French Pass at 5,360 metres and the traverse of the Hidden Valley at 5,050 metres are the twin cruxes of the route, demanding crampons, proper acclimatisation and a clear head in thin air.</p><p>What sets this circuit apart from Everest or Annapurna is its profound remoteness. There are no crowded teahouses or Wi-Fi passwords here. Trekkers carry tents and provisions, crossing a landscape largely untouched by tourism. Wildlife including Himalayan thar and snow leopard have been spotted on the high ridges, and the silence above the snowline is total.</p><p>The descent via Marpha and the Kali Gandaki valley returns trekkers to civilisation through apple orchards and Thakali guesthouses, providing a memorable contrast to the savage heights above. Best tackled with an experienced guide and full camping gear, the Dhaulagiri Circuit is an adventure that tests character as much as legs.</p>`,
    district: `Myagdi`,
    province: "GANDAKI",
    lat: 28.6965,
    lng: 83.4822,
    elevation: 5360,
    entryFee: `ACAP NPR 3000 + TIMS card required`,
    bestSeason: `Oct-Nov, Mar-May`,
    openingHours: `Always open`,
    howToGetThere: `Bus or jeep from Pokhara to Beni (3 hrs), then jeep or walk to Babiyachaur trailhead. Alternatively, jeep to Darbang. The circuit ends at Marpha or Jomsom, from which you can fly back to Pokhara.`,
    trekDays: 16,
    trekDifficulty: "EXTREME",
    trekMaxElevation: 5360,
    trekDistance: 200,
    trekStartPoint: `Beni / Babiyachaur`,
    trekEndPoint: `Marpha / Jomsom`,
    trekHighlights: [`French Pass at 5,360m with panoramic views`, `Hidden Valley at 5,050m overnight camp`, `Dhaulagiri Base Camp beneath the south face`, `Italian Base Camp and glacier approach`, `Thapa Pass (5,250m) alternative crossing`, `Remote wilderness with zero crowd teahouses`, `Descent through Thakali apple orchards at Marpha`],
    gygQuery: `Dhaulagiri Circuit Trek Nepal`,
    bookingCity: `Pokhara`,
    seoTitle: `Dhaulagiri Circuit Trek – Nepal's Ultimate Wilderness Challenge`,
    seoDescription: `Conquer French Pass (5,360m) and the Hidden Valley on the Dhaulagiri Circuit Trek, 16 days of extreme trekking around the world's 7th-highest mountain. A remote camping adventure in Myagdi, Gandaki Province.`,
    published: true,
    featured: false,
  },
  {
    name: `Mardi Himal Trek`,
    category: "TREK_ROUTE",
    summary: `The Mardi Himal Trek offers an intimate encounter with the Annapurna massif on a quieter, less-trodden trail through dense rhododendron forest to a high camp facing Machhapuchhre. Rising to 4,500 metres at the base camp, this five-to-seven day route is ideal for trekkers seeking dramatic Himalayan scenery without the crowds of the classic Annapurna circuits.`,
    story: `<p>Mardi Himal is often called the best-kept secret of the Annapurna region, a spine of trail that rises sharply east of Pokhara through forests fragrant with rhododendron and oak before breaking into open ridge-walking with jaw-dropping proximity to some of Nepal's most iconic summits. The peak itself, at 5,587 metres, is a trekking objective in its own right, though the base camp at 4,500 metres is the standard high point for most visitors.</p><p>The route begins at Kande or Dhampus Phedi, two small villages connected by bus from Pokhara. The trail climbs steadily through the sanctuary buffer zone, passing Low Camp, Middle Camp and finally High Camp at around 3,580 metres, where teahouses perch on a ridge with nothing between the trekker and a wall of white giants: Annapurna South, Hiunchuli, Machhapuchhre and Mardi Himal itself fill the sky from west to east in an almost theatrical arrangement.</p><p>What makes this route particularly special is the transition of ecosystems. The lower forests are alive with rhododendron blooms in March and April, painting the hillsides crimson and pink. Higher up the vegetation thins to wind-cropped scrub, and on clear days the summit of Dhaulagiri appears floating on the western horizon like a white island in the sky.</p><p>The descent typically leads to Siding village and then to Lwang, where local Gurung communities run homestays as part of a community tourism initiative. This grassroots model means trekking fees stay within the village economy, and travellers leave with genuine human connections as well as spectacular photographs. The Mardi Himal Trek is a remarkably complete mountain experience in a compact, manageable package.</p>`,
    district: `Kaski`,
    province: "GANDAKI",
    lat: 28.4167,
    lng: 83.9333,
    elevation: 4500,
    entryFee: `ACAP NPR 3000 + TIMS card required`,
    bestSeason: `Oct-Nov, Mar-May`,
    openingHours: `Always open`,
    howToGetThere: `From Pokhara take a taxi or local bus to Kande (30 min) to begin the trek. The trail ends at Lwang or Siding village, from where jeeps return to Pokhara. Alternatively, start from Dhampus Phedi.`,
    trekDays: 6,
    trekDifficulty: "MODERATE",
    trekMaxElevation: 4500,
    trekDistance: 55,
    trekStartPoint: `Kande / Dhampus Phedi`,
    trekEndPoint: `Lwang / Siding`,
    trekHighlights: [`Mardi Himal Base Camp at 4,500m`, `Close-up views of Machhapuchhre (Fishtail) and Annapurna South`, `High Camp ridge with 270-degree Himalayan panorama`, `Rhododendron forests in bloom (March-April)`, `Gurung community homestays in Lwang village`, `Fewer crowds than classic Annapurna routes`],
    gygQuery: `Mardi Himal Trek Pokhara Annapurna Nepal`,
    bookingCity: `Pokhara`,
    seoTitle: `Mardi Himal Trek – Secret Ridge Trek in the Annapurna Region`,
    seoDescription: `Trek to Mardi Himal Base Camp (4,500m) on this off-the-beaten-path 6-day route through rhododendron forests to a high ridge facing Machhapuchhre. A quieter alternative to the classic Annapurna circuit in Kaski, Nepal.`,
    published: true,
    featured: false,
  },
  {
    name: `Mohare Danda Trek`,
    category: "TREK_ROUTE",
    summary: `Perched at 3,300 metres between the Annapurna and Dhaulagiri ranges, Mohare Danda is an eco-community trek that delivers panoramic Himalayan views to rival Poon Hill without the crowds. The trail weaves through traditional Gurung and Magar villages, rhododendron forests and community-managed lodges that keep tourism benefits firmly local.`,
    story: `<p>Mohare Danda sits on a grassy ridgeline between the two great massifs of western Nepal, a high viewpoint that frames Dhaulagiri, Annapurna I, Annapurna South, Nilgiri, Tukuche and the unmistakable Machhapuchhre in a single glorious sweep. At 3,300 metres, the summit clearing rewards early risers with a golden sunrise over more than a dozen eight-thousander-adjacent peaks, yet the trail remains refreshingly uncrowded compared to the famous Poon Hill circuit just to the east.</p><p>The trek is classified as a community eco-trail, designed and managed by local villages in Myagdi District with support from conservation organisations. Accommodation is in community-run lodges in villages such as Nagi, Nangi, Banse Kharka and Ghandruk, where profits are recycled into school scholarships and forest conservation. Trekking here is an explicitly ethical choice as well as an adventurous one.</p><p>The route is typically accessed from Galeshwor on the Beni-Jomsom highway, following a trail that climbs through subtropical farmland before entering forests of oak, bamboo and rhododendron. In spring the slopes erupt in waves of crimson and pink blossom, filling the air with a sweetness that makes even steep ascents feel joyful. Gurung and Magar cultural traditions are very much alive along the route, and homestay evenings often include local raksi spirit and traditional song.</p><p>Because the Mohare Danda trail links with both the Annapurna Circuit and the Ghorepani-Poon Hill route, trekkers can combine it with longer journeys for a truly varied Himalayan experience. It remains one of the most rewarding short treks in Nepal for those who want authentic engagement with local culture alongside outstanding mountain scenery.</p>`,
    district: `Myagdi`,
    province: "GANDAKI",
    lat: 28.4833,
    lng: 83.6167,
    elevation: 3300,
    entryFee: `ACAP NPR 3000; community lodge fees applicable`,
    bestSeason: `Oct-Nov, Mar-May`,
    openingHours: `Always open`,
    howToGetThere: `Drive from Pokhara to Beni (3 hrs), then continue by jeep to Galeshwor (1.5 hrs) as the trailhead. Alternatively, combine with Ghorepani by exiting through Tadapani and Ghandruk. Return by jeep to Beni then bus to Pokhara.`,
    trekDays: 6,
    trekDifficulty: "MODERATE",
    trekMaxElevation: 3300,
    trekDistance: 60,
    trekStartPoint: `Galeshwor`,
    trekEndPoint: `Ghandruk / Galeshwor`,
    trekHighlights: [`Mohare Danda viewpoint (3,300m) facing Dhaulagiri and Annapurna`, `Community eco-lodges with local profits reinvested`, `Rhododendron forests in peak spring bloom`, `Traditional Gurung and Magar village homestays`, `Link trail connecting to Annapurna Circuit and Poon Hill`, `Off-the-beaten-path alternative to crowded Ghorepani route`],
    gygQuery: `Mohare Danda community trek Annapurna Nepal`,
    bookingCity: `Pokhara`,
    seoTitle: `Mohare Danda Trek – Eco-Community Trek Between Annapurna and Dhaulagiri`,
    seoDescription: `Discover the panoramic Mohare Danda ridgeline at 3,300m on a 6-day eco-community trek through traditional Gurung villages. A quieter, ethical alternative to Poon Hill in Myagdi district, Gandaki Province, Nepal.`,
    published: true,
    featured: false,
  },
  {
    name: `Makalu Base Camp Trek`,
    category: "TREK_ROUTE",
    summary: `The approach to Makalu Base Camp plunges into one of Nepal's most pristine wilderness corridors, the Makalu-Barun National Park, rising from subtropical jungle to glacial moraines beneath the fifth-highest mountain on Earth. Remote, demanding and ecologically extraordinary, this 18-to-21-day journey is reserved for experienced trekkers who want true Himalayan adventure far from the tourist trail.`,
    story: `<p>Mount Makalu at 8,463 metres is the fifth-highest peak in the world, and the trek to its base camp is a journey through one of Nepal's most biodiverse protected areas. The Makalu-Barun National Park, which shelters the route for much of its length, contains more species of rhododendron than anywhere else in Nepal, alongside red pandas, snow leopards, musk deer and over 400 bird species recorded within its boundaries.</p><p>The classic approach begins with a flight from Kathmandu to Tumlingtar in Sankhuwasabha District, cutting out days of road travel and depositing trekkers at a subtropical riverside airstrip from which the mountain vastness is still invisible. The trail climbs relentlessly north through Num, Seduwa, Tashigaon and Khongma before ascending into true alpine terrain at Mumbuk and Shershon. The base camp itself sits at around 4,870 metres, with the colossal southeast face of Makalu filling the entire northern sky.</p><p>The trek is characterised by dramatic elevation change, from under 500 metres at the Arun River valley floor to nearly 5,000 metres at base camp, passing through more ecological zones than almost any other trek in Nepal. Trekkers walk through moist tropical forest, temperate oak and maple woodland, alpine meadow and finally bare glacial moraine in the space of less than two weeks.</p><p>Infrastructure is minimal and the route demands camping equipment and experienced guides. The very remoteness that makes logistics challenging is also what makes Makalu Base Camp so extraordinary: this is a corner of Nepal where the silence is profound, the stars are brilliant and the mountain reveals itself slowly, over many days, in an almost geological unveiling of scale and power.</p>`,
    district: `Sankhuwasabha`,
    province: "KOSHI",
    lat: 27.8895,
    lng: 87.0896,
    elevation: 4870,
    entryFee: `Makalu-Barun National Park NPR 3000 + TIMS card`,
    bestSeason: `Oct-Nov, Mar-May`,
    openingHours: `Always open`,
    howToGetThere: `Fly from Kathmandu to Tumlingtar (35 min). Trek north from Tumlingtar through Num and Seduwa to base camp. Return the same way or exit via a different route through the Arun Valley. All camping gear must be carried.`,
    trekDays: 18,
    trekDifficulty: "HARD",
    trekMaxElevation: 4870,
    trekDistance: 200,
    trekStartPoint: `Tumlingtar`,
    trekEndPoint: `Makalu Base Camp`,
    trekHighlights: [`Makalu Base Camp beneath the 8,463m fifth-highest peak`, `Makalu-Barun National Park exceptional biodiversity`, `Red panda habitat in rhododendron forests`, `Dramatic ascent through five ecological zones`, `Arun River gorge canyon scenery`, `Remote wilderness with minimal trekker traffic`, `Views of Makalu, Lhotse and Everest from high points`],
    gygQuery: `Makalu Base Camp Trek Nepal Sankhuwasabha`,
    bookingCity: `Tumlingtar`,
    seoTitle: `Makalu Base Camp Trek – Wilderness Journey to the World's 5th Highest Peak`,
    seoDescription: `Trek 18 days through the Makalu-Barun National Park to base camp at 4,870m beneath Mount Makalu (8,463m). A remote, biodiversity-rich wilderness adventure in Sankhuwasabha, Koshi Province, Nepal.`,
    published: true,
    featured: false,
  },
  {
    name: `Pikey Peak Trek`,
    category: "TREK_ROUTE",
    summary: `Pikey Peak at 4,065 metres is said to offer what Sir Edmund Hillary called one of his favourite Everest views, a panorama that sweeps from Everest and Lhotse to Cho Oyu and Makalu in a single 180-degree arc. This accessible five-to-seven day route in the lower Khumbu region is perfect for acclimatisation-sensitive trekkers who want big mountain views without the altitude demands of Everest Base Camp.`,
    story: `<p>Long before the Everest Base Camp trail became Nepal's most famous trekking corridor, the Sherpa people of the Solu region venerated Pikey Peak as a sacred viewpoint where the mountains of the east reveal themselves in magnificent array. Sir Edmund Hillary is said to have called the panorama from Pikey Peak one of the finest he had witnessed anywhere in Nepal, a remarkable endorsement from a man who stood on top of the world.</p><p>The trek typically begins from Dhap, a small village in Solukhumbu accessible by a full day's drive from Kathmandu through Solu Khumbu. The trail rises through forests of oak, pine and rhododendron, passing traditional Sherpa settlements where prayer wheels turn in the mountain wind and mani walls line the path in long stone galleries. The summit push from base camp to the peak is an early-morning affair timed to catch the sunrise, when the Himalayan giants ignite from east to west in shades of amber and gold.</p><p>From Pikey Peak on a clear morning, trekkers can identify Mount Everest, Lhotse, Makalu, Cho Oyu, Kanchenjunga, Numbur Himal and the distinctive wedge of Karyolung among others, an extraordinary roll-call of the planet's highest summits spread across the entire northern horizon. The lower elevation of 4,065 metres means altitude sickness is far less of a concern than on the classic Khumbu routes, making this suitable for less experienced high-altitude trekkers.</p><p>The route passes through the historic Jiri-Everest trail corridor, linking Sherpa cultural heritage with some of Nepal's most spectacular scenery. Accommodation in simple teahouses along the route ensures a comfortable night at each village before the final summit push. Pikey Peak is a trek that consistently over-delivers on the ratio of view to effort.</p>`,
    district: `Solukhumbu`,
    province: "KOSHI",
    lat: 27.4833,
    lng: 86.6,
    elevation: 4065,
    entryFee: `Free (no special permit required)`,
    bestSeason: `Oct-Nov, Feb-May`,
    openingHours: `Always open`,
    howToGetThere: `Drive from Kathmandu to Dhap (7-8 hrs by jeep via Solu highway). Alternatively, fly to Phaplu or Lukla and drive to Dhap. Trek circuit begins and ends at Dhap, or exit via Jiri for a point-to-point route.`,
    trekDays: 6,
    trekDifficulty: "EASY",
    trekMaxElevation: 4065,
    trekDistance: 65,
    trekStartPoint: `Dhap`,
    trekEndPoint: `Dhap / Jiri`,
    trekHighlights: [`Pikey Peak summit (4,065m) with panoramic Everest view`, `Sunrise over eight-thousanders including Everest and Makalu`, `Sir Edmund Hillary's favourite Everest viewpoint`, `Traditional Sherpa and Rai villages en route`, `Accessible altitude ideal for acclimatisation`, `Junbesi and Solu valley scenery and gompas`],
    gygQuery: `Pikey Peak Trek Solukhumbu Everest view Nepal`,
    bookingCity: `Kathmandu`,
    seoTitle: `Pikey Peak Trek – Hillary's Favourite Everest Panorama in Lower Khumbu`,
    seoDescription: `Climb Pikey Peak (4,065m) for what Sir Edmund Hillary called one of Nepal's finest Everest views. A 6-day moderate trek through traditional Sherpa villages in Solukhumbu, Koshi Province — perfect for first-time high-altitude trekkers.`,
    published: true,
    featured: false,
  },
  {
    name: `Arun Valley Trek`,
    category: "TREK_ROUTE",
    summary: `The Arun Valley Trek follows the Arun River, one of the world's oldest and deepest river gorges, through a botanist's paradise of subtropical jungle, terraced farmland and Rai, Limbu and Sherpa villages virtually untouched by mass tourism. This off-the-beaten-path route from Tumlingtar offers extraordinary biodiversity and cultural richness as an approach to the Makalu region.`,
    story: `<p>The Arun River is among the most ancient waterways on Earth, predating the Himalayan uplift itself and cutting a gorge so deep that the river flows through tropical jungle at the same latitude where glaciers cling to peaks above 8,000 metres. The Arun Valley Trek follows this remarkable corridor through one of Nepal's least-visited districts, Sankhuwasabha, tracing a route that rewards patient travellers with exceptional wildlife, genuine cultural encounters and complete escape from the commercialised trekking highways.</p><p>The journey begins at Tumlingtar, a riverside airstrip surrounded by subtropical vegetation that seems improbable in a country famous for its snowfields. From here the trail winds through settlements inhabited by Rai, Limbu, Sherpa and Tamang communities, each with distinct traditions, festivals and agricultural practices. The terraced hillsides produce millet, maize and cardamom, and market days in small bazaars bring the whole valley alive with colour and noise.</p><p>Birdwatchers consider the Arun Valley among the finest destinations in South Asia, with more than 650 species recorded in the valley and its forests. The Makalu-Barun buffer zone protects much of the upper watershed, sheltering red pandas, clouded leopards and over 800 species of butterfly. The biodiversity here is not a background detail but a central attraction for naturalists and ecotourists who understand what they are looking at.</p><p>The upper Arun valley provides an alternative approach to Makalu Base Camp for those with enough time and a taste for genuine adventure. As a standalone itinerary, the trek through the valley floor and its tributary villages makes for a deeply satisfying cultural journey, connecting remote communities to the outside world in ways that are mutually enriching rather than extractive. This is the Nepal that existed before the trekking industry, and it is still very much alive.</p>`,
    district: `Sankhuwasabha`,
    province: "KOSHI",
    lat: 27.3167,
    lng: 87.1833,
    elevation: 3173,
    entryFee: `TIMS card required; Makalu-Barun Park fee NPR 3000 if entering park`,
    bestSeason: `Oct-Nov, Mar-May`,
    openingHours: `Always open`,
    howToGetThere: `Fly from Kathmandu to Tumlingtar (35 min). Trek begins from Tumlingtar, heading north along the Arun River and its tributaries. Return to Tumlingtar for the flight back, or continue to Makalu Base Camp for a longer expedition.`,
    trekDays: 14,
    trekDifficulty: "MODERATE",
    trekMaxElevation: 3173,
    trekDistance: 150,
    trekStartPoint: `Tumlingtar`,
    trekEndPoint: `Tumlingtar / Makalu Base Camp approach`,
    trekHighlights: [`Ancient Arun River gorge through subtropical jungle`, `Over 650 bird species and 800 butterfly species recorded`, `Rai, Limbu, Sherpa and Tamang cultural villages`, `Red panda and clouded leopard habitat`, `Remote trail with virtually no other trekkers`, `Link route to Makalu Base Camp trek`],
    gygQuery: `Arun Valley Trek Sankhuwasabha Nepal`,
    bookingCity: `Tumlingtar`,
    seoTitle: `Arun Valley Trek – Ancient River Gorge and Wilderness in Eastern Nepal`,
    seoDescription: `Trek the ancient Arun River gorge through a biodiversity hotspot of 650 bird species and Rai, Limbu and Sherpa villages. A 14-day off-the-beaten-path adventure in Sankhuwasabha, Koshi Province, Nepal.`,
    published: true,
    featured: false,
  },
  {
    name: `Tamang Heritage Trail`,
    category: "TREK_ROUTE",
    summary: `The Tamang Heritage Trail is a gentle cultural circuit through Rasuwa's ancient Tamang villages near the Tibetan border, passing natural hot springs, Buddhist monasteries and the frontier fortress of Rasuwagadhi. Traversing rhododendron forest and terraced hillsides with Langtang views, this eight-day trek provides an authentic window into one of Nepal's most distinctive highland communities.`,
    story: `<p>The Tamang people have lived in the high valleys north of Kathmandu for centuries, maintaining a culture that blends Tibetan Buddhist traditions with uniquely Nepalese elements: a way of life expressed through intricate woodcarving, weaving, shamanic ceremony and a calendar of festivals that mark the agricultural and spiritual year. The Tamang Heritage Trail was created to connect trekkers directly with this living culture, routing the trail through villages rather than around them.</p><p>The trek begins at Syabrubesi in Rasuwa District, a village that serves as the gateway to both the Langtang Valley and the Gosaikunda pilgrimage circuit. From here the trail climbs through forests to Gatlang, a beautifully preserved village of traditional stone-and-timber houses where the gompa at the settlement centre has been an active place of worship for generations. Continuing north, the route passes through Tatopani, where natural hot springs bubble from the hillside beside the Bhote Kosi River, providing a gloriously restorative soak after long days on the trail.</p><p>The village of Thuman sits close to the Nepal-Tibet border, and the atmosphere here carries the quality of frontier remoteness that gives the whole trail its particular character. The Rasuwagadhi fortress ruin nearby marks a historic trading and military crossing point used for centuries by merchants carrying salt, wool and grain between the two countries. Views north into Tibet and south toward the Langtang peaks make this a genuinely special vantage point.</p><p>The trail loops back south through Briddim and Goljung before returning to Syabrubesi, completing a circuit that is manageable in seven to nine days. The highest point, Nagthali Danda at 3,165 metres, is a meadow summit with sweeping views of the Langtang range. Teahouses throughout the trail are locally owned, ensuring that the modest revenues from trekking remain within Tamang communities.</p>`,
    district: `Rasuwa`,
    province: "BAGMATI",
    lat: 28.15,
    lng: 85.35,
    elevation: 3165,
    entryFee: `Langtang NP NPR 3000; TIMS card required`,
    bestSeason: `Oct-Nov, Mar-May`,
    openingHours: `Always open`,
    howToGetThere: `Bus or jeep from Kathmandu to Syabrubesi (7-8 hrs via Trishuli Bazaar and Dhunche). Trek begins and ends at Syabrubesi. Road access improved significantly since 2015 earthquake reconstruction.`,
    trekDays: 8,
    trekDifficulty: "EASY",
    trekMaxElevation: 3165,
    trekDistance: 55,
    trekStartPoint: `Syabrubesi`,
    trekEndPoint: `Syabrubesi`,
    trekHighlights: [`Gatlang traditional stone-and-timber Tamang village`, `Tatopani natural hot springs along the Bhote Kosi`, `Rasuwagadhi fortress on Nepal-Tibet border`, `Nagthali Danda meadow summit (3,165m) with Langtang views`, `Active Buddhist gompas and mani wall galleries`, `Authentic Tamang cultural immersion and community lodges`],
    gygQuery: `Tamang Heritage Trail Rasuwa Nepal trek`,
    bookingCity: `Kathmandu`,
    seoTitle: `Tamang Heritage Trail – Cultural Trek Through Rasuwa's Ancient Villages`,
    seoDescription: `Walk the 8-day Tamang Heritage Trail through traditional Tamang villages, natural hot springs and the Tibetan border fortress of Rasuwagadhi. A culturally rich, easy-to-moderate trek in Rasuwa district, Bagmati Province.`,
    published: true,
    featured: false,
  },
  {
    name: `Rolwaling Valley Trek`,
    category: "TREK_ROUTE",
    summary: `The Rolwaling Valley is a sacred glacial wilderness tucked into the mountains of Dolakha, sheltering the high-altitude settlements of Beding and Na beneath the peak of Gauri Shankar. The spectacular Tashi Lapcha Pass (5,755m) connects this hidden valley to the Everest region in a crossing that is as technically demanding as it is scenically overwhelming.`,
    story: `<p>Rolwaling, whose name translates roughly as 'the furrow left by a plough', is one of Nepal's most remote inhabited valleys, a glacial trough enclosed by peaks of extraordinary beauty and largely inaccessible except on foot. The valley is sacred to Nyingma Buddhists, who regard it as one of Nepal's beyul or hidden valleys, places of spiritual refuge concealed by Guru Rinpoche for a future time of need. The sense of sanctuary is still palpable in the clean air, the absence of noise and the unhurried pace of life in the villages of Beding and Na.</p><p>The trek begins from Simigaon or Dolakha Bazaar in Dolakha District, climbing through terraced farmland and rhododendron forest before entering the upper valley proper. Beding at 3,690 metres is the last sizeable settlement, a cluster of stone houses and a working gompa surrounded by meadows that become snowfield in winter. Higher up, the grazing settlement of Na at 4,183 metres is the last habitation before the glacier begins.</p><p>The centrepiece and climax of the full Rolwaling experience is the crossing of Tashi Lapcha Pass at 5,755 metres, a glaciated col that requires crampons, ice axes and ropes on the ascent, and connects the valley to the Khumbu region near Thame. This is not a trekking pass in the conventional sense but a genuine mountaineering objective, requiring prior technical experience and ideally a qualified guide with glacier training.</p><p>Tsho Rolpa, the glacial lake at the head of the valley, has become famous in climate discussions as one of the most rapidly expanding glacial lakes in Nepal. Trekkers visiting this melancholy but beautiful body of water are witnessing climate change in one of its most direct and visible expressions. The Rolwaling Valley rewards those willing to earn its rewards with memories that endure long after the trail dust washes away.</p>`,
    district: `Dolakha`,
    province: "BAGMATI",
    lat: 27.8833,
    lng: 86.4333,
    elevation: 5755,
    entryFee: `Gaurishankar Conservation Area NPR 2000; TIMS card required`,
    bestSeason: `Oct-Nov, Mar-May`,
    openingHours: `Always open`,
    howToGetThere: `Drive from Kathmandu to Charikot or Simigaon (5-7 hrs). Trek begins from Simigaon or Nyimare. If crossing Tashi Lapcha Pass, exit at Thame and descend to Namche Bazaar then fly home from Lukla. Technical gear required for the pass.`,
    trekDays: 17,
    trekDifficulty: "EXTREME",
    trekMaxElevation: 5755,
    trekDistance: 110,
    trekStartPoint: `Simigaon / Dolakha`,
    trekEndPoint: `Thame / Namche Bazaar (via Tashi Lapcha) or return to Simigaon`,
    trekHighlights: [`Tashi Lapcha Pass at 5,755m with technical glacier crossing`, `Sacred Rolwaling beyul valley of the Nyingma Buddhists`, `Tsho Rolpa glacial lake and climate change frontline`, `Beding and Na villages in pristine alpine setting`, `Gauri Shankar (7,134m) and Melungtse peak views`, `Route connecting to Everest region via Thame`],
    gygQuery: `Rolwaling Valley Tashi Lapcha Pass trek Nepal`,
    bookingCity: `Kathmandu`,
    seoTitle: `Rolwaling Valley Trek – Sacred Hidden Valley and Tashi Lapcha Pass`,
    seoDescription: `Explore the sacred Rolwaling beyul valley and cross the technical Tashi Lapcha Pass (5,755m) to the Everest region. A 17-day extreme adventure through glacial wilderness in Dolakha, Bagmati Province, Nepal.`,
    published: true,
    featured: false,
  },
  {
    name: `Jumla Bazaar`,
    category: "CULTURAL_VILLAGE",
    summary: `Jumla is the ancient cultural heart of the Karnali, a high-altitude district headquarters at 2,370 metres surrounded by the ruins of the medieval Khas Kingdom and apple orchards producing some of the world's highest-grown fruit. The nearby Sinja Valley, a UNESCO tentative heritage site, marks the birthplace of the Nepali language and the cradle of one of South Asia's remarkable mountain civilisations.`,
    story: `<p>Jumla sits in a broad valley in the Karnali highlands at an elevation that ensures crisp mountain air and winters cold enough to freeze rivers solid. As the administrative hub of Jumla District and one of the key centres of Karnali Province, it is a city of contrasts: modern government buildings, schools and a small airport set against a backdrop of forested ridgelines, walnut groves and the Tila River winding through terraced fields.</p><p>The historical weight of Jumla is considerable. The Khas Kingdom, which flourished between the 11th and 14th centuries and at its height controlled much of western Nepal, Uttarakhand and southern Tibet, had its capital at Sinja, just a few hours walk from Jumla Bazaar. Sinja Valley contains the ruins of palaces, temples and inscriptions that document this lost civilisation, and scholars regard it as the cradle of the Nepali language and script. The valley is on the UNESCO tentative World Heritage list and receives a trickle of intrepid cultural tourists each year.</p><p>Jumla is also famous throughout Nepal for two agricultural products that thrive nowhere else in the country at this altitude. The first is Jumli Marsi rice, a red-grained variety cultivated above 2,400 metres that produces a nutty, iron-rich grain used in ceremonies and prized as a health food across Nepal. The second is the Jumla apple, grown in orchards that turn crimson in late summer and carpet the roadsides with fallen fruit, filling the air with cider-sweetness from July to October.</p><p>The Chandannath Temple in the bazaar is the spiritual centrepiece of town, where morning and evening aarti draws devotees and the temple courtyard bustles with pilgrims from across the Karnali. As a base for exploring Rara Lake, Sinja Valley and the broader Karnali wilderness, Jumla rewards the effort of getting here with a depth of history and culture rarely found at this altitude anywhere in the Himalayas.</p>`,
    district: `Jumla`,
    province: "KARNALI",
    lat: 29.2742,
    lng: 82.1837,
    elevation: 2370,
    entryFee: `Free`,
    bestSeason: `Jun-Oct`,
    openingHours: `Always open (bazaar active during daylight hours)`,
    howToGetThere: `Fly from Kathmandu or Nepalgunj to Jumla Airport (daily flights, Tara Air or Sita Air). Overland by bus from Kathmandu via Surkhet takes 30+ hours. Jeep hire from Surkhet is an alternative overland option.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Jumla Karnali Nepal trekking tour`,
    bookingCity: `Jumla`,
    seoTitle: `Jumla – Ancient Capital of the Karnali and Gateway to Rara Lake`,
    seoDescription: `Explore Jumla, the cultural heart of Karnali at 2,370m, home to Chandannath Temple, the world's highest rice cultivation and the medieval Sinja Valley ruins. Gateway to Rara Lake and the remote Karnali wilderness in western Nepal.`,
    published: true,
    featured: false,
  },
  {
    name: `Simikot`,
    category: "CULTURAL_VILLAGE",
    summary: `Simikot is the remote headquarters of Humla, Nepal's most isolated district, perched at 2,900 metres above the Humla Karnali River gorge near the Tibetan border. This frontier town is the principal gateway for the Kailash Mansarovar pilgrimage via Nepal and a base for exploring the Limi Valley, one of the last Tibetan-culture enclaves in the Himalayas.`,
    story: `<p>There is no road to Simikot. The town, clinging to a gentle slope above the thundering Humla Karnali River in far-northwestern Nepal, is accessible only by the weekly flights operated by small STOL aircraft from Nepalgunj, or by weeks of walking from the nearest road head. This isolation has preserved Humla in a state of cultural and ecological authenticity that is becoming vanishingly rare in a modernising Nepal.</p><p>The town itself is modest, a cluster of flat-roofed stone houses surrounded by buckwheat fields, the murmur of a small bazaar and the large, breezy campus of Simikot Airport where Twin Otters and Dornier aircraft land on a 549-metre runway that demands pilots of exceptional skill. From the airstrip the views north toward the Tibetan plateau are vast and luminous, the high ridgelines dusted with snow even in summer.</p><p>Simikot's primary significance for visitors is as the launch point for the Kailash Mansarovar Yatra via Nepal, the pilgrimage to the sacred mountain of Tibet that Hindus and Buddhists regard as the centre of the universe. After flying to Simikot, pilgrims trek north to the Hilsa border crossing into Tibet, from where they continue by vehicle to Lake Mansarovar and Mount Kailash. The Nepal route is considered more adventurous and authentic than the road approach from China, and demand for it grows each year among Indian and international pilgrims.</p><p>For trekkers uninterested in the Kailash circuit, Simikot opens access to the Limi Valley, an extraordinary culturally Tibetan enclave with ancient gompas, traditional villages and high passes that has remained almost entirely outside the global tourism economy. Birdwatchers, botanists and anthropologists find Humla an endlessly rewarding destination for its biodiversity and its peoples.</p>`,
    district: `Humla`,
    province: "KARNALI",
    lat: 29.9667,
    lng: 81.8167,
    elevation: 2900,
    entryFee: `Humla Conservation Area NPR 3000 for trekkers`,
    bestSeason: `Mar-May, Sep-Nov`,
    openingHours: `Always open`,
    howToGetThere: `Fly from Kathmandu to Nepalgunj, then Nepalgunj to Simikot (20 min on Tara Air or Sita Air). No road access currently. Flights can be cancelled or delayed due to weather, so build flexibility into itineraries.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Simikot Humla Nepal Kailash pilgrimage gateway`,
    bookingCity: `Simikot`,
    seoTitle: `Simikot – Gateway to Humla and the Kailash Mansarovar Pilgrimage`,
    seoDescription: `Visit Simikot, the remote headquarters of Humla at 2,900m and Nepal's gateway to the Kailash Mansarovar pilgrimage. Explore the Limi Valley and frontier culture of far-western Nepal accessible only by small aircraft.`,
    published: true,
    featured: false,
  },
  {
    name: `Surkhet Birendranagar`,
    category: "CULTURAL_VILLAGE",
    summary: `Birendranagar is Nepal's first planned city and the vibrant provincial capital of Karnali, set in a broad fertile valley surrounded by forested hills and the Bheri River. With ancient Buddhist heritage at Kakrebihar, scenic paragliding above the valley and turquoise Bulbule Lake, Surkhet is emerging as the commercial and cultural gateway to the entire Karnali province.`,
    story: `<p>Surkhet Valley lies at an elevation of around 700 metres in mid-western Nepal, a wide flat basin of rice paddies and mango groves hemmed in by forested ridges that are remarkable by Nepali standards for their accessibility and beauty. Birendranagar, the valley's main city, was Nepal's first purpose-planned urban settlement, laid out on a grid system in the 1960s and named after the late King Birendra who conceived the project. Today it functions as the administrative and commercial capital of Karnali Province, the largest and most mountainous of Nepal's seven provinces.</p><p>The most important historical monument in Surkhet is Kakrebihar, a sprawling complex of 12th-century Buddhist monastery ruins spread across 180 hectares on a low hill above the valley. The site is on Nepal's national heritage register and contains carved stone images, architectural foundations and votive stupas that speak to the region's significant medieval Buddhist culture. Visiting Kakrebihar at dawn, when mist still clings to the surrounding fields, is one of those quietly memorable experiences that reward travellers who venture beyond the established tourist circuit.</p><p>Bulbule Lake, a small turquoise body of water on the valley floor, serves as a recreational hub for Birendranagar residents and visiting tourists alike. Paddle boats ply its calm surface and the surrounding park is pleasant for a morning stroll. More recently, Surkhet has attracted national attention as an emerging paragliding destination, with thermals rising from the valley floor enabling extended flights over the entire Surkhet basin with views of the snow-capped peaks to the north.</p><p>Birendranagar functions as the most practical hub for travellers exploring the Karnali region, with regular flights from Kathmandu, improving road connections north to Jumla and the Karnali Highway opening routes to the remote districts beyond. The city's growing hospitality infrastructure, combined with its genuine historical and natural attractions, makes it an underrated stopover for adventurous travellers headed deeper into western Nepal.</p>`,
    district: `Surkhet`,
    province: "KARNALI",
    lat: 28.6,
    lng: 81.6167,
    elevation: 720,
    entryFee: `Kakrebihar free; Bulbule Lake small entry fee`,
    bestSeason: `Oct-Mar`,
    openingHours: `Always open (Kakrebihar: dawn to dusk)`,
    howToGetThere: `Fly from Kathmandu to Surkhet Airport (1 hr, Buddha Air or Yeti Airlines). Bus from Kathmandu takes 12-14 hrs via the Prithvi Highway and Ratna Highway. Kathmandu to Nepalgunj then onward jeep is another option.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Surkhet Birendranagar Karnali Nepal tour`,
    bookingCity: `Birendranagar`,
    seoTitle: `Surkhet Birendranagar – Karnali Province Capital and Cultural Gateway`,
    seoDescription: `Discover Birendranagar, Nepal's first planned city and Karnali Province capital. Visit the 12th-century Kakrebihar Buddhist ruins, turquoise Bulbule Lake and enjoy paragliding above Surkhet Valley in western Nepal.`,
    published: true,
    featured: false,
  },
  {
    name: `Dolpo Trek (Shey Phoksundo)`,
    category: "TREK_ROUTE",
    summary: `Dolpo is one of Nepal's most mythologised wilderness regions, a remote plateau of Bon and Buddhist tradition where Shey Phoksundo, Nepal's deepest lake, glows an impossible emerald-turquoise beneath high cliffs. This restricted-area trek through the world's highest inhabited plateau passes ancient gompas, nomadic yak herders and landscapes that look more Central Asian than South Asian.`,
    story: `<p>Peter Matthiessen immortalised Dolpo in his 1978 book The Snow Leopard, describing a region so remote and spiritually charged that it seemed to exist outside ordinary time. Decades later, that quality of otherworldliness is still intact. Dolpo occupies a high plateau north of the main Himalayan divide in Dolpa District, sheltered from the monsoon by the mountains and culturally aligned with Tibet rather than the Nepal valley civilisations to the south.</p><p>The centrepiece of the Lower Dolpo Trek is Shey Phoksundo Lake, a body of water at 3,611 metres whose colour defies easy description: depending on the light and the sky, it shifts between deepest cobalt, luminous jade and a haunting aquamarine. At 145 metres deep it is Nepal's deepest lake, fed by subterranean springs and enclosed by cliffs of stratified red and brown rock that plunge directly into the water. The lake is sacred to both Bon and Buddhist traditions, and no fishing or swimming is permitted.</p><p>The trek through the Shey Phoksundo National Park crosses several high passes, including Numa La at 5,190 metres and Baga La at 5,170 metres on the classic Lower Dolpo circuit. The route passes through Dho Tarap, one of the highest permanently inhabited settlements in the world, where communities of Tibetan Buddhist and ancient Bon faith maintain a traditional pastoral economy based on yak herding and barley cultivation.</p><p>Ancient gompas at Shey and Ribo Bhumpa contain thangkas, statues and wall paintings of considerable antiquity, and the monks who maintain them live lives of remarkable austerity at altitudes where the air is thin and the winters brutal. The restricted area permit system keeps visitor numbers manageable, preserving the qualities of silence and spiritual authenticity that make Dolpo unlike anywhere else in Nepal.</p>`,
    district: `Dolpa`,
    province: "KARNALI",
    lat: 29.1167,
    lng: 82.9667,
    elevation: 5190,
    entryFee: `Shey Phoksundo NP NPR 3000 + Lower Dolpo Restricted Area Permit USD 20 per week`,
    bestSeason: `Oct-Nov, Mar-May`,
    openingHours: `Always open`,
    howToGetThere: `Fly from Kathmandu or Nepalgunj to Juphal Airport (near Dunai in Dolpa). Trek from Juphal to Shey Phoksundo Lake (2-3 days). Dolpo restricted permits must be arranged through a registered trekking agency before departure.`,
    trekDays: 16,
    trekDifficulty: "HARD",
    trekMaxElevation: 5190,
    trekDistance: 150,
    trekStartPoint: `Juphal / Dunai`,
    trekEndPoint: `Juphal / Dunai`,
    trekHighlights: [`Shey Phoksundo Lake (Nepal's deepest, 3,611m) in emerald-turquoise`, `Numa La (5,190m) and Baga La (5,170m) high passes`, `Dho Tarap, one of the world's highest inhabited villages`, `Ancient Bon and Buddhist gompas with rare murals`, `Snow leopard and Himalayan wolf habitat`, `Landscape immortalised in The Snow Leopard by Peter Matthiessen`],
    gygQuery: `Dolpo Trek Shey Phoksundo Lake Nepal`,
    bookingCity: `Nepalgunj`,
    seoTitle: `Dolpo Trek – Shey Phoksundo Lake and the Ancient Plateau of Karnali`,
    seoDescription: `Trek 16 days through the restricted Dolpo plateau to Shey Phoksundo, Nepal's deepest lake, crossing passes above 5,000m through Bon and Buddhist wilderness. A remote spiritual adventure in Dolpa district, Karnali Province.`,
    published: true,
    featured: false,
  },
  {
    name: `Royal Trek Pokhara`,
    category: "TREK_ROUTE",
    summary: `The Royal Trek is a short, easy four-day walk in the footsteps of Prince Charles through the farming villages and forested ridges north of Pokhara, offering superb Annapurna Range panoramas with none of the altitude demands of classic trekking routes. Ending at the tranquil Begnas Lake, this is the ideal introduction to Himalayan trekking for families, seniors and first-time visitors.`,
    story: `<p>In the 1980s, Prince Charles of Britain undertook a short trek through the forested hills and traditional villages north of Pokhara, accompanied by a small entourage and a considerable retinue of porters. The route he walked was not especially challenging, but it offered something the more famous mountain circuits could not: intimate access to the village life of Gurung and Magar communities with the Annapurna Range looming magnificent to the north throughout. The trail has been called the Royal Trek ever since, and it remains one of the best gentle introductions to Nepal's trekking culture.</p><p>The route begins at Bijayapur Khola on the northeastern outskirts of Pokhara and heads into the hills above the city through terraced farmland and oak-rhododendron forest. The first day brings trekkers to Kalikasthan at 1,370 metres, a ridge village with evening views that already hint at the scale of the Annapurna massif to the north. The second day climbs higher to Syaklung at 1,730 metres, the highest point of the trek, where the panorama widens to include Annapurna II, IV, Lamjung Himal and on clear days even the distant bulk of Manaslu.</p><p>The third day descends gradually to Chisapani, another ridge settlement with outstanding mountain views and friendly teahouses where trekkers can linger over tea watching clouds play around the summits. The final morning brings a leisurely walk along the forested ridge separating Rupa Lake from Begnas Lake before descending to Begnas Bazaar, where boats can be hired to cross the lake or simply to sit and watch the mountains reflected in the still water.</p><p>Throughout the route, the villages of Brahmin, Chhetri, Gurung and Magar communities offer authentic encounters that the busier Annapurna trails rarely provide. Because the Royal Trek avoids the main trekking highways, it retains a quality of unhurried discovery that makes it consistently rewarding for travellers of all experience levels.</p>`,
    district: `Kaski`,
    province: "GANDAKI",
    lat: 28.3167,
    lng: 84.0833,
    elevation: 1730,
    entryFee: `ACAP NPR 3000 + TIMS card required`,
    bestSeason: `Oct-Nov, Dec-Feb, Mar-May`,
    openingHours: `Always open`,
    howToGetThere: `Take a taxi or private vehicle from Pokhara to Bijayapur Khola (30 min, northeast of the city) to begin the trek. The trail ends at Begnas Lake, from where taxis return to Pokhara lakeside (30 min). No special transport required.`,
    trekDays: 4,
    trekDifficulty: "EASY",
    trekMaxElevation: 1730,
    trekDistance: 45,
    trekStartPoint: `Bijayapur Khola`,
    trekEndPoint: `Begnas Lake`,
    trekHighlights: [`Syaklung ridge (1,730m) with full Annapurna panorama`, `Traditional Gurung and Magar village culture`, `Chisapani viewpoint of Annapurna South face`, `Begnas and Rupa lakes at trek end`, `Following the route walked by Prince Charles`, `Ideal beginner or family trek from Pokhara`],
    gygQuery: `Royal Trek Pokhara Annapurna beginner Nepal`,
    bookingCity: `Pokhara`,
    seoTitle: `Royal Trek Pokhara – 4-Day Easy Annapurna Walk in Prince Charles's Footsteps`,
    seoDescription: `Walk the 4-day Royal Trek north of Pokhara, following the route of Prince Charles through Gurung villages and forested ridges with Annapurna panoramas. An easy beginner trek ending at Begnas Lake in Kaski, Gandaki Province, Nepal.`,
    published: true,
    featured: false,
  },
  {
    name: `Manaslu Base Camp Trek`,
    category: "TREK_ROUTE",
    summary: `The Manaslu Circuit with its base camp approach circles the world's eighth-highest peak through a restricted wilderness of glaciers, Tibetan Buddhist villages and the celebrated Larkya La Pass at 5,106 metres. Tracing the ancient Budhi Gandaki River gorge through Gorkha's most remote terrain, this twelve-to-fourteen day route offers Annapurna Circuit scenery with a fraction of the trekker traffic.`,
    story: `<p>Mount Manaslu at 8,163 metres is the eighth-highest mountain in the world and among the least known to the general public despite its extraordinary scale. The circuit that rings its flanks, incorporating a base camp side trip and the dramatic crossing of Larkya La Pass, is consistently described by experienced trekkers as one of the most beautiful routes in all Nepal, comparable to the classic Annapurna Circuit of thirty years ago before the road arrived.</p><p>The trek begins at Soti Khola in the Gorkha District lowlands, where the Budhi Gandaki River cuts a dramatic gorge through subtropical forest and settlements of great cultural variety: Gurung and Nubri communities give way gradually to Tibetan Buddhist villages as the valley narrows and the altitude climbs. Namrung, Lho and Samagaon are among the most beautiful trail-side villages in Nepal, their stone houses draped with prayer flags and backed by white mountain walls of immense verticality.</p><p>Samagaon at 3,530 metres is the base camp hub village, set at the foot of the Manaslu massif in a wide meadow valley. A short acclimatisation walk from here reaches the true base camp at around 4,800 metres, where the immense southeast face of Manaslu fills the sky. The atmosphere is serious and glacial, with seracs and crevasses visible on the lower icefalls and the sound of distant avalanche a constant background rumble.</p><p>Crossing Larkya La Pass at 5,106 metres is the physical and emotional climax of the route. The ascent begins in darkness with headtorch light dancing on the snow, and the pass is typically reached by mid-morning when the surrounding peaks of Himlung Himal, Cheo Himal, Kang Guru and Annapurna II are illuminated in golden light. The descent to Bimthang is long but beautiful, ending in meadows ringed by rhododendron where the pressure of the high mountains gives way to a vast sense of release.</p>`,
    district: `Gorkha`,
    province: "GANDAKI",
    lat: 28.55,
    lng: 84.56,
    elevation: 5106,
    entryFee: `Manaslu Conservation Area NPR 3000 + Restricted Area Permit USD 70/week (Sep-Nov) or USD 50/week (Dec-Aug) + MCAP NPR 3000`,
    bestSeason: `Oct-Nov, Mar-May`,
    openingHours: `Always open`,
    howToGetThere: `Drive from Kathmandu to Soti Khola (8-10 hrs via Arughat). All trekkers must be accompanied by a licensed guide. Exit via Dharapani and bus back to Pokhara or Kathmandu via the Annapurna Circuit road.`,
    trekDays: 13,
    trekDifficulty: "HARD",
    trekMaxElevation: 5106,
    trekDistance: 170,
    trekStartPoint: `Soti Khola`,
    trekEndPoint: `Dharapani`,
    trekHighlights: [`Larkya La Pass (5,106m) with 360-degree Himalayan panorama`, `Manaslu Base Camp beneath the world's 8th-highest peak`, `Samagaon and Nubri Tibetan Buddhist villages`, `Budhi Gandaki River gorge scenery`, `Bimthang meadows and Himalaya rhododendron descent`, `Far fewer trekkers than Annapurna Circuit`],
    gygQuery: `Manaslu Circuit Larkya Pass trek Nepal`,
    bookingCity: `Kathmandu`,
    seoTitle: `Manaslu Base Camp Trek – Larkya La Pass and the World's 8th Highest Peak`,
    seoDescription: `Trek 13 days around Mount Manaslu (8,163m) to base camp and over Larkya La Pass (5,106m). A restricted-area Himalayan adventure through Tibetan Buddhist villages in Gorkha, Gandaki Province with far fewer crowds than Annapurna.`,
    published: true,
    featured: false,
  },
  {
    name: `Birgunj`,
    category: "CULTURAL_VILLAGE",
    summary: `Birgunj is Nepal's busiest commercial border city, a dynamic trading hub in Parsa District where the Raxaul-Birgunj crossing handles more than half of Nepal's international trade with India. Its vibrant markets, Bihari-Madhesi cultural character, Gandhi Mai Temple and easy proximity to Parsa Wildlife Reserve make it a fascinating and underrated stopover for travellers crossing between Nepal and India.`,
    story: `<p>Founded in 1897 by Rana Prime Minister Bir Shamsher Jung Bahadur, Birgunj grew from a border staging post into Nepal's most commercially significant city outside the Kathmandu Valley. Today the metropolitan city processes the majority of Nepal's imports and exports across its checkpost with Raxaul in the Indian state of Bihar, and the constant flow of trucks, traders and transiting goods gives it an energy that is entirely its own among Nepali cities.</p><p>The city's cultural character is quintessentially Madhesi, with strong ties of language, cuisine, religion and family across the open border with the Bhojpuri and Maithili-speaking communities of Bihar. Hindi and Maithili are heard as often as Nepali in the market lanes, the food stalls serve Bihari specialities alongside Nepali dal bhat, and the religious calendar follows the festivals of the plains: Chhath Puja, Teej and Holi are celebrated with particular intensity.</p><p>Gandhi Mai Temple is the city's most important religious site, a revered shrine to the goddess Gandaki Mai that draws pilgrims from across the Terai and across the border from India. The Ghadiarwa Pokhari, a historic sacred pond in the city centre, provides a moment of relative calm amid the commercial bustle, its edges lined with small shrines and morning bathers. The Lord Buddha stupa on a nearby hillock offers elevated views over the flat Terai landscape stretching south into India.</p><p>Parsa Wildlife Reserve, adjacent to the famous Chitwan National Park, lies just northeast of Birgunj and provides a less-visited alternative for wildlife watching. The reserve harbours tigers, leopards, rhinoceros, wild elephants and a rich array of birds in dense sal forest and riverine grassland. For the road traveller arriving from India or departing south from the hills of Nepal, Birgunj offers far more than its reputation as a transit city might suggest.</p>`,
    district: `Parsa`,
    province: "MADHESH",
    lat: 27.0104,
    lng: 84.8778,
    elevation: 76,
    entryFee: `Free (Parsa Wildlife Reserve fee applies for the reserve)`,
    bestSeason: `Oct-Feb`,
    openingHours: `Always open (border crossing: subject to government hours)`,
    howToGetThere: `Bus from Kathmandu to Birgunj takes 5-6 hours via the Tribhuvan Highway (Hetauda) or Mahendra Highway. Direct buses from Kathmandu operate frequently. From India, cross the Raxaul-Birgunj land border by foot or cycle-rickshaw.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Birgunj Nepal India border crossing tour Madhesh`,
    bookingCity: `Birgunj`,
    seoTitle: `Birgunj – Nepal's Commercial Gateway and Madhesi Cultural Hub`,
    seoDescription: `Discover Birgunj, Nepal's busiest border city and trading hub in Parsa, Madhesh Province. Visit Gandhi Mai Temple, explore vibrant Bihari-Nepali market culture and access Parsa Wildlife Reserve near the India border.`,
    published: true,
    featured: false,
  },
  {
    name: `Salleri`,
    category: "CULTURAL_VILLAGE",
    summary: `Salleri is the hill-town headquarters of Solukhumbu, the district famous for containing Mount Everest, yet this quietly charming bazaar at 2,370 metres receives only a fraction of the trekkers who pass through Lukla. Set above the Solu valley with views of distant snowfields, Salleri is a peaceful base for exploring the lower Solu region's monasteries, traditional Sherpa culture and the Jiri trekking corridor.`,
    story: `<p>Solukhumbu District is one of the most famous geographical addresses in the world, home as it is to Mount Everest and the Sherpa culture that has become synonymous with Himalayan adventure. Yet Salleri, the district headquarters, sits far from the Lukla-Namche tourist corridor in the lower Solu region, a world of terraced rice paddies, apple orchards, Buddhist monasteries and traditional Sherpa villages that operate entirely outside the orbit of the Everest trekking economy.</p><p>The town itself occupies a broad saddle in the Solu hills at approximately 2,370 metres, accessible by the Phaplu Airport a short walk away or by the long but scenically rewarding jeep road from Salleri junction on the Jiri highway. Government offices, schools, the district hospital and a small bazaar line the main street, giving Salleri the purposeful energy of an administrative centre while retaining the unhurried pace of mountain-town life.</p><p>The surroundings of Salleri are rich in monastery culture. The famous Chiwong Gompa near Phaplu is one of the largest and most active gompas in the lower Khumbu, a Nyingma Buddhist monastery perched on a clifftop that hosts the spectacular Mani Rimdu festival in November. The monastery belongs to the same lineage as the great gompas of Tengboche and Thame in the upper Khumbu, and its annual masked dance performances draw Sherpa families from across the Solu region.</p><p>For trekkers, Salleri sits on the classic Jiri-to-Everest Base Camp trail, the route Hillary and Tenzing would have walked before airports existed in the mountains. Spending time here between village stages gives a sense of what Himalayan trekking was like before the helicopter age: slower, more immersive and rooted in the agricultural rhythms of the valleys through which the trail passes.</p>`,
    district: `Solukhumbu`,
    province: "KOSHI",
    lat: 27.5083,
    lng: 86.5917,
    elevation: 2370,
    entryFee: `Free`,
    bestSeason: `Oct-Nov, Mar-May`,
    openingHours: `Always open`,
    howToGetThere: `Fly from Kathmandu to Phaplu Airport (35 min, Tara Air or Sita Air), then short walk or jeep to Salleri. Overland from Kathmandu take the Jiri highway and turn south at the Salleri junction (8-10 hrs). Road access has improved in recent years.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Salleri Solukhumbu Solu valley Nepal trekking tour`,
    bookingCity: `Salleri`,
    seoTitle: `Salleri – Quiet Capital of Solukhumbu and Gateway to the Solu Valley`,
    seoDescription: `Explore Salleri, the peaceful district headquarters of Solukhumbu at 2,370m, surrounded by Sherpa monasteries, apple orchards and the Jiri trekking corridor. A serene base for lower Khumbu cultural discovery in Koshi Province, Nepal.`,
    published: true,
    featured: false,
  },
  {
    name: `Chainpur`,
    category: "CULTURAL_VILLAGE",
    summary: `Chainpur is an ancient bazaar town at 1,200 metres in Sankhuwasabha, celebrated for centuries as the home of the Karuwa, a distinctively shaped copper water vessel that is recognised as one of Nepal's finest traditional crafts. Surrounded by the spectacular Tinjure-Milke-Jaljale rhododendron trail and with the Siddhakali Temple at its heart, this eastern Nepal gem rewards travellers seeking authentic cultural and natural discovery.`,
    story: `<p>Long before trekking became an industry, Chainpur was famous across the eastern hills of Nepal as a centre of metalwork and trade. The Karuwa, a copper or brass water vessel with a distinctive curved spout sculpted with intricate artistic carvings, has been produced in Chainpur workshops for generations and carries the town's reputation far beyond its administrative boundaries. Visiting artisan workshops where these vessels are still crafted by hand using traditional techniques offers a rare window into living craft heritage.</p><p>The town occupies a gently sloping plateau above the Arun River basin in Sankhuwasabha District, surrounded by forested hillsides and the broader landscape of the Koshi Province mountains. The Siddhakali Temple in the town centre is Chainpur's most important religious site, associated in Hindu tradition with the legend that Sati's right eye fell here when her body was dismembered and scattered across the subcontinent to create the sacred pithas. The temple draws pilgrims on auspicious days and is the focal point of the town's festival calendar.</p><p>The surroundings of Chainpur are ecologically extraordinary. The Tinjure-Milke-Jaljale ridge system, accessible from the town, forms one of the longest rhododendron ridgelines in Nepal, stretching for days through alpine meadows where 28 of Nepal's 32 rhododendron species bloom in waves of colour between March and May. This area has been described as the rhododendron capital of Nepal and is increasingly recognised by naturalists and photographers who seek it out precisely because it has none of the infrastructure of the more famous trekking circuits.</p><p>The various high-altitude ponds in the Chainpur area, including Panch Pokhari and Gufapokhari, are sacred pilgrimage sites that attract Hindu and Buddhist worshippers during specific festival periods. Their remote high-altitude settings, typically above 4,000 metres, make the pilgrimages themselves a form of trekking adventure that blends spiritual purpose with natural spectacle.</p>`,
    district: `Sankhuwasabha`,
    province: "KOSHI",
    lat: 27.2933,
    lng: 87.3231,
    elevation: 1200,
    entryFee: `Free`,
    bestSeason: `Oct-Nov, Mar-May`,
    openingHours: `Always open`,
    howToGetThere: `Fly from Kathmandu to Tumlingtar (35 min), then jeep to Chainpur (2-3 hrs). Alternatively, fly to Bhojpur and continue by jeep. Road from Hile via Dhankuta to Chainpur is possible but long. Most visitors combine with a Makalu or Arun Valley trek.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Chainpur Sankhuwasabha eastern Nepal cultural tour`,
    bookingCity: `Tumlingtar`,
    seoTitle: `Chainpur – Ancient Craft Town and Rhododendron Gateway in Eastern Nepal`,
    seoDescription: `Discover Chainpur, Sankhuwasabha's ancient copper craft town at 1,200m, home of the famous Karuwa vessels, Siddhakali Temple and gateway to Nepal's rhododendron capital on the Tinjure-Milke-Jaljale ridge in Koshi Province.`,
    published: true,
    featured: false,
  },
  {
    name: `Lumbini Museum`,
    category: "ARCHAEOLOGICAL",
    summary: `The Lumbini Museum, designed by Japanese architect Kenzo Tange, stands within the UNESCO World Heritage Sacred Garden at the birthplace of the Buddha, housing more than 12,000 artefacts spanning 2,500 years of Buddhist history. Its collection of Maurya-era coins, Khushana-period terracottas, ancient manuscripts and international philatelic stamps makes it the finest museum of Buddhist heritage in Nepal.`,
    story: `<p>Lumbini in Rupandehi District is one of the most significant pilgrimage sites in the world, revered by over half a billion Buddhists as the birthplace of Siddhartha Gautama, the historical Buddha, born here in the Lumbini grove in approximately 563 BCE. Within this extraordinary complex, the Lumbini Museum serves as the custodian of the material heritage that documents the site's long history and its centrality to the development of Buddhism across Asia.</p><p>The museum building was designed by Kenzo Tange, one of the twentieth century's most celebrated Japanese architects, as part of a comprehensive master plan developed in collaboration with the United Nations in the 1970s. The building's proportions and materials are designed to complement the landscape of the Sacred Garden and the Ashoka Pillar, which marks the spot the emperor Ashoka identified as the birthplace of the Buddha during his pilgrimage in 249 BCE.</p><p>Inside, the collection spans from the earliest artifacts dating to the 6th century BCE through the peak of Kushana artistic production in the 1st to 3rd centuries CE. Ancient coins from the Maurya and Gupta dynasties, terracotta figurines of Buddha and bodhisattvas, bronze ritual objects, palm-leaf manuscripts in Sanskrit and Pali, and stone inscriptions documenting the site's history are displayed in a scholarly but accessible arrangement. Among the most remarkable exhibits is an international collection of postage stamps depicting Buddhist imagery from dozens of countries, illustrating the global reach of the dharma.</p><p>The museum is open Wednesday through Monday from 10:00 to 16:00, with an admission of NPR 50. Located within the Sacred Garden complex, it is best visited in combination with the Mayadevi Temple, the Ashoka Pillar and the ongoing archaeological excavations that continue to reveal the layered history of this most sacred of Nepali sites.</p>`,
    district: `Rupandehi`,
    province: "LUMBINI",
    lat: 27.4833,
    lng: 83.2764,
    elevation: 92,
    entryFee: `NPR 50`,
    bestSeason: `Oct-Mar`,
    openingHours: `Wed-Mon 10:00-16:00; closed Tuesdays`,
    howToGetThere: `Fly from Kathmandu to Bhairahawa (Gautam Buddha International Airport), then take a taxi to Lumbini Sacred Garden (30 min, 22 km). Bus from Bhairahawa to Lumbini also available. The museum is inside the main Sacred Garden complex near the Mayadevi Temple.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Lumbini Museum Buddha birthplace Nepal tour`,
    bookingCity: `Lumbini`,
    seoTitle: `Lumbini Museum – 12,000 Artefacts of Buddhist Heritage at the Buddha's Birthplace`,
    seoDescription: `Visit the Lumbini Museum inside the UNESCO World Heritage Sacred Garden at the Buddha's birthplace. Designed by Kenzo Tange, it displays 12,000 artefacts from Maurya coins to ancient manuscripts in Rupandehi, Lumbini Province.`,
    published: true,
    featured: false,
  },
  {
    name: `Darchula`,
    category: "CULTURAL_VILLAGE",
    summary: `Darchula is a remote frontier town in Nepal's far-western Sudurpashchim Province, dramatically positioned where the Mahakali River marks the border with India and the Api Himal (7,132m) rises to the north. Gateway to the Api Nampa Conservation Area, the sacred Kalidhunga glacial lake and the ancient Malikarjun Temple pilgrimage, Darchula rewards intrepid travellers seeking far-western Nepal's untouched wilderness.`,
    story: `<p>Darchula occupies a spectacular geographical position at the confluence of culture and landscape. The town sits in the deep Mahakali River gorge at the far-western tip of Nepal, with India's Dharchula town visible on the opposite bank, the Kumaon Himalaya rising beyond and the great mass of the Api Himal, Nepal's westernmost major peak at 7,132 metres, commanding the northern skyline. The frontier character of the town is embedded in its history as a trading and pilgrimage crossing point used for centuries by communities moving between Nepal, India and Tibet.</p><p>The Api Nampa Conservation Area, which encompasses the peaks of Api (7,132m), Nampa (6,757m) and Jethi Bahurani (6,850m), is one of Nepal's least-visited protected areas despite its extraordinary ecological and mountaineering significance. The conservation area shelters snow leopards, red pandas, Himalayan black bears and a remarkable diversity of high-altitude flora, including medicinal herbs harvested by traditional communities under a community forestry framework that has received international conservation recognition.</p><p>The trek to Api Himal Base Camp (4,200m) from Darchula takes trekkers through the villages of the Byansi, Raute and Humli communities, each with distinct cultural and linguistic traditions that reflect the borderland character of the region. The sacred Kalidhunga Tal, a glacial lake at 4,100 metres rimmed by cliffs of black rock, is one of the trek's most striking natural features, venerated by local communities and spectacular in its high-altitude remoteness.</p><p>The pilgrimage circuit around Malikarjun Temple and the Tripura Sundari Temple brings Hindu pilgrims from across the far-western region and from India on dates of particular religious significance. The accessibility of Darchula has improved with the extension of the road network in Sudurpashchim, but the area retains the quality of genuine frontier remoteness that draws explorers and adventurers rather than conventional tourists.</p>`,
    district: `Darchula`,
    province: "SUDURPASHCHIM",
    lat: 29.8517,
    lng: 80.5483,
    elevation: 915,
    entryFee: `Api Nampa Conservation Area fee applicable for trekkers`,
    bestSeason: `Mar-May, Sep-Nov`,
    openingHours: `Always open`,
    howToGetThere: `Fly from Kathmandu to Dhangadhi, then take a connecting flight to Darchula (Darchula Airport). Alternatively, jeep from Dhangadhi via Mahendranagar takes 2 days on rough mountain roads. Road access improving but still very remote.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Darchula Api Himal trek far-western Nepal`,
    bookingCity: `Dhangadhi`,
    seoTitle: `Darchula – Far-Western Nepal Frontier Town and Gateway to Api Himal`,
    seoDescription: `Explore Darchula, a remote frontier town on the Mahakali River border with India at the foot of Api Himal (7,132m). Gateway to the Api Nampa Conservation Area, sacred glacial lakes and far-western Nepal wilderness in Sudurpashchim Province.`,
    published: true,
    featured: false,
  },
]

async function main() {
  console.log('🌱 Seeding batch 10 — 20 places...')
  for (const p of places) {
    const s = slug(p.name)
    await prisma.place.upsert({
      where: { slug: s },
      update: {},
      create: { ...p, slug: s },
    })
    console.log('  ✅', p.name)
  }
  console.log('🌱 Batch 10 complete!')
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
