import 'dotenv/config'
import { PrismaClient } from '@prisma/client'
import slugify from 'slugify'

const prisma = new PrismaClient()
const slug = (n) => slugify(n, { lower: true, strict: true })

const places = [
  {
    name: "Ilam Tea Gardens",
    category: "CULTURAL_VILLAGE",
    summary: "Ilam is Nepal's premier tea-growing region, nestled in the eastern hills at elevations between 1,200 and 2,100 metres. Rolling emerald tea estates blanket the hillsides, producing some of the finest orthodox teas in South Asia. The region also offers sunrise viewpoints, sacred wetlands, and a rich tapestry of Limbu and Rai cultural heritage.",
    story: `<h3>Nepal's Tea Capital</h3><p>Ilam district, bordering India's Darjeeling hills, is the heartland of Nepali tea cultivation. Established by the Rana rulers in the 19th century, the gardens have grown into a thriving industry supplying premium orthodox and CTC teas to global markets. Walking the estate paths at dawn, when mist rolls through the terraced slopes and pickers move gracefully between the rows, is one of eastern Nepal's most memorable experiences.</p><h3>Kanyam: The Green Crown</h3><p>Kanyam village, perched at roughly 1,800 metres, is the centrepiece of the tea belt. Its viewpoints survey a panoramic sweep from the Kanchenjunga massif in the north to the Indian plains in the south. Visitors can join factory tours to witness withering, rolling, oxidising, and firing — the four steps that transform a fresh leaf into a fragrant cup. The nearby Mai Pokhari, a Ramsar-listed sacred wetland, shelters rare orchids, pitcher plants, and hundreds of bird species.</p><h3>Highlights</h3><ul><li>Sunrise panorama of Kanchenjunga from Antu Danda (2,328 m)</li><li>Tea factory tours and plucking demonstrations at Kanyam</li><li>Mai Pokhari sacred wetland and bird-watching sanctuary</li><li>Limbu and Rai cultural homestays and cuisine</li><li>Mechi Highway scenic drive through endless tea gardens</li></ul>`,
    district: "Ilam",
    province: "KOSHI",
    lat: 26.9094,
    lng: 87.9282,
    elevation: 1200,
    entryFee: "Free (tea factory tours may charge NPR 100\u2013200)",
    bestSeason: "March\u2013May and October\u2013December",
    openingHours: "Sunrise to sunset",
    howToGetThere: "From Kathmandu, fly or take a night bus to Biratnagar (approx. 700 km east), then drive 3\u20134 hours north to Ilam town via the Mechi Highway. From Birtamod on the East-West Highway, Ilam is about 2 hours by road. Kanyam is a further 17 km north of Ilam town along a scenic mountain road.",
    gygQuery: "Ilam tea garden tour Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Ilam Tea Gardens Nepal \u2013 Rolling Green Estates of the East",
    seoDescription: "Explore Ilam's stunning tea gardens in eastern Nepal. Walk emerald estates, witness tea processing, visit sacred Mai Pokhari, and enjoy Kanchenjunga sunrise views from Antu Danda.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Pathibhara Devi Temple",
    category: "TEMPLE",
    summary: "Pathibhara Devi Temple is a high-altitude Hindu shrine dedicated to Goddess Durga, set at 3,794 metres in the remote mountains of Taplejung district. Revered equally by Hindus and Buddhists across Nepal and India's Sikkim, it draws more than 30,000 pilgrims annually who undertake a 3\u20134 hour trek from the nearest roadhead. The dramatic Himalayan setting, with views of Kanchenjunga's snowy flanks, makes this one of Nepal's most spiritually charged destinations.",
    story: `<h3>A Goddess Above the Clouds</h3><p>Perched at 3,794 metres in the Taplejung hills of eastern Nepal, Pathibhara Devi Temple is one of the most revered Shakti shrines in the Himalayan region. The goddess, also called Mukhumlung, is believed to grant the wishes of devoted pilgrims who make the arduous trek to her doorstep. Legend holds that the goddess herself selected this commanding ridge, refusing to be housed in the valley below, so that only the truly devoted would reach her.</p><h3>Pilgrimage and Trek</h3><p>The trail begins at Phungling (Taplejung headquarters) or from the roadhead at Kafle Pati, where stone steps and rhododendron forests guide pilgrims upward for three to four hours. Animal sacrifices traditionally accompany major festivals, and the air is thick with incense and the ringing of temple bells during Dashain and Tihar. The site also serves as an alternative entry point for the Kanchenjunga Conservation Area Trek, making it popular with trekkers passing through.</p><h3>Highlights</h3><ul><li>Spectacular views of Kanchenjunga (8,586 m), the world's third-highest peak</li><li>Sacred Hindu-Buddhist confluence site revered across Nepal, Sikkim, and Darjeeling</li><li>Rhododendron forests ablaze with colour in March–April</li><li>Festive atmosphere during Dashain with thousands of pilgrims</li><li>Possible gateway for Kanchenjunga Circuit trekkers</li></ul>`,
    district: "Taplejung",
    province: "KOSHI",
    lat: 27.4292,
    lng: 87.7681,
    elevation: 3794,
    entryFee: "NPR 100 (approximate; subject to change)",
    bestSeason: "October\u2013November and March\u2013May",
    openingHours: "Open daily, dawn to dusk",
    howToGetThere: "Fly from Kathmandu to Bhadrapur (Jhapa) or Suketar (Taplejung) airport, then drive to Phungling (Taplejung headquarters). From Phungling, take a jeep to the trailhead at Kafle Pati and hike 3\u20134 hours to the temple. Alternatively, buses run from Kathmandu to Taplejung (24\u201330 hours) via the Mechi Highway.",
    gygQuery: "Pathibhara Devi Temple trek Taplejung",
    bookingCity: "Kathmandu",
    seoTitle: "Pathibhara Devi Temple Taplejung \u2013 Nepal's Sacred High-Altitude Shrine",
    seoDescription: "Visit Pathibhara Devi Temple in Taplejung, Nepal, perched at 3,794 m with views of Kanchenjunga. A sacred Hindu pilgrimage and trekking destination in eastern Nepal.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Kanchenjunga Base Camp Trek",
    category: "TREK_ROUTE",
    summary: "The Kanchenjunga Base Camp Trek is one of Nepal's most remote and rewarding wilderness journeys, leading to the base camps of the world's third-highest mountain (8,586 m) in the far eastern corner of the country. The route passes through pristine rhododendron and bamboo forests, traditional Limbu and Sherpa villages, and spectacular high-altitude ridges before reaching Pang Pema (North BC, 5,143 m) and Oktang (South BC, 4,730 m). It remains far less crowded than other Himalayan treks, offering an authentic off-the-beaten-path experience.",
    story: `<h3>The Forbidden Mountain's Footsteps</h3><p>Kanchenjunga, revered as a deity by the Sikkim and Limbu peoples and only opened to climbers in 1955, guards its base camps jealously. The trekking route from Taplejung winds through subtropical lowlands before ascending into a landscape of ancient forests, glacial moraines, and windswept alpine meadows. Each day brings a dramatic change in scenery — from cardamom farms and rice terraces to ice-polished granite and thundering seracs. The region was designated a Conservation Area in 1997 to protect its extraordinary biodiversity.</p><h3>North and South Routes</h3><p>The circuit combines two distinct arms: the northern route climbs to Pang Pema at 5,143 metres, offering a jaw-dropping close-up of Kanchenjunga's north face and the Kangchenjunga Glacier. The southern route descends through Yalung Valley to Oktang at 4,730 metres, where the towering south face reflects in glacial tarns. Connecting the two arms over the challenging Sele La Pass (4,290 m) and Mirgin La (4,663 m) turns the trek into a true circuit adventure requiring experienced mountaineering fitness.</p><h3>Highlights</h3><ul><li>Pang Pema North Base Camp (5,143 m) — closest viewpoint of Kanchenjunga's north face</li><li>Oktang South Base Camp (4,730 m) with Yalung Glacier views</li><li>Pristine forests in Kanchenjunga Conservation Area</li><li>Traditional Limbu and Tibetan-Buddhist cultural villages</li><li>Very low trekker density — true wilderness solitude</li><li>Rich wildlife including red panda, snow leopard, and Himalayan black bear</li></ul>`,
    district: "Taplejung",
    province: "KOSHI",
    lat: 27.7025,
    lng: 88.1475,
    elevation: 5143,
    entryFee: "Kanchenjunga Conservation Area permit: NPR 3,000; TIMS: NPR 2,000",
    bestSeason: "March\u2013May and October\u2013November",
    openingHours: "Year-round trek; best avoided in monsoon (June\u2013September)",
    howToGetThere: "Fly from Kathmandu to Suketar Airport (Taplejung) or Bhadrapur, then drive to Taplejung town. Most itineraries start trekking from Taplejung or Sekathum. A guide is strongly recommended; the trail passes through remote areas with few facilities.",
    trekDays: 22,
    trekMaxElevation: 5143,
    trekDifficulty: "HARD",
    trekDistance: 220.0,
    trekStartPoint: "Taplejung (Sekathum)",
    trekEndPoint: "Taplejung (Sekathum)",
    trekHighlights: ["Pang Pema North Base Camp at 5,143 m", "Oktang South Base Camp with Yalung Glacier views", "Sele La Pass (4,290 m) connecting north and south circuits", "Kanchenjunga Conservation Area old-growth forests", "Traditional Limbu villages and Buddhist monasteries", "Red panda and Himalayan black bear sightings"],
    gygQuery: "Kanchenjunga Base Camp Trek Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Kanchenjunga Base Camp Trek \u2013 Nepal's Ultimate Wilderness Journey",
    seoDescription: "Trek to Kanchenjunga Base Camp in far eastern Nepal. Reach Pang Pema (5,143 m) and Oktang (4,730 m) on a 22-day circuit through pristine forests and ancient Limbu villages.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Tansen",
    category: "DURBAR_PALACE",
    summary: "Tansen is a beautifully preserved medieval hilltop town and the administrative headquarters of Palpa district, sitting at 1,372 metres on the southern flank of the Mahabharat Range. Its atmospheric Newari bazaar, traditional dhaka weaving, fine metalwork, and commanding Himalayan views have placed it on UNESCO's Tentative World Heritage List. Once a powerful regional capital and a key trade entrep\u00f4t between India and Tibet, Tansen retains an authenticity increasingly rare in Nepal's tourist circuit.",
    story: `<h3>The Newari Kingdom of the West</h3><p>Long before Prithvi Narayan Shah unified Nepal, Tansen was the capital of the Magar Kingdom of Palpa — one of the most powerful principalities in the hills. Under King Mukunda Sen in the 16th century, Palpa nearly conquered Kathmandu, such was its military might. When the kingdom came under Rana influence in the 18th century, Newar merchants transformed Tansen into a prosperous bazaar on the Tibet–India trade route, constructing the ornate courtyard houses and pagoda temples that still crowd its narrow cobbled lanes today.</p><h3>Dhaka and Dhungedhara</h3><p>Tansen is synonymous with two crafts: dhaka weaving — the vibrant geometric fabric woven on traditional hand looms and worn as topis and shawls across Nepal — and dhaulagiri metalwork, producing distinctive black-metal water vessels and figurines. The old bazaar quarter around Shitalpati and Amar Narayan Temple thrums with the sound of looms and the smell of incense. The nearby Mul Dhoka (main gate) features one of the most intricately carved wooden doorways in western Nepal.</p><h3>Highlights</h3><ul><li>Palpa Durbar Square on UNESCO's Tentative World Heritage List</li><li>Amar Narayan Temple — a striking three-tiered pagoda</li><li>Traditional dhaka weaving workshops open to visitors</li><li>Shreenagar Hill panorama: Dhaulagiri to Annapurna and the Terai plains</li><li>Baggi Dhoka — the grand main gate of the old palace complex</li><li>Vibrant local markets selling dhaka cloth, metalwork, and spices</li></ul>`,
    district: "Palpa",
    province: "LUMBINI",
    lat: 27.8667,
    lng: 83.55,
    elevation: 1372,
    entryFee: "Free (some museums charge NPR 100\u2013200)",
    bestSeason: "October\u2013March",
    openingHours: "Town accessible 24 hours; temples and museums 6:00 AM \u2013 6:00 PM",
    howToGetThere: "From Kathmandu, take a tourist bus or night bus to Butwal (approx. 6\u20137 hours), then connect by local bus or shared jeep to Tansen (approx. 2 hours, 36 km north). From Pokhara, Tansen is about 3 hours by road. The Siddhartha Highway connects Butwal to Tansen via Palpa.",
    gygQuery: "Tansen Palpa day tour from Pokhara",
    bookingCity: "Pokhara",
    seoTitle: "Tansen Palpa Nepal \u2013 Ancient Hilltop Town of Dhaka Weaving and Heritage",
    seoDescription: "Discover Tansen, Nepal's best-preserved medieval hilltop town in Palpa district. Explore Newari architecture, dhaka weaving workshops, Himalayan viewpoints, and UNESCO-listed heritage.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Rani Mahal Palpa",
    category: "DURBAR_PALACE",
    summary: "Rani Mahal, often called the 'Taj Mahal of Nepal', is a grand neo-classical palace built in 1893 by General Khadga Shamsher Rana on the banks of the Kali Gandaki River in Palpa district. Constructed in memory of his beloved wife Tej Kumari Devi, the white-walled multi-storied structure rises dramatically above the river gorge, blending Rana-era grandeur with a romantic riverside setting. Though now partly restored, it remains one of Nepal's most evocative architectural monuments.",
    story: `<h3>Love in Stone Above the Kali Gandaki</h3><p>In 1893, exiled General Khadga Shamsher Rana channelled his grief at the loss of his wife into creating a monument that would outlast his own sorrow. Rani Mahal — 'Queen's Palace' — rises from a rocky promontory above the thundering Kali Gandaki River in a style that echoes Mughal grandeur while reflecting Rana-era Nepal's infatuation with European classicism. Its arched galleries, ornamental balustrades, and multi-storied towers stare across the gorge at terraced rice fields climbing the opposite hillside — a sight that has long drawn comparisons to the Taj Mahal in its romantic desolation.</p><h3>Abandonment and Rediscovery</h3><p>Just nine years after construction, in 1902, Khadga Shamsher was forced to flee to India following a political upheaval, leaving Rani Mahal abandoned to nature. For decades, jungle vines crept through its corridors and monsoon floods undermined its foundations. Restoration efforts by the Department of Archaeology have slowly stabilised the structure, and it is now accessible via a riverside trail. The journey itself — a 45-minute walk along the river from the roadhead at Rampur — adds to the sense of romantic discovery.</p><h3>Highlights</h3><ul><li>Iconic view of the palace reflected in the Kali Gandaki at sunrise</li><li>Rana-era neoclassical architecture in a dramatic gorge setting</li><li>Riverside walk from Rampur through forests and farmland</li><li>Combination day-trip with Tansen (35 km away)</li><li>Peaceful picnic spot with minimal crowds</li></ul>`,
    district: "Palpa",
    province: "LUMBINI",
    lat: 27.9264,
    lng: 83.5281,
    elevation: 366,
    entryFee: "No official entry fee",
    bestSeason: "October\u2013March",
    openingHours: "7:00 AM \u2013 6:00 PM",
    howToGetThere: "From Tansen, drive approximately 35 km south toward Rampur on the Siddhartha Highway. From Rampur bazaar, follow the riverside trail southwest for 45 minutes on foot (approximately 3 km) along the Kali Gandaki to reach Rani Mahal. A guide or local directions are helpful for the trail.",
    gygQuery: "Rani Mahal Palpa Nepal palace tour",
    bookingCity: "Pokhara",
    seoTitle: "Rani Mahal Palpa \u2013 The Taj Mahal of Nepal on the Kali Gandaki",
    seoDescription: "Visit Rani Mahal in Palpa, Nepal \u2014 a romantic 19th-century Rana palace rising above the Kali Gandaki gorge. Discover Nepal's most evocative abandoned royal monument.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Srinagar Hill Palpa",
    category: "HILL_VIEWPOINT",
    summary: "Srinagar Hill rises to 1,524 metres above Tansen bazaar in Palpa district, offering one of western Nepal's finest 360-degree Himalayan panoramas. On clear days, the view sweeps from Dhaulagiri and Annapurna in the north across the green Palpa hills to the Terai plains in the south. A short hike or drive from Tansen, it is the perfect complement to a cultural visit to the historic town below.",
    story: `<h3>The Rooftop of Palpa</h3><p>Srinagar Hill crowns the ridge above Tansen, its pine and juniper-clad slopes rising less than an hour's walk above the old bazaar. The name Srinagar — 'city of beauty' — is apt: from the summit view tower, the Annapurna massif, Dhaulagiri, Manaslu, Ganesh Himal, and even the distant Langtang range string across the northern horizon like a wall of ice and rock. Below, Tansen's compact medieval roofscape merges into a tapestry of cultivated terraces and dense forest rolling south toward the Terai plains and the Indian border beyond.</p><h3>Sunrise and Sunset Magic</h3><p>The hill is Palpa's premier sunrise spot, and local visitors set out before dawn to watch the first alpenglow paint the distant snowfields. A small view tower at the summit improves sightlines over the treeline, and a Hindu shrine near the top receives steady offerings from Tansen residents. The forest cover supports leopards, jungle fowl, and a rich assortment of birdlife, making the trail up a pleasant nature walk as well as a viewpoint excursion.</p><h3>Highlights</h3><ul><li>Panoramic Himalayan views including Dhaulagiri, Annapurna, and Manaslu</li><li>Tansen town and Terai plains spread out below</li><li>Short, accessible hike or driveable road to the summit</li><li>Sunrise and sunset photography vantage point</li><li>Pine and juniper forest with resident wildlife</li></ul>`,
    district: "Palpa",
    province: "LUMBINI",
    lat: 27.872,
    lng: 83.544,
    elevation: 1524,
    entryFee: "Free",
    bestSeason: "October\u2013March (clearest Himalayan views)",
    openingHours: "Open 24 hours (best at dawn)",
    howToGetThere: "Srinagar Hill is approximately 2 km from Tansen bazaar. Walk up the marked trail through the forest in about 30\u201345 minutes, or hire a motorcycle taxi from Tansen. A rough road also allows 4WD vehicles to reach near the summit.",
    gygQuery: "Srinagar Hill viewpoint Tansen Palpa Nepal",
    bookingCity: "Pokhara",
    seoTitle: "Srinagar Hill Palpa \u2013 Himalayan Panorama Above Tansen Nepal",
    seoDescription: "Climb Srinagar Hill in Palpa for sweeping views of Dhaulagiri, Annapurna, and Tansen's medieval rooftops. A perfect sunrise viewpoint above Nepal's most charming hill town.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Riri Lake (Ruru Kshetra)",
    category: "LAKE",
    summary: "Riri Lake, also known as Ruru Kshetra or Ridi, is one of Nepal's four sacred Char Dham pilgrimage sites, situated at the confluence of the Ridi Khola and Kali Gandaki River in Gulmi district near Palpa. The site is renowned for its Rishikesh temple \u2014 built by the first king of Palpa, Mukund Sen \u2014 and the abundance of sacred shaligram (ammonite) fossils found in the river bed, which are considered manifestations of Lord Vishnu. Thousands of pilgrims descend on Ridi during the Maghe Sankranti festival in January to bathe in the holy confluence.",
    story: `<h3>One of Nepal's Four Char Dhams</h3><p>Nestled in a deep, narrow river valley at the tri-junction of Gulmi, Palpa, and Syangja districts, Ruru Kshetra — popularly called Ridi — holds a singular place in Hindu cosmology as one of Nepal's four sacred Char Dhams. Ancient Hindu texts identify this confluence as a site of immense spiritual potency where bathing washes away a lifetime of sin and grants moksha — liberation from the cycle of rebirth. The presiding deity, Rishikesh (an aspect of Vishnu), has been worshipped here since the days of the Palpa kingdom.</p><h3>Shaligrams and Sacred Waters</h3><p>What makes Ridi uniquely compelling is the abundance of shaligrams — ammonite fossils embedded in the dark Kali Gandaki riverbed — which Hindus venerate as natural, uncarved images of Vishnu. Pilgrims wade into the shallows to collect these smooth black stones, which are believed to carry the divine presence without requiring consecration. The Rishikesh temple complex, with its tiered pagoda towers and riverside ghats, was originally constructed by Mukund Sen and has been expanded and restored over centuries to its present form.</p><h3>Highlights</h3><ul><li>Sacred Char Dham pilgrimage site — one of four in Nepal</li><li>Rishikesh temple with multi-tiered pagoda architecture</li><li>Shaligram ammonite fossils in the Kali Gandaki riverbed</li><li>Ridi Mela fair during Maghe Sankranti (January) drawing thousands</li><li>Scenic river gorge setting surrounded by forested hills</li></ul>`,
    district: "Gulmi",
    province: "LUMBINI",
    lat: 27.8833,
    lng: 83.4167,
    elevation: 430,
    entryFee: "Free",
    bestSeason: "October\u2013March; January for Maghe Sankranti festival",
    openingHours: "Temple open 6:00 AM \u2013 7:00 PM",
    howToGetThere: "From Tansen (Palpa), drive approximately 20 km toward Ridi Bazar via local roads. From Butwal on the Siddhartha Highway, take a bus or shared jeep toward Gulmi/Ridi \u2014 approximately 2 hours. The Rishikesh temple ghats are at the river confluence below Ridi bazaar.",
    gygQuery: "Ridi Kshetra pilgrimage Palpa Nepal",
    bookingCity: "Pokhara",
    seoTitle: "Riri Lake (Ruru Kshetra) Palpa \u2013 Nepal's Sacred Char Dham Pilgrimage",
    seoDescription: "Discover Ruru Kshetra (Ridi) in Palpa, Nepal \u2014 one of four sacred Char Dhams. Visit the Rishikesh temple, collect sacred shaligram fossils, and join the Maghe Sankranti pilgrimage.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Tilicho Lake",
    category: "LAKE",
    summary: "Tilicho Lake in Manang district sits at 4,919 metres above sea level, making it one of the highest lakes in the world and a breathtaking side-trip from the Annapurna Circuit. Fed entirely by glacial melt with no outlet, its waters display an intense turquoise-to-emerald colour from suspended glacial silt, surrounded by the towering walls of the Annapurna and Tilicho Peak (7,134 m) massifs. The 3\u20134 day detour from Manang to the lake and back is one of the most visually spectacular high-altitude hikes in the Himalayas.",
    story: `<h3>A Lake Born of Ice</h3><p>Tilicho Lake occupies a glacially carved bowl at the foot of Tilicho Peak (7,134 m) in the Annapurna Conservation Area, Manang district. It stretches four kilometres in length and 1.2 kilometres wide, yet has no visible outlet — its waters seep through the porous moraines below. This self-contained glacial basin produces a colour so vivid that first-time visitors often stop in stunned disbelief: the lake shifts from deep turquoise to emerald green as clouds and snow-light play across its surface.</p><h3>The Annapurna Circuit's Greatest Side-Trip</h3><p>Most trekkers encounter Tilicho as a two-day out-and-back from Manang (3,540 m) on the Annapurna Circuit. The route crosses a dangerous landslide belt — the infamous 'bad section' — before climbing to Tilicho Base Camp at 4,200 metres, where lodges now operate. A final four-hour ascent from base camp delivers trekkers to the lake shore at 4,919 metres. From the shoreline, the views of Tilicho Peak, Nilgiri North, and the Great Barrier ridge are among the finest in the entire Annapurna region.</p><h3>Highlights</h3><ul><li>One of the world's highest lakes at 4,919 m</li><li>Extraordinary turquoise-to-emerald glacial colouring</li><li>Framed by Tilicho Peak (7,134 m) and the Annapurna massif</li><li>Possibility of crossing Meso Kanto La (5,100 m) to Jomsom</li><li>Remote, pristine high-altitude environment with minimal crowds</li></ul>`,
    district: "Manang",
    province: "GANDAKI",
    lat: 28.6833,
    lng: 83.85,
    elevation: 4919,
    entryFee: "Annapurna Conservation Area permit: NPR 3,000; TIMS: NPR 2,000",
    bestSeason: "April\u2013May and October\u2013November",
    openingHours: "Year-round trek; high passes may be closed November\u2013March",
    howToGetThere: "Drive or take a bus from Kathmandu or Pokhara to Besisahar, then follow the Annapurna Circuit road to Manang (approx. 2 days by jeep or 8\u201310 days trekking). From Manang, trek 2 days to Tilicho Lake via Tilicho Base Camp. A jeep can now reach close to the base camp during summer.",
    gygQuery: "Tilicho Lake trek Annapurna Circuit",
    bookingCity: "Pokhara",
    seoTitle: "Tilicho Lake Nepal \u2013 World's Highest Turquoise Lake in Manang",
    seoDescription: "Trek to Tilicho Lake at 4,919 m in Manang, Nepal \u2014 one of the highest lakes on Earth. Marvel at turquoise glacial waters beneath Tilicho Peak on this Annapurna Circuit side-trip.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Shey Phoksundo Lake",
    category: "LAKE",
    summary: "Shey Phoksundo Lake is Nepal's deepest lake (145+ metres) and one of its most visually stunning, lying at 3,611 metres within Shey Phoksundo National Park in the remote Dolpa district. Its extraordinarily clear waters shift from cobalt blue to jade green against a backdrop of snow-streaked cliffs and the Tibetan-Buddhist village of Ringmo. Accessible via a challenging multi-day trek, the lake is a centrepiece of the ancient Bon culture that predates Buddhism in the high Himalayan valleys.",
    story: `<h3>The Jewel of Dolpa</h3><p>Shey Phoksundo Lake lies at the heart of Nepal's largest national park — Shey Phoksundo — in the remote trans-Himalayan district of Dolpa. Unlike most Himalayan lakes, it has no grey glacial silt colouring its waters; instead, its extraordinary clarity and the mineral composition of its catchment produce a colour palette unlike anything else in Nepal: midnight blue in the depths, turquoise at the shallows, and jade green where aquatic plants grow near the southern shore. A 108-metre waterfall — the Phoksundo Falls — cascades dramatically into the gorge below the lake's outfall, announcing the lake's presence before it comes into view.</p><h3>Ringmo and the Bon Culture</h3><p>The village of Ringmo sits at the southern edge of the lake, its flat-roofed mud houses and colourful prayer flags reflecting the Tibetan-influenced Bon religion that has shaped Dolpa's culture for millennia. Bon, the pre-Buddhist animist faith of Tibet, still has its primary seat in Dolpa, and Shey Phoksundo National Park contains numerous Bon monasteries and sacred sites rarely visited by outsiders. The trek to the lake — typically starting from Juphal, the nearest airstrip — passes through deep river gorges, ancient mani walls, and some of the most spectacular ravines in the Himalayan arc.</p><h3>Highlights</h3><ul><li>Nepal's deepest lake at over 145 metres depth</li><li>Extraordinary cobalt-to-turquoise colour unlike any other Himalayan lake</li><li>Phoksundo Waterfall — a dramatic 108-metre cascade below the lake</li><li>Ringmo village, a living Bon cultural heritage site</li><li>Shey Gompa — a remote Bon monastery above the lake</li><li>Snow leopard habitat in the surrounding national park</li></ul>`,
    district: "Dolpa",
    province: "KARNALI",
    lat: 29.205,
    lng: 82.955,
    elevation: 3611,
    entryFee: "Shey Phoksundo NP permit: NPR 3,000 (Lower Dolpa); Upper Dolpa restricted area permit varies",
    bestSeason: "May\u2013June and September\u2013October",
    openingHours: "National park open year-round; trails may be inaccessible in winter",
    howToGetThere: "Fly from Kathmandu or Nepalgunj to Juphal Airport (Dolpa). From Juphal, trek approximately 2\u20133 days to Phoksundo Lake via Dunai. The trek requires a national park permit and, for upper Dolpa access, a restricted area permit. A guide is strongly recommended for this remote region.",
    gygQuery: "Shey Phoksundo Lake trek Dolpa Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Shey Phoksundo Lake Dolpa \u2013 Nepal's Deepest and Most Mesmerising Lake",
    seoDescription: "Trek to Shey Phoksundo Lake in Dolpa, Nepal \u2014 the country's deepest lake at 3,611 m. Marvel at cobalt-blue waters, Phoksundo Falls, and ancient Bon culture in a remote Himalayan paradise.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Rara Lake National Park",
    category: "NATIONAL_PARK",
    summary: "Rara Lake is Nepal's largest lake by area (10.8 km\u00b2) and sits at 2,975 metres within Rara National Park in the remote Mugu district of Karnali Province. Often called the 'Queen of Lakes', its crystal-clear waters change colour with the light from sapphire to silver, encircled by conifer forests sheltering musk deer and Himalayan black bear. Reaching this jewel of the far west requires a flight to Talcha Airport followed by a short trek, making it one of Nepal's most exclusive natural destinations.",
    story: `<h3>The Queen of Nepal's Lakes</h3><p>Rara Lake — fed by eleven streams and draining via a single outlet — is the crown of Nepal's far-western highlands. The lake stretches 5.1 km long and 2.7 km wide, reaching a maximum depth of 167 metres, and its surface lies at 2,975 metres. The colour of the water changes hourly: morning brings a deep sapphire, afternoon a turquoise shimmer, and at sunset, the surface mirrors the golden and crimson hues of the surrounding forest. Rara National Park, Nepal's smallest national park at 106 km², is nevertheless home to 51 mammal species and over 200 bird species.</p><h3>Getting to the Edge of the World</h3><p>Rara's remoteness is its great protector and its greatest challenge. The park lies in Mugu district, one of the most inaccessible districts in Nepal, and for decades had no road link to the outside world. Even today, most visitors fly from Nepalgunj to Talcha Airport and trek 3–4 hours to the lake shore. This exclusivity keeps visitor numbers low and the ecosystem pristine. The park authorities limit fishing and camping, and the surrounding Mugu communities maintain a centuries-old tradition of respectful coexistence with the lake's ecosystem.</p><h3>Highlights</h3><ul><li>Nepal's largest lake at 10.8 km² — remarkably clear and deep</li><li>Vivid colour changes from sapphire to turquoise throughout the day</li><li>Chuchemara Peak (4,039 m) — viewpoint above the lake with Himalayan panorama</li><li>Rich wildlife: musk deer, Himalayan black bear, red panda, over 200 bird species</li><li>Traditional Mugu villages and Tibetan-influenced culture nearby</li><li>One of Nepal's least-visited and most pristine national parks</li></ul>`,
    district: "Mugu",
    province: "KARNALI",
    lat: 29.5236,
    lng: 82.1244,
    elevation: 2975,
    entryFee: "National park permit: NPR 3,000; TIMS: NPR 2,000",
    bestSeason: "May\u2013June and September\u2013November",
    openingHours: "National park open year-round; Talcha Airport seasonal flights",
    howToGetThere: "Fly from Kathmandu to Nepalgunj (1 hour), then take a twin-otter flight to Talcha Airport (Mugu) \u2014 approximately 40\u201350 minutes. From Talcha, trek 3\u20134 hours to the lake shore. Alternatively, a very challenging multi-day overland trek is possible from Jumla or Sinja Valley.",
    gygQuery: "Rara Lake Nepal trek remote wilderness",
    bookingCity: "Kathmandu",
    seoTitle: "Rara Lake National Park \u2013 Nepal's Largest Lake in Remote Karnali",
    seoDescription: "Visit Rara Lake, Nepal's largest and most pristine lake at 2,975 m in Mugu district. Explore sapphire waters, conifer forests, and exceptional wildlife in a remote far-western paradise.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Bardiya National Park",
    category: "NATIONAL_PARK",
    summary: "Bardiya National Park is Nepal's largest and most undisturbed national park in the Terai, covering 968 km\u00b2 of sal forest, grassland, and river habitat in Bardiya district of Karnali Province. Home to the country's second-largest tiger population (approximately 125 tigers), as well as greater one-horned rhinos, wild elephants, Gangetic dolphins, and barasingha deer, it offers some of the most authentic wildlife experiences in South Asia. Unlike the more visited Chitwan, Bardiya receives far fewer tourists, making encounters with wildlife genuinely wild and unpredictable.",
    story: `<h3>Nepal's Last Wild Terai</h3><p>Stretching along the eastern bank of the Karnali River in the far western Terai, Bardiya National Park preserves the largest contiguous block of riverine and sal forest in Nepal. Established as a royal hunting reserve in 1969 and elevated to national park status in 1988, Bardiya has undergone one of the most remarkable conservation turnarounds in Asia — its tiger population has grown from near-zero in the 1990s to over 125 individuals today, thanks to anti-poaching efforts and community buffer-zone management. The park's remoteness from Kathmandu has kept it refreshingly uncrowded.</p><h3>Wilderness Safari</h3><p>Jeep safaris, elephant-back rides, and guided walking safaris are the primary ways to explore the park. The grasslands and riverine beaches of the Babai and Karnali rivers are prime spots for rhino sightings, while the dense sal interior requires patience and silence for tiger encounters. Dawn boat rides on the Karnali River offer chances to spot Gangetic river dolphins — one of the world's most endangered mammals — and gharial crocodiles basking on sandbars. The park is also a stronghold for the barasingha (swamp deer), a species that was once hunted to near-extinction.</p><h3>Highlights</h3><ul><li>Among Nepal's highest tiger densities — approximately 125 individuals</li><li>Greater one-horned rhinos, wild elephants, leopards, and striped hyenas</li><li>Gangetic river dolphin and gharial crocodile in the Karnali River</li><li>Barasingha (swamp deer) — rare species recovering in the grasslands</li><li>Dawn boat safari on the Karnali — one of Nepal's top wildlife experiences</li><li>Thakurdwara village — peaceful community entry point with quality lodges</li></ul>`,
    district: "Bardiya",
    province: "LUMBINI",
    lat: 28.3833,
    lng: 81.5,
    elevation: 152,
    entryFee: "Foreigners: NPR 1,000 per day; SAARC: NPR 500 per day; Nepali: NPR 50 per day",
    bestSeason: "October\u2013March (dry season, best wildlife visibility)",
    openingHours: "Park gate open 6:00 AM \u2013 6:00 PM; safari timings by arrangement",
    howToGetThere: "From Kathmandu, fly to Nepalgunj (1 hour) then drive 3 hours south to Thakurdwara, the park headquarters village. Alternatively, take a night bus from Kathmandu to Ambassa or Rajapur on the Mahendra Highway (approx. 10\u201312 hours), then connect by local transport to Thakurdwara.",
    gygQuery: "Bardiya National Park safari tiger rhino Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Bardiya National Park Nepal \u2013 Wild Tigers and Rhinos in the Terai",
    seoDescription: "Experience Nepal's wildest national park in Bardiya. See Bengal tigers, rhinos, river dolphins, and elephants on jeep and walking safaris in an unspoiled Terai wilderness.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Khaptad National Park",
    category: "NATIONAL_PARK",
    summary: "Khaptad National Park is a unique highland plateau national park in far-western Nepal, spanning 225 km\u00b2 across the four districts of Bajhang, Bajura, Achham, and Doti at elevations between 1,400 and 3,300 metres. Unlike Nepal's other parks, Khaptad is characterised by open rolling meadows, 12 small lakes, dense rhododendron and oak forests, and a profound spiritual atmosphere centred on the Khaptad Baba Ashram of a revered Hindu saint. Its 567 plant species, 270 bird species, and extraordinary tranquillity make it one of Nepal's most distinctive and least-visited protected areas.",
    story: `<h3>The Plateau of Serenity</h3><p>High in the Seti River watershed of far-western Nepal, Khaptad National Park spreads across a gentle highland plateau so different from the jagged mountain landscapes elsewhere that visitors describe it as otherworldly. Rolling sub-alpine meadows, locally called kharka, stretch in every direction, carpeted with wildflowers in spring and dusted with snow in winter. Twelve small lakes, including Khaptad Daha, dot the plateau, and the open terrain offers unobstructed views of Api, Saipal, and the far-western Himalayan chain. Established in 1984 primarily to protect this fragile ecosystem and the spiritual heritage of the Khaptad Baba Ashram, the park sees only a few hundred foreign visitors per year.</p><h3>The Sage of the Himalayas</h3><p>Khaptad Baba — the Hindu saint Swami Sachidananda Saraswati — lived in the park's meadows for decades until his death in 1996, attracting pilgrims from across Nepal and India. His ashram near the park headquarters is still maintained as a place of worship. Khaptad Daha, Triveni Daha, and Bikhari Daha are considered sacred waters where pilgrims bathe during major Hindu festivals. The unique combination of spiritual heritage, highland ecology, and pristine wilderness continues to draw a small but devoted stream of visitors to this remote corner of Nepal.</p><h3>Highlights</h3><ul><li>Open rolling sub-alpine meadows with sweeping Himalayan views</li><li>12 sacred lakes including Khaptad Daha, Triveni, and Bikhari Daha</li><li>Khaptad Baba Ashram — revered Hindu spiritual heritage site</li><li>567 plant species including rare medicinal herbs and orchids</li><li>270 bird species — exceptional for far-western Nepal</li><li>Api, Saipal, and Himalayan panorama from the plateau edge</li></ul>`,
    district: "Achham",
    province: "SUDURPASHCHIM",
    lat: 29.27,
    lng: 80.99,
    elevation: 3000,
    entryFee: "NPR 1,000 per person (foreigners)",
    bestSeason: "March\u2013May and September\u2013November",
    openingHours: "Park open year-round; access restricted in winter due to snow",
    howToGetThere: "Fly from Kathmandu to Dipayal (Dadeldhura) Airport, then take a local bus to Silgadhi in Doti district. From Silgadhi, hike approximately 6 hours to the park entrance, then a further 7\u20138 hours to the park headquarters. Alternatively, fly to Chainpur (Bajhang) and approach from the north.",
    gygQuery: "Khaptad National Park trek far western Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Khaptad National Park Nepal \u2013 Highland Plateau Wilderness of the Far West",
    seoDescription: "Explore Khaptad National Park in far-western Nepal \u2014 a serene highland plateau with 12 sacred lakes, rare flora, 270 bird species, and the revered Khaptad Baba Ashram.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Api Nampa Conservation Area",
    category: "NATIONAL_PARK",
    summary: "Api Nampa Conservation Area in Darchula district, Sudurpashchim Province, protects 1,903 km\u00b2 of diverse Himalayan terrain ranging from subtropical valleys at 518 metres to the summit of Api Peak (7,132 m), the highest mountain in far-western Nepal. Established in 2010 and named after its twin peaks \u2014 Api (7,132 m) and Nampa (6,757 m) \u2014 the area encompasses exceptional biodiversity, Tibetan-influenced Byangsi and Shauka cultures, and some of the most remote trekking in the Himalayan arc. The Mahakali River forms its western boundary and the Nepal-Tibet border its northern edge.",
    story: `<h3>Nepal's Far-Western Himalayan Frontier</h3><p>Api Nampa Conservation Area stretches from the lowland forests of the Mahakali valley to the glaciated summit of Api Peak at 7,132 metres — a vertical range of over 6,600 metres encompassed within a single protected area. This extraordinary altitudinal diversity supports ecosystems ranging from tropical sal forests to permanent snow and ice, harbouring snow leopards, musk deer, red pandas, Himalayan tahr, and the near-mythical Himalayan wolf. The area is one of the least-explored conservation zones in Nepal, with limited tourist infrastructure making it the preserve of serious adventurers.</p><h3>Culture at the Crossroads</h3><p>The communities within Api Nampa belong primarily to the Byangsi and Shauka peoples — Tibeto-Burman groups who have historically traded between India, Nepal, and Tibet across the Lipu Lekh pass. Their flat-roofed stone villages, distinctive weaving traditions, and Bon-influenced religious practices represent a cultural heritage under pressure from modern connectivity. The Api Base Camp trek, which begins from Darchula town, passes through these villages and offers one of the most culturally immersive Himalayan journeys available to trekkers willing to venture into Nepal's overlooked far west.</p><h3>Highlights</h3><ul><li>Api Peak (7,132 m) — highest unclimbed mountain in far-western Nepal for most of history</li><li>Nampa Peak (6,757 m) — twin summit dominating the conservation area</li><li>Snow leopard, musk deer, red panda, and Himalayan wolf habitat</li><li>Byangsi and Shauka traditional communities with unique Tibetan-influenced culture</li><li>Mahakali River gorge — one of the deepest in western Nepal</li><li>Extreme remoteness and pristine wilderness unspoiled by tourism</li></ul>`,
    district: "Darchula",
    province: "SUDURPASHCHIM",
    lat: 29.85,
    lng: 80.95,
    elevation: 3800,
    entryFee: "Conservation area permit fees apply; enquire at DNPWC Kathmandu",
    bestSeason: "May\u2013June and September\u2013October",
    openingHours: "Year-round access; high routes closed October\u2013April",
    howToGetThere: "Fly from Kathmandu to Dipayal or Dhangadhi in the far west, then take a bus or jeep to Darchula town on the Mahakali River. The Api Base Camp trek begins from Darchula and takes approximately 8\u201312 days round trip. A licensed guide and proper permits are essential.",
    gygQuery: "Api Nampa Conservation Area trek Darchula Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Api Nampa Conservation Area Nepal \u2013 Far-Western Himalayan Wilderness",
    seoDescription: "Explore Api Nampa Conservation Area in Darchula, Nepal. Trek to Api Peak base camp (7,132 m), encounter snow leopards, and discover the Byangsi culture in Nepal's remotest Himalayan frontier.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Beni Bazaar",
    category: "CULTURAL_VILLAGE",
    summary: "Beni is the bustling headquarters of Myagdi district and the main gateway town for treks into the Mustang, Dolpa, and Dhaulagiri regions, sitting at the confluence of the Kali Gandaki and Myagdi rivers at just 899 metres elevation. A compact but lively bazaar town, Beni serves as the last significant supply point before the high mountains and is the starting point for the dramatic Annapurna Circuit eastern approach, the Dhorpatan route, and the trail toward Dolpa. The town's vibrant market, friendly Gurung and Magar communities, and spectacular gorge scenery make it an underrated stop in western Nepal.",
    story: `<h3>Gateway to Three Himalayan Regions</h3><p>Positioned at 899 metres at the confluence of two powerful Himalayan rivers, Beni punches well above its modest size in strategic importance. Three of Nepal's most dramatic trekking regions converge here: north along the Kali Gandaki lies the route to Jomsom, Muktinath, and the ancient kingdom of Mustang; northwest up the Myagdi Khola lies Dhorpatan and eventually Dolpa; and east rises the Annapurna massif. Trekkers, traders, and pilgrims have passed through Beni for centuries, and its lively bazaar reflects this crossroads energy.</p><h3>Market Town on the Kali Gandaki</h3><p>Beni's daily market is a window into the commercial heart of western Nepal's hills — mule caravans loaded with supplies for distant mountain villages share the narrow lanes with motorbikes, and shops selling everything from climbing equipment to salt-dried fish crowd the riverside. The Myagdi district administration is headquartered here, giving the town an institutional weight that supports its role as a service hub. The Kali Gandaki gorge north of town — eventually becoming the world's deepest river gorge between Annapurna and Dhaulagiri — is visible from the market and draws attention northward toward the high mountains.</p><h3>Highlights</h3><ul><li>Strategic confluence of Kali Gandaki and Myagdi rivers</li><li>Gateway to Mustang, Dolpa, Dhorpatan, and Dhaulagiri trekking circuits</li><li>Vibrant daily market serving the far-western hill communities</li><li>Spectacular gorge scenery visible from town</li><li>Starting point for the Beni-Jomsom Heritage Trail</li></ul>`,
    district: "Myagdi",
    province: "GANDAKI",
    lat: 28.35,
    lng: 83.5667,
    elevation: 899,
    entryFee: "Free",
    bestSeason: "October\u2013May",
    openingHours: "Town accessible 24 hours",
    howToGetThere: "From Pokhara, take a direct bus to Beni \u2014 approximately 5\u20136 hours (110 km) via the Siddhartha-Beni Highway. Some tourist buses run daily from Pokhara's tourist bus park. Beni is also accessible by local bus from Baglung (30 km, 1 hour). From Beni, jeeps and buses continue to Jomsom via the Mustang road.",
    gygQuery: "Beni Myagdi Nepal trekking gateway Mustang",
    bookingCity: "Pokhara",
    seoTitle: "Beni Bazaar Myagdi \u2013 Nepal's Gateway to Mustang, Dolpa, and Dhaulagiri",
    seoDescription: "Discover Beni, the vibrant market town at the gateway to Mustang, Dolpa, and Dhaulagiri in western Nepal. The starting point for some of the Himalayas' most dramatic trekking routes.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Jomsom",
    category: "MOUNTAIN_VIEW",
    summary: "Jomsom is the administrative headquarters of Mustang district, set at 2,743 metres in the dramatic Kali Gandaki valley between the Annapurna and Dhaulagiri massifs. Famous for its powerful afternoon winds that funnel through the world's deepest river gorge, Jomsom is the main hub for the Mustang trekking region, the gateway to the pilgrimage site of Muktinath, and an important stop on the classic Annapurna Circuit. Its airport connects the remote Mustang highlands to Pokhara, making this the launch point for Upper Mustang adventures.",
    story: `<h3>Between Two Giants</h3><p>Jomsom occupies a privileged position in one of the world's most dramatic landscapes: the Kali Gandaki gorge that separates Annapurna I (8,091 m) to the east from Dhaulagiri (8,167 m) to the west — the two eighth-thousanders flanking the deepest river gorge on Earth. At 2,743 metres, the town sits in an arid rain-shadow valley reminiscent of the Tibetan plateau, with flat-roofed whitewashed buildings, fluttering prayer flags, and the constant howl of afternoon winds that regularly ground the small aircraft at Jomsom Airport. This is the largest settlement in Mustang and the logistical centre of an entire Himalayan micro-civilisation.</p><h3>Hub of the High Mustang</h3><p>Jomsom's main street is a parade of tea houses, trekking agencies, and supply shops catering to the steady stream of trekkers heading north to Kagbeni, Muktinath, and the restricted zone of Upper Mustang. The Mustang Cave Museum displays ammonite fossils (shaligrams) and artefacts from the ancient Mustang kingdom. The town divides neatly into a newer administrative quarter and the older Jomsom village, where traditional Tibetan-style courtyard houses still shelter behind mud walls against the relentless wind. Evening light on the Nilgiri (7,061 m) north face directly above town is one of the region's classic mountain spectacles.</p><h3>Highlights</h3><ul><li>Dramatic Kali Gandaki gorge between Annapurna and Dhaulagiri</li><li>Nilgiri North (7,061 m) towering directly above town</li><li>Gateway to Muktinath pilgrimage temple (3,710 m)</li><li>Starting point for Upper Mustang restricted area permits</li><li>Classic Annapurna Circuit stop between Thorong La and Pokhara</li><li>Fossil Museum with shaligram ammonites from the Kali Gandaki</li></ul>`,
    district: "Mustang",
    province: "GANDAKI",
    lat: 28.7844,
    lng: 83.7351,
    elevation: 2743,
    entryFee: "Free to enter town; Annapurna Conservation Area permit required for trekking",
    bestSeason: "March\u2013May and September\u2013November",
    openingHours: "Town accessible 24 hours; airport flights subject to weather",
    howToGetThere: "Fly from Pokhara to Jomsom Airport (Tara Air or Summit Air, approx. 25 minutes) \u2014 one of the world's most scenic mountain flights. Alternatively, drive from Beni (Myagdi) via the Mustang road (Beni-Jomsom, approx. 4\u20135 hours by jeep) or trek the classic Annapurna Circuit from Besisahar (approximately 10\u201312 days via Thorong La).",
    gygQuery: "Jomsom Mustang Nepal mountain trek flight",
    bookingCity: "Pokhara",
    seoTitle: "Jomsom Mustang Nepal \u2013 Gateway to Upper Mustang and Muktinath",
    seoDescription: "Discover Jomsom in Mustang, Nepal \u2014 a dramatic Himalayan hub between Annapurna and Dhaulagiri. Fly from Pokhara, explore the Kali Gandaki gorge, and trek to Muktinath and Upper Mustang.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Lo Manthang",
    category: "DURBAR_PALACE",
    summary: "Lo Manthang is the ancient walled capital of the Kingdom of Lo (Upper Mustang) in northern Mustang district, sitting at 3,840 metres near the Nepal-Tibet border. Founded in 1380 AD by King Ame Pal, its 856-metre-long mud-brick walls enclose a medieval city of whitewashed houses, four-storey palace ruins, and extraordinary Buddhist temples painted with rare 15th-century murals. Opened to trekkers only in 1992, Lo Manthang remains one of the last living examples of a medieval Tibetan city-state, preserving a culture and landscape seemingly untouched by the modern world.",
    story: `<h3>The Last Forbidden Kingdom</h3><p>For decades after Nepal opened its borders to the world, Lo Manthang remained sealed — a restricted zone where the ancient Kingdom of Lo had survived in near-isolation since the 14th century. When the doors finally opened in 1992, trekkers who made the challenging five-day journey from Jomsom found a walled city that looked as though time had stopped six centuries ago. The mud-brick walls, erected by King Ame Pal in 1380, still encircle the settlement almost intact, and the kingdom's last king, Jigme Dorje Palbar Bista, continued to hold court until the monarchy was formally dissolved in 2008.</p><h3>Temples, Murals, and Desert Canyons</h3><p>Lo Manthang's four main Buddhist temples — Champa Gompa, Thupchen Gompa, Chodhe Gompa, and Mustang Gompa — contain some of the finest 15th-century Tibetan Buddhist murals in existence, comparable to the great monasteries of Lhasa and Ladakh. Restoration projects supported by the American Himalayan Foundation have painstakingly revived these frescoes, and many are now accessible to visitors. The surrounding landscape of the Mustang plateau — a high-altitude desert of ochre, red, and grey eroded canyons, natural caves, and wind-sculpted badlands — frames the walled city in a setting of surreal beauty.</p><h3>Highlights</h3><ul><li>Ancient walled city founded 1380 AD — one of the world's last medieval Tibetan city-states</li><li>Four major 15th-century Buddhist temples with restored Tibetan murals</li><li>Former royal palace of the Kingdom of Lo's last ruling family</li><li>Spectacular Mustang plateau desert canyon landscape</li><li>Tiji Festival (May) — Lo Manthang's most spectacular three-day Buddhist celebration</li><li>Hundreds of cliff-face cave monasteries and Sky Caves in the surrounding valleys</li></ul>`,
    district: "Mustang",
    province: "GANDAKI",
    lat: 29.1828,
    lng: 83.9562,
    elevation: 3840,
    entryFee: "Upper Mustang restricted area permit: USD 500 for 10 days + USD 50/day thereafter; Annapurna Conservation Area permit: NPR 3,000",
    bestSeason: "May\u2013September (Upper Mustang is accessible and drier than lower Nepal during monsoon)",
    openingHours: "Town open to permit-holders; temples have specific visiting hours",
    howToGetThere: "Fly from Pokhara to Jomsom, then trek 5\u20136 days north via Kagbeni, Chele, Ghemi, and Charang (approximately 85 km). Upper Mustang permits must be arranged in advance through a registered trekking agency. A jeep road now runs from Jomsom to Lo Manthang, cutting travel time to 1\u20132 days, but the trek route is recommended for the full cultural experience.",
    gygQuery: "Upper Mustang Lo Manthang walled city trek",
    bookingCity: "Pokhara",
    seoTitle: "Lo Manthang Upper Mustang \u2013 Ancient Walled Kingdom of Nepal",
    seoDescription: "Visit Lo Manthang, the 14th-century walled capital of Upper Mustang's Kingdom of Lo. Marvel at rare Tibetan murals, desert canyon landscapes, and a living medieval culture near the Tibet border.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Kagbeni",
    category: "CULTURAL_VILLAGE",
    summary: "Kagbeni is a medieval fortified village at the confluence of the Kali Gandaki and Jhong rivers in Mustang district, perched at 2,804 metres where the highway to Lower Mustang meets the restricted zone of Upper Mustang. Its labyrinthine lanes of mud-brick houses, crumbling red-walled gompa (founded circa 1429), and dramatic canyon backdrops give it an atmosphere unlike any other Himalayan village in Nepal. Kagbeni serves as the last freely accessible outpost before the checkpoint into Upper Mustang, making it both a cultural destination and an essential gateway stop.",
    story: `<h3>Where the Two Rivers Meet</h3><p>Kagbeni occupies a commanding position at the junction of the Kali Gandaki — whose black riverbed yields the sacred shaligram ammonite fossils — and the Jhong Khola. The village has been continuously inhabited for at least six centuries, its houses rising in stacked terraces of mud and timber above a web of covered alleyways so narrow that neighbours could shake hands from their rooftop windows. This organic medieval architecture, untouched by the modernising forces that have reshaped most Himalayan bazaars, makes Kagbeni one of the most photogenic villages in the Himalayas.</p><h3>The Red Monastery and the Gateway North</h3><p>The Kag Chode Thupten Samphel Ling Gompa — the Red Monastery — dominates Kagbeni's skyline and its spiritual life. Founded around 1429, its crimson-painted walls house a large seated Buddha, ancient thangkas, and a community of monks from the Sakya tradition. Just beyond the monastery, a police checkpoint marks the boundary of the Upper Mustang restricted zone, and only those with the USD 500 ten-day permit can proceed northward to Chele, Ghemi, and Lo Manthang. For the vast majority of visitors, Kagbeni is the end of the free-access road — and it is more than enough.</p><h3>Highlights</h3><ul><li>Kag Chode Thupten Samphel Ling Gompa — circa 1429 Red Monastery</li><li>Atmospheric medieval alleys and mud-brick courtyard houses</li><li>Last checkpoint before Upper Mustang restricted zone</li><li>Shaligram fossil-bearing Kali Gandaki riverbed below the village</li><li>Dramatic backdrop of the Kali Gandaki gorge and Nilgiri peak</li><li>Apple orchard season (September–October) in surrounding fields</li></ul>`,
    district: "Mustang",
    province: "GANDAKI",
    lat: 28.8333,
    lng: 83.75,
    elevation: 2804,
    entryFee: "Free to enter village; Upper Mustang permit required to go further north",
    bestSeason: "March\u2013November",
    openingHours: "Village accessible 24 hours; monastery 8:00 AM \u2013 5:00 PM",
    howToGetThere: "From Jomsom, Kagbeni is 8 km north along the Kali Gandaki valley \u2014 a 2\u20133 hour walk or 20-minute jeep ride on the Mustang road. From Pokhara, fly to Jomsom then trek or drive to Kagbeni. It is a standard stop on the Annapurna Circuit before or after crossing Thorong La.",
    gygQuery: "Kagbeni medieval village Mustang Nepal Annapurna Circuit",
    bookingCity: "Pokhara",
    seoTitle: "Kagbeni Mustang Nepal \u2013 Medieval Village Gateway to Upper Mustang",
    seoDescription: "Explore Kagbeni in Mustang, Nepal \u2014 a living medieval village at 2,804 m with ancient monasteries, labyrinthine lanes, and the last checkpoint before Upper Mustang's forbidden kingdom.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Dhorpatan Hunting Reserve",
    category: "NATIONAL_PARK",
    summary: "Dhorpatan Hunting Reserve is the only legally permitted hunting reserve in Nepal, covering 1,325 km\u00b2 across the Eastern Rukum, Myagdi, and Baglung districts at elevations between 2,850 and 5,500 metres. Beyond its unique hunting mandate (for Himalayan blue sheep, specifically), the reserve is a spectacular wilderness of alpine meadows, high passes, and dense oak-rhododendron forests harbouring snow leopards, red pandas, musk deer, and Cheer pheasants. The Dhorpatan valley itself is an immense east-west glacially carved basin, one of the most dramatic hidden valleys in western Nepal.",
    story: `<h3>Nepal's Only Hunting Reserve</h3><p>Dhorpatan holds a singular distinction in Nepal's protected area system: it is the only place in the country where licensed trophy hunting is permitted, specifically targeting the Himalayan blue sheep (bharal) under a strictly controlled quota system. Established in 1987, the reserve manages three hunting blocks where a small number of international hunters — typically fewer than a dozen per year — pay substantial fees that are channelled back into local conservation and community development. Far from undermining wildlife, this model has maintained one of the largest blue sheep populations in Nepal.</p><h3>A Hidden Valley of Extraordinary Beauty</h3><p>Most visitors to Dhorpatan come not to hunt but to trek and experience one of Nepal's most remote landscapes. The Dhorpatan valley — a vast, flat-floored glacial basin at 3,000 metres, surrounded by 5,000-metre ridges — supports a semi-nomadic Tibetan community whose yak herders move through the area with the seasons. The trek from Beni in Myagdi to Dhorpatan passes through rhododendron and magnolia forests, high passes with views of Dhaulagiri, and remote villages where visitors are still a genuine novelty. The reserve is also the habitat of the Cheer pheasant, one of the world's most endangered gamebirds.</p><h3>Highlights</h3><ul><li>Nepal's only legally designated hunting reserve — blue sheep quota hunts</li><li>Snow leopard, musk deer, red panda, and Himalayan wolf habitat</li><li>Immense east-west glacially carved Dhorpatan valley</li><li>Cheer and Impeyan pheasants — spectacular Himalayan gamebirds</li><li>Dhaulagiri and Dhaulagiri range views from high ridges</li><li>Traditional Tibetan pastoralist communities in a remote high-altitude setting</li></ul>`,
    district: "Baglung",
    province: "GANDAKI",
    lat: 28.4833,
    lng: 83.0667,
    elevation: 3000,
    entryFee: "NPR 1,000 per person (non-hunting entry); hunting licences arranged through Department of National Parks",
    bestSeason: "April\u2013June and September\u2013November",
    openingHours: "Reserve open year-round; high passes may be snow-covered November\u2013March",
    howToGetThere: "From Pokhara, drive or take a bus to Beni (Myagdi), then proceed by local jeep or trekking trail toward Dhorpatan. The most common trek route from Beni takes approximately 4\u20136 days. Alternatively, approach from Rukum via Sandhikharka. A guide is essential as trails are poorly marked in places.",
    gygQuery: "Dhorpatan trek Nepal remote wilderness Baglung",
    bookingCity: "Pokhara",
    seoTitle: "Dhorpatan Hunting Reserve Nepal \u2013 Remote Wilderness of the Western Himalayas",
    seoDescription: "Explore Dhorpatan Hunting Reserve, Nepal's only hunting reserve, in the remote western Himalayas. Trek through Dhaulagiri foothills, spot snow leopards, and discover a vast hidden valley.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Swargadwari Temple",
    category: "TEMPLE",
    summary: "Swargadwari \u2014 literally 'Gateway to Heaven' \u2014 is one of Nepal's most revered Hindu pilgrimage sites, set at approximately 2,200 metres in the forested hills of Pyuthan district, Lumbini Province. The site is associated with the 20th-century saint Swargadwari Mahaprabhu, who attained samadhi (liberation) here in 1940 AD, and is listed among Nepal's most important cultural and religious heritage inventories. Massive fairs held during Kartik and Baisakh draw tens of thousands of pilgrims from across Nepal and India to this remote but spiritually charged forest sanctuary.",
    story: `<h3>The Gateway the Saint Chose</h3><p>Deep in the Rapti hills of Pyuthan district, 26 kilometres west of the district headquarters at Khalanga, lies a place where the boundary between the mortal and divine is said to grow thin. Swargadwari — meaning Gateway to Heaven — owes its name to the belief that the Hindu saint Swargadwari Mahaprabhu, after decades of meditation in these forests, did not die in the ordinary sense but passed directly into samadhi, a state of eternal divine union. His samadhi shrine in 1940 transformed this remote forest hermitage into one of the holiest pilgrimage circuits in western Nepal.</p><h3>Pilgrim Festivals and Forest Trails</h3><p>Twice a year — during Kartik (October–November) and Baisakh (April–May) — the normally quiet forest trails leading to Swargadwari come alive with the shuffling feet and devotional songs of pilgrims. Many walk barefoot for hours or even days from the nearest road, carrying offerings of flowers, incense, and coconuts. The complex includes a main temple dedicated to Shiva, the saint's samadhi shrine, and several smaller shrines connected by forest paths. The altitude, the dense oak and rhododendron canopy, and the quiet between festival seasons give Swargadwari a meditative atmosphere that has drawn ascetics and seekers for generations.</p><h3>Highlights</h3><ul><li>Samadhi shrine of Swargadwari Mahaprabhu — one of western Nepal's holiest sites</li><li>Kartik and Baisakh melas — massive pilgrim fairs drawing thousands</li><li>Dense forest setting at 2,200 m above the Rapti valley</li><li>Shiva temple complex with multiple subsidiary shrines</li><li>Spiritual and ascetic atmosphere popular with Hindu renunciants</li></ul>`,
    district: "Pyuthan",
    province: "LUMBINI",
    lat: 28.1,
    lng: 82.6333,
    elevation: 2200,
    entryFee: "Free",
    bestSeason: "October\u2013November (Kartik fair) and April\u2013May (Baisakh fair)",
    openingHours: "Temple open daily, dawn to dusk",
    howToGetThere: "From Kathmandu, take a bus to Dang (approximately 8\u20139 hours), then continue to Khalanga in Pyuthan district (2\u20133 hours further). From Khalanga, a road leads approximately 26 km west toward Swargadwari, the last section accessible on foot or by motorbike. Alternatively, fly to Bhairahawa or Nepalgunj and connect by road.",
    gygQuery: "Swargadwari pilgrimage Pyuthan Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Swargadwari Temple Pyuthan \u2013 Nepal's Sacred Gateway to Heaven",
    seoDescription: "Discover Swargadwari Temple in Pyuthan, Nepal \u2014 a revered Hindu pilgrimage site at 2,200 m where the saint Swargadwari Mahaprabhu attained samadhi. Join massive seasonal pilgrim fairs.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Chandragiri Hills",
    category: "HILL_VIEWPOINT",
    summary: "Chandragiri Hills, at 2,551 metres, is the closest major Himalayan viewpoint to central Kathmandu, located just 24 km southwest of the city and accessible by a modern cable car covering 2.4 km in under 10 minutes. The summit offers a spectacular 180-degree panorama of the Himalayan range from Dhaulagiri in the west to Everest in the east, including Ganesh Himal, Langtang, Manaslu, and Annapurna. A Bhaleshwor Mahadev temple, a resort, and manicured gardens make it a popular half-day escape for Kathmandu residents and tourists alike.",
    story: `<h3>Kathmandu's Sky-High Balcony</h3><p>Rising from the southern rim of the Kathmandu Valley, Chandragiri Hill has been venerated as a sacred site since the time of King Prithvi Narayan Shah, who is said to have surveyed his future kingdom from this vantage point before his conquest of the valley in 1768. Today, a modern gondola cable car carries visitors from the base station near Thankot to the summit in under ten minutes, replacing a steep two-hour hike and making the extraordinary views accessible to all ages and fitness levels. On clear mornings, the entire Himalayan wall — from Dhaulagiri to Everest — stretches 200 kilometres across the northern horizon.</p><h3>Temple, Resort, and Forest</h3><p>At the summit, the Bhaleshwor Mahadev temple — dedicated to Shiva — attracts both Hindu pilgrims and curious visitors. The cable car company has developed a resort complex around the upper station with restaurants, a children's recreation area, and manicured gardens that make Chandragiri a family destination as much as a scenic viewpoint. Below the developed zone, the forested slopes of the Mahabharat Range are part of the Chandragiri Conservation Forest, where leopards, deer, and langur monkeys still roam relatively close to the capital. The site is particularly spectacular in October and November when the post-monsoon atmosphere is crystal clear.</p><h3>Highlights</h3><ul><li>180-degree panorama from Dhaulagiri to Everest on clear days</li><li>Modern cable car covering 2.4 km — stunning aerial valley views</li><li>Bhaleshwor Mahadev temple at the summit</li><li>Resort facilities: restaurant, gardens, children's activities</li><li>Forested slopes with leopards and langur monkeys below</li><li>Easy half-day trip from central Kathmandu (24 km)</li></ul>`,
    district: "Kathmandu",
    province: "BAGMATI",
    lat: 27.658,
    lng: 85.206,
    elevation: 2551,
    entryFee: "Cable car: Foreigners NPR 3,000 return; SAARC NPR 1,320 return; Nepali NPR 825 return; View tower NPR 50",
    bestSeason: "October\u2013December and February\u2013April",
    openingHours: "Cable car: 9:00 AM \u2013 5:00 PM (last ride); closed Tuesdays for maintenance",
    howToGetThere: "From central Kathmandu, drive southwest via the Dakshinkali road or Thankot road to the Chandragiri cable car base station near Thankot \u2014 approximately 45 minutes by car or taxi (24 km). Public microbus routes run from Kathmandu's New Road or Kalanki to Thankot, from where the cable car base is a short walk or auto-rickshaw ride.",
    gygQuery: "Chandragiri Hills cable car Kathmandu Himalayan view",
    bookingCity: "Kathmandu",
    seoTitle: "Chandragiri Hills Kathmandu \u2013 Cable Car to Nepal's Closest Himalayan Panorama",
    seoDescription: "Ride the Chandragiri cable car to 2,551 m for a sweeping Himalayan panorama from Dhaulagiri to Everest, just 24 km from Kathmandu. Nepal's most accessible hilltop viewpoint.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
]

async function main() {
  console.log(`🌱 Seeding batch 6 — ${places.length} places...`)
  for (const p of places) {
    await prisma.place.upsert({
      where: { slug: slug(p.name) },
      update: {},
      create: { ...p, slug: slug(p.name) },
    })
    console.log(`  ✅ ${p.name}`)
  }
  console.log('🌱 Batch 6 complete!')
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())