import 'dotenv/config'
import { PrismaClient } from '@prisma/client'
import slugify from 'slugify'

const prisma = new PrismaClient()
const slug = (n) => slugify(n, { lower: true, strict: true })

const places = [
  {
    name: "Annapurna Base Camp Trek",
    category: "TREK_ROUTE",
    summary: "The Annapurna Base Camp (ABC) Trek is one of Nepal's most iconic Himalayan treks, leading through lush rhododendron forests, terraced hillsides, and dramatic mountain scenery to the foot of the Annapurna massif at 4,130 m. Trekkers pass through Gurung and Magar villages, hot springs at Jhinu Danda, and the ethereal Machhapuchhre Base Camp before reaching the glacial amphitheatre of Annapurna Sanctuary. The 360-degree panorama of peaks including Annapurna I (8,091 m), Hiunchuli, Machhapuchhre, and Gangapurna makes the journey unforgettable.",
    story: `<p>The trail to Annapurna Base Camp weaves through some of the most breathtaking terrain in Nepal. Beginning in the warm subtropical foothills near Nayapul or Phedi (around 1,070 m), trekkers ascend through the terraced fields of the Modi Khola valley, past the ancient stone-paved steps of Ulleri and the charming Gurung village of Ghandruk, whose traditional culture and mountain views have drawn travellers for decades. The route gradually climbs into dense forests of rhododendron and bamboo, where the air grows cool and the silence is broken only by birdsong and rushing rivers.</p><p>Above Chhomrong, the trail enters the Annapurna Sanctuary — a high glacial basin ringed by ten peaks over 6,500 m. The approach through Bamboo, Dovan, and Himalaya Lodge stages feels almost mythic, with the towering walls of Hiunchuli and Machhapuchhre narrowing the valley into what local Gurung people consider a sacred passage. Machhapuchhre Base Camp at 3,700 m offers the first jaw-dropping glimpse of the fish-tail summit of Machhapuchhre, a peak that has never been climbed and remains sacred. The final two-hour push to Annapurna Base Camp passes through moraines and glacier debris to arrive at the stone shelters of the sanctuary.</p><p>Annapurna Base Camp itself sits in a natural amphitheatre at 4,130 m, encircled by the giants of the Annapurna range. Sunrise at the camp is transformative — the first rays of light paint the ice walls of Annapurna I, Annapurna South, and Gangapurna in shades of pink and gold. The Gurung people have revered this landscape for centuries, and teahouses at base camp are basic but warm. Most trekkers descend via the same route, stopping at the hot springs of Jhinu Danda for a well-earned soak before returning to Pokhara.</p><ul><li>Annapurna Sanctuary — a glacial amphitheatre ringed by ten giants</li><li>Machhapuchhre Base Camp at 3,700 m with stunning fish-tail peak views</li><li>Gurung and Magar village culture along the Modi Khola valley</li><li>Jhinu Danda natural hot springs for post-trek relaxation</li><li>Sunrise panorama of Annapurna I, Annapurna South, Gangapurna, and Hiunchuli</li></ul>`,
    district: "Kaski",
    province: "GANDAKI",
    lat: 28.5306,
    lng: 83.8203,
    elevation: 4130,
    entryFee: "ACAP permit NPR 3,000 + TIMS card NPR 2,000 (foreigners)",
    bestSeason: "October\u2013November and March\u2013May",
    openingHours: "Open year-round; avoid monsoon (June\u2013August)",
    howToGetThere: "Fly or take a tourist bus from Kathmandu to Pokhara (6-8 hours by road, 25 min by flight). From Pokhara, take a taxi or local bus to Nayapul (1.5 hours) or Phedi, which are the standard trek starting points. The trail follows the Modi Khola valley northward through Birethanti, Ghandruk, Chhomrong, and into the Annapurna Sanctuary.",
    trekDays: 10,
    trekMaxElevation: 4130,
    trekDifficulty: "MODERATE",
    trekDistance: 110,
    trekStartPoint: "Nayapul (1,070 m)",
    trekEndPoint: "Nayapul (1,070 m) via same route",
    trekHighlights: ["Annapurna Sanctuary glacial amphitheatre", "Machhapuchhre Base Camp (3,700 m)", "Gurung village of Ghandruk", "Chhomrong village with terraced fields", "Jhinu Danda hot springs", "360-degree Annapurna massif sunrise panorama"],
    gygQuery: "Annapurna Base Camp Trek Pokhara",
    bookingCity: "Pokhara",
    seoTitle: "Annapurna Base Camp Trek | ABC Trek Guide Nepal 2025",
    seoDescription: "Complete guide to the Annapurna Base Camp Trek (ABC Trek) in Nepal \u2014 route, itinerary, elevation, permits, best season, and tips for the iconic 10-day journey to 4,130 m in the Annapurna Sanctuary.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Poon Hill Trek (Ghorepani\u2013Poon Hill)",
    category: "TREK_ROUTE",
    summary: "The Ghorepani\u2013Poon Hill Trek is Nepal's most popular short trek, offering spectacular sunrise views over the Annapurna and Dhaulagiri ranges from Poon Hill (3,210 m) within just 4\u20135 days. The route passes through rhododendron forests, traditional Magar and Gurung villages, and the charming bazaar of Ghorepani at 2,860 m. It is ideal for first-time trekkers and families, with well-developed teahouse infrastructure throughout.",
    story: `<p>The Poon Hill Trek may be short, but it packs a remarkable density of natural beauty and cultural richness into its few days. Starting from Nayapul or Tikhedhunga (reachable by road from Pokhara), the trail climbs steeply through the Modi Khola valley, ascending stone steps through dense rhododendron and oak forests that explode in red and pink bloom from February to April. The village of Ulleri at 2,070 m offers the first sweeping views southward toward the Pokhara valley and the lowland Terai beyond. Magar and Gurung communities along the route live in traditional stone houses and maintain age-old traditions of weaving, farming, and hospitality.</p><p>Ghorepani village, sitting at 2,860 m on a windy ridge, is the gateway to Poon Hill and the beating heart of this trek. Its cluster of teahouses fills every evening with trekkers comparing stories from the trail. The standard pre-dawn hike to the Poon Hill viewpoint tower (3,210 m) takes about 45 minutes in the dark, headlamps bobbing along the forested ridge. At sunrise, the sky transforms into a canvas of orange and rose, dramatically backlighting the enormous ice walls of Dhaulagiri (8,167 m) and the entire Annapurna range including Annapurna I, Annapurna South, Hiunchuli, and the unmistakable fish-tail of Machhapuchhre.</p><p>The descent from Ghorepani toward Tadapani and Ghandruk follows equally beautiful forested ridges with continuing Annapurna views. Ghandruk, the largest Gurung village in the Annapurna region, is a highlight in its own right — stone-paved lanes, traditional gurung houses, a small museum, and panoramic mountain terraces make it an excellent overnight stop before the final descent to Nayapul. The Poon Hill circuit is so well-marked and infrastructurally developed that many trekkers complete it without a guide, making it Nepal's most accessible alpine adventure.</p><ul><li>Poon Hill sunrise over Dhaulagiri and Annapurna ranges</li><li>Rhododendron forest bloom (February–April)</li><li>Ghandruk — largest Gurung village with cultural museum</li><li>Ghorepani village bazaar and mountain lodge atmosphere</li><li>Accessible for beginners; no technical sections</li></ul>`,
    district: "Kaski",
    province: "GANDAKI",
    lat: 28.4005,
    lng: 83.6971,
    elevation: 3210,
    entryFee: "ACAP permit NPR 3,000 + TIMS card NPR 2,000 (foreigners)",
    bestSeason: "October\u2013November and February\u2013April (rhododendron bloom)",
    openingHours: "Open year-round; best avoided in monsoon (June\u2013August)",
    howToGetThere: "From Pokhara, take a taxi or local bus to Nayapul (approximately 45 km, 1.5 hours). The trek begins at Nayapul or nearby Tikhedhunga. Many trekkers also start with a short jeep ride to Hile to skip the lower flat section. Return to Pokhara via Nayapul by local transport or taxi.",
    trekDays: 5,
    trekMaxElevation: 3210,
    trekDifficulty: "EASY",
    trekDistance: 55,
    trekStartPoint: "Nayapul (1,070 m)",
    trekEndPoint: "Nayapul (1,070 m) via Ghandruk loop",
    trekHighlights: ["Poon Hill sunrise panorama of Annapurna and Dhaulagiri", "Rhododendron forest in full bloom (Feb\u2013Apr)", "Ghorepani village at 2,860 m", "Ghandruk Gurung cultural village", "Suitable for beginners and families", "Well-developed teahouse infrastructure"],
    gygQuery: "Poon Hill Trek Pokhara Ghorepani sunrise",
    bookingCity: "Pokhara",
    seoTitle: "Poon Hill Trek (Ghorepani) | Nepal's Best Sunrise Trek Guide",
    seoDescription: "Plan your Poon Hill Trek from Pokhara \u2014 4\u20135 day Ghorepani sunrise trek with Annapurna and Dhaulagiri views. Permits, itinerary, best season, and tips for Nepal's most popular short trek.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Annapurna Circuit Trek",
    category: "TREK_ROUTE",
    summary: "The Annapurna Circuit is one of the world's great long-distance treks, circumnavigating the entire Annapurna massif over 14\u201321 days and crossing the 5,416 m Thorong La Pass, the highest point reachable on the trail. The route traverses an extraordinary range of climatic zones \u2014 from subtropical lowlands and dense forests through alpine meadows and across the high-altitude rain shadow of the Mustang plateau. It passes through diverse communities including Gurung, Magar, Thakali, and Bhotiya peoples, offering a uniquely rich cultural immersion alongside the mountain spectacle.",
    story: `<p>The Annapurna Circuit has long been considered one of the world's finest trekking routes, combining extraordinary mountain scenery with a journey through Nepal's extraordinary cultural and ecological diversity. The trail traditionally begins at Besisahar or Jagat in the Marshyangdi River valley, winding northeast through the lush subtropical warmth of Bhulbhule and Ngadi before ascending into drier pine forests and the more Tibetan-influenced landscapes of upper Manang. Road extensions have altered the lower sections, but from Chame (2,710 m) northward, the trail retains its classic wilderness character.</p><p>The cultural heart of the circuit is Manang (3,519 m), a beautiful Tibetan-style town where trekkers spend an acclimatization day exploring ancient gompas, yak pastures, and the views of the Gangapurna Glacier. Above Manang, the landscape becomes increasingly alpine and austere as the trail climbs through Yak Kharka and Thorong Phedi to the high camp below the Thorong La Pass (5,416 m). The pass crossing — typically a predawn start and a punishing 6–8 hour ascent of 1,600 vertical metres — is the defining physical and psychological challenge of the entire circuit. Prayer flags snap in the bitter wind at the summit cairn, and trekkers descend steeply to the sacred Hindu and Buddhist pilgrimage site of Muktinath at 3,760 m.</p><p>The western half of the circuit through Mustang descends through the dramatic Kali Gandaki gorge — the world's deepest gorge — past the medieval walled town of Kagbeni, through the apple orchards and thakali lodges of Marpha and Tukuche, to the busy airstrip town of Jomsom. From Jomsom, trekkers historically walked south through Tatopani hot springs and Ghorepani before finishing at Nayapul. Many now fly from Jomsom back to Pokhara to complete the experience efficiently. The circuit is a living geography lesson in Himalayan ecology, geology, and culture.</p><ul><li>Thorong La Pass (5,416 m) — the circuit's supreme challenge</li><li>Muktinath temple — sacred Hindu and Buddhist pilgrimage site</li><li>Kali Gandaki gorge — world's deepest river gorge</li><li>Manang village with Gangapurna Glacier views and acclimatisation day</li><li>Marpha and Kagbeni — medieval Mustang-style villages</li><li>Extraordinary cultural diversity across Gurung, Thakali, and Bhotiya communities</li></ul>`,
    district: "Manang",
    province: "GANDAKI",
    lat: 28.7168,
    lng: 83.9281,
    elevation: 5416,
    entryFee: "ACAP permit NPR 3,000 + TIMS card NPR 2,000 (foreigners); Restricted Area Permit for upper Mustang if applicable",
    bestSeason: "October\u2013November and March\u2013May",
    openingHours: "Open year-round; Thorong La may be closed due to snow October\u2013April and during monsoon",
    howToGetThere: "Fly or bus from Kathmandu to Pokhara, then take a jeep or local bus to Besisahar (4\u20135 hours from Pokhara) to begin the trek. Many trekkers now drive to Chame or Dharapani to skip the road-affected lower section. Fly from Jomsom back to Pokhara at the end, or walk the southern half via Ghorepani to Nayapul.",
    trekDays: 18,
    trekMaxElevation: 5416,
    trekDifficulty: "HARD",
    trekDistance: 160,
    trekStartPoint: "Besisahar (820 m)",
    trekEndPoint: "Nayapul or Jomsom (2,720 m)",
    trekHighlights: ["Thorong La Pass at 5,416 m \u2014 highest trekking pass in Nepal", "Muktinath sacred pilgrimage temple", "Kali Gandaki gorge (world's deepest)", "Manang and Mustang-style medieval villages", "Annapurna II, III, IV, Gangapurna and Tilicho Lake views", "Extraordinary cultural diversity across six ethnic communities"],
    gygQuery: "Annapurna Circuit Trek Nepal Thorong La Pass",
    bookingCity: "Pokhara",
    seoTitle: "Annapurna Circuit Trek | Complete Guide to Nepal's Classic Circuit",
    seoDescription: "Ultimate guide to the Annapurna Circuit Trek in Nepal \u2014 14\u201321 days, Thorong La Pass (5,416 m), Muktinath, Kali Gandaki gorge. Route map, permits, best season, and insider tips.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Paragliding Sarangkot Pokhara",
    category: "ADVENTURE_SPORTS",
    summary: "Tandem paragliding from Sarangkot (1,600 m) above Pokhara is one of Nepal's most thrilling adventure experiences, offering 20\u201330 minutes of soaring flight over Phewa Lake with panoramic views of the Annapurna and Dhaulagiri ranges. Pokhara's unique geography \u2014 a thermal valley flanked by eight-thousanders \u2014 makes it one of the world's premier paragliding destinations, attracting both first-timers and seasoned pilots. Flights launch from the Sarangkot ridge and typically land on the grassy meadows of Lakeside Pokhara.",
    story: `<p>Sarangkot has been the launch point for paragliding in Pokhara for over two decades, and its popularity shows no sign of waning. Perched on a ridge at 1,600 m above the Pokhara valley, the site benefits from predictable thermal winds generated by the proximity of the Annapurna massif to the north and the warm Pokhara basin below. On a clear morning, the panorama from Sarangkot is extraordinary — the sharp peaks of Machhapuchhre (6,993 m), Annapurna South, Hiunchuli, and the distant outline of Dhaulagiri stretch across the northern horizon, their permanent snowfields gleaming white against a cobalt sky.</p><p>Tandem paragliding requires no prior experience — a licensed pilot controls the wing throughout the flight while the passenger sits in a comfortable harness and simply enjoys the ride. Flights typically last 20–30 minutes for a standard package or up to 60 minutes for a longer 'mountain flight' that climbs higher on thermals and ventures closer to the ridgeline. The sensation of soaring in silence above the shimmering blue mirror of Phewa Lake, with the reflected Annapurna range visible in the water below, is frequently described by travellers as one of their most memorable experiences in Nepal. Certified gopro or camera footage is usually available as an add-on from professional pilots.</p><p>The Pokhara paragliding industry is regulated by the Nepal Civil Aviation Authority, and reputable companies carry international liability insurance and use certified equipment. The season runs year-round with a pause during the monsoon heavy rains (July–August), but October through May offers the most reliable thermals and clearest visibility. Many operators include transport from Lakeside to the Sarangkot launch site and back in the package price. For adventure travellers spending time in Pokhara, a morning paraglide is the perfect complement to a lakeside afternoon, offering a completely new perspective on the city and its extraordinary mountain backdrop.</p><ul><li>Panoramic Annapurna and Dhaulagiri views during flight</li><li>Flight over mirror-like Phewa Lake with mountain reflections</li><li>20–60 minute tandem flights with certified pilots</li><li>No prior experience required</li><li>Professional photo and video packages available</li></ul>`,
    district: "Kaski",
    province: "GANDAKI",
    lat: 28.2437,
    lng: 83.9575,
    elevation: 1600,
    entryFee: "NPR 8,500\u201313,000 for standard 20\u201330 min tandem flight (approx USD 65\u2013100)",
    bestSeason: "October\u2013May (best thermals October\u2013December)",
    openingHours: "Flights operate 9:00 AM \u2013 3:00 PM weather permitting",
    howToGetThere: "From Lakeside Pokhara, take a taxi or the operator's included transport to Sarangkot (approximately 30 minutes). Most paragliding companies in Lakeside include two-way transfer in their package price. Sarangkot is also accessible by cable car. Flights land at the designated landing zone in Lakeside, a short walk from most hotels.",
    gygQuery: "paragliding Pokhara Sarangkot tandem flight",
    bookingCity: "Pokhara",
    seoTitle: "Paragliding Sarangkot Pokhara | Tandem Flights over Phewa Lake Nepal",
    seoDescription: "Book tandem paragliding from Sarangkot, Pokhara \u2014 soar over Phewa Lake with Annapurna panoramas. Prices, best season, certified operators, and everything you need to know for paragliding in Nepal.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "White Water Rafting Seti River Pokhara",
    category: "ADVENTURE_SPORTS",
    summary: "The Upper Seti River offers one of Nepal's most accessible white-water rafting adventures, with Grade III\u2013IV rapids on a glacially fed river just 30 minutes from Pokhara Lakeside. The half-day trip covers approximately 8 km of exciting water, including powerful rapids and calm stretches with views of the Annapurna foothills. The river originates in the Annapurna snowfields, making it clear and cold throughout the year with a distinctive milky-turquoise colour.",
    story: `<p>The Seti River — whose name means 'white' in Nepali, a reference to its distinctive milky-blue glacier-fed waters — provides Pokhara's resident adventure scene with one of its most exciting products. The Upper Seti rafting trip launches from the Hemja put-in point north of Pokhara, where the river tumbles out of its gorge and enters a more accessible stretch of powerful rapids. The water is fed directly from the snowfields of the Annapurna range, making it strikingly clear and cold, and the surrounding gorge walls of limestone and schist are draped in subtropical vegetation, creating a beautiful natural corridor entirely separate from the busy tourist scene of Lakeside.</p><p>The rapids on the upper section include several genuine Class III and IV features — hydraulic stoppers, pour-overs, and technical lines that require experienced guiding and proper safety equipment. Between rapids, the river calms into deep green pools and gently braided channels where trekkers can leap from rocks and simply float. Because the trip is a half-day experience starting in the morning, it integrates easily into a broader Pokhara itinerary alongside paragliding, kayaking, or a Phewa Lake sunset. All reputable operators provide helmets, life jackets, wetsuits where necessary, and a safety kayaker accompanying each raft.</p><p>Beyond the adrenaline, the Seti River offers something rarer — a chance to experience the raw Himalayan watershed landscape up close, far from the mountain-view restaurants and tourist shops of Lakeside. The gorge section near Hemja reveals natural limestone caves and eroded cliffs that the river has carved over millennia. The Lower Seti, which flows through the city of Pokhara itself and famously disappears underground in several places, is a gentler alternative suited to families and beginners. Together, the upper and lower sections make Pokhara a compelling hub for river adventure at multiple skill levels.</p><ul><li>Grade III–IV rapids on glacially fed turquoise waters</li><li>Half-day adventure, easily combined with other Pokhara activities</li><li>Gorge scenery with limestone cliffs and subtropical vegetation</li><li>Annapurna mountain views from the river valley</li><li>Suitable for adventurous beginners with guide assistance</li></ul>`,
    district: "Kaski",
    province: "GANDAKI",
    lat: 28.2956,
    lng: 83.9811,
    elevation: 820,
    entryFee: "NPR 2,500\u20134,000 per person for half-day Upper Seti trip (approx USD 20\u201330)",
    bestSeason: "September\u2013June (avoid peak monsoon July\u2013August)",
    openingHours: "Morning departures typically 9:00 AM \u2013 12:00 PM",
    howToGetThere: "Most Pokhara rafting operators pick up from Lakeside hotels and drive to the Hemja put-in point, approximately 30 minutes north of Pokhara city centre. The rafting ends at a takeout point near the dam, from where transport returns participants to Lakeside. Book through licensed operators in Lakeside or your hotel.",
    gygQuery: "white water rafting Seti River Pokhara half day",
    bookingCity: "Pokhara",
    seoTitle: "White Water Rafting Seti River Pokhara | Grade III\u2013IV Rapids Nepal",
    seoDescription: "Experience white water rafting on the Seti River near Pokhara \u2014 Grade III\u2013IV rapids, half-day adventure, glacier-blue waters. Prices, best season, and booking guide for Seti River rafting in Nepal.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Everest Base Camp Trek",
    category: "TREK_ROUTE",
    summary: "The Everest Base Camp Trek is the world's most famous trekking route, leading through Sherpa villages, Buddhist monasteries, and high-altitude wilderness to the foot of the world's highest mountain at 5,364 m. The classic 14-day round trip from Lukla passes through Namche Bazaar, Tengboche, Dingboche, and Gorakshep, with most trekkers also ascending Kala Patthar (5,643 m) for the definitive close-up view of Everest. The route is a UNESCO World Heritage journey through the heart of the Khumbu region.",
    story: `<p>No trekking route on earth carries the weight of legend that the Everest Base Camp trail does. The journey begins with the notoriously exciting landing at Lukla's Tenzing-Hillary Airport (2,840 m), where the short runway ends abruptly at a cliff and begins the story. From Lukla, the trail descends to the Dudh Koshi River and follows it north through the rhododendron and juniper forests of Phakding, crossing a series of suspension bridges festooned with prayer flags before the steep ascent to Namche Bazaar at 3,440 m — the de facto capital of the Khumbu Sherpas and gateway to the Everest region. The first acclimatisation day in Namche typically includes a hike to the Everest View Hotel (3,880 m) for the first proper glimpse of Everest above the ridge.</p><p>Above Namche, the trail enters the Sagarmatha National Park's high-altitude wilderness, passing through the monastery village of Tengboche (3,860 m), where the morning chanting of monks and the sight of Everest, Lhotse, and Ama Dablam from the monastery courtyard constitutes one of the Himalaya's great experiences. Further up through Dingboche and Lobuche, the landscape becomes increasingly stark and beautiful — yak caravans plod along moraine paths, and the peaks grow impossibly close. Gorakshep (5,164 m), the last settlement, serves as the base for the final push to Everest Base Camp through the lateral moraine of the Khumbu Glacier.</p><p>Everest Base Camp at 5,364 m is a surprisingly humble destination — a jumble of tents and prayer flags on the glacier, with Everest's summit pyramid visible over the Khumbu Icefall above. But the emotional weight of arriving here, having walked the same path as Hillary, Tenzing, and countless subsequent mountaineers, is profound. Most trekkers rise early the following morning for the steep 500 m ascent to Kala Patthar (5,643 m) for the unobstructed Everest sunrise view before descending to Lukla over two days. The journey remains one of humanity's great walks — a physical, cultural, and spiritual immersion like no other.</p><ul><li>Everest Base Camp at 5,364 m on the Khumbu Glacier</li><li>Kala Patthar (5,643 m) — best close-up Everest sunrise viewpoint</li><li>Tengboche Monastery prayers at dawn with Everest backdrop</li><li>Namche Bazaar — vibrant Sherpa cultural hub and acclimatisation stop</li><li>Suspension bridges, prayer flags, and yak caravans of the Khumbu valley</li><li>UNESCO Sagarmatha National Park high-altitude wilderness</li></ul>`,
    district: "Solukhumbu",
    province: "KOSHI",
    lat: 28.0072,
    lng: 86.8594,
    elevation: 5364,
    entryFee: "Sagarmatha National Park entry NPR 3,000 + TIMS card NPR 2,000 (foreigners); Lukla flight approx USD 180\u2013200 each way",
    bestSeason: "October\u2013November and March\u2013May",
    openingHours: "National park and trail accessible year-round; avoid monsoon (June\u2013August)",
    howToGetThere: "Fly from Kathmandu to Lukla (Tenzing-Hillary Airport) \u2014 approximately 35 minutes by twin-otter or helicopter (book well in advance, as flights are weather-dependent). Alternatively, take a flight or road to Phaplu or Salleri and walk to Lukla in 2\u20133 days for a longer approach. The entire EBC trek is conducted on foot with teahouse accommodation.",
    trekDays: 14,
    trekMaxElevation: 5643,
    trekDifficulty: "HARD",
    trekDistance: 130,
    trekStartPoint: "Lukla (2,840 m)",
    trekEndPoint: "Lukla (2,840 m)",
    trekHighlights: ["Everest Base Camp at 5,364 m on the Khumbu Glacier", "Kala Patthar (5,643 m) sunrise view of Mt Everest", "Tengboche Monastery with Everest and Ama Dablam backdrop", "Namche Bazaar \u2014 Sherpa capital and acclimatisation hub", "Khumbu Glacier and Icefall views", "Iconic suspension bridges draped in prayer flags"],
    gygQuery: "Everest Base Camp Trek guided 14 days Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Everest Base Camp Trek | 14-Day EBC Trek Guide Nepal 2025",
    seoDescription: "Complete guide to the Everest Base Camp Trek (EBC) in Nepal \u2014 14 days, 5,364 m, Kala Patthar, Tengboche Monastery. Permits, Lukla flights, itinerary, and best season for the world's most famous trek.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Namche Bazaar",
    category: "CULTURAL_VILLAGE",
    summary: "Namche Bazaar (3,440 m) is the legendary 'Gateway to Everest' \u2014 the bustling trading hub and cultural capital of the Sherpa people in Solukhumbu, Nepal. The town is built in a natural amphitheatre on the hillside above the confluence of the Bhote Koshi and Dudh Koshi rivers, its colourful lodges, bakeries, gear shops, and monasteries arrayed in terraces against the mountain backdrop. Every Saturday a famous weekly market draws Tibetan traders, high-altitude farmers, and trekkers into a vibrant bazaar that has operated for centuries.",
    story: `<p>Long before the first expedition to Everest, Namche Bazaar was already a significant trade and cultural centre in the upper Khumbu valley. Its strategic position — at the confluence of major river valleys and on the main trade route connecting the high Himalayan passes to Tibet with the lowland markets of the Terai — made it the natural hub for commerce in the region. Tibetan salt, wool, and dried meat were exchanged here for lowland rice, cotton, and manufactured goods in an annual cycle of trade that sustained the Sherpa economy for generations. The weekly Saturday market at Namche still brings a remarkable diversity of goods and people together, from yak herders selling butter and cheese to trekkers restocking supplies and porters loading expedition gear.</p><p>Namche today functions as the main acclimatisation stop for Everest region trekkers, who typically spend two nights here allowing their bodies to adapt to the altitude. The town has grown dramatically from a small village into a surprisingly well-appointed mountain town, with everything from espresso bars and wood-fired pizza to gear rental shops and a small hospital. The Sherpa Culture Museum and the Sagarmatha National Park Visitor Centre are both worth visiting, offering rich context on the Sherpa people's history, culture, and relationship with the mountains. A morning hike to the Everest View Hotel above Namche rewards with one of the classic Himalayan panoramas — Everest, Lhotse, Nuptse, Ama Dablam, and Thamserku arranged in a jaw-dropping semicircle.</p><p>The community here is deeply intertwined with the culture of high-altitude mountaineering. Nearly every Sherpa family in Namche has a member who has climbed an eight-thousander, and the annual Mani Rimdu festival at nearby Tengboche brings the entire community together for days of masked dancing, ritual, and celebration. Despite its tourist infrastructure, Namche retains an authenticity and community warmth that many mountain towns lose as they develop — partly because the mountains themselves impose a natural humility on all who pass through, trekker and local alike.</p><ul><li>Saturday weekly market with Tibetan traders and local produce</li><li>Everest View Hotel hike — panoramic 8,000 m peak views</li><li>Sherpa Culture Museum and Sagarmatha National Park Visitor Centre</li><li>Acclimatisation day activities including Khunde and Khumjung side trips</li><li>Gateway to EBC, Gokyo, Three Passes, and Amadablam Base Camp treks</li></ul>`,
    district: "Solukhumbu",
    province: "KOSHI",
    lat: 27.8069,
    lng: 86.714,
    elevation: 3440,
    entryFee: "Sagarmatha National Park entry NPR 3,000 (included on EBC/Gokyo trekking permits)",
    bestSeason: "October\u2013November and March\u2013May",
    openingHours: "Town open year-round; Saturday market is the weekly highlight",
    howToGetThere: "Fly from Kathmandu to Lukla (Tenzing-Hillary Airport, 35 min), then trek 2 days to Namche Bazaar via Phakding (approximately 20 km). The trail crosses several iconic suspension bridges over the Dudh Koshi River. Some trekkers arrive by helicopter directly from Kathmandu.",
    gygQuery: "Namche Bazaar Sherpa village Everest trek",
    bookingCity: "Kathmandu",
    seoTitle: "Namche Bazaar | The Sherpa Capital and Gateway to Everest Nepal",
    seoDescription: "Discover Namche Bazaar (3,440 m) \u2014 the Sherpa capital and Gateway to Everest in Nepal. Saturday market, acclimatisation activities, cultural highlights, and how to get there on the EBC trail.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Tengboche Monastery",
    category: "MONASTERY",
    summary: "Tengboche Monastery (3,867 m) is the most celebrated monastery in the Khumbu region and one of the most dramatically situated religious buildings in the world, standing on a forested ridge with unobstructed views of Everest, Lhotse, Ama Dablam, and Thamserku. Founded in 1916 and twice rebuilt after an earthquake (1934) and a fire (1989), it remains the spiritual heart of the Sherpa community. The annual Mani Rimdu festival of masked dances draws hundreds of pilgrims each autumn.",
    story: `<p>Tengboche Monastery occupies one of the most supernaturally beautiful positions in the entire Himalaya. Set on a broad ridge above the confluence of the Imja and Dudh Koshi rivers at 3,867 m, the monastery's red and white buildings are framed against a semicircle of the world's greatest peaks — Everest's black pyramid rising behind Nuptse's wall of ice, the elegant spike of Ama Dablam to the southeast, and the broad shoulders of Thamserku and Kangtega completing the panorama. Arriving at Tengboche on the EBC trail — usually on the third or fourth day out of Lukla — many trekkers describe the moment they round the ridge and the monastery comes into view as one of the most affecting of their lives.</p><p>The monastery belongs to the Nyingma order of Tibetan Buddhism and has been the religious centre of the Sherpa community since its founding in 1916 by Lama Gulu. The original structure was destroyed by the 1934 Bihar earthquake and rebuilt, then a fire in 1989 destroyed it again — the current structure, rebuilt with international assistance including donations from many climbing expeditions, is more robust than its predecessors but maintains the same sacred character. Daily morning puja ceremonies begin at around 5 AM and are open to respectful visitors; the sound of long horns, drums, and chanted prayers resonating against the mountain silence is an experience of rare spiritual power. The monastery also houses a small museum documenting Sherpa and mountaineering history.</p><p>The annual Mani Rimdu festival, held at Tengboche during the full moon of the Tibetan ninth month (usually October–November), is the most important cultural event in the Khumbu calendar. Monks perform elaborate cham masked dances representing the triumph of Buddhism over demon forces, drawing Sherpa pilgrims from throughout the region who camp around the monastery courtyard. For trekkers who time their visit to coincide with Mani Rimdu, it is an extraordinary window into living Himalayan Buddhism. The rhododendron forests surrounding Tengboche — ablaze with colour in spring — and the resident musk deer and Himalayan pheasants of the surrounding national park add to its character as one of the world's finest places.</p><ul><li>Unobstructed views of Everest, Lhotse, Ama Dablam, and Thamserku from the monastery courtyard</li><li>Daily 5 AM morning puja ceremony with long horns and chanting</li><li>Annual Mani Rimdu festival of masked Buddhist dances (October–November)</li><li>Surrounding rhododendron and juniper forest with wildlife</li><li>Mountaineering history museum within the monastery complex</li></ul>`,
    district: "Solukhumbu",
    province: "KOSHI",
    lat: 27.8336,
    lng: 86.6999,
    elevation: 3867,
    entryFee: "Small donation expected (NPR 200\u2013500 suggested); Sagarmatha National Park entry applies",
    bestSeason: "October\u2013November (Mani Rimdu festival) and March\u2013May",
    openingHours: "Monastery open approximately 6:00 AM \u2013 12:00 PM and 3:00 PM \u2013 5:00 PM; confirm locally",
    howToGetThere: "Trek from Namche Bazaar (3,440 m) \u2014 approximately 9.5 km and 700 m elevation gain, typically a 4\u20135 hour walk via Phunki Tenga. The standard EBC trail passes directly through Tengboche, making it a natural overnight stop on day 3\u20134 from Lukla. Helicopter access is also possible from Kathmandu or Namche.",
    gygQuery: "Tengboche Monastery Everest trek Khumbu",
    bookingCity: "Kathmandu",
    seoTitle: "Tengboche Monastery | Khumbu's Sacred Heart on the Everest Trail",
    seoDescription: "Explore Tengboche Monastery (3,867 m) \u2014 the spiritual heart of the Sherpa people with stunning Everest and Ama Dablam views. History, Mani Rimdu festival, visiting hours, and how to get there.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Khumjung Village",
    category: "CULTURAL_VILLAGE",
    summary: "Khumjung (3,790 m) is the largest and most significant Sherpa village in the Khumbu region, known worldwide as the home of the Hillary School founded by Sir Edmund Hillary in 1961 and a monastery housing a legendary alleged Yeti scalp. The village sits on a broad plateau above Namche Bazaar beneath the sacred peak of Khumbila, with sweeping views of Ama Dablam and the surrounding giants. Its all-white painted stone houses with green roofs and well-maintained monastery make it one of the most photogenic settlements in Nepal.",
    story: `<p>Khumjung occupies a special place in the story of both Sherpa culture and Himalayan exploration. Situated at 3,790 m on a sheltered plateau above Namche Bazaar, the village was one of the main permanent settlements of the Khumbu Sherpas long before mountaineering expeditions began passing through. Its elevated position provides natural protection from the coldest valley winds while offering extraordinary views of the sacred mountain Khumbila (5,765 m) — considered the home of the guardian deity of the Khumbu — and of Ama Dablam's elegant spire to the southeast. The village's houses, uniformly painted white with green roofs, give it a distinctive appearance quite unlike the more ad-hoc development of Namche below.</p><p>The Hillary School in Khumjung, built in 1961 by Sir Edmund Hillary through his Himalayan Trust, represents one of the most significant legacies of the Everest mountaineering era. Hillary, deeply moved by the poverty and lack of educational opportunity he witnessed in the Khumbu during the 1953 Everest expedition, committed himself to building schools and hospitals for the Sherpa community. Khumjung Hillary School grew from a basic primary school to a full secondary institution, and its consistent high exam results — including a 100% pass rate in Solukhumbu district in recent years — testify to the enduring impact of this early development work. Many of today's leading Sherpa guides, scientists, and professionals attended the school.</p><p>The Khumjung Monastery, which predates the Hillary school by centuries, is the cultural and religious heart of the village. Inside its simple but beautifully maintained prayer hall, alongside the usual thankas and butter lamps, sits the monastery's most unusual artefact — an alleged Yeti scalp, conical in shape and covered in reddish-brown hair. The scalp has been the subject of scientific investigation and considerable debate since Hillary himself examined it in 1960 and arranged for it to be temporarily brought to the West for testing. Today it remains in Khumjung, a fascinating relic that speaks to the deep mythological relationship between the Sherpa people and the high mountain wilderness they inhabit.</p><ul><li>Hillary School — founded 1961, top secondary school in Solukhumbu</li><li>Khumjung Monastery with the legendary alleged Yeti scalp</li><li>Panoramic views of Ama Dablam and sacred Khumbila mountain</li><li>Traditional white-and-green Sherpa village architecture</li><li>Side trip destination from Namche Bazaar acclimatisation day</li></ul>`,
    district: "Solukhumbu",
    province: "KOSHI",
    lat: 27.8189,
    lng: 86.7139,
    elevation: 3790,
    entryFee: "Free village entry; small donation expected at monastery (NPR 200)",
    bestSeason: "October\u2013November and March\u2013May",
    openingHours: "Village accessible year-round; monastery open morning and afternoon (confirm locally)",
    howToGetThere: "From Namche Bazaar, take the trail toward the Everest View Hotel and continue along the ridge to Khumjung \u2014 approximately 1.5\u20132 hours walk (around 5 km and modest elevation gain). This is the classic acclimatisation day walk from Namche, often combined with Khunde village and the Everest View Hotel. No vehicle access.",
    gygQuery: "Khumjung Village Hillary School Sherpa Namche day hike",
    bookingCity: "Kathmandu",
    seoTitle: "Khumjung Village | Sherpa Culture, Hillary School & Yeti Scalp Nepal",
    seoDescription: "Visit Khumjung Village (3,790 m) \u2014 home of the Hillary School, legendary Yeti scalp, and traditional Sherpa culture above Namche Bazaar. Guide to exploring this iconic Khumbu village in Nepal.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Gokyo Lakes",
    category: "LAKE",
    summary: "The Gokyo Lakes are the world's highest freshwater lake system, a series of six glacially fed turquoise lakes strung along the Ngozumpa Glacier valley in Solukhumbu at elevations between 4,700 m and 5,000 m. Considered sacred by both Hindus and Buddhists, the lakes are a UNESCO Ramsar Wetland Site and the centrepiece of the Gokyo Valley trek \u2014 an outstanding alternative to the classic EBC route. The viewpoint of Gokyo Ri (5,357 m) above the main lake provides one of Nepal's finest panoramas, encompassing four 8,000 m peaks.",
    story: `<p>The Gokyo Lakes occupy a valley that most Everest-bound trekkers bypass on their way to Base Camp, and this is part of their charm — they feel discovered rather than consumed. The valley is carved by the Ngozumpa Glacier, the largest glacier in Nepal and reputedly the largest in the entire Himalayas, whose vast white surface stretches north toward the borders of Tibet. The six principal lakes of the Gokyo system — Longponga, Taboche Tsho, Dudh Pokhari (the main Gokyo lake), Thonak Cho (the largest), Ngozumpa Tsho, and Gyazumpa Cho — are arranged like turquoise beads along the valley floor, their colour shifting from pale jade to deep emerald depending on the light and season.</p><p>The main settlement of Gokyo village sits at 4,750 m on the eastern shore of Dudh Pokhari, one of the highest permanently inhabited settlements in the world. The lodges here are simple but adequate, and the view across the mirror-smooth lake surface to the moraine walls of the Ngozumpa and the ice summit of Cho Oyu (8,188 m) in the background is simply magnificent. The sacred significance of the lakes is evident in the prayer flags strung along their shores and in the annual Janai Purnima festival (typically August), when Hindu pilgrims make a high-altitude pilgrimage to bathe in the glacial waters. The lakes are a Ramsar-designated wetland of international importance, supporting remarkable high-altitude wildlife including bar-headed geese, Brahminy ducks, and snow leopards in the surrounding terrain.</p><p>The ascent of Gokyo Ri (5,357 m) from the village is the essential experience of the valley — a steep 2–3 hour climb on loose moraine rewarded with one of the most exceptional viewpoints in Nepal. From the summit, trekkers can simultaneously see four of the world's fourteen 8,000 m peaks: Everest (8,848 m), Lhotse (8,516 m), Makalu (8,485 m), and Cho Oyu (8,188 m). The Gokyo valley also connects via the challenging Renjo La and Cho La passes to the classic Three Passes circuit, linking it with the Everest Base Camp trail and the Khumbu Glacier valley for a comprehensive and adventurous Khumbu experience.</p><ul><li>Six sacred glacial lakes — world's highest freshwater lake system</li><li>Gokyo Ri viewpoint (5,357 m) with four 8,000 m peaks visible simultaneously</li><li>Ngozumpa Glacier — Nepal's largest and the Himalaya's greatest glacier</li><li>Ramsar Wetland Site with rare high-altitude wildlife</li><li>Quieter and less crowded alternative to the classic EBC route</li></ul>`,
    district: "Solukhumbu",
    province: "KOSHI",
    lat: 27.9544,
    lng: 86.6953,
    elevation: 4750,
    entryFee: "Sagarmatha National Park entry NPR 3,000 + TIMS card NPR 2,000 (foreigners)",
    bestSeason: "October\u2013November and March\u2013May",
    openingHours: "Area accessible year-round; avoid monsoon (June\u2013August)",
    howToGetThere: "Fly Kathmandu to Lukla (35 min), then trek via Namche Bazaar and Dole to Gokyo \u2014 approximately 7\u20139 days from Lukla. The route diverges from the main EBC trail at Namche, heading northwest up the Dudh Koshi valley through Dole, Machhermo, and Pangka. Can be combined with EBC via the Three Passes route (Renjo La, Cho La, Kongma La).",
    gygQuery: "Gokyo Lakes trek Nepal Everest region",
    bookingCity: "Kathmandu",
    seoTitle: "Gokyo Lakes Trek | World's Highest Freshwater Lakes in Nepal Khumbu",
    seoDescription: "Explore the sacred Gokyo Lakes (4,700\u20135,000 m) in Nepal's Khumbu region \u2014 world's highest freshwater lake system, Gokyo Ri panorama of four 8,000 m peaks, and Ngozumpa Glacier. Trek guide and itinerary.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Thame Monastery",
    category: "MONASTERY",
    summary: "Thame Monastery is one of the oldest and most revered monasteries in the Khumbu region, a 17th-century Nyingma foundation perched above the remote Thame valley west of Namche Bazaar at approximately 3,800 m. The monastery is famous for its annual Mani Rimdu festival and for its association with the great Sherpa climbing families \u2014 Tensing Norgay was born in the nearby Thame village. The valley offers a peaceful alternative to the busier EBC trail with excellent views of Thamserku and the surrounding peaks.",
    story: `<p>The Thame valley, reached by a half-day walk westward from Namche Bazaar, feels like a step even further into the premodern Himalayan world. The valley was historically the main trade route between the Khumbu and Tibet — before the border closed in 1959, Tibetan traders would descend through the Nangpa La (5,716 m) into Thame with salt, wool, and semi-precious stones, exchanging them for the lowland goods that Sherpa middlemen brought up from the south. The Thame valley's remoteness has preserved a more authentic Sherpa village atmosphere than the increasingly commercialised main EBC trail, and the monastery sits above the village in a position of serene watchfulness over the valley below.</p><p>Thame Monastery (Thamo Gompa) was established in the 17th century and belongs to the Nyingma school of Tibetan Buddhism. Its assembly hall contains ancient thankas, butter lamps, and statues of Guru Padmasambhava and other Nyingma figures of significance. The annual Mani Rimdu festival at Thame, held in the spring (usually May, a month before the Tengboche Mani Rimdu), is a spectacular event of colourful masked dances performed by monks in the monastery courtyard. Because Thame is less visited than Tengboche, the Thame Mani Rimdu has a more intimate character and is often preferred by those who have already experienced the autumn version at Tengboche.</p><p>The Thame valley has a particular significance in the history of Himalayan mountaineering. Tenzing Norgay, who with Hillary made the first ascent of Everest in 1953, was born in Thame village (though he spent most of his life in Darjeeling). The village has produced a disproportionate number of the world's most accomplished high-altitude climbers and guides, and the local community's relationship with the mountain world is deep and multi-generational. A trek to Thame — easily done as a two-day return from Namche — offers a quiet valley walk through juniper and rhododendron, excellent acclimatisation, and a window into one of the least-visited corners of the Sagarmatha National Park.</p><ul><li>One of Khumbu's oldest Nyingma Buddhist monasteries (17th century)</li><li>Spring Mani Rimdu festival — more intimate than Tengboche's autumn version</li><li>Birthplace valley of Tenzing Norgay, first summiteer of Everest</li><li>Traditional Thame village life largely unchanged by tourism</li><li>Gateway to Nangpa La — historic Tibet trade route and advanced climbing objective</li></ul>`,
    district: "Solukhumbu",
    province: "KOSHI",
    lat: 27.8319,
    lng: 86.6505,
    elevation: 3800,
    entryFee: "Small monastery donation expected (NPR 200\u2013500); Sagarmatha National Park entry applies",
    bestSeason: "March\u2013May (spring Mani Rimdu) and October\u2013November",
    openingHours: "Monastery typically open during daylight hours; confirm with local caretaker",
    howToGetThere: "From Namche Bazaar, the trail to Thame heads west along the Bhote Koshi valley. The walk from Namche to Thame takes approximately 3.5\u20134 hours (about 10 km). The monastery is a short steep climb above Thame village. Can be done as an overnight trip from Namche or as a long acclimatisation day walk.",
    gygQuery: "Thame Monastery Sherpa valley Namche hike Khumbu",
    bookingCity: "Kathmandu",
    seoTitle: "Thame Monastery | Ancient Nyingma Gompa in Khumbu's Hidden Valley",
    seoDescription: "Visit Thame Monastery \u2014 one of Khumbu's oldest Nyingma Buddhist monasteries, birthplace valley of Tenzing Norgay, and site of the spring Mani Rimdu festival. How to trek there from Namche Bazaar.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Sagarmatha National Park",
    category: "NATIONAL_PARK",
    summary: "Sagarmatha National Park is Nepal's first national park and a UNESCO World Heritage Site, covering 1,148 km\u00b2 of the Solukhumbu District at elevations from 2,845 m to 8,848 m (the summit of Mount Everest). Established in 1976 and inscribed as a World Heritage Site in 1979, the park protects extraordinary high-altitude ecosystems, glaciers, and biodiversity alongside the world's most iconic mountain landscape. It is home to the Sherpa people, the Khumbu Glacier, and rare wildlife including snow leopard, red panda, and Himalayan thar.",
    story: `<p>Sagarmatha National Park takes its name from the Nepali word for Mount Everest — Sagarmatha, meaning 'Goddess of the Sky' or 'Forehead of the Ocean of the Universe.' The park was established in 1976 to protect the extraordinary natural and cultural landscape of the Khumbu region from the growing pressures of mountaineering expeditions and tourism that had accelerated after the first Everest ascent in 1953. New Zealand mountaineer Sir Edmund Hillary played a key role in lobbying for the park's creation and in developing the infrastructure that would allow it to be managed sustainably. In 1979, UNESCO recognised the park as a Natural World Heritage Site — one of the first in Asia — in acknowledgement of its outstanding universal value.</p><p>The park encompasses an elevation range of more than 6,000 vertical metres, from the subtropical forests of Monjo at 2,845 m — where birch, rhododendron, and blue pine dominate — through alpine meadows and high-altitude scrub to permanent ice and the barren rock of the world's highest peaks. This vertical range supports extraordinary biodiversity: 118 bird species, 28 mammal species, and numerous plant communities have been recorded. The snow leopard, one of the world's most elusive large cats, inhabits the upper reaches along with wolves, Himalayan thar, ghoral, and musk deer. Himalayan griffon vultures and lammergeiers soar on thermals above the valleys, while forests are enlivened by colourful pheasants and laughingthrushes.</p><p>The Sherpa people have lived within what is now the park boundary for at least five centuries, and the park's management recognises their traditional rights to continue farming, herding, and practising their Buddhist faith within its boundaries. This coexistence of indigenous community and protected wilderness is one of Sagarmatha's distinguishing characteristics globally. The park's challenges include managing the environmental impact of the approximately 50,000 trekkers who pass through annually — trail erosion, waste management on the mountain itself, and the pressure of development on fragile alpine ecosystems are ongoing management priorities. Despite these pressures, the park remains one of the most spectacular protected areas on earth.</p><ul><li>Mount Everest (8,848 m) — highest point on Earth within the park</li><li>UNESCO Natural World Heritage Site since 1979</li><li>Snow leopard, red panda, Himalayan thar, and 118 bird species</li><li>Khumbu Glacier — one of the world's great glaciers</li><li>Sherpa culture and traditional Tibetan Buddhist monasteries</li><li>Ngozumpa Glacier — Nepal's largest glacier</li></ul>`,
    district: "Solukhumbu",
    province: "KOSHI",
    lat: 27.9333,
    lng: 86.7333,
    elevation: 2845,
    entryFee: "NPR 3,000 per person (foreigners); NPR 1,500 (SAARC nationals); NPR 100 (Nepali citizens)",
    bestSeason: "October\u2013November and March\u2013May",
    openingHours: "Park open year-round; entry permitted at checkposts along main trail routes",
    howToGetThere: "Enter the park at the Monjo checkpost \u2014 reached by trekking 2 days from Lukla airport via Phakding. Fly to Lukla from Kathmandu (35 min) to access the park's main entry point. Helicopter charters from Kathmandu to Namche Bazaar or higher destinations within the park are also available.",
    gygQuery: "Sagarmatha National Park Everest UNESCO Khumbu trek",
    bookingCity: "Kathmandu",
    seoTitle: "Sagarmatha National Park | UNESCO Everest Region Nepal Complete Guide",
    seoDescription: "Explore Sagarmatha National Park \u2014 Nepal's first UNESCO World Heritage Site protecting Mount Everest, Khumbu Glacier, snow leopards, and Sherpa culture. Entry fees, highlights, and visitor guide.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Kala Patthar",
    category: "HILL_VIEWPOINT",
    summary: "Kala Patthar (5,643 m) is the definitive viewpoint for a close-up panoramic view of Mount Everest, offering an unobstructed sightline to the world's highest peak that is actually superior to the view from Everest Base Camp itself. The 'Black Rock' \u2014 named for its dark schist summit \u2014 sits on the southern ridge of Pumori and is reached by a steep 1.5\u20132 hour ascent from Gorakshep. Most trekkers make the ascent before dawn to witness the spectacular sunrise turning Everest's icy summit pyramid from grey to gold.",
    story: `<p>There is an important distinction between reaching Everest Base Camp and actually seeing Everest. At Base Camp, the mountain's summit is largely hidden behind the bulk of Nuptse and the folds of the Khumbu Icefall — you are so close to the mountain that you can only see its flanks, not its top. For the definitive view of Everest, trekkers must make the additional effort of climbing Kala Patthar, the dark rocky hill that rises above Gorakshep on the ridge connecting the valley to the flanks of Pumori. From Kala Patthar's summit at 5,643 m, Everest is visible in its full pyramidal glory, from the South Col to the Hillary Step to the very summit snow plume.</p><p>The ascent of Kala Patthar typically begins in the darkness of 4–5 AM, trekkers filing upward by headlamp through the bitter cold of Gorakshep nights — temperatures regularly drop below -15°C at this elevation. The trail is steep and the altitude punishing for anyone not yet well acclimatised, but there are no technical sections and no equipment beyond warm layers is required. The summit itself is marked by a forest of prayer flags and crowded in season with trekkers jostling for the unobstructed Everest shot. As the first rays of sunrise catch the summit pyramid, the mountain appears to glow from within — a deeply moving spectacle that, combined with the physical achievement of standing above 5,600 m, produces the emotional centrepiece of the entire EBC trek.</p><p>Beyond Everest, the Kala Patthar panorama encompasses Lhotse (the world's fourth-highest peak), Nuptse, Changtse, and the glacially sculpted ridgeline of Pumori rising immediately to the north. On clear days, Makalu's distinctive four-sided pyramid and the outline of Cho Oyu are also visible to the southeast and northwest respectively. The view is incomparably complete — a gathering of the world's greatest peaks in a single sweep of the horizon that no photograph fully captures. Most trekkers descend to Gorakshep after sunrise, have breakfast, and then continue to Everest Base Camp for the afternoon before beginning the return to Lukla.</p><ul><li>Best close-up view of Mt Everest summit from 5,643 m</li><li>Sunrise spectacle — Everest's summit pyramid glowing gold at dawn</li><li>Panorama includes Lhotse, Nuptse, Pumori, Changtse, and Makalu</li><li>No technical climbing equipment required — trekking peak</li><li>Prayer flag summit and iconic photo opportunity</li></ul>`,
    district: "Solukhumbu",
    province: "KOSHI",
    lat: 27.9958,
    lng: 86.8284,
    elevation: 5643,
    entryFee: "Included within Sagarmatha National Park entry (NPR 3,000)",
    bestSeason: "October\u2013November and March\u2013May",
    openingHours: "Accessible year-round during trekking season; ascent typically begins at 4\u20135 AM for sunrise",
    howToGetThere: "Kala Patthar is reached by trekking to Gorakshep (5,164 m) \u2014 approximately 12\u201314 days from Lukla via the classic EBC route through Namche, Tengboche, Dingboche, and Lobuche. From Gorakshep, the ascent to Kala Patthar summit takes 1.5\u20132 hours on a steep but non-technical trail.",
    gygQuery: "Kala Patthar viewpoint Everest sunrise trek Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Kala Patthar Viewpoint | Best Everest View at 5,643 m Nepal",
    seoDescription: "Reach Kala Patthar (5,643 m) for the best panoramic view of Mt Everest in Nepal. Sunrise experience, trail guide from Gorakshep, elevation profile, and tips for the iconic EBC trek viewpoint.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Mera Peak",
    category: "TREK_ROUTE",
    summary: "Mera Peak (6,476 m) is the highest trekking peak in Nepal and offers non-technical climbers their best opportunity to stand above 6,000 m with a relatively straightforward high camp and summit push via a glacier route. Located in the remote Hinku Valley of Solukhumbu, the approach trek through wild forested valleys and high passes is itself a superb wilderness journey. On a clear summit day, five of the world's fourteen 8,000 m peaks are visible from the top.",
    story: `<p>Mera Peak's appeal lies in the combination of genuine high-altitude achievement with a technically accessible route — a rare pairing that makes it the most popular trekking peak in Nepal despite (or because of) its considerable height. At 6,476 m, Mera is higher than any mountain in the Alps, Andes, or Rocky Mountains, yet its normal route to the summit involves no more than basic crampon and ice axe technique on moderate glaciated slopes. This accessibility, combined with the extraordinary remoteness and beauty of the Hinku Valley approach, makes a Mera expedition one of the most satisfying mountain adventures available to non-technical climbers anywhere in the world.</p><p>The approach to Mera begins from Lukla, but almost immediately diverges from the standard EBC and Gokyo trails, heading south and east into the Hinku Valley — a wild, rarely visited drainage system of dense rhododendron and birch forest, river crossings, and high lateral ridges. The high camp on the Mera La glacier (approximately 5,800 m) is reached after 7–9 days of trekking, and from here the summit push follows a broad glaciated ridge to the three summits of Mera (Mera North 6,476 m, Mera Central 6,461 m, and Mera South 6,065 m). The summit day typically begins before midnight — a headlamp procession of clients and guides ascending through the darkness to catch the dawn panorama from the summit ridge.</p><p>From Mera Peak's summit on a clear day, the view is genuinely extraordinary — five 8,000 m peaks arranged across the horizon: Everest, Lhotse, Makalu, Cho Oyu, and Kanchenjunga. This five-8000m panorama is one of the finest high-altitude views accessible to non-mountaineers anywhere in the world. Mera Peak expeditions typically take 16–20 days in total and require standard trekking fitness plus willingness to use ice axe and crampons. A technical briefing and equipment rental is easily arranged in Kathmandu, and many agencies offer fully-guided expeditions with all logistics included.</p><ul><li>Nepal's highest trekking peak at 6,476 m with non-technical summit route</li><li>Five 8,000 m peaks visible from the summit (Everest, Lhotse, Makalu, Cho Oyu, Kanchenjunga)</li><li>Wild Hinku Valley approach through remote rhododendron forest</li><li>Mera La high camp on the glacier at approximately 5,800 m</li><li>Most popular trekking peak in Nepal — well-supported infrastructure</li></ul>`,
    district: "Solukhumbu",
    province: "KOSHI",
    lat: 27.7092,
    lng: 86.8683,
    elevation: 6476,
    entryFee: "Trekking Peak climbing permit USD 125 per person (Nepal Mountaineering Association) + Sagarmatha National Park entry NPR 3,000",
    bestSeason: "October\u2013November and April\u2013May",
    openingHours: "Summit accessible weather permitting; avoid monsoon and winter",
    howToGetThere: "Fly Kathmandu to Lukla (35 min), then trek south and east into the Hinku Valley via Chutanga and the Zatrwa La pass (4,610 m). The Mera Base Camp and high camp are reached after approximately 7\u20139 days from Lukla. Full expedition typically 16\u201320 days total. Guides and equipment rental best arranged in Kathmandu.",
    trekDays: 18,
    trekMaxElevation: 6476,
    trekDifficulty: "HARD",
    trekDistance: 80,
    trekStartPoint: "Lukla (2,840 m)",
    trekEndPoint: "Lukla (2,840 m)",
    trekHighlights: ["Summit of Mera Peak at 6,476 m \u2014 Nepal's highest trekking peak", "Five 8,000 m peaks visible from summit", "Remote Hinku Valley wilderness approach", "Zatrwa La pass (4,610 m) with Khumbu panorama", "Mera La high camp glacier experience", "Genuine high-altitude mountaineering without technical rock climbing"],
    gygQuery: "Mera Peak climbing expedition Nepal Solukhumbu",
    bookingCity: "Kathmandu",
    seoTitle: "Mera Peak (6,476 m) | Nepal's Highest Trekking Peak Climbing Guide",
    seoDescription: "Climb Mera Peak (6,476 m), Nepal's highest trekking peak \u2014 non-technical glacier route, five 8,000 m peak views, remote Hinku Valley approach. Permits, itinerary, difficulty, and gear guide.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Island Peak (Imja Tse)",
    category: "TREK_ROUTE",
    summary: "Island Peak (Imja Tse, 6,189 m) is one of Nepal's most popular trekking peaks, named in 1953 by the British Everest expedition for its appearance as an island surrounded by glaciers when viewed from Dingboche. Located above Chukung in the shadow of Lhotse's massive south face, the climb combines a superb high-altitude approach through the heart of the Khumbu with a genuine mountaineering challenge on a glaciated summit ridge. It is commonly combined with the Everest Base Camp trek.",
    story: `<p>Island Peak was christened by the 1953 British Everest expedition — from their vantage point at Dingboche, the peak's dark rocky mass appeared to float as an island in a sea of surrounding glaciers, a visual impression that remains accurate today. The mountain's technical name, Imja Tse, references the Imja River that drains the valley below. Situated just north of the growing Imja Glacial Lake (one of the world's most closely monitored glacial lakes for outburst flood risk) and beneath the towering south face of Lhotse (8,516 m), Island Peak occupies some of the most dramatic glacial topography in the Khumbu.</p><p>The approach to Island Peak from Lukla typically takes 10–12 days, following the classic EBC route through Namche, Tengboche, and Dingboche before branching east to Chukung (4,730 m). From Chukung, a further half-day walk reaches Island Peak Base Camp (5,100 m) and high camp (5,600 m). The summit push involves a predawn start, crossing a broad glacier and navigating a fixed-rope section on the final 55-degree ice headwall below the summit ridge. This headwall — the crux of the route — requires competent crampon technique and comfort with exposure but is within the reach of most physically fit and mentally determined trekkers who have spent adequate time acclimatising.</p><p>From the summit ridge at 6,189 m, the view is breathtaking — Lhotse's enormous south face fills the northern sky, while Makalu, Baruntse, Ama Dablam, and the Khumbu ranges extend in every direction. The summit is a narrow ice ridge with significant drops on either side, requiring care but offering a magnificent high-altitude experience that few non-mountaineers ever attain. Island Peak is frequently combined with an EBC trek to create a comprehensive 20-day Khumbu adventure that includes Base Camp, Kala Patthar, and a genuine summit above 6,000 m — a package that represents one of the finest mountain journeys available anywhere in the world.</p><ul><li>Summit at 6,189 m with views of Lhotse, Makalu, Ama Dablam, and Baruntse</li><li>Technical ice headwall (55 degrees) on approach to summit ridge</li><li>Spectacular high-altitude glacial approach from Chukung</li><li>Imja Lake — one of the world's most closely monitored glacial lakes</li><li>Commonly combined with EBC trek for ultimate 20-day Khumbu experience</li></ul>`,
    district: "Solukhumbu",
    province: "KOSHI",
    lat: 27.9242,
    lng: 86.9373,
    elevation: 6189,
    entryFee: "Trekking Peak climbing permit USD 125 per person (Nepal Mountaineering Association) + Sagarmatha National Park entry NPR 3,000",
    bestSeason: "October\u2013November and April\u2013May",
    openingHours: "Summit accessible weather permitting; avoid monsoon",
    howToGetThere: "Fly Kathmandu to Lukla (35 min), then follow the EBC trail through Namche and Dingboche to Chukung (approximately 10 days). From Chukung, Island Peak Base Camp is a half-day walk east. Guides, crampons, ice axes, and harnesses are essential \u2014 equipment rental available in Namche and Kathmandu. Full expedition typically 18\u201322 days.",
    trekDays: 20,
    trekMaxElevation: 6189,
    trekDifficulty: "HARD",
    trekDistance: 85,
    trekStartPoint: "Lukla (2,840 m)",
    trekEndPoint: "Lukla (2,840 m)",
    trekHighlights: ["Island Peak summit at 6,189 m with Lhotse south face views", "Technical ice headwall on the summit approach", "Chukung valley and Imja Lake glacial scenery", "Ama Dablam, Makalu, and Baruntse panorama from summit", "Combines perfectly with EBC and Kala Patthar for complete Khumbu experience", "One of Nepal's most popular and achievable 6,000 m peaks"],
    gygQuery: "Island Peak Imja Tse climbing Nepal Everest region",
    bookingCity: "Kathmandu",
    seoTitle: "Island Peak (Imja Tse 6,189 m) | Climbing Guide Nepal Khumbu",
    seoDescription: "Complete guide to climbing Island Peak (Imja Tse, 6,189 m) in Nepal's Khumbu region \u2014 route, difficulty, permits, gear, and how to combine it with the Everest Base Camp trek.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Kathesimbu Stupa",
    category: "STUPA",
    summary: "Kathesimbu Stupa is the most important Buddhist shrine in the Thamel district of Kathmandu, a 17th-century chaitya built as a replica of the sacred Swayambhunath Stupa to serve those unable to make the pilgrimage to the hilltop original. Set within a courtyard surrounded by smaller chaityas, votive offerings, and an ancient monastery, it is a living place of daily worship for local Newari Buddhists and a serene refuge from the busy lanes of Thamel just metres away. The name means 'Kathmandu Swayambhunath' in Newari.",
    story: `<p>Kathesimbu Stupa was built around 1650, during the height of the Malla dynasty's patronage of Buddhist architecture throughout the Kathmandu Valley. According to local tradition, the stupa was constructed from the leftover materials used in the renovation of Swayambhunath Stupa — a story that gives Kathesimbu a direct material connection to one of the most sacred sites in Vajrayana Buddhism. Its primary purpose was charitable and practical: the steep climb to Swayambhunath on its hilltop was difficult for the elderly, the infirm, and mothers with young children, so Kathesimbu was established as a proximate substitute where the same merit could be accumulated by a simple walk through the lanes of central Kathmandu. The all-seeing eyes of the Buddha, characteristic of Newari stupa design, are painted on the four faces of the harmika above the dome.</p><p>The stupa is technically classified as a monumental chaitya rather than a stupa — a distinction in Nepali Buddhist architecture relating to its form and the nature of the relics enshrined within it. It stands within a closed courtyard approached through narrow lanes south of Thamel, surrounded by a fascinating collection of smaller votive chaityas, ancient stone sculptures, metal relief panels, and inscriptions in Sanskrit and Newari scripts. The adjacent monastery, Sighahbaha, adds to the atmosphere of the complex and is home to a small community of monks and nuns who conduct daily rituals throughout the day. The courtyard functions as a neighbourhood gathering place — elderly women circling the stupa with prayer beads, children playing, monks engaged in quiet conversation.</p><p>For travellers staying in Thamel, Kathesimbu offers an easily overlooked but deeply rewarding pocket of authentic religious life amid the tourist commercial noise of the surrounding streets. The stupa is particularly animated in the early morning, when devotees begin their circumambulations before the shops open, and in the evening when butter lamps are lit at the niches surrounding the dome. It has survived multiple earthquakes, including the major 2015 Gorkha earthquake, with relatively minor damage — a testament to the skill of the medieval builders and the quality of the subsequent restorations. The stupa occupies a significant position in the Kathmandu Valley's Buddhist sacred geography, forming part of a network of shrines that together map the mandala of the valley floor.</p><ul><li>17th-century chaitya — replica of sacred Swayambhunath built from surplus materials</li><li>Living place of daily Newari Buddhist worship in central Thamel</li><li>Surrounding courtyard with ancient chaityas, stone sculptures, and inscriptions</li><li>Adjacent Sighahbaha monastery with resident monks and nuns</li><li>Serene refuge from the bustle of Thamel, just metres from tourist streets</li></ul>`,
    district: "Kathmandu",
    province: "BAGMATI",
    lat: 27.7152,
    lng: 85.3123,
    elevation: 1310,
    entryFee: "Free (donations welcome)",
    bestSeason: "Year-round; most animated during Buddhist festivals (Losar, Buddha Jayanti)",
    openingHours: "Courtyard accessible daily from approximately 5:00 AM \u2013 9:00 PM",
    howToGetThere: "The stupa is located in the Chhetrapati area south of Thamel, approximately a 5\u201310 minute walk from most Thamel hotels. Head south from Thamel toward Chhetrapati Square \u2014 the stupa's courtyard entrance is signposted off the main lane. No vehicle access required.",
    gygQuery: "Kathesimbu Stupa Thamel Kathmandu Buddhist temple visit",
    bookingCity: "Kathmandu",
    seoTitle: "Kathesimbu Stupa Thamel | Kathmandu's Hidden Buddhist Shrine Guide",
    seoDescription: "Visit Kathesimbu Stupa in Thamel, Kathmandu \u2014 a beautiful 17th-century Buddhist chaitya, replica of Swayambhunath, with daily worship and peaceful courtyard. History, visiting tips, and location.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Dharan Bazaar",
    category: "CULTURAL_VILLAGE",
    summary: "Dharan is a vibrant and historically significant city in the Sunsari District of eastern Nepal, sitting at the junction of the Mahabharat foothills and the Terai plains at an elevation of approximately 350 m. Known as the gateway to the eastern hills and a melting pot of Limbu, Rai, Brahmin, Chhetri, and Madhesi cultures, Dharan is famed for its clean streets, garden-like ambience, retired Gurkha soldier communities, and proximity to important temples including Budhasubba and Dantakali. It was historically the capital of the ancient Morang Kingdom and remains a major commercial hub of eastern Nepal.",
    story: `<p>Dharan occupies a unique geographical and cultural position in Nepal's eastern landscape. Built on the gently sloping piedmont where the Mahabharat foothills begin to rise from the flat expanses of the Terai, the city enjoys a cooler and more pleasant climate than the lowland cities of the Terai while remaining well-connected to the plains highway network. This transitional position made Dharan a natural entrepôt throughout its history — hill communities bringing their agricultural surpluses and forest products down to trade with the Madhesi merchants of the Terai, and manufactured goods flowing upward toward the remote hill settlements of Dhankuta, Taplejung, and beyond. The ancient trade route from the plains to the eastern hills passed through what is now Dharan's central bazaar.</p><p>The city's modern character was significantly shaped by its role as the recruiting and pension centre for British Gurkha soldiers. Britain's Brigade of Gurkhas maintained a substantial presence in Dharan for decades until the camp's closure in the 1990s, and the influence remains visible in the city's well-organised layout, relatively high standard of civic infrastructure, and the significant community of retired soldiers and their families who chose to settle here with their British army pensions. This Gurkha connection brought a cosmopolitan flavour to what might otherwise have been a provincial market town, and today Dharan is considered one of eastern Nepal's most liveable and pleasant cities, with a reputation for cleanliness and civic pride unusual in Nepal's urban hierarchy.</p><p>Culturally, Dharan is extraordinarily rich in its diversity. The city's Limbu and Rai communities maintain their indigenous Kirat traditions, festivals, and sacred sites — most notably the Budhasubba Temple, which is the tomb of the last Limbu king and a powerful place of worship for the Kirat people. The Dantakali Shakti temple, the Pindeshwar Mahadev complex, and the Vijayapur Hill temples add Hindu sacred geography to the mix. The city is also increasingly recognised as a base for exploring the biodiversity of Barun National Park and the cultural landscapes of Ilam, Taplejung, and the eastern Himalayan foothills. Dharan's Bhanuvabhakta Chowk and its evening promenade culture give it an agreeable, small-city vitality that makes it one of Nepal's most enjoyable urban stops.</p><ul><li>Gateway to eastern Himalayan treks and Kangchenjunga Base Camp route</li><li>Limbu and Kirat indigenous culture and the Budhasubba sacred site</li><li>British Gurkha heritage shaping city character and infrastructure</li><li>Dantakali Shakti Peeth — powerful Goddess temple pilgrimage</li><li>Pleasant climate, clean streets, and excellent local food scene</li></ul>`,
    district: "Sunsari",
    province: "KOSHI",
    lat: 26.7944,
    lng: 87.2818,
    elevation: 350,
    entryFee: "Free city; individual temple entry donations apply",
    bestSeason: "October\u2013March (avoid peak monsoon June\u2013August)",
    openingHours: "City open year-round; bazaar most active during daylight hours",
    howToGetThere: "From Kathmandu, take a flight to Biratnagar airport (50 min, then 1 hour by road to Dharan) or take an overnight bus (12\u201314 hours). From Biratnagar, frequent local buses and taxis connect to Dharan. The city is also reachable by bus from Itahari on the East\u2013West Highway (30 min). Dharan is 5 hours east of Janakpur by road.",
    gygQuery: "Dharan city temple tour eastern Nepal day trip",
    bookingCity: "Kathmandu",
    seoTitle: "Dharan Bazaar | Eastern Nepal's Cultural Gateway City Guide",
    seoDescription: "Explore Dharan Bazaar in eastern Nepal \u2014 Limbu culture, Gurkha heritage, Budhasubba and Dantakali temples, and gateway to eastern Himalayan treks. Complete travel guide to Dharan, Sunsari.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Budhasubba Temple Dharan",
    category: "TEMPLE",
    summary: "Budhasubba Temple in Dharan is one of eastern Nepal's most revered and culturally complex sacred sites, believed by the indigenous Limbu (Kirat) people to be the burial place of their last king, Buddhi Karna Raya Khebang Limbu, killed in 1773 during Prithvi Narayan Shah's conquest of Limbuwan. Hindus simultaneously worship the site as a manifestation of Lord Shiva and Parvati, making it a remarkable example of syncretic sacred geography. The temple complex is surrounded by Nepal's only known stand of tipless bamboo and sits above Dharan at approximately 445 m elevation.",
    story: `<p>The Budhasubba Temple is a place where mythology, history, and living faith intersect in a uniquely eastern Nepali manner. The site's name breaks down as 'Budha' (old, or the name of the king) and 'Subba' or 'Haang' — the Limbu language title for 'king.' According to Kirat historian Iman Singh Chemjong and Limbu oral tradition, the temple marks the burial site of Buddhi Karna Raya Khebang Limbu, the last independent king of Limbuwan, who was lured to the Bijaypur area of Dharan by emissaries of Prithvi Narayan Shah and assassinated in 1773 — the same year the Shah king completed his unification of Nepal. The Limbu people began to venerate the king's spirit as a protective deity, and the site became a powerful place of supplication where requests for health, prosperity, and justice could be made to the spirit of a wronged king.</p><p>The syncretic overlay of Hinduism onto the site is typical of how Nepal's dominant religious traditions have historically absorbed and reinterpreted indigenous sacred spaces. Hindu worshippers understand the main deity of Budhasubba as a manifestation of Lord Shiva — in the hunting form of Thebasamang — accompanied by Parvati in the form of Yumasammang. This dual interpretation means the temple attracts worshippers from both communities simultaneously, and festival days bring Limbu community elders conducting Kirat rituals alongside Hindu priests performing Vedic ceremonies — a remarkably peaceful coexistence that reflects the depth of Dharan's cultural integration. The Limbu title 'Kewasumang' is also used for the deity, representing the idea of a great king who protects his people from the afterlife.</p><p>The physical setting of Budhasubba is remarkable. The temple is surrounded by a grove of a rare variant of bamboo — Dendrocalamus species characterised by the absence of the usual pointed tips on their culms — that is found nowhere else in Nepal and is considered sacred and inviolable by the local community. The grove is under pressure from urban encroachment, and conservationists have raised concerns about infrastructure development threatening it. Worshippers circumambulate the temple complex, tie red threads to bamboo stalks as prayers, and bring coconuts, flowers, and alcohol (traditional Kirat offering) to the shrine. The site is particularly animated during Sakela, the Kirat spring and autumn festival, and during the Limbu New Year celebrations.</p><ul><li>Burial site of the last Limbu king — sacred to the indigenous Kirat community</li><li>Syncretic worship by both Limbu (Kirat) and Hindu communities simultaneously</li><li>Rare grove of tipless bamboo (Dendrocalamus sp.) — found nowhere else in Nepal</li><li>Sakela and Limbu festival ceremonies held at the site</li><li>Important archaeological and cultural heritage site of eastern Nepal</li></ul>`,
    district: "Sunsari",
    province: "KOSHI",
    lat: 26.8203,
    lng: 87.2967,
    elevation: 445,
    entryFee: "Free (donations welcome)",
    bestSeason: "Year-round; Sakela festival (spring/autumn) most vibrant",
    openingHours: "Temple open daily approximately 5:00 AM \u2013 8:00 PM",
    howToGetThere: "Located in the upper area of Dharan city, approximately 3 km from the city centre bus park. Accessible by auto-rickshaw, tempo, or taxi from central Dharan (10\u201315 minutes). From Biratnagar, take a bus or taxi to Dharan (1 hour) and then local transport to the temple.",
    gygQuery: "Budhasubba Temple Dharan Limbu cultural heritage Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Budhasubba Temple Dharan | Sacred Limbu Heritage Site Eastern Nepal",
    seoDescription: "Visit Budhasubba Temple in Dharan, eastern Nepal \u2014 the sacred tomb of the last Limbu king, a place of syncretic Hindu-Kirat worship surrounded by rare bamboo groves. History, visiting guide, and cultural significance.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Dantakali Temple Dharan",
    category: "TEMPLE",
    summary: "Dantakali Temple in Dharan is one of the most powerful Shakti Peeths of eastern Nepal, believed to mark the spot where the sacred teeth of the goddess Satidevi (Parvati) fell when Shiva carried her body across the subcontinent after her self-immolation. The temple sits on Vijayapur Hill above Dharan at approximately 450 m and houses nine sacred teeth enclosed in silver \u2014 a rare and potent relic that draws thousands of pilgrims annually. The temple complex offers sweeping views of the Sunsari plains and the Koshi River valley.",
    story: `<p>The mythology of Dantakali Temple belongs to the great narrative cycle of Sati — the first wife of Lord Shiva, who immolated herself in protest at her father Daksha's insulting exclusion of Shiva from a great yajna (sacrificial ceremony). Grief-stricken, Shiva wandered the cosmos carrying Sati's body on his shoulder, his sorrow so intense that the universe was threatened by his anguish. To restore balance, Vishnu intervened by using his Sudarshana Chakra (divine discus) to cut Sati's body into pieces as Shiva carried it, so that he was gradually relieved of his burden. Each spot where a body part fell became a Shakti Peetha — a supremely powerful sacred site of the goddess — and the Dantakali site is where her teeth (danta) are said to have landed, giving the temple its name.</p><p>The temple structure at Dharan houses nine teeth in a silver-covered box within its sanctum, making it a genuinely unusual Shakti Peetha — most such sites mark the fall of a single body part, and the presence of nine teeth makes Dantakali particularly potent in the devotional geography of the goddess tradition. The temple has been built in the gumba (dome) style, with a copper gajur (pinnacle ornament) crowning the roof — a form that reflects the mixed Hindu-Buddhist architectural influences characteristic of the eastern Himalayan foothills. The inner sanctum is tended by priests who conduct regular pujas throughout the day, and the air inside is thick with incense, camphor smoke, and the sound of devotional bells.</p><p>The setting of Dantakali on Vijayapur Hill gives it considerable strategic and visual importance in Dharan's sacred landscape. From the temple platform, the view extends southward across the broad floodplain of the Koshi River valley to the Terai and in good visibility to the Indian border — a panorama that puts Dharan's geographical position as the junction of hills and plains into dramatic physical perspective. The path up to the temple passes through a neighbourhood of smaller temples, shrines, and pilgrims' rest houses, creating a complete sacred precinct on the hillside. Major festivals, including the Dashain celebrations in autumn, bring enormous crowds to Dantakali for animal sacrifices and collective worship, transforming the normally peaceful hillside temple into one of eastern Nepal's great festival spectacles.</p><ul><li>Major Shakti Peeth housing nine sacred teeth of goddess Sati</li><li>Panoramic views of the Koshi floodplain and Terai from the temple hilltop</li><li>Gumba-style architecture with copper gajur pinnacle</li><li>Dashain festival brings massive pilgrimage gatherings</li><li>Part of Vijayapur Hill's cluster of sacred temples above Dharan</li></ul>`,
    district: "Sunsari",
    province: "KOSHI",
    lat: 26.8197,
    lng: 87.2868,
    elevation: 450,
    entryFee: "Free (donations welcome; small fee during major festivals)",
    bestSeason: "Year-round; most vibrant during Dashain (October) and Navaratri",
    openingHours: "Temple open daily approximately 5:00 AM \u2013 8:00 PM",
    howToGetThere: "Located on Vijayapur Hill above central Dharan, approximately 3 km from the city centre. Accessible by auto-rickshaw, taxi, or on foot via the temple road that winds up the hillside from central Dharan (30\u201340 minute walk from city centre). The temple is close to Budhasubba Temple and can be visited in a single hilltop walking tour.",
    gygQuery: "Dantakali Temple Dharan Shakti Peeth eastern Nepal pilgrimage",
    bookingCity: "Kathmandu",
    seoTitle: "Dantakali Temple Dharan | Powerful Shakti Peeth of Eastern Nepal",
    seoDescription: "Visit Dantakali Temple in Dharan, eastern Nepal \u2014 a powerful Shakti Peeth housing the sacred teeth of goddess Sati, with panoramic Terai plains views. History, mythology, visiting guide, and festivals.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Vijayapur Hill Dharan",
    category: "HILL_VIEWPOINT",
    summary: "Vijayapur Hill is the prominent ridge above Dharan city in Sunsari district, a historically significant hilltop that was the capital of the ancient Morang Kingdom of Limbuwan and today hosts a cluster of major temples \u2014 Dantakali, Budhasubba, Pindeshwar, and Panchakanya \u2014 amid a pleasant park and walking environment. From the hilltop, sweeping views extend across the Sunsari plains, the Koshi River basin, and on clear days toward the Himalayan foothills to the north. The hill is Dharan's most popular leisure destination and a significant pilgrimage site.",
    story: `<p>Vijayapur Hill's strategic importance in the eastern Himalayan foothills has been recognised for centuries. From 1584 to 1774 AD, the hilltop settlement of Bijaypur served as the capital of the Morang Kingdom, one of the Limbu (Kirat) kingdoms of Limbuwan — the broad territory of the eastern Himalayan foothills inhabited by the Limbu people. The kingdom's control of the trade routes between the Terai plains and the high hill settlements of Taplejung, Dhankuta, and beyond gave Bijaypur considerable strategic and commercial significance. The ruins and sacred sites of this ancient capital are scattered across the hill, and the major temples that now occupy the ridge are built on sites that have been sacred to the Limbu people for far longer than their current Hindu-era structures suggest.</p><p>Today, Vijayapur Hill functions simultaneously as a religious pilgrimage circuit, a civic park, and a popular viewpoint for Dharan's residents. The main approach road winds up the hillside from the city centre past increasing numbers of tea shops, stone-paved paths, and occasional roadside shrines. At the summit area, the four main temples — Dantakali Shakti Peeth, Budhasubba, Pindeshwar Mahadev, and Panchakanya — are connected by paths through a pleasant green environment of pine and broadleaf trees that feels refreshingly cool compared to the city below. Local families, young couples, and school groups use the hill as a recreational destination, creating an unusually inclusive and lively atmosphere for a pilgrimage site.</p><p>The views from Vijayapur Hill are genuinely impressive by any standard. Southward, the floodplain of the Sunsari district stretches flat and green toward the Koshi River and the distant Terai — a vast agricultural canvas punctuated by towns and the silver thread of canals. Eastward, the hills of Dhankuta district rise steeply from the valley of the Tamur River, and on very clear mornings after fresh rains, the outline of the Himalayan foothills to the north becomes visible above the haze. The hill's dual role as a sacred and recreational space makes it one of the most authentic cross-sections of contemporary Nepali life accessible to travellers — here you see the full spectrum of Dharan's population in a single morning walk.</p><ul><li>Panoramic views over Sunsari plains, Koshi valley, and Terai from the ridgeline</li><li>Four major temples in one hilltop walking circuit</li><li>Historical capital of the ancient Morang Kingdom of Limbuwan</li><li>Popular recreation destination for Dharan residents — authentic local atmosphere</li><li>Cool forested environment above the city heat</li></ul>`,
    district: "Sunsari",
    province: "KOSHI",
    lat: 26.822,
    lng: 87.2883,
    elevation: 500,
    entryFee: "Free public access (individual temple donations apply)",
    bestSeason: "October\u2013March (pleasant weather; avoid peak monsoon heat and humidity)",
    openingHours: "Hill accessible year-round during daylight; temples open approximately 5:00 AM \u2013 8:00 PM",
    howToGetThere: "From Dharan city centre, the hill is approximately 3\u20134 km by road. Accessible by taxi, auto-rickshaw, or on foot (30\u201340 min uphill walk from the bazaar). The road to the top passes the lower entrance of Budhasubba and continues to Dantakali Temple at the summit area. Can be explored as a half-day walking circuit visiting all four main temples.",
    gygQuery: "Vijayapur Hill Dharan temple tour viewpoint eastern Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Vijayapur Hill Dharan | Hilltop Temples and Panoramic Views Eastern Nepal",
    seoDescription: "Explore Vijayapur Hill in Dharan, eastern Nepal \u2014 ancient Limbu kingdom capital, four major temples, and sweeping Sunsari plains panorama. Day trip guide and temple circuit walking tour.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
]

async function main() {
  console.log(`🌱 Seeding batch 5 — ${places.length} places...`)
  for (const p of places) {
    await prisma.place.upsert({
      where: { slug: slug(p.name) },
      update: {},
      create: { ...p, slug: slug(p.name) },
    })
    console.log(`  ✅ ${p.name}`)
  }
  console.log('🌱 Batch 5 complete!')
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())