import 'dotenv/config'
import { PrismaClient } from '@prisma/client'
import slugify from 'slugify'

const prisma = new PrismaClient()
const slug = (n) => slugify(n, { lower: true, strict: true })

const places = [
  {
    name: `Three Passes Trek`,
    category: "TREK_ROUTE",
    summary: `The ultimate Everest region challenge, the Three Passes Trek links the iconic Khumbu circuit by crossing Kongma La (5,535 m), Cho La (5,420 m), and Renjo La (5,360 m). Trekkers visit Everest Base Camp, the Gokyo Lakes, and remote Sherpa villages in one sweeping Himalayan odyssey that few other trails on earth can match.`,
    story: `<p>Few treks in the world carry the raw prestige of the Three Passes Trek. Winding through the heart of the Khumbu — Nepal's most celebrated high-altitude wilderness and a UNESCO World Heritage landscape — the route demands not only physical fitness but genuine mountain experience. The three passes it crosses are all above 5,300 metres, and each presents a distinctly different character: Kongma La, the highest and most remote, rewards tenacious climbers with a stunning ridge-walk above Chhukung Valley; Cho La forces trekkers across a heavily crevassed glacier where crampons are often necessary; and Renjo La, the most scenic of the three, opens onto a panorama of Everest, Lhotse, Makalu, and the sapphire expanse of the Gokyo Lakes below.</p><p>The standard itinerary of 17 to 22 days departs from Lukla and loops through Namche Bazaar — the commercial heart of Sherpa country — before branching into progressively wilder terrain. Acclimatisation days are built in at Namche and again at the Gokyo or Chhukung valleys, allowing trekkers to ascend to Gokyo Ri (5,357 m) or Kala Patthar (5,545 m) for sunrise views of Everest. The full circuit covers roughly 160 to 190 km of trail that passes through rhododendron forest, yak pastures, glacial moraines, and wind-scoured ridgelines.</p><p>Cultural richness runs throughout the journey. Ancient Buddhist monasteries at Tengboche and Thame punctuate the trail, their prayer flags snapping in the thin mountain air. Sherpa teahouses serve steaming dal bhat to weary trekkers, and yak caravans still ferry goods to high camps just as they have for centuries. The trek visits Everest Base Camp itself, where climbers prepare for ascents of the world's highest peak.</p><p>Spring (March to May) and autumn (September to November) offer the clearest skies and most stable conditions. Independent trekking is permitted with the required permits — a TIMS card and Sagarmatha National Park entry fee — though an experienced guide is strongly recommended given the technical terrain of Cho La and the remoteness of the Kongma La approach.</p>`,
    district: `Solukhumbu`,
    province: "KOSHI",
    lat: 27.9814,
    lng: 86.8522,
    elevation: 5535,
    entryFee: `NPR 3,000 Sagarmatha National Park entry; TIMS card required`,
    bestSeason: `March to May, September to November`,
    openingHours: `Open year-round (weather permitting)`,
    howToGetThere: `Fly Kathmandu to Lukla (35 min); trek begins from Lukla. Alternatively, drive to Salleri and trek to Lukla.`,
    trekDays: 19,
    trekDifficulty: "EXTREME",
    trekMaxElevation: 5535,
    trekDistance: 170,
    trekStartPoint: `Lukla`,
    trekEndPoint: `Lukla`,
    trekHighlights: [`Crossing Kongma La (5,535 m), the highest of the three passes`, `Glacier crossing on Cho La Pass (5,420 m)`, `Panoramic views from Renjo La over Gokyo Lakes and Everest`, `Visit to Everest Base Camp (5,364 m)`, `Sunrise from Kala Patthar (5,545 m)`, `Gokyo Lakes — a chain of glacial lakes above 4,700 m`, `Tengboche Monastery — one of Nepal's most revered Buddhist sites`],
    gygQuery: `Three Passes Trek Everest Khumbu Nepal`,
    bookingCity: `Kathmandu`,
    seoTitle: `Three Passes Trek Nepal | Kongma La, Cho La & Renjo La Guide`,
    seoDescription: `Conquer the Three Passes Trek in Nepal's Everest region — crossing Kongma La (5,535 m), Cho La, and Renjo La while visiting EBC and the Gokyo Lakes. Full guide, permits, best season and itinerary tips.`,
    published: true,
    featured: false,
  },
  {
    name: `Kanchenjunga Conservation Area`,
    category: "NATIONAL_PARK",
    summary: `Sprawling across 2,035 sq km of far-eastern Nepal, Kanchenjunga Conservation Area protects the flanks of the world's third-highest peak (8,586 m) and an extraordinary range of biodiversity from subtropical rainforest to permanent glaciers. Remote and pristine, it rewards adventurous trekkers with solitude, snow leopard habitat, and cultures untouched by mass tourism.`,
    story: `<p>At the far northeastern rim of Nepal, where the Himalaya curves into the border with Sikkim and Tibet, lies one of Asia's most spectacular and least-visited wilderness areas. The Kanchenjunga Conservation Area, established in 1997 and covering 2,035 sq km in Taplejung District, wraps around Kangchenjunga — a five-summited giant that the Sikkimese revere as the 'Five Treasures of Snow' and that Himalayan climbers regard as among the most technically demanding 8,000-metre peaks on earth.</p><p>The conservation area spans an extraordinary ecological gradient. At its lowest reaches, subtropical evergreen forest shelters red pandas, clouded leopards, and hundreds of bird species including the rare spiny babbler. Higher up, oak and rhododendron forest — ablaze with crimson and pink blossoms in April — gives way to alpine meadows where snow leopards hunt blue sheep across open slopes. Above the treeline, glaciers creep from the high snowfields, feeding rivers that eventually drain toward the Bay of Bengal.</p><p>Trekking in Kanchenjunga requires a restricted area permit and a licensed guide, keeping visitor numbers low and the experience genuinely wild. The classic circuit trek links the northern base camp at Pangpema (5,143 m) — a turquoise glacial lake beneath Kanchenjunga's north face — with the southern base camp at Oktang (4,730 m), where a sacred lake and panoramic glacier views await. The full circuit covers 200 to 220 km and typically takes 18 to 22 days from Taplejung.</p><p>The Limbu and Tibetan communities along the route maintain a way of life shaped by highland farming, yak herding, and Buddhist and animist traditions. Kanchenjunga Conservation Area is managed jointly by local communities and the National Trust for Nature Conservation, an approach that has proved successful in curbing poaching while providing sustainable livelihoods — making a trek here as much a lesson in conservation as an adventure.</p>`,
    district: `Taplejung`,
    province: "KOSHI",
    lat: 27.7025,
    lng: 88.1475,
    elevation: 8586,
    entryFee: `NPR 2,000 foreigners; USD 20/week restricted area permit`,
    bestSeason: `March to May, October to November`,
    openingHours: `Open year-round; trekking season March–May, Oct–Nov`,
    howToGetThere: `Fly Kathmandu to Bhadrapur, then drive ~6 hours to Taplejung; or direct flight to Taplejung (when operational).`,
    trekDays: 20,
    trekDifficulty: "HARD",
    trekMaxElevation: 5143,
    trekDistance: 210,
    trekStartPoint: `Taplejung`,
    trekEndPoint: `Taplejung`,
    trekHighlights: [`Pangpema North Base Camp (5,143 m) beneath Kanchenjunga's north face`, `Oktang South Base Camp (4,730 m) with glacial lake views`, `Red panda and snow leopard habitat through pristine forests`, `April rhododendron blooms across alpine slopes`, `Limbu and Tibetan cultural villages along the route`, `Remote wilderness with minimal trekker crowds`],
    gygQuery: `Kanchenjunga Base Camp Trek Nepal`,
    bookingCity: `Kathmandu`,
    seoTitle: `Kanchenjunga Conservation Area Trek | Nepal's Wildest Himalayan Route`,
    seoDescription: `Trek through Kanchenjunga Conservation Area in eastern Nepal — a 2,035 sq km wilderness surrounding the world's third-highest peak. Complete guide to permits, base camps, and the classic circuit trek.`,
    published: true,
    featured: false,
  },
  {
    name: `Taplejung`,
    category: "CULTURAL_VILLAGE",
    summary: `Perched at around 1,820 metres in Nepal's far-eastern hills, Taplejung is the gateway district headquarters to the Kanchenjunga massif and a vibrant market town rooted in Limbu culture. Its colourful bazaar, panoramic Himalayan backdrops, and position at the foot of major trekking routes make it a compelling stopover before heading into the wilderness.`,
    story: `<p>Taplejung sits in the far northeastern corner of Nepal — a district headquarters town cradled by forested ridges with the snow peaks of Kanchenjunga glittering on the northern horizon. Also known as Phungling, the town is the administrative and commercial hub of Taplejung District, and its lively bazaar buzzes with traders, trekking outfitters, and the daily rhythms of Limbu hill life.</p><p>The Limbu people are the dominant community here, and their culture infuses every aspect of daily life in Taplejung. Traditional Limbu homes with carved wooden facades, the haunting melodies of the sarangi lute, and locally brewed tongba — a warm millet beer sipped through a bamboo straw — offer visitors an authentic taste of one of Nepal's most distinctive indigenous cultures. The Kirat Mundum oral tradition, the spiritual backbone of Limbu society, is still practiced in the villages surrounding the town.</p><p>Taplejung's elevation of roughly 1,820 metres ensures a cool, pleasant climate for most of the year. The surrounding landscape is a patchwork of terraced fields, cardamom plantations, and dense subtropical forest. The district is one of Nepal's largest producers of large cardamom, and harvest season brings a distinctive spiced fragrance to the hillsides.</p><p>For trekkers, Taplejung is the essential staging post for the Kanchenjunga Conservation Area. The town has a growing range of guesthouses, trekking agencies, and permit offices, and a small domestic airport connects it — when weather allows — to Kathmandu and Bhadrapur. Even for those not heading into the high mountains, Taplejung itself rewards a day or two of exploration: the weekly market, the Pathibhara Devi Temple revered across eastern Nepal, and the warm hospitality of the Limbu community create memories that linger long after the journey home.</p>`,
    district: `Taplejung`,
    province: "KOSHI",
    lat: 27.3547,
    lng: 87.6675,
    elevation: 1820,
    entryFee: `Free`,
    bestSeason: `October to May`,
    openingHours: `Open year-round`,
    howToGetThere: `Fly Kathmandu to Bhadrapur then drive ~6 hours, or fly directly to Taplejung Airport (seasonal/weather dependent).`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Taplejung Nepal tour eastern hills`,
    bookingCity: `Kathmandu`,
    seoTitle: `Taplejung Nepal | Gateway to Kanchenjunga & Limbu Culture`,
    seoDescription: `Discover Taplejung, the far-eastern Nepal hill town and gateway to Kanchenjunga Conservation Area. Explore Limbu culture, cardamom farms, and breathtaking Himalayan views from this vibrant mountain bazaar.`,
    published: true,
    featured: false,
  },
  {
    name: `Terhathum`,
    category: "HILL_VIEWPOINT",
    summary: `Named for its thirteen peaks, Terhathum is a green and largely undiscovered hill district in eastern Nepal offering rhododendron-draped ridgelines, panoramic Himalayan views, and the celebrated Tinjure-Milke-Jaljale rhododendron trail. Its cool climate, Limbu and Rai cultural heritage, and intimate hill-town atmosphere make it an ideal off-the-beaten-path destination.`,
    story: `<p>Hidden in the hilly heartland of Koshi Province, Terhathum District takes its evocative name from the Nepali words for 'thirteen peaks' — an apt description for a landscape dominated by rolling ridges clad in rhododendron, oak, and bamboo forest. Few international travellers find their way here, yet the district conceals some of eastern Nepal's most rewarding hill experiences.</p><p>The centrepiece for nature lovers is the Tinjure-Milke-Jaljale (TMJ) Trail, often called the 'Rhododendron Capital of Nepal.' This ridge-top route, linking three distinct hill zones, bursts into vivid crimson, pink, and white blooms each April as dozens of rhododendron species flower simultaneously. The views from the trail encompass the full arc of the eastern Himalaya — Kanchenjunga, Makalu, and the lesser-known but no less magnificent peaks of the Taplejung borderland glittering on the horizon.</p><p>Terhathum's district headquarters at Myanglung sits at a moderate elevation and serves as a base for exploring the district's cultural riches. The Limbu and Rai communities that inhabit these hills maintain vibrant living traditions — tonics, songs, and festivals rooted in the Kirat Mundum worldview that predates both Buddhism and Hinduism in the region. The Singha Bahini Temple at Myanglung is a significant pilgrimage destination during Hindu festivals, drawing devotees from across eastern Nepal.</p><p>For those seeking even more dramatic views, the viewpoints at Teen Jure Danda (3,066 m) and Mike Danda (2,905 m) reward a day hike with sweeping Himalayan panoramas and unforgettable sunrise spectacles. The Hyatrung Waterfall in the district's southern sector adds a dramatic natural feature to an already diverse landscape. Terhathum rewards patient, independent travellers with the kind of authentic hill Nepal that is rapidly disappearing elsewhere.</p>`,
    district: `Terhathum`,
    province: "KOSHI",
    lat: 27.1325,
    lng: 87.5778,
    elevation: 1495,
    entryFee: `Free`,
    bestSeason: `March to May (rhododendrons), October to November (clear skies)`,
    openingHours: `Open year-round`,
    howToGetThere: `Bus or jeep from Dharan (5–6 hours) or Biratnagar via the Koshi Highway north through Dhankuta.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Terhathum rhododendron trek eastern Nepal`,
    bookingCity: `Kathmandu`,
    seoTitle: `Terhathum Nepal | Rhododendron Hills & Himalayan Views in Koshi`,
    seoDescription: `Explore Terhathum, eastern Nepal's hidden gem of thirteen peaks, rhododendron forests, and breathtaking Himalayan vistas. Discover the TMJ trail, Limbu culture, and peaceful hill towns off the beaten path.`,
    published: true,
    featured: false,
  },
  {
    name: `Num`,
    category: "TREK_ROUTE",
    summary: `The remote village of Num in Sankhuwasabha District marks the legendary starting point for the Makalu Base Camp Trek, one of Nepal's most demanding and rewarding Himalayan journeys. Perched above the wild Arun River gorge at roughly 1,560 metres, it is the last road-accessible settlement before trekkers descend into the wild canyon country below Makalu, the world's fifth-highest peak.`,
    story: `<p>At the confluence of two great river systems — the Arun and the Barun — lies Num, a small but strategically vital village in the Sankhuwasabha District of eastern Nepal. For Himalayan trekkers, the name Num carries an almost mythical resonance: it is here that the road ends and the wilderness begins, marking the departure point for one of the world's most challenging and least-crowded high-altitude routes.</p><p>The Makalu Base Camp Trek sets out from Num, plunging almost immediately into the extraordinary terrain of the Arun Valley. From the village, the trail drops sharply to the Arun River — one of the world's oldest rivers, whose gorge predates the Himalaya itself — before climbing steeply through tropical forest, then temperate woodland, and eventually into the bare alpine zone that surrounds Makalu (8,485 m), the fifth-highest peak on earth and one of the most challenging 8,000-metre mountains in the world.</p><p>Num itself is a simple settlement of stone houses and terraced fields, inhabited largely by Rai and Sherpa communities who have farmed these steep hillsides for generations. The village sits at approximately 1,560 metres and enjoys a commanding position above the river gorge, with cloud-draped forest stretching in every direction. A few basic teahouses serve trekkers, and permit checking takes place here before the journey into the Makalu Barun National Park deeper in the hills.</p><p>Getting to Num requires a flight from Kathmandu to Tumlingtar, followed by a rough jeep ride of several hours — itself an adventure through terraced hillsides and rushing mountain streams. The effort to reach this remote village only heightens the sense of entering genuinely untracked country. For those who make the journey, Num represents the purest kind of trekking threshold: a point of no return into one of the Himalaya's last great wild places.</p>`,
    district: `Sankhuwasabha`,
    province: "KOSHI",
    lat: 27.537,
    lng: 87.341,
    elevation: 1560,
    entryFee: `Makalu Barun National Park entry: NPR 3,000 foreigners; TIMS required`,
    bestSeason: `March to May, October to November`,
    openingHours: `Open year-round`,
    howToGetThere: `Fly Kathmandu to Tumlingtar (35 min), then jeep 4–5 hours to Num village.`,
    trekDays: 21,
    trekDifficulty: "HARD",
    trekMaxElevation: 5535,
    trekDistance: 130,
    trekStartPoint: `Num`,
    trekEndPoint: `Num`,
    trekHighlights: [`Descent into the ancient Arun River gorge`, `Makalu Base Camp (4,870 m) at the foot of the world's fifth-highest peak`, `Barun Valley — one of Nepal's most pristine alpine wilderness zones`, `Makalu Barun National Park biodiversity from tropical to alpine zones`, `Remote Rai and Sherpa communities with minimal outside influence`, `Views of Makalu, Baruntse, and Chamlang from upper camps`],
    gygQuery: `Makalu Base Camp Trek Nepal Num village`,
    bookingCity: `Kathmandu`,
    seoTitle: `Num Village Nepal | Gateway to Makalu Base Camp Trek`,
    seoDescription: `Num in Sankhuwasabha is the starting point of the Makalu Base Camp Trek — one of Nepal's wildest Himalayan adventures. Learn how to get there, permits needed, and what awaits in the Arun and Barun valleys.`,
    published: true,
    featured: false,
  },
  {
    name: `Hile`,
    category: "HILL_VIEWPOINT",
    summary: `Hile is a bustling hill bazaar in Dhankuta District perched at nearly 1,948 metres, long famous as the traditional roadhead for trekkers heading into the Arun Valley and Makalu region. Its dramatic mountain views, diverse community of hill traders, and cool highland atmosphere make it one of eastern Nepal's most characterful market towns.`,
    story: `<p>There is something enduringly alive about Hile. Strung along a ridge above the Koshi Highway about 13 km north of Dhankuta Bazaar, this bustling hill market has been a commercial crossroads for eastern Nepal for generations. Traders from the remote Arun Valley and Bhojpur district still descend to Hile to sell their produce — cardamom, ginger, dried mushrooms, and handwoven cloth — and return with salt, sugar, and manufactured goods. The result is a bazaar that pulses with authentic market-town energy largely untouched by the tourism economy.</p><p>At an elevation of roughly 1,948 metres, Hile enjoys a cool, often misty climate that keeps the surrounding hillsides lush and green. On clear mornings, the Himalayan panorama is breathtaking: Kanchenjunga, Makalu, and a host of lesser summits crowd the northern horizon, their snow faces catching the first pink light of dawn above a sea of forested ridges. Photographers and early risers are well rewarded by the views from the ridgeline above the bazaar.</p><p>Hile's history as a trekking hub dates back to the era of expedition mountaineering in the Khumbu and Makalu regions, when it served as the starting point for long approach marches into the high mountains. A network of stone-paved trails still radiates from the town into the hills, connecting it with villages that have changed little in decades. The Limbu, Rai, and Brahmin communities who share this corner of Dhankuta District contribute to a cultural diversity that reveals itself in the festivals, food, and music of the town.</p><p>While Hile has lost some of its trekking prominence since roads pushed deeper into the hills, it retains an essential eastern Nepal character. Local teahouses serve excellent dal bhat, the wood-smoke-scented lanes are full of colour and conversation, and the surrounding countryside invites exploration on foot along trails that lead through bamboo groves and cardamom gardens to viewpoints few outsiders ever discover.</p>`,
    district: `Dhankuta`,
    province: "KOSHI",
    lat: 27.026,
    lng: 87.31,
    elevation: 1948,
    entryFee: `Free`,
    bestSeason: `October to May`,
    openingHours: `Open year-round`,
    howToGetThere: `Bus or jeep from Dharan (~3 hours) via the Koshi Highway; or from Biratnagar (~4 hours).`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Hile Dhankuta hill bazaar eastern Nepal`,
    bookingCity: `Kathmandu`,
    seoTitle: `Hile Dhankuta Nepal | Hill Bazaar & Himalayan Views in Koshi Province`,
    seoDescription: `Discover Hile, eastern Nepal's vibrant hill bazaar in Dhankuta District at 1,948 m. Famous for mountain views of Kanchenjunga and Makalu, authentic market culture, and as a historic trekking hub.`,
    published: true,
    featured: false,
  },
  {
    name: `Basantapur Hill Station`,
    category: "HILL_VIEWPOINT",
    summary: `Basantapur is a serene hill station in Terhathum District at around 2,200 metres, celebrated for its sweeping views of Kanchenjunga, Makalu, and the eastern Himalayan chain. Surrounded by rhododendron forests and Limbu cultural villages, it offers some of Nepal's finest sunrise spectacles and serves as the gateway to the spectacular Tinjure-Milke-Jaljale rhododendron trail.`,
    story: `<p>Perched on a high ridge in Terhathum District at roughly 2,200 metres above sea level, Basantapur is the kind of hill station that rewards travellers willing to leave the tourist trail behind. Its name — 'place of spring' — is perfectly chosen: each April, the surrounding forests erupt in cascading waves of rhododendron bloom, painting the ridgelines in vivid crimson, pink, and white as far as the eye can see.</p><p>The mountain panorama from Basantapur is genuinely exceptional. On clear mornings, the entire arc of the eastern Himalaya stretches across the northern horizon — Kanchenjunga and its subsidiary peaks dominating the northeast, Makalu's pyramid rising to the northwest, and dozens of lesser summits filling the spaces between. The viewpoints at Teen Jure Danda (3,066 m) and Mike Danda (2,905 m), both reachable by day hike from the hill station, push the vista even higher and offer golden-hour light that photographers treasure.</p><p>Basantapur is also the primary jumping-off point for the Tinjure-Milke-Jaljale (TMJ) Trail — a ridge-top trekking route running through one of Nepal's densest concentrations of rhododendron species. The TMJ links Terhathum with Taplejung and Solukhumbu and is increasingly recognised by botanists, birdwatchers, and trekkers as one of the Himalayan foothills' most extraordinary journeys, traversing habitats that shelter red pandas, Himalayan black bears, and a remarkable diversity of high-altitude bird species.</p><p>The Limbu community of Basantapur maintains a warm and distinctive highland culture. Local homes produce handwoven fabrics and traditional jewellery, and the flavours of Limbu cuisine — including the celebrated tongba millet beer served warm in a bamboo vessel — make evenings around a wood fire particularly memorable. With a small but functional range of guesthouses and homestays, Basantapur offers a genuinely authentic hill Nepal experience without crowds.</p>`,
    district: `Terhathum`,
    province: "KOSHI",
    lat: 27.2291,
    lng: 87.3336,
    elevation: 2200,
    entryFee: `Free`,
    bestSeason: `March to May (rhododendrons), October to November (mountain views)`,
    openingHours: `Open year-round`,
    howToGetThere: `Drive from Dharan via Dhankuta and Hile (~6–7 hours); or from Taplejung side via Terhathum roads.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Basantapur Terhathum hill station Nepal`,
    bookingCity: `Kathmandu`,
    seoTitle: `Basantapur Hill Station Terhathum | Nepal's Rhododendron Viewpoint`,
    seoDescription: `Visit Basantapur in Terhathum, eastern Nepal — a 2,200 m hill station famed for Kanchenjunga views, April rhododendron blooms, and access to the Tinjure-Milke-Jaljale trail. A hidden gem of Koshi Province.`,
    published: true,
    featured: false,
  },
  {
    name: `Ilam Bazaar`,
    category: "CULTURAL_VILLAGE",
    summary: `Ilam Bazaar is the charming headquarters of Nepal's tea country, set at around 1,200 metres in the emerald hills of far-eastern Nepal. Ringed by manicured tea estates, rhododendron forests, and views of the Kanchenjunga range, it is the ideal base from which to explore Kanyam Tea Garden, Mai Pokhari lake, and the sunrise spectacle at Antu Danda.`,
    story: `<p>Nepal's tea country has a capital, and it is Ilam Bazaar. This pleasant hill town in far-eastern Koshi Province sits at around 1,200 metres amid some of the most productive tea-growing terrain outside Darjeeling, its cool, mist-wrapped hillsides and fertile, acidic soils nurturing tea bushes whose leaves are celebrated across Asia for their delicate, muscatel-inflected flavour.</p><p>The history of tea cultivation in Ilam dates to the mid-nineteenth century, when plants propagated from Chinese seed were first introduced to these hillsides. Today the district's signature estates — Kanyam (1,800 m), Ilam Tea Estate, and dozens of smaller gardens — produce orthodox teas that compete on international markets and form the backbone of the local economy. Visitors can walk the manicured rows of tea bushes, observe the plucking and withering process in the processing sheds, and taste fresh first-flush tea with a directness of experience impossible elsewhere.</p><p>Beyond the tea gardens, Ilam District is a treasury of natural beauty. Mai Pokhari, a high-altitude lake at 2,121 metres surrounded by primeval forest, is sacred to the local community and shelters remarkable wetland biodiversity. Antu Danda, a ridge at 2,328 metres, has become famous across Nepal for its extraordinary sunrise views over the eastern Himalaya, with Kanchenjunga, Makalu, and the Sikkim peaks glowing in the first light of dawn above a rolling sea of forest and tea gardens.</p><p>Ilam Bazaar itself is a lively and colourful town with a large central market, a proud Limbu and Brahmin cultural mix, and excellent local food. The streets fill with the fragrance of freshly roasted tea and spices on market days, and local festivals celebrate everything from the tea harvest to Hindu and Kirat religious occasions. Ilam rewards visitors with an authenticity and beauty that few of Nepal's better-known hill destinations can match.</p>`,
    district: `Ilam`,
    province: "KOSHI",
    lat: 26.9108,
    lng: 87.9218,
    elevation: 1208,
    entryFee: `Free (tea estate tours may charge small fee)`,
    bestSeason: `March to May, October to December`,
    openingHours: `Open year-round`,
    howToGetThere: `Drive from Biratnagar (~4 hours) or Kakarbhitta border crossing (~3 hours) by bus or jeep.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Ilam tea garden Nepal tour eastern hills`,
    bookingCity: `Kathmandu`,
    seoTitle: `Ilam Bazaar Nepal | Tea Gardens, Antu Danda & Eastern Hill Culture`,
    seoDescription: `Explore Ilam Bazaar, Nepal's tea capital in the eastern hills. Visit Kanyam tea estates, Mai Pokhari lake, and Antu Danda sunrise point near Kanchenjunga. A complete guide to Ilam's best attractions.`,
    published: true,
    featured: false,
  },
  {
    name: `Mechi River`,
    category: "RIVER",
    summary: `The Mechi River is eastern Nepal's defining boundary waterway, originating in the Ilam hills and flowing south to form the international border between Nepal and India before joining the Mahananda in Bihar. Revered along its banks for religious festivals, the river also sustains rich riparian ecosystems and frames the verdant tea-country landscapes of Ilam and Jhapa districts.`,
    story: `<p>Rivers have always defined eastern Nepal, and none more so than the Mechi. Originating in the Mahabharat Range — the middle hills that rise sharply above the Terai plains — the Mechi River flows south through the lush districts of Ilam and Jhapa, its clear waters cutting through tea estates, paddy fields, and subtropical forest before reaching the plains and forming the natural border between Nepal and the Indian state of West Bengal.</p><p>The river's total length of approximately 80 kilometres belies its cultural and ecological significance. Along its banks in Ilam District, the Mechi flows through some of Nepal's most picturesque hill scenery, where terraced fields drop steeply to the water's edge and small wooden suspension bridges sway above the current. The river is fed by dozens of smaller streams descending from the high ridges of the eastern hills, giving it a clarity and cool vitality that makes its banks a favourite picnic destination for locals.</p><p>In the Terai lowlands of Jhapa District, the Mechi broadens and slows, its floodplain supporting rich agricultural land and diverse wetland habitats. Migratory birds congregate here during winter months, and the river's fish populations sustain local fishing communities who cast their nets in the traditional manner. The border crossing at Kakarbhitta, where Nepal meets India at the Mechi's bank, is one of the country's busiest overland entry points and a place where the cultural exchange between the two nations is palpably alive.</p><p>Religious significance runs deep along the Mechi. Hindu festivals including Chhath Puja draw large congregations to the river's banks, where devotees offer worship to the sun god in rituals that transform the waterside into a spectacle of colour, song, and devotion. For travellers journeying between Kathmandu and Darjeeling, the crossing of the Mechi — whether by the modern bridge at Kakarbhitta or by foot along the ancient trail — marks the threshold between Nepal and the wider Himalayan world.</p>`,
    district: `Ilam`,
    province: "KOSHI",
    lat: 26.8936,
    lng: 88.0,
    elevation: 300,
    entryFee: `Free`,
    bestSeason: `October to March`,
    openingHours: `Open year-round`,
    howToGetThere: `Access via Kakarbhitta (Nepal-India border) or from Ilam by local bus or jeep (~2 hours south).`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Mechi River Nepal Kakarbhitta border Jhapa`,
    bookingCity: `Kathmandu`,
    seoTitle: `Mechi River Nepal | Eastern Border River of Ilam and Jhapa`,
    seoDescription: `Discover the Mechi River — eastern Nepal's storied boundary river flowing through Ilam's tea hills and Jhapa's plains to form the India-Nepal border. Learn about its cultural festivals, ecology, and scenic appeal.`,
    published: true,
    featured: false,
  },
  {
    name: `Koshi Barrage`,
    category: "RIVER",
    summary: `The Koshi Barrage is a remarkable feat of mid-twentieth century engineering spanning 1,150 metres across the great Koshi River in Sunsari District. Built under a Nepal-India bilateral agreement and completed in 1962, it controls the historically devastating floods of the 'Sorrow of Bihar', and today its banks host Chhath Puja pilgrimages, Gangetic river dolphin sightings, and the adjacent Koshi Tappu Wildlife Reserve.`,
    story: `<p>The Koshi River — known historically as the 'Sorrow of Bihar' for the catastrophic floods it unleashed across the plains of Nepal and India — was tamed, in part, by the construction of the Koshi Barrage. Completed between 1958 and 1962 under a landmark bilateral agreement between Nepal and India signed in 1954, the barrage stretches 1,150 metres across the river in Sunsari District, its 56 sluice gates controlling the flow of one of the Himalaya's most powerful and unpredictable river systems.</p><p>Standing on the barrage itself is an experience that connects visitors to both engineering history and living nature. In the water below, Gangetic river dolphins — one of the world's most endangered freshwater cetaceans — can be spotted feeding and playing, often in groups of half a dozen or more. The Koshi's broad, braided channels here support extraordinary bird diversity: the adjacent Koshi Tappu Wildlife Reserve, a Ramsar-designated wetland of international importance, protects over 480 bird species and is one of South Asia's premier birding destinations, drawing ornithologists from around the world.</p><p>The barrage road carries vehicular, bicycle, and pedestrian traffic between Saptari and Sunsari districts, making it a functional artery of everyday Terai life as well as a tourist attraction. On religious occasions — particularly Chhath Puja, the sun-worship festival central to the culture of Nepal's Madhesh region — the river banks transform into a spectacle of devotion, with tens of thousands of pilgrims gathering at dawn and dusk to offer prayers at the water's edge, the air thick with incense and traditional song.</p><p>The barrage sits close to the Indian border and is accessible from Lahan or Itahari by road. The nearby town of Chatara, upstream, is another sacred bathing site on the Koshi, further enriching the river's cultural landscape. A visit to the Koshi Barrage, combined with a morning at Koshi Tappu Wildlife Reserve, makes for one of the most rewarding nature and heritage days in Nepal's eastern Terai.</p>`,
    district: `Sunsari`,
    province: "KOSHI",
    lat: 26.5263,
    lng: 86.9269,
    elevation: 78,
    entryFee: `Free`,
    bestSeason: `October to March (bird watching best Nov–Feb)`,
    openingHours: `Open year-round`,
    howToGetThere: `Drive from Itahari (~1 hour) or Lahan (~1.5 hours); accessible by local bus from Biratnagar.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Koshi Barrage Sunsari Nepal wildlife birding`,
    bookingCity: `Kathmandu`,
    seoTitle: `Koshi Barrage Sunsari Nepal | River Dolphins, Birding & History`,
    seoDescription: `Visit the Koshi Barrage in Sunsari, Nepal — a 1,150 m engineering marvel on the mighty Koshi River. Spot Gangetic dolphins, enjoy world-class birding at Koshi Tappu, and experience Chhath Puja on the riverbanks.`,
    published: true,
    featured: false,
  },
  {
    name: `Janakpur Dham Railway`,
    category: "CULTURAL_VILLAGE",
    summary: `The Janakpur-Jaynagar Railway is Nepal's oldest operational rail link, connecting the holy city of Janakpur in Madhesh Province with Jaynagar in India. Originally a 1937 narrow-gauge timber line, it has been rebuilt as broad gauge and reopened in 2022, offering a uniquely nostalgic and historically rich journey through the Maithili heartland of the Terai.`,
    story: `<p>In a country that for most of its modern history had almost no railways, the Janakpur-Jaynagar line holds a special and somewhat romantic significance. It is Nepal's oldest surviving railway, born in 1937 as a narrow-gauge track laid to carry timber from the forests of the Terai to the railhead at Jaynagar across the Indian border. When the forests were exhausted, the line passed to the Nepali government and found a new life as a passenger railway serving the communities of the Dhanusha region.</p><p>For decades, the line was famous among railway enthusiasts worldwide for its steam locomotives — sturdy little engines that chugged through the flat Terai countryside, linking villages that had no other reliable connection to the wider world. British and European trainspotters made pilgrimages to Janakpur in the 1980s and 1990s to ride the steam trains, and the last steam excursion ran as late as 2006, giving the line a cult following in international railway circles.</p><p>After closure in 2014 for gauge conversion, the railway was rebuilt to broad gauge (1,676 mm) with Indian support and reopened in April 2022 as the Jaynagar-Bardibas Railway — at the time of its reopening, the only operational passenger railway in Nepal. The first section from Jaynagar to Kurtha (17 km) runs through the sacred landscape of the Janakpur area, and a second section onward to Bijalpura opened in July 2023, extending the line into the agricultural heartland of Madhesh.</p><p>The railway's cultural context is as compelling as its history. Janakpur, the line's Nepali terminus, is one of Hinduism's most sacred cities — traditionally identified as the birthplace of Sita, consort of Lord Ram, and the site of their celebrated marriage. The city's Maithili cultural identity is expressed through vivid Mithila paintings, traditional music, and festivals that draw pilgrims from across Nepal and India. Boarding the train at Janakpur Dham station is to step into a landscape shaped entirely by devotion, history, and the slow rhythm of rural Terai life.</p>`,
    district: `Dhanusha`,
    province: "MADHESH",
    lat: 26.7288,
    lng: 85.9255,
    elevation: 73,
    entryFee: `Train ticket: NPR 30-60 per section`,
    bestSeason: `October to March`,
    openingHours: `Trains operate daily; schedule varies — check Nepal Railways`,
    howToGetThere: `Bus from Kathmandu to Janakpur (~6-7 hours); fly Kathmandu to Janakpur (~30 min). Station is in central Janakpur Dham.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Janakpur Railway Nepal Terai heritage train`,
    bookingCity: `Kathmandu`,
    seoTitle: `Janakpur Dham Railway | Nepal's Historic Terai Train Journey`,
    seoDescription: `Ride the Janakpur-Jaynagar Railway — Nepal's oldest rail line, rebuilt as broad gauge and reopened in 2022. A unique heritage journey through the Maithili heartland near the sacred city of Janakpur Dham.`,
    published: true,
    featured: false,
  },
  {
    name: `Gadhimai Temple`,
    category: "TEMPLE",
    summary: `The Gadhimai Temple in Bara District is one of Nepal's most powerful and controversial Hindu pilgrimage sites, dedicated to Gadhimai — an aspect of the goddess Kali. Every five years it hosts the Gadhimai Mela, drawing millions of devotees from Nepal and India and once associated with the world's largest animal sacrifice festival, now undergoing significant reform.`,
    story: `<p>Deep in the Terai plains of Bara District, approximately 160 km south of Kathmandu and just a few kilometres from the Indian border, stands a temple that has drawn millions of pilgrims and sparked global debate in equal measure. The Gadhimai Temple is dedicated to Gadhimai — a fierce aspect of the Hindu goddess Kali, associated with power, protection, and the transcendence of earthly bondage — and its five-yearly festival, the Gadhimai Mela, has long been one of the largest religious gatherings in South Asia.</p><p>The origin myth of the temple is rooted in a devotee's vision in which the goddess Gadhimai appeared and demanded blood sacrifice in exchange for the liberation of the faithful. For centuries, this mandate was interpreted literally, and the Gadhimai Mela became associated with mass animal sacrifice on a scale that shocked international observers and animal rights advocates. At its peak in 2009, an estimated 250,000 to 500,000 animals were sacrificed over the course of the festival — making it the largest recorded sacrifice ritual in human history.</p><p>The temple committee, in response to sustained advocacy and a Supreme Court order, announced a move away from live animal sacrifice from 2019 onwards, transitioning the festival toward vegetarian offerings and symbolic devotion while maintaining the profound spiritual character that draws such enormous crowds. The transformation is ongoing and contested — devotion to Gadhimai runs extraordinarily deep among the Madhesi communities of Nepal and Bihar — but the direction of change is clear.</p><p>The temple itself sits in the village of Bariyarpur in Mahagadhimai Municipality. The central shrine is a powerful and atmospheric space, heavy with incense, oil lamps, and the offerings of countless pilgrims. Even outside festival years, the temple attracts steady streams of worshippers seeking blessings for health, fertility, and protection. For students of living religious culture in South Asia, Gadhimai offers an extraordinary and sobering window into the transformative power of faith.</p>`,
    district: `Bara`,
    province: "MADHESH",
    lat: 26.9934,
    lng: 85.0473,
    elevation: 85,
    entryFee: `Free`,
    bestSeason: `November (Gadhimai Mela, every 5 years); October to March generally`,
    openingHours: `Open daily, sunrise to sunset`,
    howToGetThere: `Drive from Kathmandu (~5 hours) via the Mahendra Highway to Kalaiya, then 7 km east to Bariyarpur; or bus to Kalaiya then local transport.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Gadhimai Temple Bara Nepal pilgrimage`,
    bookingCity: `Kathmandu`,
    seoTitle: `Gadhimai Temple Bara Nepal | Pilgrimage Site & Gadhimai Mela Guide`,
    seoDescription: `Visit Gadhimai Temple in Bara, Nepal — one of South Asia's most powerful Hindu pilgrimage sites dedicated to Goddess Gadhimai. Learn about the Gadhimai Mela festival, its history, reforms, and how to visit.`,
    published: true,
    featured: false,
  },
  {
    name: `Bagmati River Sarlahi`,
    category: "RIVER",
    summary: `Where the sacred Bagmati River descends from its hill origins and enters the Madhesh plains of Sarlahi District, it becomes a lifeline of agriculture, faith, and ecology. Revered by Hindus and Buddhists alike, the Bagmati at Sarlahi draws pilgrims to its banks for Chhath Puja and other festivals, and its floodplains support rich wetland biodiversity in the heart of Nepal's Terai.`,
    story: `<p>The Bagmati is Nepal's most spiritually significant river, and its passage through Sarlahi District marks the point at which the sacred waterway completes its transition from mountain-born stream to great Terai river. Rising near Gosaikunda in the Langtang hills and flowing through the sacred ghats of Kathmandu — past Pashupatinath, where it carries the ashes of the cremated into the Hindu afterworld — the Bagmati arrives in Sarlahi as a broad, seasonally flooding river that has shaped the landscape and livelihoods of the Madhesh for millennia.</p><p>In Sarlahi, the Bagmati forms the western border of the district before continuing into Rautahat and eventually crossing into Bihar, India, where it joins the Ganga. The river's floodplain here is extraordinarily fertile — the dark alluvial soil produces rice, wheat, and vegetables that feed millions — and the annual monsoon floods, though sometimes destructive, replenish the soil with the nutrients that make this one of Nepal's most productive agricultural zones.</p><p>Religious life along the Sarlahi Bagmati is vibrant. The Kabilasi Temple, situated on the river bank, is a significant pilgrimage site that attracts both Hindus and devotees of the river's divine feminine energies. Chhath Puja — the sun-worship festival central to Terai culture — transforms the Bagmati's banks into a sea of orange and gold twice each year, as devotees stand waist-deep in the river at sunrise and sunset to offer prayers and sacred offerings to Surya, the sun god. The scene at these moments is among the most visually spectacular in all of Madhesh Province.</p><p>For nature travellers, the Bagmati's floodplain in Sarlahi hosts seasonal wetlands that attract migratory birds during the winter months, and the riparian forest along its banks shelters wildlife that has largely retreated from the increasingly developed agricultural plains. The river remains a living thread connecting Sarlahi's rural communities to both the natural world and an ancient sacred geography that spans the entire subcontinent.</p>`,
    district: `Sarlahi`,
    province: "MADHESH",
    lat: 27.0808,
    lng: 85.4792,
    elevation: 118,
    entryFee: `Free`,
    bestSeason: `October to March`,
    openingHours: `Open year-round`,
    howToGetThere: `Drive from Kathmandu (~4-5 hours) via the Mahendra Highway to Malangwa (Sarlahi headquarters); local transport to river access points.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Bagmati River Sarlahi Nepal Terai pilgrimage`,
    bookingCity: `Kathmandu`,
    seoTitle: `Bagmati River Sarlahi | Nepal's Sacred River in Madhesh Province`,
    seoDescription: `Explore the sacred Bagmati River as it flows through Sarlahi District in Nepal's Madhesh Province. Learn about Chhath Puja pilgrimages, the Kabilasi Temple, wetland ecology, and how to visit this holy Terai waterway.`,
    published: true,
    featured: false,
  },
  {
    name: `Kapilvastu`,
    category: "ARCHAEOLOGICAL",
    summary: `Kapilvastu is the ancient Shakya kingdom where Prince Siddhartha Gautama lived his first 29 years before renouncing the world and attaining Buddhahood. The archaeological site of Tilaurakot — identified by many scholars as the ancient capital — preserves the ruins of the palace, city walls, and gateways where the future Buddha walked, making it a profoundly significant destination for Buddhist pilgrims and historians alike.`,
    story: `<p>Few places on earth carry the weight of spiritual transformation that rests upon Kapilvastu. This ancient kingdom in what is now the Rupandehi-Kapilvastu border region of Lumbini Province was the childhood home and royal seat of Siddhartha Gautama — the prince who would renounce his wealth, leave through the Eastern Gateway of his palace, and, after years of meditation and asceticism, attain enlightenment as the Buddha under a Bodhi tree in Bodh Gaya.</p><p>The archaeological site of Tilaurakot — coordinates 27°34'N, 83°03'E — is widely identified by Nepali and international scholars as the site of ancient Kapilavastu. Excavations here have revealed the fortified mud-brick city walls, moated enclosures, palace foundations, and monastic remains of a settlement that flourished between roughly the sixth and third centuries BCE. The Eastern Gateway, through which tradition holds that Siddhartha made his 'Great Renunciation,' has been partly excavated and is now one of the most emotionally resonant spots in the entire Buddhist pilgrimage circuit.</p><p>Pilgrims who come to Tilaurakot often spend time in contemplative silence within the excavated palace compound, walking the same ground where the young prince once lived a life of sheltered luxury before his fateful encounters with sickness, old age, and death prompted his spiritual quest. The site is surrounded by farmland and is quieter and more meditative than nearby Lumbini — a quality many Buddhist visitors find deeply appropriate.</p><p>The broader Kapilvastu District encompasses numerous other sites of Buddhist and Hindu significance, including the Kudan Stupa (where Buddha reportedly returned after enlightenment to visit his father), Nigrodharam (where he preached to his Shakya kinsmen), and Sagarhawa — the site traditionally associated with the massacre of the Shakya clan. Together these form a circuit of immense importance for understanding the world and times of the historical Buddha.</p>`,
    district: `Kapilvastu`,
    province: "LUMBINI",
    lat: 27.5764,
    lng: 83.055,
    elevation: 93,
    entryFee: `NPR 200 foreigners; NPR 50 SAARC; free for Nepalis`,
    bestSeason: `October to March`,
    openingHours: `7:00 AM to 5:00 PM daily`,
    howToGetThere: `Drive from Lumbini (~1 hour) or Bhairahawa (~1.5 hours); bus services available from Butwal and Tansen.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Kapilvastu Tilaurakot ancient ruins Nepal Buddhist pilgrimage`,
    bookingCity: `Kathmandu`,
    seoTitle: `Kapilvastu Nepal | Ancient Kingdom of the Buddha's Early Life`,
    seoDescription: `Visit Kapilvastu and the Tilaurakot archaeological site — the ancient Shakya kingdom where Siddhartha Gautama spent his first 29 years. A key stop on Nepal's Buddhist pilgrimage circuit in Lumbini Province.`,
    published: true,
    featured: false,
  },
  {
    name: `Devdaha`,
    category: "ARCHAEOLOGICAL",
    summary: `Devdaha in Rupandehi District is the ancient hometown of Queen Maya Devi, the mother of the Buddha, and a site of deep Maithili and Buddhist heritage. Traditional accounts hold that Maya Devi and members of the Koliya clan who inhabited this settlement shaped the very origins of the Buddhist world, making Devdaha a quietly powerful destination on the Lumbini pilgrimage circuit.`,
    story: `<p>Seven kilometres east of the sacred garden of Lumbini — where the Buddha was born beneath a sal tree in 563 BCE — lies a place even more deeply connected to the origins of the Buddhist story. Devdaha, an ancient settlement in present-day Rupandehi District, was the maternal home of the Koliya clan: the royal family from which Queen Maya Devi, the Buddha's mother, came. It was from Devdaha that Maya Devi set out on the journey to Lumbini, and it was on that journey — while resting in the sacred garden — that she gave birth to Siddhartha Gautama.</p><p>Traditional accounts identify Devdaha as the birthplace not only of Maya Devi but also of Prajapati Gautami — the aunt who raised Siddhartha after his mother's death seven days after his birth — and Yashodhara, the princess who became Siddhartha's wife. The Koliya lineage thus contributed three of the central women figures in the early Buddhist narrative: mother, foster-mother, and wife. This feminine dimension of Buddhist origins, often underemphasised in mainstream pilgrimage itineraries, makes Devdaha particularly significant for scholars of early Buddhism and for practitioners who value the tradition's founding women.</p><p>The modern village of Devdaha sits at approximately 154 metres above sea level on the flat Terai plain. Archaeological investigations in and around the site have located ancient mounds, brickwork, and material culture consistent with occupation during the Shakya period. A temple complex at the site marks the traditional spot associated with Maya Devi's family. The atmosphere is quiet and somewhat contemplative — lacking the international infrastructure of Lumbini but retaining a raw historical intimacy that many pilgrims find more moving.</p><p>Devdaha is most rewarding when visited as part of a broader Lumbini circuit that includes Kapilvastu (Tilaurakot), Niglihawa, and the monasteries of the Lumbini Cultural Zone. The drive from Lumbini takes approximately 30 minutes on Terai roads, and local guides can help interpret the archaeological and textual evidence for the site's extraordinary importance in Buddhist history.</p>`,
    district: `Rupandehi`,
    province: "LUMBINI",
    lat: 27.6605,
    lng: 83.5703,
    elevation: 154,
    entryFee: `Free`,
    bestSeason: `October to March`,
    openingHours: `Open year-round (daylight hours)`,
    howToGetThere: `Drive from Lumbini (~30 min) or Bhairahawa (~45 min) by local bus or hired vehicle.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Devdaha Rupandehi Nepal Buddhist pilgrimage Lumbini`,
    bookingCity: `Kathmandu`,
    seoTitle: `Devdaha Nepal | Birthplace of Maya Devi, Mother of the Buddha`,
    seoDescription: `Visit Devdaha in Rupandehi, Nepal — the ancient homeland of Queen Maya Devi, mother of the Buddha. A sacred Buddhist site near Lumbini connected to the origins of Buddhism. Guide to history, location, and visiting.`,
    published: true,
    featured: false,
  },
  {
    name: `Tansen Shreenagar Hill`,
    category: "HILL_VIEWPOINT",
    summary: `Shreenagar Hill rises above the medieval town of Tansen in Palpa District to offer one of western Nepal's finest panoramic viewpoints, with a sweeping Himalayan horizon that takes in Dhaulagiri, Annapurna, Machhapuchhre, and Langtang. A short half-hour hike through juniper and pine forest from Tansen's old bazaar leads to an observatory tower that rewards visitors with vistas few Nepal viewpoints can rival.`,
    story: `<p>The medieval hill town of Tansen has been captivating travellers for centuries — its distinctive Newari architecture, winding stone-paved lanes, metalwork tradition, and strategic position above the Palpa valley making it one of western Nepal's most treasured destinations. But it is Shreenagar Hill, the juniper-clad ridge that rises above the town to approximately 1,524 metres, that offers the perspective to truly understand Tansen's extraordinary setting.</p><p>The hike from Tansen's central Shitalpati square to the Shreenagar viewpoint takes roughly thirty minutes on a well-maintained trail through a fragrant forest of juniper, pine, and rhododendron. The ascent passes through the town's quieter residential quarters, where children play in cobbled courtyards and the sound of metalworkers hammering dhaka fabric and dhaka metalwork drifts from open workshops. The forest above the town is peaceful and birdsong-rich, offering a pleasant transition from the urban energy of the bazaar to the alpine serenity of the ridge.</p><p>At the summit, an observatory tower provides an unobstructed 360-degree panorama. To the north, the full arc of the Nepal Himalaya stretches across the horizon in extraordinary clarity on fine mornings — Dhaulagiri (8,167 m) dominates the northwest, the great massif of Annapurna (8,091 m) fills the north, Machhapuchhre's iconic fishtail silhouette rises to the northeast, and the Langtang Range completes the eastern horizon. Below, the Kali Gandaki and Andhi Khola valleys carve deep gorges through the middle hills, and the flat shimmer of the Terai plains is visible to the south on clear days.</p><p>Tansen itself — the historic Magar and Newari trading town that served as capital of the Palpa kingdom — deserves at least a full day of exploration before or after the Shreenagar climb. The Tansen Durbar, Amar Narayan Temple, and the lanes of the old bazaar with their distinctive Newari-style facades and metalwork shops are among the finest examples of traditional hill town architecture outside the Kathmandu Valley.</p>`,
    district: `Palpa`,
    province: "LUMBINI",
    lat: 27.8673,
    lng: 83.5456,
    elevation: 1524,
    entryFee: `Free`,
    bestSeason: `October to April`,
    openingHours: `Open year-round; best visited at dawn for mountain views`,
    howToGetThere: `Drive from Pokhara (~3 hours) or Butwal (~2 hours) to Tansen; Shreenagar Hill is a 30-minute walk from Tansen bazaar.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Tansen Palpa Nepal viewpoint hill station`,
    bookingCity: `Pokhara`,
    seoTitle: `Tansen Shreenagar Hill Palpa | Panoramic Himalayan Viewpoint Nepal`,
    seoDescription: `Climb Shreenagar Hill above Tansen in Palpa, Nepal, for breathtaking views of Dhaulagiri, Annapurna, and Machhapuchhre. Discover this hidden western Nepal viewpoint above the medieval town of Tansen.`,
    published: true,
    featured: false,
  },
  {
    name: `Fewa Lake Boating`,
    category: "LAKE",
    summary: `Fewa Lake (Phewa Tal) is Pokhara's iconic centrepiece and Nepal's second-largest lake, where wooden rowboats carry visitors across mirror-still waters reflecting the snow peak of Machhapuchhre and the Annapurna range. A boat ride to the island Tal Barahi Temple at dawn, with mountains turning pink above their perfect reflection, is one of Nepal's most quintessential travel experiences.`,
    story: `<p>There are moments in travel that crystallise into permanent memory, and a dawn boat ride on Fewa Lake is reliably one of them. As the first light touches the snow summit of Machhapuchhre — the sacred 'Fishtail Mountain' that no climber has ever been permitted to summit — the peak's reflection materialises on the lake's glassy surface, a perfect double image of rose and gold that seems almost too beautiful to be real. This is Pokhara at its most magical, and it is available every clear morning to anyone willing to hire a wooden rowboat at the lakeside ghats.</p><p>Phewa Tal — Fewa Lake — is the second-largest lake in Nepal, covering approximately 4.43 square kilometres at an elevation of 742 metres in the south of the Pokhara Valley. Its shoreline is lined with the hotels, restaurants, and shops of Lakeside, the tourist district that has grown around the lake over recent decades, but the lake itself remains a place of serene natural beauty, its waters sustained by the Modi Khola inflow and sheltered by the Annapurna and Dhaulagiri ranges to the north.</p><p>Boating on Fewa Lake offers several distinct experiences. The most popular is the short paddle to Tal Barahi Temple, a two-roofed pagoda on a small island near the lake's centre that is one of Pokhara's most important Hindu religious sites. Pilgrims and tourists alike visit the temple by boat, particularly on Saturdays when worshippers gather for puja and the water surface is busy with wooden craft. Longer rowing expeditions can circle the lake's quieter western shores, where the forest meets the water and kingfishers dart among the reeds.</p><p>Evening light on Fewa Lake rivals dawn for spectacle. As the sun descends behind the Pokhara ridge, the mountains turn deep amber and the lake surface shifts through every shade of copper and violet. Kayaking, stand-up paddleboarding, and pedal-boating are all available at the lakeside rental points. The combination of easy accessibility, dramatic mountain backdrop, and the meditative quality of being on the water makes Fewa Lake boating an experience that transcends ordinary tourism and touches something closer to wonder.</p>`,
    district: `Kaski`,
    province: "GANDAKI",
    lat: 28.2154,
    lng: 83.9453,
    elevation: 742,
    entryFee: `Free to visit; rowboat hire NPR 450-500/hour; Tal Barahi temple boat NPR 100/person`,
    bestSeason: `September to May`,
    openingHours: `Boats available daily, approximately 6:00 AM to 6:00 PM`,
    howToGetThere: `Fewa Lake is central to Pokhara's Lakeside district; fly or drive from Kathmandu (~25 min flight, ~7 hours drive).`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Fewa Lake Phewa boating Pokhara Nepal`,
    bookingCity: `Pokhara`,
    seoTitle: `Fewa Lake Boating Pokhara | Nepal's Most Iconic Lake Experience`,
    seoDescription: `Experience boating on Fewa Lake (Phewa Tal) in Pokhara, Nepal — row to the Tal Barahi Temple on its island shrine with Machhapuchhre reflected in the still water. Prices, best time, and travel tips.`,
    published: true,
    featured: false,
  },
  {
    name: `Pokhara International Airport`,
    category: "MOUNTAIN_VIEW",
    summary: `Pokhara International Airport, which opened on 1 January 2023, is Nepal's newest and most modern aviation facility — a transformative infrastructure project built at Chhinedanda, 800 metres above sea level, with a runway offering dramatic views of the Annapurna and Machhapuchhre ranges. Designed to handle international traffic and reduce Nepal's aviation dependence on Kathmandu, it represents a new chapter in Himalayan connectivity.`,
    story: `<p>On the first day of 2023, Nepal inaugurated a new gateway to the Himalaya. Pokhara International Airport — built at Chhinedanda on the hillside above the city at an elevation of approximately 800 metres — is the country's third international airport and, by far, its most modern, representing a USD 215 million investment in infrastructure that promises to reshape how visitors access the Gandaki region and its world-class trekking, adventure sports, and natural heritage.</p><p>The airport was conceived to solve a structural problem in Nepal's tourism geography. For decades, virtually all international arrivals to Nepal funnelled through Tribhuvan International Airport in Kathmandu — one of the world's most challenging commercial airports, notorious for its restricted airspace, short runway, and frequent weather closures. Pokhara, as Nepal's second city and primary adventure tourism hub, served millions of visitors annually but received them only after they had passed through Kathmandu and taken either a domestic flight or a seven-hour mountain road journey. The new airport changes this calculus entirely.</p><p>The facility is built to international standards with a 2,500-metre runway capable of accommodating wide-body aircraft, modern passenger terminals, and navigational equipment suited to the complex mountain environment. Its position on the hillside affords arriving and departing passengers extraordinary views of the Annapurna massif, Machhapuchhre, Dhaulagiri, and Manaslu — a Himalayan panorama that unfolds through the terminal windows and makes even the most seasoned travellers reach for their cameras.</p><p>The broader significance of the airport extends beyond convenience. By enabling direct international connections to Pokhara, it opens the possibility of a genuinely distributed Nepal tourism economy in which the Gandaki region, the Mustang corridor, and the Annapurna trekking zones can receive visitors without the bottleneck of Kathmandu. For the adventure travel industry — paragliding, trekking, white-water rafting, ultra-running — this represents a generational shift in accessibility, and Pokhara's future as a world-class outdoor destination has never looked more firmly established.</p>`,
    district: `Kaski`,
    province: "GANDAKI",
    lat: 28.1994,
    lng: 83.9784,
    elevation: 800,
    entryFee: `Standard airport taxes apply`,
    bestSeason: `Year-round (best mountain views October to April)`,
    openingHours: `24-hour facility; flight schedules vary`,
    howToGetThere: `Located at Chhinedanda, Pokhara; approximately 20 min drive from Pokhara Lakeside. Direct international and domestic flights.`,
    trekDays: null,
    trekDifficulty: null,
    trekMaxElevation: null,
    trekDistance: null,
    trekStartPoint: null,
    trekEndPoint: null,
    trekHighlights: [],
    gygQuery: `Pokhara International Airport Nepal Gandaki`,
    bookingCity: `Pokhara`,
    seoTitle: `Pokhara International Airport | Nepal's New Himalayan Gateway 2023`,
    seoDescription: `Pokhara International Airport, opened January 2023, is Nepal's newest aviation hub at 800 m with dramatic Annapurna views. Learn about flights, facilities, and how this airport is transforming Nepal's tourism access.`,
    published: true,
    featured: false,
  },
  {
    name: `Annapurna Conservation Area`,
    category: "NATIONAL_PARK",
    summary: `Spanning 7,629 sq km across five districts of the Gandaki region, the Annapurna Conservation Area is one of the world's largest protected areas and Nepal's most visited trekking destination. From subtropical valleys to the Trans-Himalayan plateau of Mustang, it encompasses the full range of Nepal's ecological and cultural diversity, including the classic Annapurna Circuit and Base Camp treks.`,
    story: `<p>If there is a single protected landscape that encapsulates the full sweep of what makes Nepal extraordinary, it is the Annapurna Conservation Area. Covering 7,629 square kilometres across the districts of Kaski, Manang, Mustang, Myagdi, and Lamjung in the Gandaki Province, it is Nepal's largest conservation area and one of the most ecologically and culturally diverse protected territories anywhere on earth.</p><p>The conservation area spans an ecological gradient that astonishes botanists, zoologists, and trekkers alike. At its southern margins, subtropical forests of oak, rhododendron, and fern shelter barking deer, leopards, and hundreds of bird species. As elevation increases through the middle hills, temperate forests give way to alpine meadows and then to the dramatic bare landscapes above the treeline, where snow leopards hunt blue sheep across rocky slopes at 4,000 to 5,000 metres. Beyond the great Himalayan barrier, the conservation area extends into the rain-shadow plateau of Upper Mustang — an arid, wind-scoured landscape of ochre cliffs and Buddhist monasteries that has more in common with Tibet than with the Nepal of popular imagination.</p><p>The human geography is equally remarkable. Gurung, Magar, Thakali, Tibetan, and Manange communities inhabit the conservation area's valleys, each maintaining distinct languages, religions, architectural traditions, and agricultural practices shaped by their specific altitude and ecology. The Thakali people of the Kali Gandaki Valley are famous across Nepal for their cooking — a sophisticated cuisine that blends Tibetan and Nepali influences and produces some of the finest dal bhat and buckwheat pancakes in the Himalaya.</p><p>Trekking infrastructure within the Annapurna Conservation Area is the most developed in Nepal. The Annapurna Circuit — one of the world's great trekking routes — circles the entire Annapurna massif, crossing the Thorong La pass at 5,416 metres. The Annapurna Base Camp trek reaches the inner sanctuary of the Annapurna range at 4,130 metres. The Ghorepani-Poon Hill route offers extraordinary mountain views for less experienced trekkers. The ACAP permit, required for all visitors, funds conservation programmes and community development initiatives that have made Annapurna Conservation Area one of the world's models for integrated mountain conservation and sustainable tourism.</p>`,
    district: `Kaski`,
    province: "GANDAKI",
    lat: 28.5983,
    lng: 83.82,
    elevation: 8091,
    entryFee: `NPR 3,000 foreigners (ACAP permit); SAARC NPR 1,000`,
    bestSeason: `March to May, September to November`,
    openingHours: `Open year-round`,
    howToGetThere: `Fly or drive to Pokhara; most treks enter via Nayapul (Annapurna BC), Besisahar (Circuit), or Ghandruk.`,
    trekDays: 14,
    trekDifficulty: "MODERATE",
    trekMaxElevation: 5416,
    trekDistance: 160,
    trekStartPoint: `Besisahar or Nayapul`,
    trekEndPoint: `Pokhara or Nayapul`,
    trekHighlights: [`Thorong La Pass (5,416 m) on the Annapurna Circuit`, `Annapurna Base Camp (4,130 m) in the inner Himalayan sanctuary`, `Poon Hill sunrise (3,210 m) — Nepal's most iconic mountain panorama`, `Kali Gandaki Gorge — world's deepest river gorge`, `Upper Mustang trans-Himalayan plateau and ancient monasteries`, `Diverse ecosystems from subtropical forest to alpine desert`, `Gurung, Thakali, and Manange cultural villages`],
    gygQuery: `Annapurna Conservation Area trek Nepal ACAP`,
    bookingCity: `Pokhara`,
    seoTitle: `Annapurna Conservation Area Nepal | Trekking, Permits & Complete Guide`,
    seoDescription: `Explore Nepal's Annapurna Conservation Area — 7,629 sq km of protected Himalayan landscape encompassing the Annapurna Circuit, Base Camp trek, Poon Hill, and Upper Mustang. Permits, seasons, and route guide.`,
    published: true,
    featured: false,
  },
  {
    name: `Machhapuchhre Base Camp`,
    category: "MOUNTAIN_VIEW",
    summary: `Machhapuchhre Base Camp (MBC) sits at 3,700 metres in the heart of the Annapurna Sanctuary, a natural amphitheatre ringed by some of the world's highest peaks. The last major stop before Annapurna Base Camp, MBC offers unrivalled close-up views of the sacred 'Fishtail Mountain' (Machhapuchhre, 6,993 m) — a peak that has never been summited and whose vertical south face towers directly above the camp.`,
    story: `<p>There are campsites in the Himalaya that feel like the centre of the world, and Machhapuchhre Base Camp is one of them. Positioned at 3,700 metres in the upper Modi Khola valley, within the natural amphitheatre known as the Annapurna Sanctuary, MBC sits at the convergence of several of the planet's most dramatic mountain faces, each visible with an immediacy that no viewpoint at distance can replicate.</p><p>The mountain that gives the camp its name — Machhapuchhre, 'Fishtail Mountain' — rises to 6,993 metres directly above, its twin summits creating the distinctive silhouette that defines Pokhara's skyline. The mountain holds a unique status in Himalayan mountaineering: it has been climbed only once in the modern era (by Wilfrid Noyce in 1957, who stopped just below the summit as promised), and the Nepali government has since banned all ascents of Machhapuchhre out of respect for its sanctity to the Hindu god Shiva. Seeing the mountain from directly below its south face, comprehending its sheer scale, is one of the great experiences of Himalayan trekking.</p><p>The journey to MBC follows the well-established Annapurna Base Camp (ABC) trail from Pokhara via Ghandruk or Chhomrong. As trekkers ascend through rhododendron forest, then bamboo groves, then open alpine terrain, the valley narrows and the surrounding peaks — Hiunchuli, Annapurna South, and finally Machhapuchhre itself — close in above the trail. The transition into the Annapurna Sanctuary, through the narrow gorge above Hinku Cave, is a genuinely dramatic moment.</p><p>MBC serves as the final acclimatisation stop before Annapurna Base Camp (4,130 m), approximately two to three hours above. Many trekkers spend the night here, waking to a dawn that illuminates the surrounding peaks — Annapurna I (8,091 m), Annapurna South, Gangapurna, and Machhapuchhre itself — in a colour sequence from deep navy to violet, rose, gold, and brilliant white that has converted countless visitors to lifelong devotees of the high Himalaya.</p>`,
    district: `Kaski`,
    province: "GANDAKI",
    lat: 28.5267,
    lng: 83.8981,
    elevation: 3700,
    entryFee: `Covered by ACAP permit (NPR 3,000 foreigners)`,
    bestSeason: `March to May, September to November`,
    openingHours: `Open year-round (trail may close during heavy snowfall)`,
    howToGetThere: `Trek from Pokhara via Nayapul-Ghandruk or Phedi-Chhomrong; approximately 5-7 days one way depending on route.`,
    trekDays: 10,
    trekDifficulty: "MODERATE",
    trekMaxElevation: 4130,
    trekDistance: 110,
    trekStartPoint: `Nayapul or Phedi (Pokhara)`,
    trekEndPoint: `Nayapul or Phedi (Pokhara)`,
    trekHighlights: [`Close-up view of Machhapuchhre (6,993 m) south face from base camp`, `Entry into the Annapurna Sanctuary — a natural mountain amphitheatre`, `Annapurna Base Camp (4,130 m) with 360-degree Himalayan panorama`, `Rhododendron forests in bloom (March-April)`, `Sunrise on Annapurna I, the world's tenth-highest peak`, `Gurung villages of Ghandruk and Chhomrong along the approach`, `Himalayan Tahr and Himalayan Griffon vulture sightings`],
    gygQuery: `Machhapuchhre Base Camp Annapurna trek Nepal`,
    bookingCity: `Pokhara`,
    seoTitle: `Machhapuchhre Base Camp Nepal | Fishtail Mountain Trek Guide`,
    seoDescription: `Trek to Machhapuchhre Base Camp (3,700 m) in the Annapurna Sanctuary — an unforgettable viewpoint directly beneath Nepal's sacred Fishtail Mountain. Complete guide to the MBC trek, route, and best season.`,
    published: true,
    featured: false,
  },
]

async function main() {
  console.log('🌱 Seeding batch 11 — 20 places...')
  for (const p of places) {
    const s = slug(p.name)
    await prisma.place.upsert({
      where: { slug: s },
      update: {},
      create: { ...p, slug: s },
    })
    console.log('  ✅', p.name)
  }
  console.log('🌱 Batch 11 complete!')
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
