import 'dotenv/config'
import { PrismaClient } from '@prisma/client'
import slugify from 'slugify'

const prisma = new PrismaClient()
const slug = (n) => slugify(n, { lower: true, strict: true })

const places = [
  {
    name: "Sindhupalchok District",
    category: "CULTURAL_VILLAGE",
    summary: "Sindhupalchok is a scenic district in Bagmati Province northeast of Kathmandu, drained by the Melamchi and Indrawati river valleys and bordered by Tibet to the north. It shelters ancient pilgrimage sites, traditional Tamang and Sherpa villages, and moving earthquake memorial sites from the devastating 2015 earthquake. The district serves as the gateway to high alpine treks, sacred lakes, and the Helambu region.",
    story: `<p>Sindhupalchok District, covering 2,542 km² along the upper Indrawati and Melamchi river valleys, has been inhabited since antiquity by Tamang, Sherpa, Newar, and Brahmin communities whose temples and gompas punctuate every ridge. The Melamchi River—now famous for the Melamchi Water Supply Project that delivers water to Kathmandu—has for centuries been a pilgrimage and trade corridor between the Kathmandu Valley and Tibet.</p><p>The district was among the hardest hit by the April 2015 Gorkha Earthquake: entire villages like Barpak and Langtang were buried or destroyed. Today, rebuilt villages and quiet memorial sites around Sindhupalchok tell the story of resilience, with many communities constructing earthquake-resistant homes while preserving traditional Newari and Tibetan-influenced architecture. The Tatopani hot springs near the Chinese border and the Indreshwar Mahadev temple in Melamchi are important pilgrimage draws.</p><h3>Highlights</h3><ul><li>Melamchi River valley walks and village homestays</li><li>Indreshwar Mahadev Temple, one of the most sacred Shiva shrines in the region</li><li>Earthquake memorial sites and rebuilt resilient communities</li><li>Gateway to Panch Pokhari, Helambu, and Jugal Himal treks</li><li>Tatopani (hot springs) near the Nepal–Tibet border at Kodari</li></ul>`,
    district: "Sindhupalchok",
    province: "BAGMATI",
    lat: 27.7833,
    lng: 85.7,
    elevation: 846,
    entryFee: "Free (national park/trek permits apply separately)",
    bestSeason: "March\u2013May and September\u2013November",
    openingHours: "Open year-round",
    howToGetThere: "Sindhupalchok is accessible by road from Kathmandu along the Araniko Highway (Kathmandu\u2013China road). Melamchi town is about 50 km (2 hours) northeast of Kathmandu by bus or private vehicle. Regular buses depart from Kathmandu's Sundhara and Chabahil bus parks. Jeeps and local buses connect further to Helambu and Jugal trailheads.",
    gygQuery: "Sindhupalchok day trip from Kathmandu",
    bookingCity: "Kathmandu",
    seoTitle: "Sindhupalchok District Nepal \u2013 Melamchi Valley, Pilgrimage Sites & Earthquake Memorials",
    seoDescription: "Explore Sindhupalchok district northeast of Kathmandu: scenic Melamchi river valley, ancient pilgrimage temples, Tamang villages, earthquake memorial sites, and trailheads for Helambu and Panch Pokhari treks.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Panch Pokhari",
    category: "LAKE",
    summary: "Panch Pokhari \u2014 literally 'five lakes' \u2014 is a cluster of five sacred alpine lakes at approximately 4,100 m elevation in the Sindhupalchok District, revered by both Hindus and Buddhists. The lakes are associated with the five Pandava brothers of the Mahabharata and draw thousands of pilgrims during the Janai Purnima festival each August. Surrounded by meadows within Langtang National Park, the site offers stunning Himalayan panoramas and a serene high-altitude wilderness.",
    story: `<p>Perched in the remote Bhotang area of Sindhupalchok District at around 4,100 metres, Panch Pokhari has been a revered pilgrimage destination for centuries. According to Hindu tradition the five lakes correspond to the five Pandava brothers — Yudhishthira, Bhima, Arjuna, Nakula, and Sahadeva — who meditated here during their exile in the Mahabharata. Buddhists equally venerate the site, and mani walls, prayer flags, and a small gompa at the lakeside bear witness to its dual spiritual identity.</p><p>The most spectacular time to visit is Janai Purnima (the full moon of Shrawan, usually August), when thousands of Hindu pilgrims make a barefoot overnight trek to bathe in the icy glacial waters, believing this purifies the soul and allows the annual sacred thread (janai) to be renewed. Buddhist devotees circle the lakes in meditation. For most of the year, however, the site is peacefully empty, accessible only to committed trekkers willing to endure steep ascents of 500–800 m per day.</p><h3>Highlights</h3><ul><li>Five sacred alpine glacial lakes at 4,100 m within Langtang National Park</li><li>Janai Purnima pilgrimage festival in August — one of Nepal's most dramatic high-altitude festivals</li><li>360-degree panorama of Jugal Himal, Langtang range, and surrounding peaks</li><li>Rich rhododendron and bamboo forests on the approach trail</li><li>Small Buddhist gompa and ancient mani walls beside the lakes</li></ul>`,
    district: "Sindhupalchok",
    province: "BAGMATI",
    lat: 28.0425,
    lng: 85.7161,
    elevation: 4100,
    entryFee: "Langtang National Park permit (NPR 3,000 foreigners), TIMS card required",
    bestSeason: "May\u2013June and September\u2013October; pilgrimage peak in August (Janai Purnima)",
    openingHours: "Open year-round; winter (Dec\u2013Feb) access difficult due to snow",
    howToGetThere: "Drive from Kathmandu to Chautara or Bhotang via the Araniko Highway (2\u20133 hours). The trek to Panch Pokhari takes 4\u20137 days depending on starting point; most itineraries begin from Bhotang or Gyalthum. All trekkers must hold a TIMS card and Langtang National Park entry permit obtainable in Kathmandu.",
    trekDays: 7,
    trekMaxElevation: 4100,
    trekDifficulty: "MODERATE",
    trekDistance: 55.0,
    trekStartPoint: "Bhotang / Gyalthum (Sindhupalchok)",
    trekEndPoint: "Panch Pokhari Lakes",
    trekHighlights: ["Five sacred alpine glacial lakes", "Janai Purnima pilgrimage festival", "Jugal Himal and Langtang range panoramas", "Dense rhododendron and bamboo forests", "Buddhist gompa and mani walls at lakeside", "Rich birdlife and possible red panda sightings"],
    gygQuery: "Panch Pokhari trek Sindhupalchok",
    bookingCity: "Kathmandu",
    seoTitle: "Panch Pokhari Trek \u2013 Five Sacred Alpine Lakes in Sindhupalchok, Nepal",
    seoDescription: "Trek to Panch Pokhari, five sacred glacial lakes at 4,100 m in Sindhupalchok's Langtang National Park. A deeply spiritual journey combining Himalayan wilderness with Hindu and Buddhist pilgrimage tradition.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Helambu Trek",
    category: "TREK_ROUTE",
    summary: "The Helambu Trek is a classic short trekking route winding through the culturally rich Helambu region north of Kathmandu, passing through Sherpani and Tamang villages, rhododendron forests, and high ridges with Himalayan views. Starting from Sundarijal and typically ending at Melamchi Bazaar in Sindhupalchok, the trek reaches a maximum elevation of 3,690 m at Tharepati. It is one of the most accessible multi-day treks from Kathmandu, requiring no high-altitude acclimatization.",
    story: `<p>Helambu — also called Yolmo — is a highland valley and cultural zone stretching north from the rim of the Kathmandu Valley into the lower flanks of the Jugal and Langtang massifs. The people of Helambu, known as Hyolmo or Sherpa, maintain a rich tradition of Tibetan Buddhism: gompas with painted murals, prayer-flag-draped ridges, and chortens line the trail. The trek begins at Sundarijal on the northeastern edge of Kathmandu, passes through Shivapuri National Park, and ascends to the high ridge at Chisapani before descending into the valley proper.</p><p>The route threads through villages like Kutumsang, Mangengoth, Tharepati (the highest point at 3,690 m), Tarke Gyang — the largest settlement in Helambu — and Sermathang, before dropping to Melamchi Bazaar in Sindhupalchok. Each village offers a window into a way of life little changed for centuries: yak cheese making, hand-woven textiles, and Buddhist monastery ceremonies. The forests burst into colour during spring with blooming rhododendrons of pink, red, and white.</p><h3>Highlights</h3><ul><li>Tharepati ridge (3,690 m) with sweeping views of Jugal Himal and Langtang peaks</li><li>Tarke Gyang gompa — the spiritual heart of the Helambu region</li><li>Dense rhododendron and oak forests through Shivapuri National Park</li><li>Authentic Hyolmo (Sherpa) village culture and Buddhist monasteries</li><li>Chisapani viewpoint with sunrise panoramas over the Kathmandu Valley</li><li>Relative solitude compared to Everest and Annapurna circuits</li></ul>`,
    district: "Sindhupalchok",
    province: "BAGMATI",
    lat: 27.9167,
    lng: 85.5833,
    elevation: 3690,
    entryFee: "TIMS card (NPR 2,000 foreigners), Shivapuri National Park entry (NPR 500 foreigners)",
    bestSeason: "March\u2013May and September\u2013November",
    openingHours: "Open year-round; trails may be snowy December\u2013February above 3,000 m",
    howToGetThere: "Sundarijal is 17 km northeast of Kathmandu. Take a local bus or taxi from Koteshwor or Chabahil to Sundarijal (30\u201345 minutes). The trek ends at Melamchi Bazaar from where buses return to Kathmandu (2\u20133 hours).",
    trekDays: 7,
    trekMaxElevation: 3690,
    trekDifficulty: "MODERATE",
    trekDistance: 72.0,
    trekStartPoint: "Sundarijal, Kathmandu",
    trekEndPoint: "Melamchi Bazaar, Sindhupalchok",
    trekHighlights: ["Tharepati ridge with Jugal Himal panoramas", "Tarke Gyang gompa and Hyolmo village culture", "Rhododendron forests in Shivapuri National Park", "Chisapani sunrise viewpoint", "Traditional Sherpa/Hyolmo homestays", "Low-altitude route suitable for beginners"],
    gygQuery: "Helambu trek Kathmandu",
    bookingCity: "Kathmandu",
    seoTitle: "Helambu Trek Nepal \u2013 7-Day Route from Sundarijal to Melamchi through Hyolmo Villages",
    seoDescription: "The Helambu Trek is the ideal short trekking adventure from Kathmandu: 7 days through Shivapuri forest, Hyolmo Sherpa villages, and high ridges reaching 3,690 m, with stunning Himalayan views and authentic Buddhist culture.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Langtang Valley Trek",
    category: "TREK_ROUTE",
    summary: "The Langtang Valley Trek is one of Nepal's most celebrated short-to-medium treks, following the Langtang River deep into a glaciated valley flanked by Langtang Lirung (7,227 m) and a wall of Himalayan giants just south of the Tibetan border. The standard 8-day route from Syabrubesi passes Lama Hotel, the rebuilt Langtang Village, and Kyanjin Gompa at 3,870 m \u2014 home to a famous yak cheese factory and the optional ascent of Tserko Ri at 4,984 m. The valley lies entirely within Langtang National Park.",
    story: `<p>Langtang Valley was Nepal's 'third most popular trekking region' before April 2015, when a catastrophic earthquake-triggered avalanche obliterated Langtang Village, killing more than 350 people. The rebuilt village now stands as a testament to Tamang resilience, with new stone houses, a rebuilt gompa, and a growing memorial site for those who perished. The road to recovery has slowly brought trekkers back, and the valley's raw, uncrowded beauty — rated by many as the finest in Nepal for scenery per day of walking — rewards those who make the journey.</p><p>Leaving Syabrubesi (1,460 m), the trail climbs through semi-tropical forest to Lama Hotel (2,470 m), then ascends the dramatic U-shaped glacial valley past waterfalls and cliffs patrolled by grey langur monkeys and red pandas. Langtang Village (3,430 m) and Kyanjin Gompa (3,870 m) sit beneath an almost vertical wall of ice: Langtang Lirung rises over 3,000 m in a single sweep from the valley floor. The Kyanjin cheese factory, established by the Swiss Development Corporation in the 1950s, still produces yak cheese you can taste and buy.</p><h3>Highlights</h3><ul><li>Kyanjin Gompa and 360° Himalayan views from Tserko Ri (4,984 m)</li><li>Langtang Lirung (7,227 m) and Kimshung glacier views</li><li>Yak cheese factory at Kyanjin — a unique tasting experience</li><li>Rebuilt Langtang Village and earthquake memorial site</li><li>Rich wildlife: red panda, snow leopard, Himalayan tahr</li><li>Tamang village culture, mani walls, and Buddhist monasteries</li></ul>`,
    district: "Rasuwa",
    province: "BAGMATI",
    lat: 28.2115,
    lng: 85.5169,
    elevation: 3870,
    entryFee: "Langtang National Park permit (NPR 3,000 foreigners), TIMS card (NPR 2,000 foreigners)",
    bestSeason: "March\u2013May and September\u2013November",
    openingHours: "Open year-round; Kyanjin area can have heavy snow November\u2013February",
    howToGetThere: "Drive from Kathmandu to Syabrubesi (120 km, 7\u20139 hours by bus/jeep via Dhunche). Daily tourist buses depart Kathmandu's Machhapokhari bus park early morning. Alternatively, fly to Kathmandu and hire a private jeep (5\u20136 hours). The trek begins at Syabrubesi (1,460 m).",
    trekDays: 8,
    trekMaxElevation: 4984,
    trekDifficulty: "MODERATE",
    trekDistance: 65.0,
    trekStartPoint: "Syabrubesi (1,460 m)",
    trekEndPoint: "Syabrubesi (return, or Sundarijal via Helambu circuit)",
    trekHighlights: ["Tserko Ri (4,984 m) panoramic viewpoint", "Langtang Lirung (7,227 m) and Kimshung glacier", "Kyanjin Gompa and yak cheese factory", "Earthquake memorial at Langtang Village", "Red panda and Himalayan wildlife", "Tamang culture and ancient Buddhist monasteries"],
    gygQuery: "Langtang Valley trek Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Langtang Valley Trek Nepal \u2013 8-Day Classic Route to Kyanjin Gompa & Tserko Ri",
    seoDescription: "Trek deep into the Langtang Valley: 8 days from Syabrubesi to Kyanjin Gompa beneath Langtang Lirung (7,227 m). Discover rebuilt Tamang villages, a yak cheese factory, and summit Tserko Ri for 360\u00b0 Himalayan views inside Langtang National Park.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Sundarijal",
    category: "WATERFALL",
    summary: "Sundarijal is a scenic village and waterfall 17 km northeast of Kathmandu, sitting at the entrance to Shivapuri Nagarjun National Park at 1,350 m elevation. The dramatic cascade of the Bagmati River tributary makes it a popular weekend destination for Kathmandu residents, while the village also serves as the primary trailhead for the Helambu and Chisapani treks. Sundarijal's water reservoir supplies a significant portion of Kathmandu Valley's drinking water.",
    story: `<p>Sundarijal — meaning 'beautiful water' in Nepali — lives up to its name with a striking waterfall that plunges down a rocky gorge flanked by dense forest on the northeastern rim of the Kathmandu Valley. The area has been designated part of Shivapuri Nagarjun National Park, protecting its watershed function and the rich biodiversity of its subtropical and temperate forest zones. For generations, Kathmandu residents have made day trips here to picnic, bathe, and escape the capital's dust and noise.</p><p>Beyond the waterfall, Sundarijal is Nepal's most convenient trek starting point: within 30 minutes of reaching the village from the city, trekkers can be on forest trails that within a day ascend to Chisapani ridge with sweeping Himalayan sunrise views. The trail continues into the Helambu region and can connect with the Langtang circuit via Gosaikunda. The national park entry checkpoint here also marks the boundary of the protected watershed that feeds the Sundarijal water treatment plant, which supplies roughly a third of Kathmandu's drinking water.</p><h3>Highlights</h3><ul><li>Sundarijal Waterfall — dramatic cascade in a forested gorge</li><li>Trailhead for Helambu, Chisapani, and Gosaikunda treks</li><li>Shivapuri Nagarjun National Park wildlife and birdwatching</li><li>Kathmandu Valley viewpoint from Chisapani (2,165 m) within a day's hike</li><li>Easy 30–45 minute drive from central Kathmandu</li></ul>`,
    district: "Kathmandu",
    province: "BAGMATI",
    lat: 27.7675,
    lng: 85.4234,
    elevation: 1350,
    entryFee: "Shivapuri Nagarjun National Park: NPR 500 foreigners, NPR 50 Nepalis",
    bestSeason: "Year-round; monsoon (June\u2013August) gives fullest waterfall; autumn and spring for trekking",
    openingHours: "Park gate: 7:00 AM \u2013 5:00 PM daily",
    howToGetThere: "From central Kathmandu take a local microbus or tempo from Chabahil or Koteshwor to Sundarijal (30\u201345 minutes, ~NPR 30). Taxis from Thamel cost approximately NPR 600\u2013800 one way. The route follows the Maharajgunj\u2013Baudha\u2013Gokarna\u2013Sundarijal road.",
    gygQuery: "Sundarijal waterfall day trip Kathmandu",
    bookingCity: "Kathmandu",
    seoTitle: "Sundarijal Waterfall & Trek Kathmandu \u2013 Day Trip Guide, Entry Fee & Trail Info",
    seoDescription: "Visit Sundarijal, Kathmandu's favourite waterfall and trek gateway inside Shivapuri National Park. Just 17 km from the city, it is the starting point for the Helambu and Chisapani treks with stunning Himalayan valley views.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Nagarkot Sunrise Trek",
    category: "HILL_VIEWPOINT",
    summary: "Nagarkot is a celebrated hill station at 2,175 m on the northeastern rim of the Kathmandu Valley, renowned for offering one of the broadest Himalayan panoramas in central Nepal \u2014 from Dhaulagiri in the west to Kanchenjunga in the east, with Everest visible on clear days. The sunrise viewpoint, complete with a tower at 2,164 m, draws visitors from Kathmandu for early morning mountain views, and the ridgeline connects to the Nagarkot\u2013Changu Narayan hiking trail. It is classified as a HILL_VIEWPOINT destination with optional overnight stays in mountain resort hotels.",
    story: `<p>Nagarkot has been attracting sunrise-seekers since the early days of Nepal's tourism industry, and with good reason: the hill station sits at a 'sweet spot' on the Kathmandu Valley rim where the valley's eastern edge opens to an almost unobstructed 160-km arc of Himalayan peaks. On a clear morning, the pink and gold alpenglow lights up eight distinct mountain ranges simultaneously. The village is quiet, with small hotels and lodges lining the ridge and little motorized traffic to disturb the pre-dawn atmosphere.</p><p>Beyond the sunrise spectacle, Nagarkot offers a rewarding day hike westward along the forested ridge to the ancient Changu Narayan temple (a UNESCO World Heritage Site), descending to Bhaktapur — a classic 12–15 km traverse that passes through Tamang villages, rhododendron groves, and viewpoints above the valley's patchwork of rice terraces and brick-kiln towns. During spring, the trail is lined with blooming rhododendrons. A shorter early-morning options includes a 2-hour hike directly from the bus park to the main viewpoint tower.</p><h3>Highlights</h3><ul><li>360-degree Himalayan panorama including Everest, Annapurna, and Manaslu</li><li>Sunrise viewpoint tower at 2,164 m on the valley rim</li><li>Nagarkot to Changu Narayan day hike (12–15 km)</li><li>Peaceful hill station resort atmosphere</li><li>Rhododendron forests in spring bloom</li><li>8 mountain ranges visible on clear days</li></ul>`,
    district: "Bhaktapur",
    province: "BAGMATI",
    lat: 27.7167,
    lng: 85.5167,
    elevation: 2175,
    entryFee: "Free to access Nagarkot; viewpoint tower entry ~NPR 50",
    bestSeason: "October\u2013November and March\u2013April for clearest skies; also June for monsoon mist atmosphere",
    openingHours: "Open year-round; sunrise viewpoint best visited 5:30\u20137:00 AM",
    howToGetThere: "Nagarkot is 32 km east of Kathmandu. Take a local bus from Bhaktapur (Kausi bus park) to Nagarkot (1\u20131.5 hours, NPR 60). Alternatively hire a taxi from Kathmandu (NPR 2,000\u20132,500 one way, 1.5 hours). Tourist buses also run directly from Thamel in the morning.",
    gygQuery: "Nagarkot sunrise tour Kathmandu",
    bookingCity: "Kathmandu",
    seoTitle: "Nagarkot Sunrise Trek Nepal \u2013 Best Himalayan Viewpoint East of Kathmandu",
    seoDescription: "Wake before dawn at Nagarkot (2,175 m) for one of Nepal's most breathtaking Himalayan panoramas \u2014 eight mountain ranges including Everest visible on clear mornings. Combine with a day hike to UNESCO-listed Changu Narayan temple.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Manaslu Circuit Trek",
    category: "TREK_ROUTE",
    summary: "The Manaslu Circuit Trek is a spectacular 14-day wilderness route that circumnavigates Mount Manaslu (8,163 m), the world's eighth-highest peak, through the restricted Manaslu Conservation Area in Gorkha District. The trail follows the Budhi Gandaki River gorge, passes through Tibetan-influenced Nubri and Tsum villages, and crosses the dramatic Larkya La Pass (5,106 m) before descending into the Annapurna Conservation Area. Far less crowded than Everest or Annapurna, it combines high-mountain scenery, glacier crossings, and authentic Himalayan culture.",
    story: `<p>The Manaslu Circuit remained off-limits to foreign trekkers until 1991, and its restricted-area status — requiring a special permit and a minimum group of two with a licensed guide — has kept it blessedly crowd-free compared to Nepal's other classic circuits. The route begins at Machha Khola (869 m) after a long drive from Gorkha, then follows the great gorge of the Budhi Gandaki for days through subtropical jungle, suspension bridges, and waterfalls before the landscape opens into the high Himalayan zone. The village of Samagaun (3,520 m) serves as a rest and acclimatization day, with an optional side trek to Manaslu Base Camp (4,800 m) beneath the icy south face of Manaslu itself.</p><p>The physical and emotional climax is the crossing of Larkya La Pass (5,106 m): a pre-dawn start from Dharamsala (4,470 m) through moraine and glacier leads to the windswept col, from which the panorama of Himlung (7,126 m), Kanguru (6,981 m), Annapurna II (7,937 m), and dozens of other giants unfolds. The descent into the Annapurna zone feels like entering a different world — greener, warmer, and busier. Most trekkers complete the circuit by exiting at Dharapani and driving to Pokhara or Kathmandu.</p><h3>Highlights</h3><ul><li>Larkya La Pass (5,106 m) — the dramatic high-altitude crossing</li><li>Manaslu Base Camp optional day trip from Samagaun</li><li>Budhi Gandaki gorge — one of Nepal's deepest and most scenic river canyons</li><li>Tibetan-Buddhist villages of Lho, Samagaun, and Samdo with ancient gompas</li><li>Views of Manaslu (8,163 m), Ganesh Himal, and Annapurna ranges</li><li>Red-panda habitat and rich alpine wildlife</li><li>Restricted area status ensuring low trekker density</li></ul>`,
    district: "Gorkha",
    province: "GANDAKI",
    lat: 28.55,
    lng: 84.56,
    elevation: 5106,
    entryFee: "Restricted Area Permit (USD 100/week), Manaslu Conservation Area Permit (NPR 3,000), ACAP (NPR 3,000), TIMS card",
    bestSeason: "March\u2013May and September\u2013November",
    openingHours: "Open year-round; Larkya La may be impassable December\u2013February",
    howToGetThere: "Drive from Kathmandu to Gorkha (140 km, 4\u20135 hours) then to Arughat or Machha Khola (another 2\u20133 hours by jeep). Alternatively, drive via Beshisahar. Most trekkers hire a guide and arrange transport through Kathmandu trekking agencies. A licensed guide is mandatory.",
    trekDays: 14,
    trekMaxElevation: 5106,
    trekDifficulty: "HARD",
    trekDistance: 177.0,
    trekStartPoint: "Machha Khola (869 m), Gorkha District",
    trekEndPoint: "Dharapani / Beshisahar, Lamjung",
    trekHighlights: ["Larkya La Pass (5,106 m) glacier crossing", "Manaslu Base Camp (4,800 m) side trip", "Budhi Gandaki gorge and canyon scenery", "Tibetan-Buddhist Nubri villages (Lho, Samagaun, Samdo)", "Manaslu (8,163 m) and Himlung (7,126 m) views", "Restricted area solitude \u2014 far fewer trekkers than Annapurna/Everest", "Confluence with Annapurna Circuit at Dharapani"],
    gygQuery: "Manaslu Circuit Trek Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Manaslu Circuit Trek 14 Days \u2013 Larkya La Pass & Mt Manaslu, Gorkha Nepal",
    seoDescription: "Circumnavigate 8,163 m Mt Manaslu on this spectacular 14-day restricted-area trek through Budhi Gandaki gorge and Tibetan-Buddhist Nubri villages, crossing Larkya La Pass (5,106 m) for breathtaking Himalayan views.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Tsum Valley Trek",
    category: "TREK_ROUTE",
    summary: "Tsum Valley is a remote, culturally preserved Tibetan-Buddhist valley in northern Gorkha District, closed to foreigners until 2008 and still accessible only with a restricted-area permit and licensed guide. The valley's inhabitants practice Shyagya \u2014 a centuries-old tradition of total non-violence \u2014 meaning no animals are hunted or slaughtered, giving the valley an almost otherworldly sense of harmony. Key sites include Mu Gompa, Rachen Gompa, and the Milarepa meditation cave at Piren Phu.",
    story: `<p>Tsum Valley — known as 'Tsum' from the Tibetan word for vivid or clear — occupies a remote northern corridor of Gorkha District between the Ganesh Himal to the west and Sringi Himal to the east, sharing a border with Tibet. For centuries it functioned as a self-contained Buddhist kingdom governed by non-violence: the Tsumba people have never hunted animals or eaten meat killed within the valley, making it a sanctuary for wildlife and a living example of Buddhist ecology. Foreigners were excluded until 2008, and even today the mandatory licensed guide and restricted permit protect the valley's fragile culture from mass tourism.</p><p>The standard trek combines with the Manaslu Circuit, branching north from Jagat into the Tsum corridor. Days pass slowly through ancient village clusters of Chhokangparo, Nile, and Chhule, with walls of carved mani stones lining every trail. The twin monasteries of Mu Gompa (3,700 m) — home to hundreds of monks and nuns — and Rachen Gompa, with its particularly fine thangka paintings, are the valley's spiritual anchors. The trek can be extended to the Ngula Dhojhyang Pass (5,093 m) on the Tibetan border for extraordinary mountain views.</p><h3>Highlights</h3><ul><li>Mu Gompa — the largest monastery in the Manaslu region</li><li>Rachen Gompa with ancient thangka paintings and nunnery</li><li>Milarepa meditation cave at Piren Phu</li><li>Shyagya non-violence tradition — exceptional wildlife encounters</li><li>Ngula Dhojhyang Pass (5,093 m) with Tibet border views</li><li>Immaculate mani walls, chortens, and traditional Tsumba architecture</li></ul>`,
    district: "Gorkha",
    province: "GANDAKI",
    lat: 28.7,
    lng: 84.85,
    elevation: 3700,
    entryFee: "Restricted Area Permit (USD 35\u201350/week), MCAP (NPR 3,000), TIMS card; minimum 2 trekkers + licensed guide required",
    bestSeason: "March\u2013May and September\u2013November",
    openingHours: "Open year-round; winter access limited by high passes",
    howToGetThere: "Drive from Kathmandu to Arughat via Gorkha (5\u20136 hours), then continue to Jagat or Machha Khola by jeep on the Budhi Gandaki road. The Tsum Valley branch trail begins at Jagat. Most trekkers arrange the full package through Kathmandu trekking agencies. A licensed guide is legally mandatory.",
    trekDays: 16,
    trekMaxElevation: 5093,
    trekDifficulty: "HARD",
    trekDistance: 150.0,
    trekStartPoint: "Machha Khola / Jagat, Gorkha District",
    trekEndPoint: "Machha Khola (loop), or continue on Manaslu Circuit",
    trekHighlights: ["Mu Gompa \u2014 largest monastery in Manaslu region", "Rachen Gompa nunnery with ancient thangkas", "Milarepa meditation cave (Piren Phu)", "Shyagya non-violence tradition and wildlife sanctuary", "Ngula Dhojhyang Pass (5,093 m) Tibet border views", "Traditional Tsumba culture and mani wall corridors", "Combination possible with Manaslu Circuit"],
    gygQuery: "Tsum Valley trek Gorkha Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Tsum Valley Trek Nepal \u2013 Sacred Hidden Buddhist Valley in Gorkha, 16 Days",
    seoDescription: "Explore the mystical Tsum Valley, a restricted Buddhist sanctuary in Gorkha's northern Himalayas unchanged for centuries. Trek to Mu Gompa, Rachen Gompa, and Milarepa's cave in one of Nepal's most culturally preserved wilderness valleys.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Gorkha Durbar",
    category: "DURBAR_PALACE",
    summary: "Gorkha Durbar is a magnificent hilltop palace-fortress complex in Gorkha town, Gandaki Province, built in the 16th century and birthplace of Prithvi Narayan Shah (1723\u20131775), the founder-king who unified Nepal. Perched at approximately 1,650 m on a dramatic ridge with sweeping views of the Himalayan range from Dhaulagiri to Manaslu, the complex blends palace, fortress, and temple in superb Newari architecture. It was partially damaged in the 2015 earthquake and restored, reopening in 2023.",
    story: `<p>Gorkha Durbar stands on a sharp sandstone ridge rising above Gorkha Bazaar, and for several centuries it was the nerve centre of the Gorkha kingdom — the small mountain principality from which Prithvi Narayan Shah launched his ambitious campaign to unify the fractious kingdoms of the Kathmandu Valley and beyond. Construction of the original palace is attributed to Ram Shah in the early 17th century, but it was Prithvi Narayan Shah, born here in 1723, who transformed Gorkha into the seat of a new Nepal. The climb of roughly 1,500 steep stone steps from the bazaar, or a shorter jeep route, arrives at a complex of temples, courtyards, and the royal chambers where Nepal's unification was planned.</p><p>The Gorakhkali Mandir inside the palace complex houses the goddess Kali and the shrine of Gorakhnath, the patron saint of the Gorkha rulers, from whom both the royal house and the famous Gurkha soldiers drew their name and identity. Non-Hindus may view the exterior of the inner shrine but not enter it. The palace suffered significant damage in the April 2015 earthquake, which caused masonry walls to collapse and the main tower to crack; extensive restoration by the Department of Archaeology, with support from international heritage partners, brought the complex back to visitors in late 2023.</p><h3>Highlights</h3><ul><li>Birthplace of Prithvi Narayan Shah — founding king of unified Nepal</li><li>Gorakhkali and Gorakhnath shrines with active religious rituals</li><li>Panoramic Himalayan views: Manaslu, Himlung, Annapurna range</li><li>Exceptional Newari woodcarving on windows, struts, and doors</li><li>Archaeological Museum of Gorkha with royal artifacts and coins</li><li>1,500-step stone stairway through rhododendron forest</li></ul>`,
    district: "Gorkha",
    province: "GANDAKI",
    lat: 28.0,
    lng: 84.6333,
    elevation: 1650,
    entryFee: "NPR 150 foreigners, NPR 25 Nepalis (approximate; verify locally)",
    bestSeason: "October\u2013November and February\u2013April",
    openingHours: "9:00 AM \u2013 5:00 PM daily",
    howToGetThere: "Gorkha town is 140 km northwest of Kathmandu (4\u20135 hours by bus or car via Prithvi Highway to Abu Khaireni, then north). Tourist buses run from Kathmandu to Gorkha Bazaar. From the bazaar, climb the stone steps (45\u201360 minutes on foot) or take a jeep to the upper parking and walk the final stretch.",
    gygQuery: "Gorkha Durbar palace tour Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Gorkha Durbar \u2013 Birthplace of Nepal's Founding King, Hilltop Palace-Fortress",
    seoDescription: "Visit Gorkha Durbar, the dramatic 16th-century hilltop palace-fortress that was birthplace of Prithvi Narayan Shah and command centre for Nepal's unification, with magnificent Himalayan views and superb Newari architecture.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Bandipur",
    category: "CULTURAL_VILLAGE",
    summary: "Bandipur is a beautifully preserved Newari hilltop market town at 1,030 m in Tanahun District, straddling the Mahabharat range between Kathmandu and Pokhara. Once an important trading post on the India\u2013Tibet route, the town was bypassed by the Prithvi Highway in the 1970s, accidentally freezing its architecture in time. Today its vehicle-free main bazaar of 19th-century Newari houses, Bindabasini temple, and sweeping Annapurna and Manaslu views make it one of Nepal's most charming heritage destinations.",
    story: `<p>Bandipur's golden era was the 19th and early 20th centuries, when Newari merchant families from the Kathmandu Valley settled here to trade along the strategic route connecting India's plains to Tibet's plateau. They built the robust, multi-storey brick townhouses with elaborately carved wooden windows and balconies that still line the main bazaar today. When the Prithvi Highway was routed through the valley below in 1972, trade shifted away, many families left, and Bandipur entered a long sleep. That neglect turned out to be Bandipur's greatest asset: the town's architectural heritage survived intact while other Himalayan trading towns modernized and lost their character.</p><p>Today Bandipur has reinvented itself as a model for responsible heritage tourism: the main bazaar is vehicle-free, several families have opened heritage guesthouses in restored Newari buildings, and a thriving community tourism program connects visitors with local artisans, farmers, and festivals. The Bindabasini Temple on the western bluff attracts Hindu pilgrims, while the cave system at Siddha Gupha (one of Nepal's largest caves) draws adventure seekers. In clear weather, the Annapurna and Manaslu massifs fill the northern horizon in one of the finest mountain panoramas accessible by road in Nepal.</p><h3>Highlights</h3><ul><li>Heritage bazaar street — vehicle-free 19th-century Newari architecture</li><li>Annapurna and Manaslu panorama from Tundikhel viewpoint</li><li>Bindabasini Temple and Khadga Devi Temple</li><li>Siddha Gupha cave — one of Nepal's largest limestone caverns</li><li>Thani Mai viewpoint for sunrise over Marsyangdi valley</li><li>Community-based heritage guesthouses and cultural programs</li></ul>`,
    district: "Tanahun",
    province: "GANDAKI",
    lat: 27.56,
    lng: 84.25,
    elevation: 1030,
    entryFee: "Free to enter Bandipur town; Siddha Gupha cave entry ~NPR 100",
    bestSeason: "October\u2013November and March\u2013May",
    openingHours: "Open year-round; village accessible at all hours",
    howToGetThere: "Bandipur is 143 km west of Kathmandu and 80 km east of Pokhara, just off the Prithvi Highway near Dumre. From Kathmandu take a Pokhara-bound bus to Dumre (3\u20134 hours), then a shared jeep or local bus up the ridge to Bandipur (30 minutes). Direct tourist vehicles from Kathmandu or Pokhara take 3\u20134.5 hours.",
    gygQuery: "Bandipur heritage village Nepal tour",
    bookingCity: "Pokhara",
    seoTitle: "Bandipur Nepal \u2013 Preserved Newari Hilltop Town with Annapurna Views, Tanahun",
    seoDescription: "Discover Bandipur, Nepal's best-preserved Newari hilltop market town in Tanahun district: vehicle-free heritage bazaar, sweeping Annapurna panoramas, Siddha Gupha cave, and authentic community heritage guesthouses between Kathmandu and Pokhara.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Tatopani Hot Springs",
    category: "HOT_SPRING",
    summary: "Tatopani \u2014 meaning 'hot water' \u2014 is a small village at 1,190 m on the Kali Gandaki River in Myagdi District (Mustang border area), famous for its natural geothermal hot spring pools that soothe weary muscles on the Annapurna Circuit. The hot springs at the confluence of the Kali Gandaki and Ghar Khola rivers are considered sacred, and the village has historically been an important stop for traders, pilgrims, and trekkers alike. Surrounded by orange and banana groves, it offers a lush microclimate in contrast to the high alpine terrain above.",
    story: `<p>Tatopani sits in one of the deepest river gorges on Earth — the Kali Gandaki corridor between Dhaulagiri and Annapurna creates the world's deepest valley measured from peak to river. At 1,190 m, Tatopani is dramatically warmer and lusher than the austere high-altitude terrain of the Annapurna Circuit above it, with terraced orange orchards and subtropical vegetation thriving in the sheltered gorge microclimate. The hot springs bubble up naturally at the bank of the Kali Gandaki, channelled into concrete pools where trekkers, pilgrims, and locals soak together in mineral-rich water reputed to ease joint pain and altitude-related fatigue.</p><p>Since the opening of the Beni–Jomsom motor road, Tatopani has become easily accessible by jeep from Beni, and many trekkers now use it as either a starting or ending point for treks into the Annapurna region. The village itself is a pleasant mix of Thakali guesthouses, small restaurants, and orchards. A significant annual fair draws pilgrims who make a ritual bath in the hot springs during major Hindu festivals. From Tatopani, the trail climbs steeply to Ghorepani and the famous Poon Hill sunrise viewpoint — making it a popular base for the Ghorepani–Poon Hill circuit as well as the longer Annapurna Circuit.</p><h3>Highlights</h3><ul><li>Natural geothermal hot spring pools at the Kali Gandaki riverside</li><li>Gateway to Ghorepani–Poon Hill trek (steep 1,700 m ascent)</li><li>Deepest river valley in the world — Kali Gandaki gorge between Dhaulagiri and Annapurna</li><li>Lush sub-tropical microclimate with orange, lemon, and banana trees</li><li>Thakali cuisine and traditional guesthouses</li><li>Sacred bathing festival during major Hindu holidays</li></ul>`,
    district: "Myagdi",
    province: "GANDAKI",
    lat: 28.4968,
    lng: 83.6538,
    elevation: 1190,
    entryFee: "Hot spring pool entry: NPR 200\u2013400 (approximate, paid to local management committee)",
    bestSeason: "October\u2013May; accessible year-round but road may be difficult in monsoon",
    openingHours: "Hot springs open 6:00 AM \u2013 8:00 PM daily",
    howToGetThere: "Drive from Pokhara to Beni (2\u20133 hours, 70 km) then by jeep or bus along the Kali Gandaki road to Tatopani (2\u20133 more hours, 60 km). Alternatively, reach Tatopani on foot via the Annapurna Circuit from Marpha (descending south) or from Ghorepani (descending north). The road is now accessible by jeep year-round in normal conditions.",
    gygQuery: "Tatopani hot springs Annapurna Nepal",
    bookingCity: "Pokhara",
    seoTitle: "Tatopani Hot Springs Nepal \u2013 Natural Geothermal Pools on the Annapurna Circuit, Myagdi",
    seoDescription: "Soak in Tatopani's legendary natural hot springs at 1,190 m on the Kali Gandaki River in Myagdi \u2014 the perfect muscle-soothing stop on the Annapurna Circuit, with access to Ghorepani\u2013Poon Hill and the world's deepest river gorge.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Bhaktapur Pottery Square",
    category: "CULTURAL_VILLAGE",
    summary: "Bhaktapur Pottery Square (Bolachha Tole / Kumha Tole) is a living open-air workshop in the heart of Bhaktapur city where Newar potters have practiced their craft for generations, shaping clay vessels on traditional foot-powered wheels in full view of visitors. The square is covered in drying pots, terracotta wares, and sacred items for festivals, using the unique black clay \u2014 called 'Dyo Cha' or 'clay of God' \u2014 that gives Bhaktapur pottery its distinctive quality and colour. It remains one of the most authentic artisan traditions in the Kathmandu Valley.",
    story: `<p>A short walk south of Bhaktapur Durbar Square, Bolachha Tole has been the domain of the Kumha (potter) caste for as long as Bhaktapur has existed. The square is not a museum or a performance — it is a working neighbourhood where terracotta production is the primary livelihood. Each morning, potters arrive to knead black clay (dug from specific fields blessed by tradition) and spin it into vases, water pots, temple oil lamps, and ritual funeral pots. The wet forms are arranged across every flat surface to dry in the sun before firing in the communal kilns that stand at the square's edges.</p><p>The craft holds deep religious significance in Nepal: Bhaktapur's potters supply terracotta wares for festivals across the Kathmandu Valley, including the massive Bisket Jatra and Indra Jatra celebrations that require hundreds of specially shaped clay vessels. The Bhaktapur Pottery Training Centre on the square's edge offers hands-on sessions where visitors can learn basic wheel-throwing techniques and take their creation home. Bhaktapur's ceramics are considered superior across the valley because of the exceptional quality of its local black clay, which fires to a warm reddish-black with excellent structural integrity.</p><h3>Highlights</h3><ul><li>Working terracotta workshop — watch master potters at foot-powered wheels</li><li>Try pottery-making yourself at the training centre (NPR 100–150)</li><li>Traditional firing kilns and outdoor drying grounds</li><li>Unique 'Dyo Cha' black clay tradition of Bhaktapur</li><li>Festival supply production — see ritual wares for Bisket Jatra</li><li>Small temples and chaityas within the square</li></ul>`,
    district: "Bhaktapur",
    province: "BAGMATI",
    lat: 27.6712,
    lng: 85.4284,
    elevation: 1400,
    entryFee: "Included in Bhaktapur entry fee (NPR 1,800 foreigners); Pottery Square itself is free within Bhaktapur",
    bestSeason: "Year-round; winter mornings and autumn light are best for photography",
    openingHours: "Potters work approximately 7:00 AM \u2013 6:00 PM; Training Centre 9:00 AM \u2013 6:00 PM daily",
    howToGetThere: "Bhaktapur is 13 km east of Kathmandu. Take a local bus or taxi to Bhaktapur Durbar Square, then walk south through the narrow lanes past Kedarnath temple for about 5\u201310 minutes to reach Pottery Square (Bolachha Tole). Taxis from Thamel cost approximately NPR 500\u2013700.",
    gygQuery: "Bhaktapur pottery square tour Kathmandu",
    bookingCity: "Kathmandu",
    seoTitle: "Bhaktapur Pottery Square \u2013 Living Terracotta Craft Tradition in Nepal's Ancient City",
    seoDescription: "Experience Bhaktapur's Pottery Square (Bolachha Tole) \u2014 a living open-air workshop where Newar potters shape sacred black clay on traditional wheels. Watch, learn, and try wheel-throwing in one of Kathmandu Valley's most authentic artisan traditions.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Changu Narayan Temple",
    category: "TEMPLE",
    summary: "Changu Narayan is Nepal's oldest standing Vishnu temple, built around the 4th century CE on a wooded hilltop in Bhaktapur District, and a UNESCO World Heritage Site since 1979. The two-tiered pagoda temple is richly adorned with exquisite stone, wood, and metal carvings spanning 1,500 years of Nepali art history, including some of the finest Lichhavi-era sculptures in existence. The hilltop setting at 1,543 m above the Kathmandu Valley offers fine views and a peaceful village atmosphere.",
    story: `<p>Changu Narayan's founding inscription — carved in stone and dated to 464 CE during the reign of Lichhavi King Mandeva — is the oldest stone inscription discovered in Nepal and transforms the temple from a merely beautiful place into one of the subcontinent's great historical documents. The deity within, Vishnu in his ten-armed Vishwarupa (cosmic) form, is one of the most complex and powerful representations of the god in Nepali art. Around the temple courtyard, stone sculptures accumulate like a museum of a thousand years: Vishnu astride his eagle Garuda, Vishnu reclining on the serpent Ananta, Vishnu as the man-lion Narasimha, and dozens of other manifestations, each carved with extraordinary skill.</p><p>The temple was rebuilt after a fire in 1702 but incorporates stone elements and inscriptions from its earliest phases. The double-tiered roof carries copper gilding, and the wooden struts are carved with deities, erotic scenes (serving an apotropaic function), and mythological narratives that would take days to fully decipher. The hilltop village around the temple retains a quiet, traditional character: Newar craftspeople sell thangka paintings and metalwork, and small guesthouses welcome visitors who stay overnight to experience the hilltop at sunrise before the day-trippers arrive.</p><h3>Highlights</h3><ul><li>Oldest active Hindu temple in Nepal — Lichhavi-era foundation ~4th century CE</li><li>UNESCO World Heritage Site since 1979</li><li>Oldest stone inscription in Nepal (464 CE, King Mandeva)</li><li>Extraordinary stone, wood, and metal Lichhavi sculpture collection</li><li>Two-tiered gilded copper roof and intricate carved struts</li><li>Hilltop village setting with valley views; starting point for Nagarkot hike</li></ul>`,
    district: "Bhaktapur",
    province: "BAGMATI",
    lat: 27.7164,
    lng: 85.4279,
    elevation: 1543,
    entryFee: "NPR 300 foreigners, NPR 50 SAARC, NPR 50 Nepalis",
    bestSeason: "Year-round; October\u2013April for clearest weather",
    openingHours: "6:00 AM \u2013 7:00 PM daily",
    howToGetThere: "Changu Narayan is 12 km east of Kathmandu and 5 km north of Bhaktapur. Take a taxi from Kathmandu (NPR 800\u20131,000, 45 minutes) or a bus to Bhaktapur and then a local microbus or taxi up to Changunarayan village. A popular approach is the 12\u201315 km hike from Nagarkot along the ridge trail through Tamang villages.",
    gygQuery: "Changu Narayan temple Bhaktapur tour",
    bookingCity: "Kathmandu",
    seoTitle: "Changu Narayan Temple \u2013 Nepal's Oldest Vishnu Temple & UNESCO World Heritage Site",
    seoDescription: "Visit Changu Narayan, Nepal's oldest Hindu temple near Bhaktapur \u2014 a UNESCO World Heritage Site with the country's oldest stone inscription (464 CE) and 1,500 years of extraordinary Lichhavi sculpture on a forested hilltop.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Budhanilkantha Vishnu Temple",
    category: "TEMPLE",
    summary: "Budhanilkantha is home to Nepal's most remarkable religious image: a 5-metre reclining Vishnu carved from a single block of black basalt, lying in a recessed pool representing the cosmic ocean, dating to the Lichhavi period (7th\u20138th century CE). Located at the foot of Shivapuri Hill 8 km north of Kathmandu, the Jalakshayan Narayan (Vishnu resting on water) statue draws thousands of Hindu devotees, especially during the Haribodhini Ekadashi festival when the temple holds massive celebrations. By a curious royal taboo, the kings of Nepal were forbidden from visiting the site.",
    story: `<p>The discovery of Budhanilkantha is one of Nepal's most beloved origin stories: a farmer ploughing his field struck a buried stone with his plough, whereupon blood began to flow — upon excavation, the massive recumbent form of Vishnu was revealed, having lain buried for centuries. The statue, 5 metres long and resting in a 13-metre tank of water, depicts the god in his cosmic sleep form (Anantashayana), lying on the coils of the thousand-headed serpent Shesha, navel facing the sky from which Brahma and creation emerged. The figure's benign expression and the extraordinary preservation of the black basalt after centuries of immersion make it one of South Asia's great sculptural masterpieces.</p><p>The Lichhavi-era origins (approximately 7th–8th century CE) of the sculpture are well established by stylistic comparison with other dated works, though the exact king who commissioned it is debated. A peculiar royal prohibition decreed that the Shah kings of Nepal must never visit Budhanilkantha, as a prophecy warned that a king who did so would die — a prohibition so seriously observed that no Shah monarch ever visited. The temple is particularly crowded on Haribodhini and Harishayani Ekadashi, marking the four-month period when Vishnu is said to sleep and then awaken, drawing pilgrims from across Nepal for bathing rituals and all-night devotional singing.</p><h3>Highlights</h3><ul><li>5-metre reclining Vishnu in black basalt — one of South Asia's finest sculptures</li><li>Lichhavi-era origin (7th–8th century CE) in natural spring-fed pool</li><li>Haribodhini Ekadashi festival — massive annual celebration</li><li>Royal taboo — Shah kings forbidden from visiting by ancient prophecy</li><li>Peaceful setting at foot of Shivapuri Hills</li><li>Accessible half-day trip from central Kathmandu</li></ul>`,
    district: "Kathmandu",
    province: "BAGMATI",
    lat: 27.783,
    lng: 85.358,
    elevation: 1370,
    entryFee: "Free (non-Hindus may view but not enter innermost sanctum)",
    bestSeason: "Year-round; most atmospheric during Haribodhini Ekadashi (October\u2013November)",
    openingHours: "6:00 AM \u2013 5:00 PM daily",
    howToGetThere: "Located 8 km north of central Kathmandu. Take a local bus or microbus from Ratna Park towards Budhanilkantha (40\u201360 minutes, NPR 25). Taxis from Thamel cost approximately NPR 400\u2013500. The temple is a straightforward half-day trip combinable with a visit to Shivapuri National Park.",
    gygQuery: "Budhanilkantha sleeping Vishnu temple Kathmandu",
    bookingCity: "Kathmandu",
    seoTitle: "Budhanilkantha Temple Kathmandu \u2013 Reclining Sleeping Vishnu Statue, Lichhavi Era",
    seoDescription: "See Nepal's most extraordinary religious sculpture at Budhanilkantha: a 5-metre Lichhavi-era reclining Vishnu in black basalt, lying in a cosmic water pool 8 km from Kathmandu \u2014 a living spiritual treasure free to visit.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Dakshinkali Temple",
    category: "TEMPLE",
    summary: "Dakshinkali is one of Nepal's most important Shakti shrines, dedicated to the fierce goddess Kali and located 22 km southwest of Kathmandu near Pharping village at the confluence of two sacred streams. Founded by the Malla king Pratap Malla in the 17th century, the temple is particularly venerated on Tuesdays and Saturdays when animal sacrifices of male goats and cockerels are performed as offerings to the goddess. The setting at the confluence of two rivers in a forested gorge is considered deeply auspicious.",
    story: `<p>Dakshinkali — the name combines 'dakshin' (south) indicating this Kali shrine faces south, an auspicious direction for tantric worship — sits at the sacred confluence of the Bagmati tributary and Nakhu Khola in a narrow gorge lined with pipal trees draped in red cloth and marigold garlands. According to legend, the temple was built after Malla king Pratap Malla received a vision of the goddess commanding him to establish her shrine at this precise spot. The idol of Kali inside is eight-armed, standing on Shiva's prone body, with a fierce expression and blood-red tongue — the classic iconography of the goddess in her most powerful and wrathful aspect.</p><p>Animal sacrifice is central to Kali worship at Dakshinkali, and the temple draws its largest crowds on Tuesday and Saturday mornings when devotees — many having traveled overnight from remote villages — bring male goats and cockerels for ritual slaughter. The blood is offered to the goddess and the meat consumed by the devotee family in a sacred feast. During the Dashain festival in October, the ritual reaches its maximum intensity, with up to 10,000 animals sacrificed over the festival period. The site can be confronting for visitors unfamiliar with this tradition, but it is an authentic expression of Nepal's living Shakta religious culture, observed sincerely by millions of Nepalis.</p><h3>Highlights</h3><ul><li>One of Nepal's most powerful Shakti Peethas and Tantric shrines</li><li>Animal sacrifice ritual on Tuesdays and Saturdays</li><li>Sacred confluence of two rivers in a forested gorge</li><li>Dashain festival — Nepal's largest religious celebration</li><li>Nearby Pharping village with Tibetan Buddhist monasteries (Asura Cave, Yanglesho Gompa)</li><li>Scenic drive through Chobar Gorge and Kirtipur</li></ul>`,
    district: "Kathmandu",
    province: "BAGMATI",
    lat: 27.5833,
    lng: 85.25,
    elevation: 1560,
    entryFee: "Free to enter",
    bestSeason: "Year-round; Dashain festival (October) for the most intense atmosphere; avoid non-festival Tuesdays/Saturdays if sensitive to animal sacrifice",
    openingHours: "5:00 AM \u2013 7:00 PM daily (Tuesdays and Saturdays from 4:00 AM)",
    howToGetThere: "Drive 22 km southwest of Kathmandu via the Ring Road to Balkhu then south through Kirtipur or Chobar. Taxis from Thamel cost approximately NPR 700\u2013900 one way (45 minutes). Local buses from Ratna Park to Pharping pass near the temple. Many tour operators offer combined Dakshinkali\u2013Pharping\u2013Chobar day tours.",
    gygQuery: "Dakshinkali temple tour Kathmandu",
    bookingCity: "Kathmandu",
    seoTitle: "Dakshinkali Temple Kathmandu \u2013 Nepal's Fierce Kali Shakti Shrine & Sacrifice Ritual",
    seoDescription: "Visit Dakshinkali, Nepal's most powerful Kali goddess temple 22 km from Kathmandu \u2014 a living Shakti shrine at a sacred river confluence where animal sacrifice rituals on Tuesdays and Saturdays draw tens of thousands of devotees.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Kirtipur",
    category: "CULTURAL_VILLAGE",
    summary: "Kirtipur is an ancient Newari hilltop town 5 km southwest of Kathmandu, founded in 1099 CE and famous for its fierce resistance to the Gorkha conquest of Prithvi Narayan Shah in the 18th century. Perched on a twin-peaked ridge at 1,342 m, the town preserves fine examples of traditional Newar architecture, the important Uma Maheshwar and Chilancho Stupa temples, and breathtaking views over the Kathmandu Valley and its surrounding Himalayan rim. As home to Tribhuvan University's main campus, Kirtipur blends ancient heritage with Nepal's modern intellectual life.",
    story: `<p>Few places in Nepal carry as dramatic a historical memory as Kirtipur. When Prithvi Narayan Shah began his campaign to conquer the Kathmandu Valley, Kirtipur — commanding a strategic ridge with natural defensive advantages — twice repulsed Gorkha armies. During the first assault in 1757 the Gorkhali commander Kalu Pande was killed and the king himself barely escaped disguised as a holy man. It took until 1767, on the 23rd attempt, for Kirtipur to fall — and even then only through the defection of a local nobleman. The town's punishment was infamous: Prithvi Narayan Shah ordered the noses and lips of all adult male inhabitants cut off as retribution for their stubborn resistance, a historical trauma the town has not forgotten.</p><p>Today Kirtipur's heritage is slowly being rediscovered by both tourists and urban Kathmanduites seeking authentic Newar culture close to the capital. The twin shrines of Uma Maheshwar temple — with its erotic carvings, elaborately carved wooden struts, and gilded finials — and the massive Chilancho Stupa on the southern hill attract religious visitors. The vehicle-free upper lanes of the old town, where traditional Newar houses of brick and carved wood line narrow alleys, feel remarkably unchanged. The town is also known for its weaving tradition: fine cotton and acrylic fabric is still woven on handlooms in ground-floor workshops throughout the old settlement.</p><h3>Highlights</h3><ul><li>Uma Maheshwar temple with exquisite Newar woodcarving and erotic struts</li><li>Chilancho Stupa — one of the valley's most important Buddhist sites</li><li>Historic Battle of Kirtipur — memorial to the town's legendary resistance</li><li>Traditional Newar weaving workshops producing cotton and acrylic fabrics</li><li>Panoramic views of Kathmandu Valley and surrounding Himalayan peaks</li><li>Vehicle-free historic lanes with well-preserved traditional architecture</li></ul>`,
    district: "Kathmandu",
    province: "BAGMATI",
    lat: 27.6787,
    lng: 85.2775,
    elevation: 1342,
    entryFee: "Free to enter Kirtipur; temple donations welcome",
    bestSeason: "Year-round; October\u2013April for clearest mountain views",
    openingHours: "Town open at all times; temples 6:00 AM \u2013 6:00 PM",
    howToGetThere: "Kirtipur is 5 km southwest of Kathmandu. Take a local microbus from Ratna Park or Kalimati to Kirtipur (20\u201330 minutes, NPR 20). Taxis from Thamel cost approximately NPR 300\u2013400. It combines easily with Chobar Gorge and Dakshinkali in a half-day itinerary.",
    gygQuery: "Kirtipur ancient Newari town Kathmandu day trip",
    bookingCity: "Kathmandu",
    seoTitle: "Kirtipur Nepal \u2013 Ancient Newari Hilltop Town, Historic Battlefield & Traditional Weaving",
    seoDescription: "Explore Kirtipur, the ancient Newari hill town 5 km from Kathmandu that famously withstood the Gorkha conquest \u2014 a living heritage site with Uma Maheshwar temple, Chilancho Stupa, traditional weaving, and sweeping valley panoramas.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Nuwakot Durbar",
    category: "DURBAR_PALACE",
    summary: "Nuwakot Durbar is a remarkable 7-storey palace (Saat Talle Durbar) built by Prithvi Narayan Shah after his conquest of Nuwakot in 1744\u201345, which became his forward base for the conquest of the Kathmandu Valley. Located in Bidur at approximately 830 m in Nuwakot District, the palace complex includes multiple temples, the Bhairavi shrine, and commanding hilltop views over the Trishuli River valley. On Nepal's UNESCO tentative list since 2008, the complex was damaged in the 2015 earthquake and is currently being restored.",
    story: `<p>Nuwakot was the first major strategic conquest of Prithvi Narayan Shah's Gorkha unification campaign: capturing the ancient town in 1744–45 gave him control of the vital trade route between the Kathmandu Valley and Tibet via the Trishuli corridor, cutting off the valley kingdoms' access to Tibetan salt, wool, and trade revenue. He immediately relocated his base of operations from Gorkha to Nuwakot, and the seven-storey palace he constructed on the hilltop became the nerve centre of his expanding kingdom for over two decades. From Nuwakot, he coordinated the long siege of the Kathmandu Valley that ultimately succeeded in 1768–69.</p><p>The palace's seven storeys, each slightly narrower than the one below, create a tower-like silhouette on the ridge that is visible for miles around. The architecture blends military functionality — commanding sightlines, thick walls — with the carved woodwork, painted eaves, and tiered roofs of classical Newar palace design. The complex includes the Taleju Bhawani temple (whose goddess was the patron deity of the Malla kings), a Bhairavi shrine, and several smaller shrines arranged in a fortified courtyard. The 2015 earthquake caused significant damage, particularly to the upper storeys, and restoration work is ongoing with Department of Archaeology support.</p><h3>Highlights</h3><ul><li>Seven-storey Saat Talle Durbar — Prithvi Narayan Shah's strategic command palace</li><li>Taleju Bhawani temple within the palace complex</li><li>Commanding views over Trishuli River valley and surrounding hills</li><li>Living history of Nepal's unification campaign (1744–1769)</li><li>Traditional Newari palace architecture on UNESCO tentative list</li><li>Combines with Trishuli River rafting for an adventure and heritage day trip</li></ul>`,
    district: "Nuwakot",
    province: "BAGMATI",
    lat: 27.9138,
    lng: 85.1647,
    elevation: 830,
    entryFee: "NPR 50\u2013100 foreigners (approximate; verify locally during restoration period)",
    bestSeason: "October\u2013April; avoid monsoon for clearest road access",
    openingHours: "9:00 AM \u2013 5:00 PM daily (restoration may affect some areas)",
    howToGetThere: "Nuwakot is 72 km northwest of Kathmandu along the Trishuli Highway (2\u20133 hours by bus or private vehicle). Buses depart from Kathmandu's Machapokhari or Balaju bus parks to Bidur/Nuwakot. The palace sits on a hill above Bidur town \u2014 a short walk or local vehicle ride from the bus park.",
    gygQuery: "Nuwakot palace fortress Kathmandu day trip",
    bookingCity: "Kathmandu",
    seoTitle: "Nuwakot Durbar \u2013 Prithvi Narayan Shah's 7-Storey Palace Fortress, Nuwakot Nepal",
    seoDescription: "Visit Nuwakot Durbar, the 7-storey hilltop palace fortress from which Prithvi Narayan Shah planned Nepal's unification \u2014 a UNESCO tentative site with Taleju temple, sweeping Trishuli valley views, and living Newari heritage 72 km from Kathmandu.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Manakamana Temple",
    category: "TEMPLE",
    summary: "Manakamana \u2014 'heart's wish fulfilled' \u2014 is a celebrated Hindu temple dedicated to the wish-granting goddess Bhagwati (an incarnation of Parvati) at 1,302 m in Gorkha District's Cahikot hills, overlooking the confluence of the Marsyangdi and Trishuli rivers. Founded according to tradition in 1678, the temple is today most famously accessed via Nepal's first aerial cable car, which opened in 1998, carrying over a million pilgrims and visitors per year. Animal sacrifice of goats and cockerels is a key devotional practice here.",
    story: `<p>The origin myth of Manakamana is one of Nepal's most compelling: a Gorkha queen possessed of divine power revealed herself as a goddess to a Magar priest named Lakhan Thapa. When the king discovered his wife's divine nature and died of the shock, the queen performed sati on his funeral pyre, but before dying she told Lakhan Thapa that she would return. Six months later, a farmer splitting a stone saw blood and milk flow from the crack — and within was the divine image of the goddess. The spot became Manakamana, and the Magar family of Lakhan Thapa were declared hereditary caretakers (pujaris) of the temple — a role they still hold today.</p><p>For nearly three centuries pilgrims hiked for hours up steep jungle trails to reach the temple and make their offerings. Since 1998, the Austrian-built aerial cable car from Kurintar has transformed access: the 2.8 km ride climbs 1,044 m of vertical elevation in 10 minutes, offering extraordinary views of the Marsyangdi and Trishuli gorges below. The cable car carries devotees with live animals destined for sacrifice (a unique engineering and logistical consideration), and on auspicious days the queues for both the cable car and the temple inner sanctum can stretch for hours. The goddess is believed to grant the sincere wish of any devotee who visits with true devotion.</p><h3>Highlights</h3><ul><li>Nepal's first aerial cable car — 10-minute ride with dramatic gorge views</li><li>Wish-fulfilling goddess Bhagwati — one of Nepal's most venerated Shakti shrines</li><li>Animal sacrifice ritual and major pilgrimage festivals</li><li>Views of Marsyangdi and Trishuli river confluence from the hilltop</li><li>Over one million visitors annually — major living pilgrimage tradition</li><li>Gateway to Gorkha Durbar and Manaslu trek combination itineraries</li></ul>`,
    district: "Gorkha",
    province: "GANDAKI",
    lat: 27.9042,
    lng: 84.584,
    elevation: 1302,
    entryFee: "Cable car: NPR 1,145 one-way, NPR 2,060 return for foreigners (approximate 2025 rates); temple entry free",
    bestSeason: "Year-round; Dashain (October) for peak pilgrimage atmosphere",
    openingHours: "Cable car: 9:00 AM \u2013 5:00 PM daily (closed Tuesdays for maintenance); temple open from 5:00 AM",
    howToGetThere: "Drive from Kathmandu to Kurintar (about 105 km, 3 hours via Prithvi Highway). The cable car lower station is 5 km east of Mugling at Kurintar. All Pokhara-bound buses stop at Mugling from where shared vehicles reach Kurintar. The temple can also be reached on foot (2\u20133 hour hike from Kurintar) but the cable car is recommended.",
    gygQuery: "Manakamana temple cable car Nepal",
    bookingCity: "Kathmandu",
    seoTitle: "Manakamana Temple Nepal \u2013 Wish-Fulfilling Goddess & Aerial Cable Car, Gorkha",
    seoDescription: "Take Nepal's first aerial cable car to Manakamana, the famous wish-fulfilling goddess temple at 1,302 m in Gorkha \u2014 a profound pilgrimage experience with spectacular Himalayan gorge views and Nepal's most vibrant living Shakti tradition.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Phulchoki Hill",
    category: "HILL_VIEWPOINT",
    summary: "Phulchoki (meaning 'place of flowers') is the highest point on the Kathmandu Valley rim at 2,782 m, located 20 km southeast of Kathmandu in Lalitpur District. Renowned as one of South Asia's premier birding sites with over 300 recorded bird species, including the rare Spiny Babbler (Nepal's only endemic bird), Phulchoki also offers sweeping views of the Himalayas and the Kathmandu Valley, and its forests burst into rhododendron bloom from February through April. A rough jeep road reaches the summit, where a small Phulchoki Mai shrine sits amid dense forest.",
    story: `<p>Phulchoki rises steeply from the southern edge of the Kathmandu Valley, its forested slopes sheltering a remarkably rich assemblage of birds and wildlife within easy reach of the capital. The hill derives its name from the Nepali word for 'flower place' — referring to the spectacular annual bloom of rhododendrons, magnolias, primulas, and orchids that transform the forest from February through April. The summit is marked by a small Phulchoki Mai temple dedicated to the local goddess who protects the forest, and offerings of flowers and incense are made here by local devotees and pilgrims.</p><p>For birdwatchers, Phulchoki is in a different league from any other site in the Kathmandu Valley region: its vertical range of nearly 1,400 m spans subtropical and temperate forest zones, and the diversity of habitats supports an extraordinary list of species. The Spiny Babbler — found only in Nepal and one of Asia's most sought-after endemics — is reliably seen in the lower forest. Higher up, Satyr Tragopan, Nepal Cutia, Black-throated Parrotbill, Fire-tailed Myzornis, and scores of warblers, flycatchers, and laughingthrushes reward patient observers. Leopard, Himalayan black bear, and red panda have been recorded in the forest, though sightings are rare.</p><h3>Highlights</h3><ul><li>Highest point on Kathmandu Valley rim (2,782 m) with Himalayan panoramas</li><li>Over 300 bird species — premier birding site near Kathmandu</li><li>Nepal's only endemic bird, the Spiny Babbler, reliably seen here</li><li>Spectacular rhododendron and magnolia bloom February–April</li><li>Phulchoki Mai temple and forest shrine</li><li>Leopard, Himalayan black bear, and red panda in the forest</li></ul>`,
    district: "Lalitpur",
    province: "BAGMATI",
    lat: 27.5833,
    lng: 85.4,
    elevation: 2782,
    entryFee: "No formal entry fee; jeep hire or private vehicle required for summit access",
    bestSeason: "February\u2013April (rhododendrons and spring migration); September\u2013November (autumn migration and clear views)",
    openingHours: "Open year-round; best birding from 6:00\u201310:00 AM",
    howToGetThere: "Drive from Patan (Lalitpur) via Godavari to the base of Phulchoki (15\u201320 minutes). A rough jeep track continues to the summit (45 minutes by 4WD from Godavari). Hiring a jeep from Patan or Kathmandu for a half-day trip costs approximately NPR 3,000\u20134,000. Alternatively, hike from Godavari Botanical Garden (3\u20134 hours to summit). Public buses serve Godavari from Ratna Park.",
    gygQuery: "Phulchoki birdwatching hill Kathmandu",
    bookingCity: "Kathmandu",
    seoTitle: "Phulchoki Hill Kathmandu \u2013 Highest Valley Viewpoint & Premier Birdwatching Site",
    seoDescription: "Explore Phulchoki, the highest peak on the Kathmandu Valley rim at 2,782 m \u2014 a world-class birdwatching site with 300+ species including Nepal's Spiny Babbler, spectacular rhododendron forests, and sweeping Himalayan panoramas just 20 km from the city.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Palanchowk Bhagawati Temple",
    category: "TEMPLE",
    summary: "Palanchowk Bhagawati is one of Nepal's most important Shakti shrines, a three-storey pagoda temple housing a black stone idol of the goddess Bhagawati on a hilltop at 1,563 m in Panchkhal Municipality, Kavrepalanchok District, overlooking the Indrawati River. Dating to the Lichhavi period, it is considered an Adi Shakti Pitha \u2014 a primal seat of the goddess \u2014 and draws pilgrims from across Nepal and India. The temple is 42 km east of Kathmandu on the Araniko Highway corridor toward the Chinese border.",
    story: `<p>Palanchowk Bhagawati occupies one of the most dramatically positioned temple sites in the Kathmandu Valley region: the summit of Palanchok Hill rises sharply above the Indrawati River gorge, and on clear days the views from the hilltop encompass an extraordinary sweep from the Langtang range in the north to the plains of the Terai visible in the south. The goddess worshipped here — Bhagawati, the supreme form of the Divine Mother (Devi) — is enshrined in a three-foot black stone idol of Lichhavi-period craftsmanship, considered to be self-manifested (swayambhu) rather than carved by human hands.</p><p>The temple's position above the sacred Indrawati River gives it heightened ritual significance: rivers, hills, and goddess shrines form the classic trinity of Shakta sacred geography in Nepal, and Palanchowk Bhagawati fulfils all three. The temple is particularly busy during Dashain (October), when tens of thousands of pilgrims climb the steep stone steps to make animal sacrifice offerings and receive the goddess's blessing. The site narrowly survived the 2015 earthquake with relatively minor structural damage, and restoration work restored it to its pre-earthquake state. Many Nepalis from the eastern Kathmandu Valley regard Palanchowk Bhagawati as their family's most important goddess shrine, visiting for weddings, thread ceremonies, and major life transitions.</p><h3>Highlights</h3><ul><li>Primal Adi Shakti Pitha — one of Nepal's most powerful goddess shrines</li><li>Lichhavi-era black stone self-manifested idol of Bhagawati</li><li>Panoramic views: Langtang range, Indrawati valley, and Terai plains</li><li>Major Dashain pilgrimage site — tens of thousands of devotees annually</li><li>Sacred location above the Indrawati River confluence</li><li>Accessible en route to Dhulikhel and the Araniko Highway border crossing</li></ul>`,
    district: "Kavrepalanchok",
    province: "BAGMATI",
    lat: 27.68,
    lng: 85.61,
    elevation: 1563,
    entryFee: "Free to enter; donations welcome",
    bestSeason: "Year-round; Dashain festival (October) for maximum pilgrimage atmosphere",
    openingHours: "5:00 AM \u2013 7:00 PM daily",
    howToGetThere: "Located 42 km east of Kathmandu along the Araniko Highway (road to China), past Dhulikhel toward Panchkhal. Drive takes approximately 1.5\u20132 hours by car or bus. Take any Dolalghat or Kodari-bound bus from Kathmandu's Chabahil bus stand to the Palanchowk junction, then walk or hire a local vehicle up the hill. Combines well with a Dhulikhel or Namobuddha visit.",
    gygQuery: "Palanchowk Bhagawati temple day trip Kathmandu",
    bookingCity: "Kathmandu",
    seoTitle: "Palanchowk Bhagawati Temple \u2013 Sacred Shakti Pitha on Indrawati River, Kavre Nepal",
    seoDescription: "Pilgrimage to Palanchowk Bhagawati, one of Nepal's most powerful Adi Shakti Peethas \u2014 a Lichhavi-era black stone goddess temple on a hilltop 42 km from Kathmandu with sweeping Himalayan and Indrawati valley views.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
]

async function main() {
  console.log(`🌱 Seeding batch 7 — ${places.length} places...`)
  for (const p of places) {
    await prisma.place.upsert({
      where: { slug: slug(p.name) },
      update: {},
      create: { ...p, slug: slug(p.name) },
    })
    console.log(`  ✅ ${p.name}`)
  }
  console.log('🌱 Batch 7 complete!')
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())