import 'dotenv/config'
import { PrismaClient } from '@prisma/client'
import slugify from 'slugify'

const prisma = new PrismaClient()
const slug = (n) => slugify(n, { lower: true, strict: true })

const places = [
  {
    name: "Chitwan National Park",
    category: "NATIONAL_PARK",
    summary: "Nepal's first national park and a UNESCO World Heritage Site since 1984, Chitwan protects one of Asia's last remaining pristine alluvial grasslands and subtropical forests. Spanning 952 km\u00b2 in the Terai lowlands, it shelters endangered Bengal tigers, one-horned rhinoceroses, gharial crocodiles, and 543 bird species. The park is the benchmark wildlife destination in South Asia, offering jeep safaris, canoe rides, jungle walks, and Tharu cultural experiences.",
    story: `<p>Chitwan National Park, established in 1973 as Nepal's first protected area, occupies the flood plains and sal forests of the Inner Terai lowlands of Chitwan and Nawalpur districts. Before its designation, the valley was a royal hunting reserve—King Mahendra hosted dignitaries such as Queen Elizabeth II here in the 1960s. In 1984, UNESCO recognized its extraordinary biodiversity by inscribing it as a World Heritage Site. The park's landscape ranges from 100 metres in the river valleys to 815 metres in the Chure (Sivalik) Hills, creating a mosaic of riverine grasslands, sal forests, and oxbow lakes that sustain an exceptional concentration of wildlife.</p><p>The park's conservation success story is globally celebrated. Nepal's one-horned rhinoceros population, once hunted to near-extinction, had recovered to more than 700 individuals by the mid-2020s, with Chitwan alone holding over 600. Bengal tigers breed here in meaningful numbers, documented by camera-trap surveys and annual counts. Gharial crocodiles—critically endangered worldwide—find one of their last refuges in the Rapti and Narayani rivers. Over 540 bird species have been recorded, including the giant hornbill and the Bengal florican, making Chitwan one of the premier birding destinations in Asia.</p><p>Visitors access the park primarily through the riverside village of Sauraha, where licensed operators run half-day and full-day jeep safaris into the core zone, guided jungle walks along buffer-zone trails, and dugout-canoe rides on the Rapti River at dawn. The Tharu cultural programme, performed each evening in Sauraha, introduces guests to the indigenous community that has coexisted with the forest for centuries. The best wildlife sightings occur in the cool, dry months of October through March, when tall elephant grass has been cut or burned and animals congregate near the water.</p><ul><li>UNESCO World Heritage Site since 1984—Nepal's first national park</li><li>Over 700 one-horned rhinoceroses and a thriving Bengal tiger population</li><li>543 recorded bird species, including rarities like the Bengal florican</li><li>Gharial and mugger crocodiles in the Rapti and Narayani rivers</li><li>Gateway village Sauraha sits on the Rapti River opposite the park boundary</li><li>Jungle walks, jeep safaris, canoe rides, elephant-back safaris, and birdwatching towers</li></ul>`,
    district: "Chitwan",
    province: "BAGMATI",
    lat: 27.5,
    lng: 84.3333,
    elevation: 150,
    entryFee: "NPR 2000 foreigners / NPR 1000 SAARC / NPR 150 Nepali (per day)",
    bestSeason: "Oct\u2013Feb",
    openingHours: "Sunrise to sunset daily",
    howToGetThere: "Sauraha, the main gateway, is 150 km south of Kathmandu and 105 km east of Pokhara. Tourist buses depart Kathmandu's Kalanki bus park daily (5\u20136 hours) and drop directly at Sauraha. From Pokhara, buses to Bharatpur (3 hours) connect with local transport to Sauraha (30 minutes). Private cars and taxis are available from both cities. The nearest airport is Bharatpur (Bharatpur Airport, BTR), a 30-minute drive from Sauraha, with daily flights from Kathmandu.",
    gygQuery: "Chitwan National Park safari Nepal",
    bookingCity: "Sauraha",
    seoTitle: "Chitwan National Park \u2013 Nepal's UNESCO Wildlife Sanctuary",
    seoDescription: "Explore Chitwan National Park, Nepal's first UNESCO World Heritage Site. See one-horned rhinos, Bengal tigers, and 540+ bird species on jeep safaris, canoe rides, and guided jungle walks in the Terai lowlands.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Jungle Safari Chitwan",
    category: "ADVENTURE_SPORTS",
    summary: "Chitwan's jungle safaris deliver close encounters with one-horned rhinoceroses, Bengal tigers, sloth bears, and crocodiles through a variety of expertly guided activities. Jeep safaris penetrate the park's core zone along forest tracks at dawn and dusk, while elephant-back rides and guided jungle walks offer an immersive ground-level perspective. The combination of boat, vehicle, and on-foot exploration makes Chitwan one of the most complete wildlife safari experiences in Asia.",
    story: `<p>The jungle safari experience at Chitwan is built around multiple modes of exploration, each revealing a different dimension of the park's ecosystem. Jeep safaris—the most popular activity—use open 4WD vehicles that enter the core zone via designated tracks early in the morning and again in the late afternoon, the two windows when tigers, rhinos, and leopards are most active. Knowledgeable naturalist guides track pugmarks and alert the driver to wildlife, and jeep convoys maintain respectful distances from animals while allowing photographers extended viewing time.</p><p>Canoe rides on the Rapti River offer a quieter, more intimate encounter with the riparian ecosystem. Flat-bottomed wooden dugouts glide silently along the river's edge while guides point out gharial and mugger crocodiles basking on sandbanks, smooth-coated otters, and hundreds of bird species perched in overhanging trees. A jungle walk following the canoe ride completes the morning circuit, taking guests along forest trails where rhino dung piles and fresh tracks keep adrenaline levels high. Elephant-back safaris, though reduced in number due to conservation guidelines, still operate through select responsible camps and provide a height advantage for spotting wildlife through tall grass.</p><p>The standard package sold in Sauraha combines a park entry permit, a two-hour jeep safari, a 45-minute canoe ride, a guided jungle walk, and an evening Tharu cultural show. More dedicated wildlife enthusiasts opt for multi-day packages that include a dawn birdwatching walk from an observation tower and a full-day deep-zone jeep safari. The park's buffer zones are also rich in wildlife and accessible without the core-zone entry surcharge, offering a cost-effective alternative for budget travellers. October through March is optimal, with February and March also excellent for birdwatching as migratory species are still present.</p><ul><li>Jeep safaris penetrate the core zone at dawn and dusk for maximum wildlife sightings</li><li>Canoe rides on the Rapti River for crocodile and bird watching</li><li>Guided jungle walks along buffer-zone trails with expert naturalists</li><li>Elephant-back safaris available through select responsible operators</li><li>Combined packages include park entry, canoe ride, jungle walk, and cultural show</li><li>Best sightings of rhino, tiger, sloth bear, and leopard October–March</li></ul>`,
    district: "Chitwan",
    province: "BAGMATI",
    lat: 27.5743,
    lng: 84.4989,
    elevation: 150,
    entryFee: "NPR 2000 park entry (foreigners) + NPR 1500\u20133000 jeep safari per person",
    bestSeason: "Oct\u2013Mar",
    openingHours: "Safaris depart at dawn (approx. 06:00) and late afternoon (approx. 15:00)",
    howToGetThere: "All safaris are booked through licensed operators based in Sauraha village, which is 150 km from Kathmandu (5\u20136 hours by tourist bus) and 30 minutes from Bharatpur Airport. Operators pick guests up from their lodge in Sauraha and handle all park logistics, permits, and guides.",
    gygQuery: "Chitwan jungle safari jeep rhino tiger Nepal",
    bookingCity: "Sauraha",
    seoTitle: "Chitwan Jungle Safari \u2013 Jeep, Canoe & Elephant Safari Nepal",
    seoDescription: "Book a jungle safari at Chitwan National Park: jeep safaris, canoe rides, elephant experiences, and guided walks to spot rhinos, tigers, crocodiles, and hundreds of bird species in Nepal's premier wildlife park.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Tharu Cultural Village",
    category: "CULTURAL_VILLAGE",
    summary: "The Tharu are the indigenous people of Nepal's Terai, renowned for their genetic resistance to malaria and their centuries-old forest-dwelling culture. Villages near Sauraha in Chitwan offer visitors an authentic window into Tharu life through traditional mud-and-bamboo architecture, artisan craft workshops, and the electrifying Tharu stick dance performed every evening. Guided village walks, ox-cart tours, and homestays provide genuine cultural exchange beyond the national park experience.",
    story: `<p>The Tharu people have inhabited the malaria-prone Terai forests of Nepal for well over a thousand years, developing a remarkable biological immunity to the disease that kept outsiders at bay until the 1950s. In Chitwan, Tharu villages cluster along the buffer zone of the national park, particularly around Sauraha and Bagmara. Traditional homesteads are built of mud, clay, and bamboo with thatched roofs, the exterior walls decorated with intricate geometric murals painted by women using natural earth pigments. Entire extended families live in long communal structures that face an inner courtyard—a spatial arrangement that reflects the tight-knit social fabric of Tharu society.</p><p>The village walk is the centrepiece of the cultural experience. Accompanied by a Tharu guide, visitors thread through rice paddies and mustard fields to reach working homesteads where potters throw clay on hand-turned wheels, weavers work wooden looms producing the distinctive Tharu dhurrie rugs, and women pound rice with long wooden pestles in a rhythmic communal exercise. Fish traps woven from bamboo strips hang drying in doorways—fishing in the Rapti's backwaters supplements the rice and lentil diet that defines Tharu cuisine. The guide explains animist rituals, the role of the shaman (guruwa), and how Tharu festivals like Maghi (New Year in January) and Chitwan's Tharu culture festival mark the agricultural calendar.</p><p>Every evening in Sauraha, cultural troupes perform the Tharu stick dance (Danda Nach) and Peacock Dance to the beat of the madal drum and the haunting notes of the bansuri flute. Male dancers manipulate pairs of hardwood sticks with extraordinary precision, clashing them together in complex patterns that mimic both martial combat and ceremonial ritual. For a deeper engagement, several community lodges around Bachhauli and Kumroj offer homestays where guests share meals, join the family's morning rice harvest, and learn to weave a basic dhurrie—income that flows directly to the host family rather than to tour intermediaries.</p><ul><li>Indigenous community with centuries-old cultural traditions and malaria-resistant genetics</li><li>Traditional mud-and-bamboo homes with intricate geometric murals painted by women</li><li>Guided village walks through rice fields, pottery workshops, and weaving demonstrations</li><li>Evening Tharu stick dance (Danda Nach) and Peacock Dance performances in Sauraha</li><li>Ox-cart village tours and bicycle rides through surrounding farmland</li><li>Homestays with local families at Bachhauli and Kumroj community lodges</li></ul>`,
    district: "Chitwan",
    province: "BAGMATI",
    lat: 27.5756,
    lng: 84.4928,
    elevation: 148,
    entryFee: "Free village entry; guided tour NPR 400; ox-cart tour NPR 1200",
    bestSeason: "Oct\u2013Mar",
    openingHours: "Village walks: morning and afternoon; Cultural show: approx. 19:00 daily",
    howToGetThere: "Tharu villages are within easy walking distance (30 minutes on foot) or a short bicycle ride from Sauraha's main tourist hub. Bicycle rentals are widely available in Sauraha for NPR 200\u2013300 per day. Most lodges in Sauraha organise guided village walks as part of their standard activity packages.",
    gygQuery: "Tharu cultural village Chitwan Nepal",
    bookingCity: "Sauraha",
    seoTitle: "Tharu Cultural Village Chitwan \u2013 Indigenous Heritage & Stick Dance",
    seoDescription: "Visit a Tharu Cultural Village near Chitwan and experience the indigenous people of Nepal's Terai: traditional mud homes, evening stick dances, weaving demonstrations, and authentic homestays alongside the jungle.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Rapti River Chitwan",
    category: "RIVER",
    summary: "The Rapti River forms the northern boundary of Chitwan National Park, serving as a lifeline for the park's extraordinary biodiversity and the primary venue for canoe-based wildlife watching. Dawn canoe rides in hand-carved dugouts drift silently past basking gharial crocodiles, smooth-coated otters, and flocks of migratory waders on sandbars. The river crossing between Sauraha and the park is itself a ritual moment\u2014locals paddle flat-bottomed boats while rhinos drink on the far bank.",
    story: `<p>The Rapti River drains the southern slopes of the Mahabharat Range and flows roughly east along the northern margin of Chitwan National Park before joining the Narayani near Bharatpur. In the dry months—October through April—the river drops to manageable levels, exposing long white sandbars that become haul-out zones for gharial crocodiles and nesting grounds for skimmers and sandpipers. The Rapti's calm, clear water is translucent enough to spot the long, needle-nosed snouts of gharials resting on the bottom in the shallows, while mugger crocodiles—stockier and more aggressive—prefer the vegetated banks.</p><p>Canoe rides on the Rapti have been a defining feature of the Chitwan experience since the park opened to tourism in the late 1970s. The dugouts are carved from a single sal tree trunk, low in the water and virtually silent, allowing them to approach wildlife with minimal disturbance. A typical 45-minute morning ride launches before dawn from the Sauraha bank, drifting downstream with the current while a guide paddles from the stern and a naturalist at the prow identifies birds and calls out crocodile positions. Common sightings include cormorants, herons, kingfishers, storks, and the Indian skimmer cutting the water's surface with its orange lower mandible.</p><p>Beyond wildlife watching, the Rapti serves as an evening gathering point for the entire Sauraha community. Locals bathe and wash clothes while mahouts lead elephants to drink and roll in the cool water. The setting sun turns the river gold and silhouettes the park's sal trees on the opposite bank, often with a rhinoceros or two grazing in the grassland just behind the tree line. Longer canoe excursions of two to three hours venture further upstream and include a jungle walk return, combining river and forest habitats in a single morning and producing some of the highest wildlife encounter rates in the park.</p><ul><li>Northern boundary of Chitwan National Park—a critical wildlife corridor</li><li>Dawn canoe rides in hand-carved dugout boats for minimum disturbance to wildlife</li><li>Gharial and mugger crocodiles visible on sandbars year-round</li><li>Over 200 bird species recorded along the river including the Indian skimmer</li><li>Smooth-coated otters, Gangetic dolphins occasionally sighted</li><li>River crossing between Sauraha and park is an iconic daily ritual</li></ul>`,
    district: "Chitwan",
    province: "BAGMATI",
    lat: 27.5838,
    lng: 84.4999,
    elevation: 144,
    entryFee: "Canoe ride approx. NPR 700\u20131000 per person (includes guide); park entry fee additional",
    bestSeason: "Oct\u2013Mar",
    openingHours: "Dawn canoe rides from approx. 06:00; afternoon rides from approx. 14:30",
    howToGetThere: "The Rapti River canoe launch point is at the southern end of Sauraha village, a 5-minute walk from most lodges. All licensed operators along the main Sauraha strip sell canoe packages; the park entry permit is purchased separately at the tourist service center before boarding.",
    gygQuery: "Rapti River canoe ride Chitwan National Park",
    bookingCity: "Sauraha",
    seoTitle: "Rapti River Chitwan \u2013 Canoe Rides, Crocodiles & Dawn Wildlife",
    seoDescription: "Float silently along the Rapti River on a dawn canoe ride through Chitwan National Park. Spot gharial crocodiles, otters, kingfishers, and rhinos on the far bank in Nepal's most iconic river wildlife experience.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Devghat Dham",
    category: "TEMPLE",
    summary: "Devghat is one of Nepal's holiest Hindu pilgrimage sites, located at the sacred confluence of the Trishuli and Kali Gandaki rivers\u2014together forming the mighty Narayani\u2014about 7 km northwest of Narayanghat. Ashrams, temples, and cave shrines line the wooded riverbanks, sheltering hundreds of sadhus and elderly devotees who come to spend their final years at this spiritually charged tirtha. During the Makar Sankranti festival in January, hundreds of thousands of pilgrims descend for ritual bathing in one of Nepal's largest religious gatherings.",
    story: `<p>Devghat occupies the triangular wedge of land where the Trishuli River—sweeping south from the mountains above Kathmandu—merges with the Kali Gandaki, which has carved the world's deepest gorge on its journey from the Mustang plateau. The combined stream, now called the Narayani, is sacred to Hindus as a manifestation of Vishnu himself, and the Shaligram stones—ammonite fossils found in the riverbed—are venerated as the direct embodiment of the deity. Mention of Devghat appears in the Baraha Purana, Skanda Purana, and Padma Purana, underscoring its antiquity as a pilgrimage destination. The site lies on the boundary of Tanahun, Chitwan, and Nawalpur districts in Gandaki Province, a geographical convergence that mirrors its spiritual significance as a meeting point of sacred waters.</p><p>Walking through Devghat's forest paths feels like entering a living monastery. Dozens of ashrams—many founded centuries ago—provide food and lodging to wandering sadhus and to the community of retired Hindus who have chosen to spend their final years here in the belief that dying at this tirtha ensures moksha (liberation from the cycle of rebirth). Smoke from dhuni fires mingles with the scent of marigold garlands and incense at shrines to Shiva, Vishnu, Hanuman, and a cave temple associated with Goddess Sita. Small stone ghats step down to the river where pilgrims perform tarpan rituals for deceased ancestors, pouring water cupped in their palms back into the confluence.</p><p>Makar Sankranti—falling in mid-January when the sun transitions into Capricorn—transforms Devghat into one of Nepal's largest festivals. Hundreds of thousands of pilgrims arrive by bus, jeep, and on foot, bathing in the confluence before dawn to wash away sins accumulated over the year. Tent cities spring up along the riverbanks, and the chanting of Vedic hymns continues through the night. Outside festival time, Devghat rewards the unhurried traveller with its peaceful atmosphere, forest walks, and extraordinary bird life along the river—bee-eaters, kingfishers, and osprey are commonly seen. The site is 20 km from Sauraha and makes an excellent half-day cultural excursion from a Chitwan base.</p><ul><li>Sacred confluence of Trishuli and Kali Gandaki rivers, forming the Narayani</li><li>Mentioned in the Baraha Purana, Skanda Purana, and Padma Purana</li><li>Hundreds of ashrams, sadhus, and elderly devotees in permanent residence</li><li>Makar Sankranti festival (mid-January) draws hundreds of thousands of pilgrims</li><li>Shaligram stones (ammonite fossils) venerated as manifestations of Vishnu</li><li>Cave shrine associated with Goddess Sita; multiple temples along the ghats</li></ul>`,
    district: "Chitwan",
    province: "GANDAKI",
    lat: 27.7429,
    lng: 84.4231,
    elevation: 174,
    entryFee: "Free",
    bestSeason: "Oct\u2013Mar; Jan for Makar Sankranti festival",
    openingHours: "Open all day; ghats most active at dawn and dusk",
    howToGetThere: "Devghat is approximately 7 km northwest of Narayanghat city centre. Local buses and microvans run frequently from Narayanghat's Pulchowk bus stand (20 minutes, NPR 30). Private taxis from Narayanghat take about 15 minutes. From Sauraha, the journey is 20 km (40 minutes by private vehicle). Pokhara is approximately 150 km west; taxis from Pokhara take around 2.5 hours.",
    gygQuery: "Devghat pilgrimage Narayanghat Nepal",
    bookingCity: "Narayanghat",
    seoTitle: "Devghat Dham \u2013 Sacred Hindu Confluence near Chitwan Nepal",
    seoDescription: "Visit Devghat Dham, Nepal's holiest river confluence where the Trishuli meets the Kali Gandaki. Walk ancient forest paths lined with ashrams and temples, and witness Makar Sankranti\u2014one of Nepal's grandest pilgrimages.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Pokhara City",
    category: "CULTURAL_VILLAGE",
    summary: "Pokhara is Nepal's tourism capital and second-largest city, spectacularly situated at 827 metres on the shores of Phewa Lake with the snow-capped Annapurna and Dhaulagiri massifs rising just 30 kilometres away. The city is simultaneously a base for Annapurna Circuit and Sanctuary treks, a paragliding hub, a lakeside leisure destination, and a cultural melting pot where Gurung, Magar, Tibetan, and Thakali communities coexist. Its compact Lakeside district (Baidam) hosts hundreds of restaurants, guesthouses, and shops catering to travellers of every budget.",
    story: `<p>Pokhara occupies a broad valley that was once the bed of an ancient lake, and the flat alluvial terrain—ringed by hills and fronted by Phewa Lake—creates a natural amphitheatre for one of the world's most dramatic mountain panoramas. On clear mornings, Machapuchare (6,993 m), the sacred 'Fishtail' peak, floats above the lake's mirror surface as if suspended from the sky, while Annapurna South, Hiunchuli, and Dhaulagiri line the northern horizon in a wall of white. The city sits at the western end of the Pokhara Valley within Kaski District, Gandaki Province, and serves as the administrative capital of the province as well as the commercial hub of a region stretching from Mustang in the north to the Gandaki plains in the south.</p><p>The city divides into distinct neighbourhoods that cater to different needs. Lakeside (Baidam) is the tourist heartland—a strip of garden restaurants, rooftop cafés, outdoor gear shops, travel agencies, and guesthouses running south along the eastern shore of Phewa Lake. Damside, at the lake's southern end near the dam, is quieter and less commercialised. The older Bazar area north of the lake preserves the original trading-town character of Pokhara, where Newari merchants and hill-community families have done business for centuries. The recently developed Prithvi Narayan Campus road and Nadipur area host the city's growing population of students and professionals. The International Mountain Museum, Annapurna Regional Museum, and the recently opened Pokhara International Airport (2023) sit in the southern districts.</p><p>As a trekking base, Pokhara's strategic location is unmatched. The Annapurna Circuit—one of the world's great long-distance walks—begins its northern loop from Besisahar, two hours east by road. The Annapurna Sanctuary trek starts from Nayapul, 42 km west. The Poon Hill trek, suitable for beginners, also departs from Nayapul or Birethanti. Closer to town, the one-day hike to Sarangkot and the afternoon walk to the World Peace Pagoda give casual visitors their Himalayan fix without a multi-day commitment. Beyond trekking, Pokhara is South Asia's paragliding capital—tandem flights from Sarangkot landing on the Lakeside strip are booked months in advance during peak season—and the Seti River canyon through the city centre offers white-water rafting and kayaking starting points.</p><ul><li>Nepal's official Tourism Capital, gateway to Annapurna Circuit and Sanctuary treks</li><li>Phewa Lake lakeside strip (Baidam) with restaurants, cafes, and gear shops</li><li>South Asia's premier paragliding destination—flights from Sarangkot viewpoint</li><li>Seven lakes within the valley: Phewa, Begnas, Rupa, Khaste, Neureni, Maidi, Dipang</li><li>International Mountain Museum and Annapurna Regional Museum in the city</li><li>Pokhara International Airport opened 2023 with regional and charter international connections</li></ul>`,
    district: "Kaski",
    province: "GANDAKI",
    lat: 28.2096,
    lng: 83.9856,
    elevation: 827,
    entryFee: "Free (city); individual attractions have separate fees",
    bestSeason: "Oct\u2013Nov, Feb\u2013Apr",
    openingHours: "City open year-round",
    howToGetThere: "Pokhara is 200 km west of Kathmandu. Tourist buses depart Kathmandu's Kantipath/Sundhara area daily (7\u20138 hours, NPR 700\u20131500). Express or luxury coaches on the Prithvi Highway take 6\u20137 hours. Domestic flights from Kathmandu to Pokhara Airport (PKR) take 25 minutes and operate multiple times daily (NPR 3000\u20137000 one-way). From Chitwan/Sauraha, buses to Pokhara run via Narayanghat (4\u20135 hours).",
    gygQuery: "Pokhara city tour lake paragliding Nepal",
    bookingCity: "Pokhara",
    seoTitle: "Pokhara City \u2013 Nepal's Tourism Capital on Phewa Lake",
    seoDescription: "Discover Pokhara, Nepal's tourism capital: a lakeside city below the Annapurna Himalaya offering trekking, paragliding, boating, temples, caves, and mountain views. The perfect base for the Annapurna Circuit and Sanctuary treks.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Phewa Lake",
    category: "LAKE",
    summary: "Phewa Lake is Nepal's most famous lake and Pokhara's centrepiece, its 5.7 km\u00b2 of still water perfectly reflecting the snow-capped summit of Machapuchare (Fishtail Mountain) and the Annapurna range on clear mornings. Wooden rowing boats and brightly painted canoes can be hired from the Lakeside ghats for leisurely paddles to the island Tal Barahi Temple at the lake's centre, or simply for the pleasure of floating beneath one of the world's most photogenic mountain backdrops. The lake is the second largest in Nepal and sustains the livelihoods of thousands of fishers and tourism workers.",
    story: `<p>Phewa Lake—known locally as Fewa Tal—occupies the western end of the Pokhara Valley at 742 metres above sea level, hemmed in by the Pame Hills to the south and west and open to the sky and the great Himalayan wall to the north. The lake covers approximately 5.7 km² at high water, with an average depth of 8.6 metres and a maximum depth of 24 metres near the dam. It is fed by the Harpan Khola and several smaller seasonal streams descending from the surrounding hills, and is drained at its southern end by a dam that controls water level and once powered a small hydroelectric plant. The lake's perimeter extends to around 23 km, and its elongated east-west basin was formed by a massive prehistoric landslide that blocked the valley drainage.</p><p>The reflection of Machapuchare (6,993 m) in the lake's morning surface is one of the most reproduced images in Nepalese tourism and has appeared on countless magazine covers and travel documentaries. The full panorama visible on clear days spans from Dhaulagiri (8,167 m) in the west through the Annapurna massif to Lamjung Himal in the east—a sweep of peaks totalling more than 150 km of Himalayan ridgeline. The best light falls in the first hour after sunrise and again in the half-hour before sunset, when alpenglow turns the snow peaks orange and rose. A rowing boat rented from any of the lakeside ghats for NPR 500–800 per hour provides the ideal floating viewpoint, far from the road noise and well clear of the restaurant strip.</p><p>The lake sustains a rich freshwater ecosystem supporting rohu, common carp, and catfish that sustain both artisanal fishers and the restaurant trade. Pied kingfishers hover over the surface and plunge for small fish; little cormorants and spot-billed ducks patrol the shallower margins; and during winter, bar-headed geese—the high-altitude migrants that cross the Himalaya at up to 7,000 m—occasionally settle on the lake. The forested southern hillside, accessible by a short hike, hosts the World Peace Pagoda at its crest and forms a protected green buffer that keeps the lake's western shore peaceful and undeveloped. An informal lakeside promenade runs along the eastern shore from the Baidam tourist strip south to the dam, popular at sunset with both tourists and local families.</p><ul><li>Second largest lake in Nepal at 5.7 km²; elevation 742 m</li><li>Mirror reflection of Machapuchare (Fishtail, 6,993 m) and the Annapurna range</li><li>Rowing boats and canoes available from Lakeside ghats for NPR 500–800 per hour</li><li>Tal Barahi Temple on a central island—reachable only by boat</li><li>Rich birdlife including pied kingfishers, cormorants, and wintering bar-headed geese</li><li>Best sunrise reflections photographed from the middle of the lake by rowing boat</li></ul>`,
    district: "Kaski",
    province: "GANDAKI",
    lat: 28.2154,
    lng: 83.9453,
    elevation: 742,
    entryFee: "Boat hire approx. NPR 500\u2013800/hour; no lake entry fee",
    bestSeason: "Oct\u2013Nov, Feb\u2013Apr",
    openingHours: "Open year-round; boats available sunrise to sunset",
    howToGetThere: "Phewa Lake is in the heart of Pokhara's Lakeside (Baidam) district, within walking distance of all Lakeside hotels. From Pokhara bus park (Prithvi bus park), take a taxi or rickshaw to Lakeside (10\u201315 minutes). The main boat hire ghats are at the northern Lakeside strip near the Pame temple landing and at the Baidam boat club.",
    gygQuery: "Phewa Lake boating Pokhara Annapurna reflection",
    bookingCity: "Pokhara",
    seoTitle: "Phewa Lake Pokhara \u2013 Annapurna Reflection & Boating Nepal",
    seoDescription: "Discover Phewa Lake in Pokhara, Nepal: rent a rowing boat and drift beneath stunning reflections of Machapuchare and the Annapurna range. Visit the Tal Barahi island temple and enjoy sunrise on Nepal's most iconic lake.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "World Peace Pagoda",
    category: "STUPA",
    summary: "Pokhara's World Peace Pagoda (Shanti Stupa) crowns Ananda Hill at 1,100 metres above Phewa Lake, offering a 360-degree panorama of the Annapurna and Dhaulagiri ranges alongside a bird's-eye view of the lake and the Pokhara Valley. Built by Japanese Buddhist monks of the Nipponzan-My\u014dh\u014dji order and inaugurated in 1999, the gleaming white stupa enshrines relics of the Buddha beneath its central chamber. A steep 45-minute hike through forest from the lakeside, or a short boat-and-hike combination, rewards visitors with one of the finest vantage points in Nepal.",
    story: `<p>The World Peace Pagoda on Pokhara's southern hillside is one of 80 peace pagodas built worldwide by the Nipponzan-Myōhōji Buddhist order under the guidance of Japanese monk Nichidatsu Fujii, who laid the foundation stone—along with relics of the Gautama Buddha—on 12 September 1973. Construction took over two decades of local volunteer labour and Japanese donations, with the inaugural ceremony conducted on 30 October 1999 in the presence of former Prime Minister Girija Prasad Koirala. The pagoda stands 35 metres tall (115 feet) and is 105 metres wide (344 feet), its two tiers clad in brilliant white plaster and adorned with four gilded Buddha figures facing the cardinal directions, each depicting a different episode in the Buddha's life: birth, enlightenment, preaching, and nirvana.</p><p>Reaching the pagoda is itself a rewarding journey. The forest trail ascends steeply from the Lakeside boat landing at Damside, winding through a subtropical forest of oak, rhododendron, and pine that shelters langur monkeys and an impressive variety of forest birds including the scarlet minivet, great barbet, and Asian paradise flycatcher. The hike takes approximately 45 minutes at a steady pace and gains about 350 metres of elevation. Alternatively, visitors can take a rowing boat south across the lake from the main Lakeside ghats to the Phewa Lake boat landing near Anada Hill, then hike 30 minutes through the forest directly to the pagoda—a route that avoids road-side noise and is highly recommended at dawn.</p><p>From the pagoda's upper terrace, the panorama is transformative. Phewa Lake glitters 350 metres below, its surface dotted with rowing boats and edged by the hotel strip and forest. The Annapurna South (7,219 m), Hiunchuli (6,441 m), and Machapuchare (6,993 m) rise immediately to the north, while Dhaulagiri (8,167 m) anchors the western horizon and the long ridgeline of the Annapurna II, III, and IV group extends east. On winter mornings, cloud inversions fill the lower valleys while the peaks stand clear above in alpenglow—a sight that has made this viewpoint one of the most photographed spots in all of Nepal. The pagoda's resident monk rings the bell at intervals throughout the day, its deep resonance rolling across the lake and valley below.</p><ul><li>Built by Japanese Nipponzan-Myōhōji monks; inaugurated 1999; enshrines Buddha relics</li><li>Elevation 1,100 m; 35 m tall; two-tiered white pagoda with four gilded Buddhas</li><li>360-degree panorama: Phewa Lake below, Annapurna and Dhaulagiri ranges above</li><li>45-minute forest hike from Damside, or boat+hike combination from Lakeside</li><li>Best light for photography at sunrise and late afternoon</li><li>Free entry; resident monks present for prayer and meditation</li></ul>`,
    district: "Kaski",
    province: "GANDAKI",
    lat: 28.1955,
    lng: 83.9373,
    elevation: 1100,
    entryFee: "Free",
    bestSeason: "Oct\u2013Nov, Feb\u2013Apr",
    openingHours: "Sunrise to sunset",
    howToGetThere: "From Lakeside (Baidam), take a rowing boat south across Phewa Lake to the Phewa Lake boat landing (NPR 400\u2013500), then hike 30 minutes through forest to the pagoda. Alternatively, walk or take a taxi to Damside and ascend the forest trail (45 minutes, steep). Motorcycles and jeeps can access the hilltop via a rough road from Pame village on the south side of the lake.",
    gygQuery: "World Peace Pagoda Pokhara hike Shanti Stupa",
    bookingCity: "Pokhara",
    seoTitle: "World Peace Pagoda Pokhara \u2013 Hilltop Stupa with Annapurna Views",
    seoDescription: "Hike or boat across Phewa Lake to Pokhara's World Peace Pagoda (Shanti Stupa) at 1,100 m. Enjoy 360-degree views of the Annapurna range and Phewa Lake from this iconic Japanese-built Buddhist monument inaugurated in 1999.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Tal Barahi Temple",
    category: "TEMPLE",
    summary: "Tal Barahi Temple is the most sacred religious monument in Pokhara, a two-storey pagoda-style Hindu shrine dedicated to the goddess Barahi\u2014a fierce manifestation of Durga\u2014situated on a small wooded island at the centre of Phewa Lake. Reaching the temple requires a short rowing-boat ride from the Lakeside ghats, making the approach across the sparkling lake as memorable as the shrine itself. Devotees throng the island during the Hindu months of Baisakh (April\u2013May) and Kartik (October\u2013November), burning incense and offering flower garlands to the golden-trident-bearing deity.",
    story: `<p>The island that holds Tal Barahi Temple was formed when the Harpan Khola was dammed in the early twentieth century, slowly raising Phewa Lake's water level until a low wooded hillock became an island. The temple itself, however, predates the lake's current extent: it was built in 1864 by King Kulmandhan Shah of the Kaski Shah Dynasty, a fervent devotee of Goddess Varahi, the boar-headed form of Durga who slew the demon Andhakasura according to Shaivite mythology. The name 'Barahi' derives from 'baraha,' the Sanskrit word for boar, and the deity's principal image—a fierce, multi-armed goddess seated on a stylised boar—is housed in the temple's sanctum sanctorum, its golden face gazing towards the southern hills.</p><p>The temple complex consists of a two-storey pagoda structure with a stone base and a thatched roof, its gold-gilded gajur (pinnacle) and brass bells reflecting in the lake's surface on calm mornings. The exterior walls are painted in the warm ochre tones traditional to Nepali Hindu shrines, and the courtyard supports a dhwajastambha (ceremonial flagpole) from which a crimson pennant flies continuously. A priest maintains a small residence on the island and performs daily puja at dawn and dusk. Visitors are welcome to observe but are asked to remove footwear before entering the temple precincts and to refrain from photography inside the inner sanctum.</p><p>The experience of visiting Tal Barahi Temple is inseparable from the journey across the lake. Boatmen row or paddle wooden vessels from the main Lakeside ghats, weaving between fishing lines and the wakes of other tourist boats, with the silhouette of the temple framed by the Annapurna panorama throughout the crossing. During major festivals—particularly the eighth and ninth days of Dasain (Fulpati and Mahanawami) and on Purnima (full moon) evenings—the island fills with worshippers, flower offerings, and the thick smoke of butter lamps, while drums and cymbals echo across the water. For non-Hindu visitors, the spectacle of lakeside Nepali religious life at close range is deeply compelling.</p><ul><li>Built 1864 by King Kulmandhan Shah; dedicated to goddess Barahi (manifestation of Durga)</li><li>Two-storey pagoda structure with stone base, thatched roof, and golden pinnacle</li><li>Accessible only by rowing boat from Lakeside ghats (NPR 400–600 return per boat)</li><li>Most important religious monument in Pokhara for Hindu worshippers</li><li>Major festival dates: Baisakh (April–May) and Kartik (October–November)</li><li>Daily dawn and dusk puja performed by resident priest</li></ul>`,
    district: "Kaski",
    province: "GANDAKI",
    lat: 28.2125,
    lng: 83.9425,
    elevation: 742,
    entryFee: "Free entry to island; boat hire NPR 400\u2013600 return",
    bestSeason: "Oct\u2013Nov, Feb\u2013Apr",
    openingHours: "Sunrise to sunset; daily puja at dawn and dusk",
    howToGetThere: "Take a rowing boat from any of the Lakeside (Baidam) ghats near Pokhara's hotel strip. The crossing takes 10\u201315 minutes and boats can be hired for NPR 400\u2013600 for a return trip with waiting time. The island is centrally located in Phewa Lake and clearly visible from all lakeside vantage points.",
    gygQuery: "Tal Barahi Temple Phewa Lake boat Pokhara",
    bookingCity: "Pokhara",
    seoTitle: "Tal Barahi Temple Pokhara \u2013 Island Temple on Phewa Lake",
    seoDescription: "Visit Tal Barahi Temple, Pokhara's sacred island shrine dedicated to Goddess Barahi. Reach this two-storey pagoda by rowing boat across Phewa Lake and enjoy mountain reflections on one of Nepal's most picturesque religious journeys.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Davis Falls",
    category: "WATERFALL",
    summary: "Davis Falls\u2014locally called Patale Chhango, meaning 'Underworld Waterfall'\u2014is one of Pokhara's most dramatic natural attractions, where an outflow channel from Phewa Lake plunges vertically into a deep gorge before disappearing through a 150-metre underground tunnel. The waterfall, named after a Swiss woman who drowned here in 1961, is at its most powerful during the monsoon (July\u2013September) when the torrent fills the gorge with roaring white water and spray. A viewing platform and a network of stone paths descend to viewpoints at various levels of the chasm.",
    story: `<p>The water that creates Davis Falls begins its journey at Phewa Lake, carried by an outflow channel that spills over a low concrete weir at the lake's southern dam before gathering speed along a short canal. The channel abruptly disappears into a narrow cleft in the limestone bedrock just south of the Siddhartha Highway, dropping into a darkened pit before vanishing through a natural tunnel approximately 150 metres long and running 30 metres below ground level. The tunnel was carved by centuries of hydraulic action on the fractured limestone formation that underlies the southern Pokhara Valley, the same geological feature that creates the dramatic Seti River Gorge visible elsewhere in the city.</p><p>The name 'Davis Falls' emerged from a tragic incident on July 31, 1961, when a Swiss couple—Mr. and Mrs. Davis—swam in the pool just above the waterfall. The woman was caught by the current and swept into the gorge, her body recovered three days later from the Phusre River. In her memory, her father requested the site be named in her honour, though the name has appeared in various forms—Devi's Falls, Devis Falls, and Davis Falls—reflecting multiple transliterations from Nepali tourism literature. The official Nepali name, Patale Chhango ('Patale' meaning the underworld in Hindu cosmology), more accurately captures the waterfall's character: a swirling descent into an underground darkness.</p><p>A small visitor complex at the site includes a landscaped viewing path that descends alongside the gorge, providing viewpoints from three levels. At monsoon peak—July through September—the roar of the falls is audible from the road and the viewing platforms are drenched in mist, making waterproof gear advisable. In the dry season, the flow is dramatically reduced, but the geology of the gorge is more clearly visible, revealing the smoothly sculpted limestone walls and the dark mouth of the underground tunnel into which the water vanishes. Across the Siddhartha Highway, just 50 metres east, stands the entrance to Gupteshwor Mahadev Cave, where the water from Davis Falls re-emerges in the cave's inner chamber—the two attractions complement each other perfectly in a single two-hour visit.</p><ul><li>Named after a Swiss woman (Mrs. Davis) who drowned here on July 31, 1961</li><li>Water sourced from Phewa Lake flows into a 150-metre underground limestone tunnel</li><li>Official Nepali name: Patale Chhango ('Underworld Waterfall')</li><li>Most spectacular during monsoon (July–September); dramatically reduced in dry season</li><li>Viewing platforms at multiple levels descend alongside the gorge</li><li>Complementary visit with Gupteshwor Cave directly across the highway</li></ul>`,
    district: "Kaski",
    province: "GANDAKI",
    lat: 28.1935,
    lng: 83.9574,
    elevation: 827,
    entryFee: "NPR 100 foreigners / NPR 30 Nepali",
    bestSeason: "Jul\u2013Sep (most powerful); Oct\u2013Apr (accessible and clear)",
    openingHours: "07:00\u201319:00 daily",
    howToGetThere: "Davis Falls is located on the Siddhartha Highway approximately 2 km southwest of Pokhara's main Lakeside (Baidam) area. Taxis from Lakeside take 5\u201310 minutes (NPR 150\u2013200). Rented bicycles and motorcycles are also popular options. The site is on the main road between Lakeside and the Tibetan settlement of Tashiling.",
    gygQuery: "Davis Falls Pokhara waterfall Patale Chhango",
    bookingCity: "Pokhara",
    seoTitle: "Davis Falls Pokhara \u2013 Patale Chhango Underground Waterfall",
    seoDescription: "Explore Davis Falls (Patale Chhango) in Pokhara\u2014a dramatic waterfall that plunges into an underground limestone tunnel. Visit during monsoon for full power, then cross the highway to discover the connected Gupteshwor Mahadev Cave.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Gupteshwor Mahadev Cave",
    category: "CAVE",
    summary: "Gupteshwor Mahadev Cave is Nepal's longest cave system and one of Pokhara's most venerated Hindu pilgrimage sites, stretching 2,950 metres through the limestone bedrock directly opposite Davis Falls on the Siddhartha Highway. Inside, a succession of chambers shelters shrines dedicated to Shiva, Parvati, and Nageswor, their walls decorated with votive offerings and natural stalactites and stalagmites. The innermost chamber dramatically reveals a window onto the back wall of Davis Falls, where the waterfall plunges into the underground world described in the cave's name\u2014'Gupteshwor' meaning 'Hidden Lord.'",
    story: `<p>Gupteshwor Mahadev Cave lies beneath the limestone hills of Chhorepatan in Pokhara's Ward 17, Kaski District, and is said to have been discovered in the sixteenth century, though formal public access to the main entrance was only developed in 1991. The cave system is reputed to be the longest in Nepal and South Asia, extending 2,950 metres through a complex network of passages, chambers, and underground streams. Its religious significance is enormous: the cave is a swayambhu shrine, meaning the Shiva lingam enshrined within is believed to have appeared naturally from the rock rather than being installed by human hands. Generations of Hindu priests have maintained the shrines, and local tradition holds that the cave connects spiritually with the sacred Muktinath temple in Mustang far to the north.</p><p>The cave is entered through a narrow passage behind a modern concrete gateway beside the Siddhartha Highway. The route descends through progressively lower and narrower passages—some requiring crouching—past two principal shrine chambers. The first chamber contains a statue of a cow bowed over a Shiva lingam, a reference to the mythological white cow (dhenu) that revealed the cave's sacred nature. The second, deeper chamber houses the principal Shiva temple, flanked by shrines to Parvati and the serpent deity Nageswor, where oil lamps and incense maintain a perpetual haze. Photography is not permitted in this inner sanctum. Stalactites of various sizes descend from the cave ceiling, and water seeps through the limestone in wet season, creating natural columns and flowstone formations.</p><p>The cave's most dramatic moment arrives at the innermost accessible point, where a window cut in the rock opens onto a thundering view of Davis Falls crashing into the pit on the other side of the limestone wall. During the monsoon, the roar is deafening and spray shoots through the window; in the dry season, a more modest flow allows a clearer view of the falls' underground journey and the dark tunnel through which the water continues on its way to the Phusre River. Emerging from the cave, visitors re-enter daylight through a separate exit—a symbolic rebirth that reinforces the cave's role in Hindu cosmology as a passage between the earthly and underworld realms. The site is best combined with Davis Falls in a single morning visit.</p><ul><li>Nepal and South Asia's longest cave at 2,950 metres; discovered 16th century</li><li>Swayambhu Shiva lingam—believed to have appeared naturally from the rock</li><li>Shrines to Shiva, Parvati, Nageswor and a sacred cow statue inside the cave</li><li>Inner chamber window provides a dramatic view of Davis Falls underground</li><li>Natural stalactites, stalagmites, and seasonal underground streams</li><li>One entry, one exit—symbolically a passage between earthly and underworld realms</li></ul>`,
    district: "Kaski",
    province: "GANDAKI",
    lat: 28.1943,
    lng: 83.9583,
    elevation: 827,
    entryFee: "NPR 100 foreigners / NPR 50 Nepali",
    bestSeason: "Oct\u2013Jun (cave open year-round but inner chambers may flood in deep monsoon)",
    openingHours: "06:00\u201318:00 daily",
    howToGetThere: "Gupteshwor Mahadev Cave is located directly opposite Davis Falls on the Siddhartha Highway, approximately 2 km southwest of Pokhara Lakeside. Taxis from Lakeside take 5\u201310 minutes (NPR 150\u2013200). The cave entrance is immediately visible from the road; tickets are purchased at the gate.",
    gygQuery: "Gupteshwor Cave Pokhara sacred cave Shiva",
    bookingCity: "Pokhara",
    seoTitle: "Gupteshwor Mahadev Cave \u2013 Sacred Shiva Cave near Davis Falls Pokhara",
    seoDescription: "Explore Gupteshwor Mahadev Cave in Pokhara, Nepal's longest cave (2,950 m) and a sacred Shiva pilgrimage site. Navigate candlelit chambers, see ancient shrines, and peer through the cave wall onto the thundering Davis Falls.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Begnas Lake",
    category: "LAKE",
    summary: "Begnas Lake is the tranquil, unspoilt alternative to Phewa Lake, Nepal's third-largest freshwater lake lying 15 km southeast of Pokhara with clear water, forested hillside surroundings, and clear mountain views stretching to Annapurna and Manaslu. At 650 metres elevation, the L-shaped lake covers 3.28 km\u00b2 and supports caged fish farms, artisanal fishing, and low-key boating tourism far from the crowds of Lakeside. The absence of heavy tourist infrastructure makes Begnas the preferred destination for travellers seeking peaceful nature immersion.",
    story: `<p>Begnas Lake lies in the southeastern reach of the Pokhara Valley within Kaski District, separated from the city's bustle by a low ridge that effectively insulates the lake from the development pressures that have reshaped Phewa Lake's eastern shore. The lake sits at 650 metres, slightly lower than Phewa, and is fed by the Syankhudi and Talbesi streams descending from the surrounding hills. A dam constructed in 1988 on the western outlet Khudi Khola regulates water levels, preventing seasonal flooding of the lakeside villages and stabilising conditions for the caged fish-farm operations that are a significant source of local income. The lake's L-shaped basin—with one arm extending south and another west—creates varied shoreline habitats including reed beds, mudflats, and open water that attract different species of waterfowl.</p><p>The lake is home to an impressive diversity of freshwater fish—rohu, grass carp, silver carp, and catfish—and the caged aquaculture operations visible from the lakeside road supply a significant portion of Pokhara's restaurant fish demand. Traditional fishers in dugout canoes or bamboo-and-wood flat-bottomed boats work the lake's outer margins, their lines extending to the reed-fringed banks where fish shelter. Birdlife is exceptional by Terai standards: pied kingfishers hover and plunge throughout the day, spot-billed ducks lead ducklings through the reeds, and in winter, flocks of common teal and ferruginous ducks congregate on the open water. The surrounding hills support populations of rhesus macaques and langur monkeys, visible in the trees along the access road.</p><p>The lakeside village of Begnas Bazar, a 20-minute local bus ride from Pokhara's Prithvi Chowk, provides a low-key base with several small lakeside restaurants serving fresh fish and local daal-bhat. Rowing boats can be hired from the Begnas jetty for NPR 300–500 per hour for independent exploration or for crossing to Rupa Lake, which sits just 3 km to the southeast across a low watershed. A modest hilltop viewpoint tower on the northern shore offers a panoramic view over both lakes and the Annapurna range. The combination of Begnas and Rupa Lakes in a single full-day cycle ride or jeep excursion from Pokhara provides a deeply rewarding alternative to the standard Lakeside circuit.</p><ul><li>Third-largest lake in Nepal; 3.28 km² surface; elevation 650 m</li><li>Far quieter than Phewa Lake—favoured by local visitors and independent travellers</li><li>Clear mountain views of Annapurna and Manaslu ranges on clear mornings</li><li>Caged fish farms and artisanal fishing sustain local livelihoods</li><li>Rich birdlife: kingfishers, spot-billed ducks, winter teal, and ferruginous ducks</li><li>Easily combined with adjacent Rupa Lake in a single day excursion</li></ul>`,
    district: "Kaski",
    province: "GANDAKI",
    lat: 28.174,
    lng: 84.0961,
    elevation: 650,
    entryFee: "Free; boat hire NPR 300\u2013500/hour",
    bestSeason: "Oct\u2013Apr",
    openingHours: "Open year-round",
    howToGetThere: "From Pokhara's Prithvi Chowk bus park, take a local bus or microvan towards Lekhnath/Begnas (30\u201340 minutes, NPR 50\u201370). Taxis from Lakeside take 25\u201330 minutes (NPR 600\u2013800). The lake is 15 km from Pokhara city centre via the Ring Road east. Bicycles from Lakeside make the trip in about 1 hour on a mostly flat route.",
    gygQuery: "Begnas Lake Pokhara boating peaceful Nepal",
    bookingCity: "Pokhara",
    seoTitle: "Begnas Lake Pokhara \u2013 Peaceful Freshwater Lake with Mountain Views",
    seoDescription: "Escape the crowds at Begnas Lake, a tranquil freshwater gem 15 km from Pokhara. Enjoy rowing boats, fresh fish restaurants, excellent birdwatching, and clear views of the Annapurna range at Nepal's third-largest lake.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Rupa Lake",
    category: "LAKE",
    summary: "Rupa Lake is the smallest and most secluded of Pokhara Valley's trio of famous lakes, a glacial freshwater body of 1.35 km\u00b2 nestled at 600 metres elevation between forested ridges 10 km southeast of Pokhara. Its striking sky-blue colour\u2014caused by glacial flour suspended in the water\u2014and the stillness of its surface make it a serene escape for photographers, birdwatchers, and travellers seeking solitude over scenery. Rupa is best visited in tandem with neighbouring Begnas Lake, the two connected by a dirt track through farmland and forest.",
    story: `<p>Rupa Lake occupies a gentle depression in the southern Pokhara Valley, straddling the boundary between Pokhara Metropolitan and Rupa Rural Municipality of Kaski District. At 600 metres above sea level—50 metres lower than Begnas Lake just 3 km to the northwest—it is the third-largest lake in the valley and the fourth-largest natural lake in Nepal. Its catchment area of 30 km² encompasses surrounding forested ridges and terraced agricultural land, with water fed by the Talbesi stream and Dhovan Khola. The outlet, Tal Khola, drains south at Sistani Ghat. The lake's shallow average depth of 3 metres (maximum 6 metres) makes it extremely sensitive to seasonal water level fluctuations, expanding noticeably in the monsoon and contracting in the dry months to expose mudflats that attract wading birds.</p><p>The lake's distinctive colour sets it apart from the green-tinted waters of Phewa and the more turbid Begnas. The glacial flour—microscopic rock particles ground by ancient glacial action and still suspended in the water from glacial-melt tributaries—scatters light in the blue wavelengths, giving the surface a luminous, almost cerulean hue on overcast days and a deep sapphire tinge in direct sunlight. This same effect makes the lake's underwater clarity surprisingly high in the dry season, with the sandy bottom visible in the shallows. The surrounding hills remain largely forested and protected under community forestry programmes, and langur monkeys and rhesus macaques are regularly seen in the trees above the eastern shoreline.</p><p>Rupa's relative inaccessibility—there is no paved road directly to its shore—preserves the lake's peaceful character. A dirt track from the Begnas Bazar connects to the northern lakeside in about 40 minutes on foot or 15 minutes by bicycle, passing through small Gurung and Magar villages where stone-built houses, millet-drying yards, and prayer flags mark the transition from Pokhara's urban fringe to traditional hill culture. A simple wooden viewpoint tower on the northern shore surveys both the lake and the Annapurna III and Machhapuchhare peaks to the north. Birdwatching is outstanding: the reed margins host purple heron, black-crowned night heron, and spot-billed pelican in season, while raptors—osprey, white-bellied sea eagle, and pied harrier—hunt over the open water. Local initiatives promote tent camping on the western shoreline for those who wish to spend the night beneath the stars beside the lake.</p><ul><li>Glacial lake with distinctive sky-blue colour caused by suspended glacial flour</li><li>Third-largest lake in Pokhara Valley; 1.35 km²; elevation 600 m; depth up to 6 m</li><li>No direct paved road—preserves exceptional tranquillity and natural character</li><li>Outstanding birdwatching: purple heron, pelican, osprey, white-bellied sea eagle</li><li>Camping permitted on the western shoreline under community tourism scheme</li><li>Gurung and Magar villages en route from Begnas Bazar—cultural interest</li></ul>`,
    district: "Kaski",
    province: "GANDAKI",
    lat: 28.1495,
    lng: 84.1067,
    elevation: 600,
    entryFee: "Free",
    bestSeason: "Oct\u2013Apr",
    openingHours: "Open year-round",
    howToGetThere: "Rupa Lake is best reached from Begnas Lake (3 km southeast via dirt track, 40 minutes on foot or 15 minutes by bicycle). From Pokhara, take a local bus to Begnas Bazar (30\u201340 minutes), then continue by bicycle or on foot. Alternatively, hire a taxi from Pokhara directly to the lake (35\u201340 minutes, NPR 800\u20131000).",
    gygQuery: "Rupa Lake Pokhara secluded lake birdwatching Nepal",
    bookingCity: "Pokhara",
    seoTitle: "Rupa Lake Pokhara \u2013 Glacial Lake & Birdwatching Retreat Nepal",
    seoDescription: "Visit Rupa Lake near Pokhara, a pristine glacial lake with striking blue water and exceptional birdwatching. Explore this tranquil retreat surrounded by Gurung villages and Annapurna mountain views, far from the tourist crowds.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Bat Cave (Chamero Gufa)",
    category: "CAVE",
    summary: "Bat Cave (Chamero Gufa) is a solutional limestone cave near Batulechaur, approximately 9 km northwest of Pokhara Lakeside, home to thousands of roosting horseshoe and roundleaf bats that cluster in dense formations on the cave ceiling. The 150-metre cave requires crouching through narrow passages\u2014including a tight exit squeeze\u2014and features stalactites, stalagmites, and carvings of Hindu deities on the walls. Often visited alongside the nearby Mahendra Cave, Bat Cave provides an adventurous and atmospheric underground experience for a wide range of ages.",
    story: `<p>Chamero Gufa—the Bat Cave—formed through the dissolution of the Pokhara Valley's limestone bedrock by mildly acidic groundwater over thousands of years, the same geological process that created Gupteshwor Mahadev Cave on the southern side of the valley. The cave system at Batulechaur is roughly 150 metres long, with a single main passage that descends gently from the entrance before widening into a central chamber and then narrowing again toward the exit, which is significantly tighter than the entrance and requires careful navigation. The formation is part of a cluster of caves in the northern hills of the Pokhara Valley that formed in the Palaeocene-era limestone exposed along the valley's flanks.</p><p>The cave's central attraction—the thousands of bats hanging from the ceiling and walls—is immediately apparent upon entering. The colony consists primarily of greater and lesser horseshoe bats (Rhinolophus ferrumequinum and R. hipposideros) and several roundleaf bat species (Hipposideros spp.), all belonging to the suborder Microchiroptera and navigating by echolocation. In the cave's dim interior, their bodies form a dense, living carpet on the ceiling, their wings folded tightly around them during the day. At dusk, the entire colony erupts from the cave mouth in a spiralling black torrent that can last 20–30 minutes—a spectacle worth timing a visit for. Natural stalactites and stalagmites add geological interest, and in several alcoves, carvings of Hindu deities—Shiva, Ganesh, and Nandi—have been placed by local devotees, reflecting the Nepali tradition of identifying sacred presence within cave environments.</p><p>Bat Cave is typically combined with a visit to Mahendra Cave, another limestone cave 200 metres uphill that is larger, better lit, and has a more developed internal pathway, making the two a complementary pair. Flashlights (provided by guides or sold at the entrance) are essential for the darker inner sections of Chamero Gufa. A local guide service operates at the cave entrance, and guides are particularly useful for the tight exit passage and for identifying bat species. The cave is a popular morning excursion from Pokhara, often combined with a drive past Seti River Gorge viewpoints at Mahendra Pul before returning to Lakeside for lunch.</p><ul><li>150-metre limestone cave home to thousands of horseshoe and roundleaf bats</li><li>Tight exit passage requires crouching—part of the adventurous appeal</li><li>Dusk bat flight from cave mouth lasts 20–30 minutes—a dramatic natural spectacle</li><li>Stalactites, stalagmites, and Hindu deity carvings inside the cave</li><li>Located 9 km northwest of Lakeside near Batulechaur</li><li>Best combined with adjacent Mahendra Cave in a single half-day excursion</li></ul>`,
    district: "Kaski",
    province: "GANDAKI",
    lat: 28.2823,
    lng: 83.9573,
    elevation: 900,
    entryFee: "NPR 150 foreigners / NPR 80 SAARC / NPR 50 Nepali; guide NPR 300",
    bestSeason: "Oct\u2013Jun",
    openingHours: "09:00\u201317:00 daily",
    howToGetThere: "Bat Cave is located near Batulechaur village, approximately 9 km north of Pokhara Lakeside. Taxis from Lakeside take 20\u201325 minutes (NPR 400\u2013600). Rented motorcycles or bicycles reach the cave via the Prithvi Highway north. The cave is often included in guided northern Pokhara half-day tours that also cover the Seti River Gorge viewpoints.",
    gygQuery: "Bat Cave Pokhara Chamero Gufa cave tour Nepal",
    bookingCity: "Pokhara",
    seoTitle: "Bat Cave Pokhara (Chamero Gufa) \u2013 Limestone Cave with Bats Nepal",
    seoDescription: "Explore the Bat Cave (Chamero Gufa) near Pokhara\u2014a 150-metre limestone cave packed with thousands of roosting bats, stalactites, and Hindu carvings. Watch the dramatic dusk bat exodus and combine with nearby Mahendra Cave.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Pokhara Regional Museum",
    category: "ARCHAEOLOGICAL",
    summary: "The Pokhara Regional Museum (Annapurna Regional Museum) is Pokhara's principal ethnographic and natural history institution, preserving artefacts, traditional costumes, tools, and ecological specimens related to the cultural diversity and natural heritage of the Gandaki Province. Located in the Prithvi Narayan Campus area, the museum's compact galleries document the material culture of the Gurung, Magar, Thakali, Tibetan, and other hill communities of the Pokhara region, providing essential cultural context before or after a trek in the Annapurna area.",
    story: `<p>The Pokhara Regional Museum was established in 1979 under the Department of Archaeology to document and preserve the material culture of the western hill region of Nepal, including the many distinct ethnic communities—Gurung, Magar, Thakali, Chhetri, Tibetan, and others—whose traditions were at risk of disappearing as the region urbanised through the late twentieth century. The museum's collection grew through community donations, field research expeditions, and government cultural preservation programmes, and its galleries now house several thousand artefacts representing multiple centuries of craft production, ritual practice, and daily life in the hills and valleys of Gandaki Province.</p><p>The museum's exhibits are arranged thematically across several rooms. The ethnographic hall presents traditional costumes of major ethnic groups: the Gurung's distinctive green and red lungi skirts and silver jewellery, the Thakali's heavily embroidered jackets and distinctive headgear, and the Tibetan monks' robes and butter-lamp holders. Display cases contain agricultural implements, hunting weapons including longbows and iron-tipped arrows, hand-loomed fabrics, and ceremonial objects associated with shamanic (jhankri) and Buddhist ritual practice. A natural history section exhibits mounted specimens of birds and mammals found in the Pokhara Valley and Annapurna region, including several species of pheasant, deer, and endangered mammals.</p><p>A collection of ancient coins—dating from the Licchavi and Malla periods—and inscribed stone tablets recovered from excavations in the valley provide evidence of Pokhara's role as a trading waystation on the salt routes between the Tibetan plateau and the Gangetic plains. The museum is a modest but worthwhile 60-to-90-minute visit that rewards curiosity and provides a grounding in the cultural diversity of the trekking regions visited on the Annapurna Circuit. Photography is permitted in most areas with a camera fee. The museum is located near the Prithvi Narayan Campus just east of the Pokhara city centre, easily accessible by taxi or on foot from the Bazar area.</p><ul><li>Established 1979; documents the cultural heritage of Gandaki Province</li><li>Ethnic costumes, tools, and ceremonial objects of Gurung, Magar, Thakali, Tibetan communities</li><li>Ancient coins and inscribed stone tablets from Licchavi and Malla periods</li><li>Natural history section with mounted birds and mammals of the Annapurna region</li><li>Shamanic and Buddhist ritual artefacts collected from remote hill villages</li><li>Compact 60–90 minute visit; essential cultural context for Annapurna trekkers</li></ul>`,
    district: "Kaski",
    province: "GANDAKI",
    lat: 28.2344,
    lng: 83.9864,
    elevation: 827,
    entryFee: "NPR 50 (all visitors); camera fee additional",
    bestSeason: "Year-round",
    openingHours: "10:00\u201317:00 daily (closed Tuesday)",
    howToGetThere: "The Pokhara Regional Museum is located near Prithvi Narayan Campus in the Bhansar area of Pokhara, approximately 2 km northeast of the Lakeside tourist strip. Taxis from Lakeside take 10 minutes (NPR 150\u2013200). The museum is a 30-minute walk from Lakeside along the main Mahendra Pul road.",
    gygQuery: "Pokhara Regional Museum Annapurna cultural Nepal",
    bookingCity: "Pokhara",
    seoTitle: "Pokhara Regional Museum \u2013 Culture & Heritage of Gandaki Province",
    seoDescription: "Visit the Pokhara Regional Museum to explore the cultural diversity of Nepal's Gandaki Province. See ethnic costumes, traditional artefacts, ancient coins, and natural history specimens from Gurung, Magar, and Thakali communities.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "International Mountain Museum",
    category: "ARCHAEOLOGICAL",
    summary: "The International Mountain Museum in Pokhara is Asia's premier mountaineering museum, dedicated to the history of Himalayan exploration and the indigenous mountain cultures of Nepal. Opened in 2004 and established by the Nepal Mountaineering Association, the museum's three main exhibition halls display original expedition equipment, historical photographs, summit diaries, and rock specimens from the world's fourteen 8,000-metre peaks. An outdoor garden features full-size tents, aircraft, and a climbing wall, making it the single most informative attraction about Nepal's mountain heritage.",
    story: `<p>The International Mountain Museum was established on February 5, 2004, following a foundation-stone ceremony in December 1995, when the Nepal Mountaineering Association committed to creating a world-class institution that would preserve and celebrate the extraordinary history of Himalayan mountaineering. Located approximately 1.5 km south of Pokhara International Airport in the Ratopairo area of Ward 17, the museum's modern building is designed to echo the forms of mountain ridgelines, its roofline rising and falling against the backdrop of the Annapurna range visible on clear days through the ground-floor windows. The museum attracts over 100,000 domestic and international visitors annually.</p><p>The museum's three primary exhibition halls are arranged thematically. The Mountain Lifestyle Hall documents the cultures, agricultural practices, festivals, and religious traditions of Nepal's indigenous mountain peoples—Sherpa, Gurung, Thakali, Magar, and others—through dioramas, costume displays, and artefact collections. The Mountaineering History Hall presents the gripping chronology of Himalayan exploration: hand-drawn maps and surveying instruments used by Great Trigonometric Survey teams in the nineteenth century, the original oxygen cylinders and ice axes from early Everest expeditions, summit diaries, and the famous photograph of Tenzing Norgay holding flags on Everest's summit on 29 May 1953. The Mountain Environment Hall displays geological rock specimens from all fourteen 8,000-metre peaks, a yeti structure, and a Buddhist lhakhang (chapel) maintained by the resident monk.</p><p>The museum's outdoor grounds include a full-size recreation of a base camp tent, a Dhruv helicopter used in mountain search-and-rescue operations, the Maurice Herzog Climbing Wall (a short artificial climbing wall where visitors can try harness climbing with an instructor), and a garden where cultural demonstrations are occasionally held. A comprehensive library holds mountaineering literature in multiple languages, and the souvenir shop stocks quality books, prints, and memorabilia related to Nepal's peaks. The museum's café opens onto mountain views that on clear mornings—October through December—frame Dhaulagiri, Annapurna, and Manaslu in a single panoramic sweep. A visit of two to three hours is recommended to do justice to the collection.</p><ul><li>Established 2004 by Nepal Mountaineering Association; 100,000+ annual visitors</li><li>Three halls: Mountain Lifestyle, Mountaineering History, Mountain Environment</li><li>Original expedition equipment from historic Everest and Annapurna ascents</li><li>Rock specimens from all fourteen 8,000-metre peaks on display</li><li>Outdoor Maurice Herzog Climbing Wall and base-camp recreation in museum garden</li><li>Comprehensive library, café with mountain views, and quality souvenir shop</li></ul>`,
    district: "Kaski",
    province: "GANDAKI",
    lat: 28.1973,
    lng: 83.9726,
    elevation: 827,
    entryFee: "NPR 750 foreigners / NPR 350 SAARC / NPR 100 Nepali",
    bestSeason: "Year-round",
    openingHours: "08:30\u201317:00 daily (365 days)",
    howToGetThere: "The International Mountain Museum is located in Ratopairo, Ward 17 of Pokhara, approximately 1.5 km south of Pokhara International Airport and 5 km from the Lakeside area. Taxis from Lakeside take 15\u201320 minutes (NPR 300\u2013400). The museum is signposted from the main Siddhartha Highway and from Pokhara Airport road.",
    gygQuery: "International Mountain Museum Pokhara mountaineering Nepal",
    bookingCity: "Pokhara",
    seoTitle: "International Mountain Museum Pokhara \u2013 Nepal's Mountaineering Heritage",
    seoDescription: "Visit the International Mountain Museum in Pokhara\u2014Asia's premier Himalayan mountaineering museum. See original Everest expedition gear, indigenous mountain cultures, 8,000-metre peak rock specimens, and a climbing wall in Nepal.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Seti River Gorge",
    category: "RIVER",
    summary: "The Seti River Gorge is one of Pokhara's most surprising geological spectacles\u2014a narrow limestone canyon where the milky-white Seti Gandaki River disappears underground for three kilometres beneath the city before re-emerging at the base of cliffs downstream. At several city-centre bridge viewpoints the gorge is barely two metres wide but plunges 20 metres straight down, and the roar of invisible white water rises eerily from the darkness below. The river's white colour comes from glacial sediment carried from the Annapurna massif, making it instantly distinctive from every crossing point.",
    story: `<p>The Seti Gandaki River originates from the glaciers of the Annapurna massif above Pokhara, carrying a heavy load of pulverised glacial rock—known as glacial flour or rock flour—that gives the water its characteristic milky white appearance and lends the river its name: 'Seti' means 'white' in Nepali. As it approaches Pokhara from the north, the river encounters a zone of ancient fractured limestone that underlies much of the valley floor, and at some point in geological history the river found a path underground, hollowing out a cave system that now routes the entire river flow beneath the city for approximately three kilometres. The underground passage includes lateral chambers that extend up to 250 metres from the main channel, and the cave ceiling rises as high as 80 metres above the water in some sections.</p><p>The gorge is viewable from several bridges and open vantage points within the city. Mahendra Pul, the most central bridge over the Seti, provides a dramatic straight-down view into the narrow crack where the river churns through the limestone—the gap at road level is sometimes barely wide enough to extend an arm across, yet the water roars invisibly below. K.I. Singh Pul further upstream offers a wider angle and is a popular viewpoint for local residents in the evening. Prithvi Chowk bridge provides yet another perspective. The contrast between the ordinary city streetscape and the sudden abyss of the gorge makes each viewpoint unexpectedly vertiginous. In the monsoon, when the Seti runs at full volume, the sound of the underground river can be heard from considerable distance.</p><p>Downstream of the city, the Seti re-emerges at the base of a series of limestone cliffs and continues south before joining the Madi River. This lower section of the gorge—accessible by a rough trail from the south end of the city—reveals the full scale of the underground erosion, with cave mouths visible in the cliff faces where side tributaries once entered. Geologists have identified the formation as a karst collapse feature similar to underground rivers found in Slovenia and China. For travellers, the Seti River Gorge is best experienced by walking between several bridges over an hour or two, observing how the city's daily life—markets, shops, traffic—continues right at the edge of this extraordinary geological void. The viewpoints require no entry fee and are accessible at any hour.</p><ul><li>Milky-white river carrying glacial sediment from Annapurna glaciers—'Seti' means 'white'</li><li>River disappears underground for ~3 km through a limestone karst system beneath the city</li><li>Gorge is barely 2 m wide at road level but up to 20 m deep at central bridges</li><li>Underground chambers extend 250 m laterally and 80 m high in some sections</li><li>Viewable free of charge from Mahendra Pul, K.I. Singh Pul, and Prithvi Chowk bridges</li><li>Most dramatic during monsoon when the underground roar is audible from street level</li></ul>`,
    district: "Kaski",
    province: "GANDAKI",
    lat: 28.2434,
    lng: 83.9875,
    elevation: 860,
    entryFee: "Free",
    bestSeason: "Year-round; most dramatic Jul\u2013Sep (monsoon flow)",
    openingHours: "Open 24 hours (outdoor viewpoints)",
    howToGetThere: "The main Seti River Gorge viewpoint at Mahendra Pul bridge is in central Pokhara, approximately 3 km northeast of the Lakeside tourist strip. Walk or take a taxi (NPR 150\u2013200 from Lakeside). Multiple other viewpoints at K.I. Singh Pul and Prithvi Chowk are within a 500-metre walking radius of Mahendra Pul.",
    gygQuery: "Seti River Gorge Pokhara underground gorge viewpoint",
    bookingCity: "Pokhara",
    seoTitle: "Seti River Gorge Pokhara \u2013 White River Underground Canyon Nepal",
    seoDescription: "Peer into the Seti River Gorge in Pokhara, where the glacial white Seti Gandaki flows underground through a dramatic 20-metre-deep limestone canyon barely 2 metres wide. Walk between city-centre bridges for free views of this geological wonder.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Matepani Gumba",
    category: "MONASTERY",
    summary: "Matepani Gumba is a serene Tibetan Buddhist monastery perched on a small wooded hill five kilometres east of central Pokhara, established in 1960 by Nyeshang families who migrated from the Manang valley following Tibetan refugees into Nepal. The monastery's main hall houses large statues of Shakyamuni Buddha, Padmasambhava, and Karmapa, their gilded surfaces gleaming in the lamplight, and the walls are covered with detailed thangka paintings of the Buddhist cosmology. From the hilltop, panoramic views extend across Pokhara to Machapuchare and the full Annapurna range.",
    story: `<p>Matepani Gumba stands in the Kundahar district of Pokhara at coordinates 28.2165°N, 84.0074°E, on a green hillock east of the city that has been a site of Buddhist practice since the monastery's founding in 1960 A.D. The founding community consisted of Nyeshang people from the high-altitude Manang valley—traders and farmers who had centuries of involvement with Tibetan Buddhist culture through the trans-Himalayan salt and wool trade. When Tibetan refugees fled across the mountains following the 1959 Lhasa uprising, the Nyeshang diaspora in Pokhara created Matepani as a spiritual anchor for the displaced community, establishing a pattern of monastic patronage that has continued for sixty-five years. The monastery belongs to the Kagyu school of Tibetan Buddhism, the tradition most associated with the Karmapa lineage holders.</p><p>The monastery complex is entered through a traditional Tibetan gateway painted with the Eight Auspicious Symbols and flanked by white chorten (stupas). The main prayer hall—rebuilt and expanded in the 1990s—is dominated by three seated statues approximately 3.5 metres tall: Shakyamuni Buddha in the centre, Padmasambhava (the 8th-century tantric master who brought Buddhism to Tibet) on the left, and the 16th Karmapa on the right. The walls are covered floor to ceiling with thangka paintings depicting the Wheel of Life, the paradise of Amitabha, and elaborate mandala compositions. Butter lamps burn before the altar throughout the day, and the fragrance of juniper incense drifts through the hall. Approximately 50 monks reside at the monastery, following a strict daily schedule of dawn prayers, individual study, group recitation, and evening prayers.</p><p>The hilltop grounds of Matepani offer one of the finest accessible vantage points in Pokhara for mountain views without a long hike. Machapuchare (6,993 m) rises directly north in a near-perfect triangular profile, flanked by Annapurna South (7,219 m) and Hiunchuli (6,441 m). The Pokhara Valley spreads below, its lakes gleaming silver in the early morning and the city's temples and stupa visible among the trees. The monastery welcomes respectful visitors throughout the day; donations to the gompa fund go toward education and maintenance of the monastic community. Morning visits—between 6:00 and 8:00 AM—coincide with the monks' puja ceremony, a deeply moving soundtrack of drums, conch shells, and chanting that resonates across the hillside.</p><ul><li>Established 1960 by Nyeshang community from Manang; Kagyu school Tibetan Buddhism</li><li>Houses ~50 monks with daily puja at dawn and late afternoon</li><li>Three large gilded statues: Shakyamuni, Padmasambhava, and the 16th Karmapa</li><li>Walls covered in detailed thangka paintings and Buddhist cosmological murals</li><li>Hilltop views of Machapuchare, Annapurna South, and the Pokhara Valley</li><li>Best visited at dawn (06:00–08:00) to witness the monks' morning puja ceremony</li></ul>`,
    district: "Kaski",
    province: "GANDAKI",
    lat: 28.2165,
    lng: 84.0074,
    elevation: 930,
    entryFee: "Free (donations appreciated)",
    bestSeason: "Year-round",
    openingHours: "05:30\u201319:00 daily; main puja 06:00\u201308:00 and 16:00\u201318:00",
    howToGetThere: "Matepani Gumba is located approximately 5 km east of Pokhara's Mahendrapul central area. Taxis from Lakeside take 15\u201320 minutes (NPR 300\u2013400). Motorcycles and bicycles can navigate the narrow road up the hill. The monastery is also reachable on foot from the Ring Road via a 20-minute uphill path through the forest.",
    gygQuery: "Matepani Monastery Pokhara Tibetan Buddhist Nepal",
    bookingCity: "Pokhara",
    seoTitle: "Matepani Gumba Pokhara \u2013 Tibetan Monastery with Annapurna Views",
    seoDescription: "Visit Matepani Gumba, a peaceful Tibetan Buddhist monastery above Pokhara established by the Nyeshang community in 1960. Witness morning puja with 50 resident monks, see gilded Buddha statues, and enjoy Annapurna panoramas.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Bindhyabasini Temple",
    category: "TEMPLE",
    summary: "Bindhyabasini Temple is Pokhara's oldest and most revered Hindu temple, dedicated to the goddess Bindhyabasini\u2014a fierce manifestation of Durga\u2014and seated atop a wooded hillock in the city's old Bazar area with panoramic views of the Annapurna and Machapuchare peaks. Established around the 1760s and built in Shikhara architectural style\u2014unusual for Nepal's predominantly pagoda-form temples\u2014the complex also houses shrines to Saraswati, Shiva, Hanuman, and Ganesha within a park-like compound. Local Pokhara residents consider this temple their most significant place of worship and throng here during Dasain and Shivaratri.",
    story: `<p>Bindhyabasini Temple stands at 915 metres above sea level (3,002 feet) on a natural hillock that has likely been a site of worship for far longer than any written record confirms. The deity herself—Goddess Bindhyabasini, whose name means 'Vindhya Dweller' and refers to the Vindhya mountain range in central India—was brought to Pokhara from the famous Vindhyachal temple in Uttar Pradesh according to local legend, when King Siddhi Narayan Shah of Kaski received a divine vision commanding him to establish her presence in his kingdom. The idol became unmovable upon reaching the hilltop, which was interpreted as the goddess choosing her own location—a common trope in Nepali temple origin narratives that reflects the animist belief that sacred geography precedes and determines built form.</p><p>The temple structure, formally established in 1842 B.S. (approximately 1785 CE) on a compound of 47 ropanis, is built in the North Indian Shikhara style—a curvilinear tower rising above the sanctum sanctorum—rather than the Newar pagoda style dominant in the Kathmandu Valley. The choice of Shikhara architecture reflects the Kaski kingdom's cultural connections with the Indian plains through the salt and grain trade routes, and gives the temple a distinctly different visual character from Pokhara's other religious monuments. Two gilded stone lions guard the main entrance, and the outer terrace is ringed by subsidiary shrines and a covered gallery where devotees sit and meditate facing the Himalayan panorama. A small elevator, inaugurated in 2019 by Nepal's President to assist elderly and disabled worshippers, ascends from the base of the hill to the temple gate.</p><p>The temple's significance in local spiritual life is reflected in the extraordinary attendance during major Hindu festivals. Dasain—Nepal's greatest festival—brings thousands of worshippers to the temple during Fulpati and Mahanawami for animal sacrifices and blood offerings to the goddess, the temple courtyard thick with flower garlands and the drumming of dhime bands. Shivaratri in February draws ascetics and pilgrims who maintain all-night vigils around bonfires in the compound. From the temple's balcony terrace, the view north encompasses the full Annapurna panorama—Annapurna I (8,091 m), II (7,937 m), III (7,555 m), IV (7,525 m), South (7,219 m), Machapuchare (6,993 m), and Lamjung Himal (6,983 m)—spread in an unbroken white arc above the city's rooftops.</p><ul><li>Pokhara's oldest temple, established ~1760s; Shikhara architectural style</li><li>Dedicated to Goddess Bindhyabasini—manifestation of Durga; hilltop at 915 m</li><li>Panoramic view of Annapurna I, II, III, IV, Machapuchare and Lamjung Himal</li><li>Subsidiary shrines to Saraswati, Shiva, Hanuman, and Ganesha in compound</li><li>Elevator for elderly visitors, inaugurated 2019 by Nepal's President</li><li>Major festivals: Dasain (Fulpati/Mahanawami), Shivaratri, and Fulpati</li></ul>`,
    district: "Kaski",
    province: "GANDAKI",
    lat: 28.2378,
    lng: 83.9842,
    elevation: 915,
    entryFee: "Free",
    bestSeason: "Year-round; Oct (Dasain) and Feb (Shivaratri) for festivals",
    openingHours: "05:00\u201319:00 daily",
    howToGetThere: "Bindhyabasini Temple is located in the old Bazar area of Pokhara, approximately 2 km north of the main Lakeside tourist strip. Taxis from Lakeside take 5\u201310 minutes (NPR 150\u2013200). The temple is walkable from the main Mahendrapul area in 15 minutes. Stone staircases ascend from the north, east, and southeast; the elevator operates from the base of the eastern staircase.",
    gygQuery: "Bindhyabasini Temple Pokhara hilltop Hindu Nepal",
    bookingCity: "Pokhara",
    seoTitle: "Bindhyabasini Temple Pokhara \u2013 Oldest Hindu Temple with Himalayan Views",
    seoDescription: "Visit Bindhyabasini Temple, Pokhara's oldest Hindu shrine dedicated to Goddess Durga atop a hillock at 915 m. Enjoy sweeping views of the Annapurna range and witness vibrant festival celebrations during Dasain and Shivaratri.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
  {
    name: "Sarangkot Viewpoint",
    category: "HILL_VIEWPOINT",
    summary: "Sarangkot is Pokhara's premier sunrise viewpoint, a hilltop at 1,600 metres above sea level offering a panoramic sweep of the Dhaulagiri, Annapurna, and Manaslu massifs as the first light ignites the snow peaks in shades of orange and gold. The viewpoint is also South Asia's most popular paragliding launch site, with hundreds of tandem flights daily soaring off the ridge and landing on the Lakeside strip 800 metres below. A pre-dawn drive or two-hour hike from Pokhara city brings visitors to the observation tower in time for a mountain sunrise that is widely regarded as one of the finest in Nepal.",
    story: `<p>Sarangkot sits at 28°14'30"N 83°58'0"E in the Kaski District, 11 km northwest of Pokhara's Lakeside area, at an elevation of 1,592–1,600 metres on the crest of a ridge that divides the Pokhara Valley from the Madi River watershed to the north. The name derives from a historic fort ('kot') once maintained by the Kaski kingdom, though only scattered stone foundations remain. In its modern incarnation as Ward 18 of Pokhara Metropolitan City (merged into the city in 2015), Sarangkot is best known as a viewpoint and paragliding hub that draws an estimated 200,000 visitors annually. The hill rises dramatically above Phewa Lake's western shore, and its eastern face falls away in a series of terraced farms and forested gullies to the Lakeside strip below—the same slope that provides the 800-metre thermal lift that makes paragliding here so reliable.</p><p>The Sarangkot sunrise experience requires an early start: most visitors leave Lakeside hotels between 4:00 and 4:30 AM by taxi or jeep, reaching the hilltop by 5:30 AM well before the 6:00–6:30 AM sunrise in October through March. The observation tower—a simple concrete platform with railings—provides an unobstructed 180-degree northward panorama. From left (west) to right (east), the peaks appear in order: Dhaulagiri I (8,167 m), Tukuche Peak (6,920 m), Nilgiri (7,061 m), Annapurna I (8,091 m), Annapurna South (7,219 m), Hiunchuli (6,441 m), Machapuchare (6,993 m), Annapurna III (7,555 m), Annapurna II (7,937 m), Annapurna IV (7,525 m), and Lamjung Himal (6,983 m). On the clearest winter mornings, Manaslu (8,163 m) is visible far to the east. The alpenglow sequence—first lighting Dhaulagiri's summit, then sweeping rapidly east through the chain—lasts approximately 12 minutes before full daylight flattens the colour.</p><p>After sunrise, the hill transforms into a paragliding hub as thermal conditions develop by mid-morning. The Sarangkot launch ramp sits just below the observation tower, and on a busy day in October or November, tandem pilots launch at 5–10 minute intervals, their colourful canopies spiralling in thermals above the lake before gliding south to land on the dedicated landing strip beside the Lakeside road. The 20–40 minute flight covers up to 25 km and provides an aerial perspective of Phewa Lake, the Pokhara Valley, and the full Annapurna range that is impossible to replicate from any other vantage point. Prices range from USD 75–100 for a standard tandem flight, including a GoPro video. In the evenings, Sarangkot is equally popular for sunset—the western light painting the snowy peaks in rose and violet before they fade to grey.</p><ul><li>Elevation 1,600 m; 11 km northwest of Pokhara Lakeside; Ward 18 of Pokhara</li><li>180-degree panorama from Dhaulagiri (8,167 m) to Manaslu (8,163 m)—20+ peaks</li><li>Best sunrise in Nepal: alpenglow sequence lasts ~12 minutes at first light</li><li>South Asia's premier paragliding site: tandem flights USD 75–100, 20–40 minutes</li><li>Accessible by taxi (30 minutes from Lakeside, NPR 800–1200) or 2-hour hike</li><li>Both sunrise and sunset viewings equally spectacular; small restaurants at summit</li></ul>`,
    district: "Kaski",
    province: "GANDAKI",
    lat: 28.2417,
    lng: 83.9667,
    elevation: 1592,
    entryFee: "NPR 50 observation tower; paragliding USD 75\u2013100",
    bestSeason: "Oct\u2013Dec, Feb\u2013Apr (clearest skies)",
    openingHours: "Open 24 hours; sunrise viewings from ~05:00; paragliding 09:00\u201316:00",
    howToGetThere: "From Pokhara Lakeside, taxis take 30\u201335 minutes (NPR 800\u20131200 one-way). Shared jeeps depart from Lakeside around 4:30 AM for sunrise visits (NPR 300\u2013400 per seat). The hiking trail ascends from Miruwa village on the Pokhara-Baglung Highway (1.5\u20132 hours) or from Lakeside via Kaskikot (2\u20133 hours). Most paragliding operators include taxi transfers in the package price.",
    gygQuery: "Sarangkot sunrise Pokhara paragliding Annapurna view",
    bookingCity: "Pokhara",
    seoTitle: "Sarangkot Viewpoint Pokhara \u2013 Sunrise & Paragliding over Annapurna",
    seoDescription: "Visit Sarangkot at 1,600 m for Nepal's finest Himalayan sunrise\u2014a 20-peak panorama from Dhaulagiri to Manaslu at dawn. Book a tandem paragliding flight over Phewa Lake and Pokhara Valley at South Asia's top paragliding site.",
    published: true,
    featured: false,
    publishedAt: new Date(),
  },
]

async function main() {
  console.log(`🌱 Seeding batch 4 — ${places.length} places...`)
  for (const p of places) {
    await prisma.place.upsert({
      where: { slug: slug(p.name) },
      update: {},
      create: { ...p, slug: slug(p.name) },
    })
    console.log(`  ✅ ${p.name}`)
  }
  console.log('🌱 Batch 4 complete!')
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())