/**
 * Build-time prerendering.
 *
 * Serves the built dist/ SPA locally, visits every URL listed in the
 * sitemap (already generated by generate-sitemap.js + copied into dist/
 * by vite build), and writes the fully client-rendered HTML to
 * dist/<path>/index.html. Static hosts (Render included) serve an
 * existing file for a path before falling back to the SPA rewrite rule,
 * so every crawler — Googlebot, GPTBot, ClaudeBot, PerplexityBot, social
 * bots, or a plain `curl` — gets real content with no JS execution
 * required. The original bundle <script> tags stay in the captured HTML,
 * so real visitors still get the full interactive React app on top.
 *
 * Run after `vite build` (needs dist/ to exist).
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import express from 'express'
import puppeteer from 'puppeteer'

const __dir = dirname(fileURLToPath(import.meta.url))
const DIST = join(__dir, '../dist')
const PORT = process.env.PRERENDER_PORT || 4173
const CONCURRENCY = Number(process.env.PRERENDER_CONCURRENCY || 4)
const THIN_CONTENT_LOG = []

function getPaths() {
  const xml = readFileSync(join(DIST, 'sitemap.xml'), 'utf-8')
  const locs = [...xml.matchAll(/<loc>(.*?)<\/loc>/g)].map((m) => m[1])
  const paths = locs
    .map((loc) => loc.replace(/^https?:\/\/[^/]+/, ''))
    .map((p) => (p === '' ? '/' : p))
  // Homepage last so an in-progress crawl of other routes never falls back
  // to an already-overwritten index.html mid-run.
  return paths.sort((a, b) => (a === '/' ? 1 : b === '/' ? -1 : 0))
}

function startServer() {
  return new Promise((resolve) => {
    const app = express()
    app.use(express.static(DIST))
    // Express 5 rejects bare '*' route patterns — use path-less middleware
    // as the SPA fallback instead.
    app.use((_req, res) => res.sendFile(join(DIST, 'index.html')))
    const server = app.listen(PORT, () => resolve(server))
  })
}

async function renderOnce(browser, path) {
  const page = await browser.newPage()
  try {
    await page.goto(`http://localhost:${PORT}${path}`, {
      waitUntil: 'networkidle0',
      timeout: 30000,
    })
    // Network-idle can fire before a lazy route chunk finishes rendering
    // (Suspense fallback, then data fetch, then paint). Wait for both the
    // page's <main> content AND react-helmet-async's own <head> mutations
    // (title/meta/canonical, marked with data-rh) to land — the two don't
    // always commit on the same tick, and only checking <main> text length
    // was capturing pages with real body content but a still-generic head.
    const hasContent = await page
      .waitForFunction(
        () =>
          (document.querySelector('main')?.innerText?.trim().length ?? 0) > 200 &&
          document.querySelector('[data-rh]') !== null,
        { timeout: 15000 }
      )
      .then(() => true)
      .catch(() => false)
    // Extra settle time in case more Helmet tags are still landing.
    await new Promise((r) => setTimeout(r, 300))
    const html = await page.evaluate(
      () => '<!DOCTYPE html>\n' + document.documentElement.outerHTML
    )
    return { html, hasContent }
  } finally {
    await page.close()
  }
}

async function renderPath(browser, path) {
  let result = await renderOnce(browser, path)
  if (!result.hasContent) {
    // One retry — usually contention from other concurrent pages, not the
    // route itself, so a second uncontended-ish attempt often succeeds.
    result = await renderOnce(browser, path)
  }
  if (!result.hasContent) {
    THIN_CONTENT_LOG.push(path)
  }
  return result.html
}

async function run() {
  const paths = getPaths()
  console.log(`Prerendering ${paths.length} pages…`)

  const server = await startServer()
  const browser = await puppeteer.launch({
    headless: 'new',
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  })

  const queue = [...paths]
  const failed = []
  let done = 0

  async function worker() {
    while (queue.length) {
      const path = queue.shift()
      try {
        const html = await renderPath(browser, path)
        const outDir = path === '/' ? DIST : join(DIST, path)
        if (path !== '/') mkdirSync(outDir, { recursive: true })
        writeFileSync(join(outDir, 'index.html'), html, 'utf-8')
        done++
      } catch (e) {
        failed.push(path)
        console.warn(`  Failed: ${path} — ${e.message}`)
      }
    }
  }

  await Promise.all(Array.from({ length: CONCURRENCY }, worker))

  await browser.close()
  server.close()

  console.log(`Prerendered ${done}/${paths.length} pages.`)
  if (failed.length) {
    console.log(`${failed.length} failed:`, failed.join(', '))
  }
  if (THIN_CONTENT_LOG.length) {
    console.log(
      `${THIN_CONTENT_LOG.length} page(s) never hit the content threshold ` +
        `even after a retry — captured whatever rendered, worth spot-checking:`,
      THIN_CONTENT_LOG.join(', ')
    )
  }
}

run().catch((e) => {
  console.error(e)
  process.exit(1)
})
